lerna.json, packages/gatsby-plugin-graphql/package.json, packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-theme-ui/package.json, packages/gatsby-plugin-vtex-nginx/package.json, packages/gatsby-source-vtex/package.json, packages/gatsby-theme-vtex/package.json, packages/gatsby-transformer-vtex-cms/package.json, packages/lighthouse-config/package.json, packages/store-ui/package.json
In this PR I fixed the versions of all packages. 
@cezarguimaraes released the 0.70.0 but for some reason, the versions were not published in npm. Other versions were created above and this ended up creating a problem similar to this:
But @vtex/gatsby-transformer-vtex-cms not is a marinbrasil package
=> Fix Versions

packages/gatsby-theme-vtex/src/components/cms/components.ts, packages/gatsby-theme-vtex/src/pages/preview.tsx, packages/gatsby-transformer-vtex-cms/src/cms.ts, packages/gatsby-transformer-vtex-cms/src/compiler.ts, packages/gatsby-transformer-vtex-cms/src/gatsby-node.ts
CMS has changed the location of the meta and title information.
This PR updates the logic so that it can accept this type of page:
```
{
"lastUpdatedAt": "2020-09-24T17:34:56.493Z",
"afterBlocks": [],
"beforeBlocks": [],
"extraBlocks": [
{
"name": "admin/visibilityTitle",
"blocks": [
{
"name": "informations",
"props": {
"title": "Page comming from VTEX CMS",
"slug": "/about"
}
}
]
}
],
"blocks": [
{
"name": "img",
"props": {
"src": "https://content.vtexassets.com/assets/vtex.file-manager-graphql/images/chile-bike-2318___52930c4e532472f5263a0fbfdb067a1e.jpg"
}
}
]
}
```
- Preview
- Landing Page
=> Fix cms-transformer to render beforeBlocks, afterBlocks and extraBlocks

packages/gatsby-theme-vtex/src/components/Search/List/index.tsx, packages/gatsby-theme-vtex/src/templates/search.tsx
Currently, biggy search does not return all data that Portal returns. This is addressed by using origin-vtex in search queries
=> Uses product from vtex

packages/gatsby-theme-vtex/package.json, yarn.lock
Store UI is like a dev dependency and is therefore not entering the build pipeline.
=> Store UI Deps

lerna.json, packages/gatsby-theme-vtex/package.json, packages/gatsby-theme-vtex/src/sdk/search/controller.ts
As mentioned by our customers, when the user is in a department page and removes the last search filter, the user is redirected to the home page. This happens because a department page follows the pattern `/:department`, and when the user removes this filter, the search controller removes the filter, having the url `/`, thus redirecting the user to the home page
To solve the aforementioned problem, the simple solution of not being able to remove the first filter was implemented in this PR. So, for example, if the user is in the `/banana` and tries to remove the filter `banana`, nothing will happen. Also, if the user is in `/banana/pera` and the user tries to remove `banana` filter, nothing will also happen, since, at least for me, it makes no sense to remove the department filter in a …
=> Fix Home Redirect

lerna.json, packages/gatsby-theme-vtex/package.json, packages/gatsby-theme-vtex/src/components/ProductPage/AboveTheFold.tsx, packages/gatsby-theme-vtex/src/components/ProductPage/__generated__/ProductDetailsTemplate_product.graphql.ts, packages/gatsby-theme-vtex/src/sdk/product/useSku.ts, packages/gatsby-theme-vtex/src/templates/__generated__/ProductPageQuery.graphql.ts, packages/gatsby-theme-vtex/src/templates/product.tsx
Since Gatsby still does not support query shadowing, I'm adding some info needed in marinbrasil to make product title and product reference work correctly via SKU props
=> Product code

.eslintrc.js, package.json, packages/gatsby-theme-vtex/src/components/Minicart/Drawer/Quantity.tsx, packages/store-ui/src/ProductQuantity/useNumericStepper.ts, yarn.lock
Currently, our `react-preset/gatsby` is only matched against `*.tsx` files, which means every `use*.ts`, `hooks.ts`, `theme.ts` etc were not being checked properly.
Now, there are a bunch of hooks-deps related errors. I'm not confident enough to automatically change them so I'll ask for help with this in future PRs 😁
=> Run react-preset over hook and theme files

package.json, yarn.lock
Made a silly mistake when I updated our preset `@typescript-eslint/eslint-plugin` from v3 to v4. This PR explicitly updates them to prevent someone from getting unnecessary errors.
=> Explicitly update linter deps

lerna.json, packages/gatsby-source-vtex/package.json, packages/gatsby-source-vtex/src/gatsby-config.ts, packages/gatsby-source-vtex/src/gatsby-node.ts, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/gatsby-config.ts, packages/gatsby-theme-store/src/gatsby-node.ts, packages/gatsby-theme-store/src/pages/account.tsx, packages/gatsby-theme-store/src/pages/index.tsx, packages/gatsby-theme-store/src/sdk/auth/Service/api.ts, packages/gatsby-theme-store/src/sdk/auth/Service/startLogin.ts, packages/gatsby-theme-store/src/templates/product.tsx, packages/gatsby-theme-store/src/templates/search.tsx, yarn.lock
This PR moves most of VTEX related code from theme-store to source-vtex. This will make us closer to the OpenStore initiative.
Also, this PR adds schema validation to theme-store and source-vtex options and changes the env var VTEX_TENANT to STORE_ID
=> Move redirects to source vtex

lerna.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/ProductPage/SEO/useStructuredProduct.ts
When priceValidUntill is null, we must return null, and not the string "null" so google does not complain
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/282)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/415)
=> Fixes priceValidUntil when null

lerna.json, packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-cms/src/gatsby-node.ts, packages/gatsby-plugin-cms/src/index.ts, packages/gatsby-plugin-cms/src/node-api/actions/createNode.ts, packages/gatsby-plugin-cms/src/node-api/actions/deleteNode.ts, packages/gatsby-plugin-cms/src/node-api/remoteId.ts, packages/gatsby-plugin-cms/src/node-api/sourceAllLocalNodes.ts, yarn.lock
This PR makes it possible to use fixtures for local development using the CMS plugin. Also, this implies that starters may define standard pages for initial development
Any json added to the `fixtures` folder in the shadowed path will appear as a `PageContent` instance.
The developer can then query this artificial `PageContent` to program the pages locally.  In the future, we may be able to create an interface that outputs the PageContent automatically and help the development process.  
All changes done inside the `fixtures` folder is watched by a filesystem watcher that re-sources any changed node, thus making incremental builds possible
To a more detailed implementation: [check out how storecomponents use this feature](https://github.com/vtex-sites/storecomponents.store/pull/428) …
=> CMS Fixtures API

packages/gatsby-theme-store/i18n/en.json, packages/gatsby-theme-store/i18n/pt.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/Error/Error.tsx, packages/gatsby-theme-store/src/gatsby-browser.tsx, packages/gatsby-theme-store/src/pages/account.tsx, packages/gatsby-theme-store/src/pages/index.tsx, packages/gatsby-theme-store/src/pages/login.tsx, packages/gatsby-theme-store/src/templates/404.tsx, packages/gatsby-theme-store/src/templates/product.tsx, packages/gatsby-theme-store/src/templates/search.tsx
Move error boundary to page wrapper
Error boundaries had to be manually inserted in each page. If a developer didn't think about error boundaries, no error boundary would be added to the page. We had such error in the `institucional` pages at marinbrasil were no error boundaries were present.
Error boundaries were moved from each page into the `wrapPageElement`.  When we were developing error boundaries the first time, we couldn't place it into wrapPageElement because the i18n plugin used the same API, thus breaking a lot of error handling pages. After a complete refactor in i18n plugin, it uses the wrapRootElement API and we can now add default error boundaries in `wrapPageElement`
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/431) …
=> Error handler in page wrapper

packages/gatsby-theme-store/src/sdk/buyButton/useBuyButton.ts, packages/gatsby-theme-store/src/sdk/pixel/events.ts
Make it possible to have an interface like:
Because we were not sending the oneClickBuy in the pixel event, if we had two buttons, one with oneClickBuy option an another without it, the pixel event would be launched and we would always end up navigating into the checkout. This PR fixes this bug by sending the oneClickBuy option to the event
=> Fix one click buy

lerna.json, packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-cms/src/gatsby-node.ts, packages/gatsby-plugin-cms/src/index.ts, packages/gatsby-theme-store/package.json, packages/store-ui/package.json
As required by CMS team, this PR changes the exported config json. 
1. The path `/page-data/_cms/contentTypes.json` was renamed to `/page-data/_cms/builderConfig.json`
2. `blocks` and `messages` were moved to the json's root 
3. A special contentTypes property was created
The json shapes are available in:
1. [storecomponents](https://deploy-preview-427--faststore.netlify.app/page-data/_cms/builderConfig.json)
2. [marinbrasil](https://deploy-preview-296--marinbrasil.netlify.app/page-data/_cms/builderConfig.json)
<em>Extra tip: adding references to related issues …
=> Change CMS shape

lerna.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/pages/account.tsx, packages/gatsby-theme-store/src/pages/login.tsx
As title says, this adds `<meta name="robots" content="noindex, nofollow" />` on these pages because google was indexing them
With this PR we hope to make google remove this `Entrar` in google search page
=> No follow no index in `/account` and in `/login`

lerna.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/sdk/once.ts
`once` function parameters were wrong, this caused the [nprogress](https://ricostacruz.com/nprogress/) loading bar to not being displayed
[marin](https://github.com/vtex-sites/marinbrasil.store/pull/309)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/436)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/2)
=> Fix `once` function

lerna.json, packages/gatsby-source-vtex/package.json, packages/gatsby-source-vtex/src/api.ts, packages/gatsby-source-vtex/src/staticPaths.ts, packages/gatsby-source-vtex/src/types.ts
This PR exposes a new function called `staticPaths` from `@vtex/gatsby-source-vtex` to generate the staticPaths. This function exports all category paths along with the best selling products to statically generate the most importante pages. This is the first step toward an intelligent page generation algorithm
Generates all category paths, alongside the best selling products.
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/310)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/439)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/4)
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>  
<em>Extra tip: add references to related issues or mention people important to this PR may be good …
=> Static Paths

lerna.json, packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-graphql/package.json, packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-nginx/package.json, packages/gatsby-plugin-theme-ui/package.json, packages/gatsby-source-vtex/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/ProductPage/SEO/index.tsx, packages/gatsby-theme-store/src/components/SearchPage/SEO.tsx, packages/gatsby-theme-store/src/templates/search.tsx, packages/lighthouse-config/package.json, packages/store-ui/package.json
Add `<link rel="canonical">` tags to search/product pages
Consider you have pre-rendered a search on the path `/foo/bar` and the same content is rendered on /foo/bar?map=c,b 
this PR adds a `<link rel="canonical" href="https://origin/foo/bar">` tag on all /foo/bar variants so we deduplicate content on Google.
Note that if `/foo/bar` is not pre-rendered, it will receive a `<meta name="robots" content="noindex">` tag instead
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/315)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/445)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/9)
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>  
<em>Extra tip: add references to related issues or …
=> SEO | Search canonicals 

packages/gatsby-theme-store/src/components/HomePage/SEO/Canonical.tsx, packages/gatsby-theme-store/src/components/HomePage/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/components/HomePage/SEO/StructuredData.tsx, packages/gatsby-theme-store/src/components/HomePage/SEO/index.tsx, packages/gatsby-theme-store/src/components/ProductPage/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/components/ProductPage/SEO/StructuredData.tsx, packages/gatsby-theme-store/src/components/ProductPage/SEO/index.tsx, packages/gatsby-theme-store/src/components/SearchPage/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/components/SearchPage/SEO/index.tsx
This PR adds a custom SiteMetadata.tsx to all SEO folders so users can easily shadow a specific file, without having to deal with canonicals or structured data.
Also, this PR adds a [Searchbox](https://developers.google.com/search/docs/data-types/sitelinks-searchbox) from Google so a searchbar appears on google search when the user is searching for something
<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and …
=> SEO | Home

lerna.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/Shelf/index.tsx, packages/store-ui/package.json, packages/store-ui/src/RichText/index.tsx, packages/store-ui/src/Shelf/ArrowLeft.tsx, packages/store-ui/src/Shelf/ArrowRight.tsx, packages/store-ui/src/Shelf/Container.tsx, packages/store-ui/src/Shelf/PaginationDots.tsx, packages/store-ui/src/Shelf/Title.tsx, packages/store-ui/src/index.tsx
Move UI components of RichText and some Shelf components to @vtex/store-ui.
I left `Shelf/index.tsx` and `Shelf/Page.tsx` in the `@vtex/gatsby-theme-store` because it connects with GraphQL queries.
=> Move RichText and Shelf to store-ui

lerna.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/sdk/graphql/useLazyQuery.ts, packages/gatsby-theme-store/src/sdk/graphql/useQuery.ts, packages/gatsby-theme-store/src/sdk/graphql/useQueryInfinite.ts
SWR revalidates on many different cases. This may lead to previous static data being replaced right in the middle of a page navigation making the page to `samba`
This PR disable by default all revalidation related features from SWR so all static data is well preserved during the navigation. Of course, if the user desires, he can still opt-in for these features
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/332)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/31)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/461)
<em>Extra tip: adding references to …
=> Chore | Disable revalidation SWR 

packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/Search/List/Page.tsx, packages/gatsby-theme-store/src/components/Search/List/__generated__/SearchQuery.graphql.ts, packages/gatsby-theme-store/src/gatsby-node.ts, packages/gatsby-theme-store/src/sdk/orderForm/controller/__generated__/AddToCartMutation.graphql.ts, packages/gatsby-theme-store/src/sdk/orderForm/controller/__generated__/UpdateItemsMutation.graphql.ts, packages/gatsby-theme-store/src/sdk/search/useSearchFiltersFromPageContext.ts, packages/gatsby-theme-store/src/templates/__generated__/SearchPageQuery.graphql.ts
Here be unicorns 🦄  🦄  🦄 
This PR makes it possible to have data in category pages that only change when the user navigates to a different category page, a.k.a category.
This allow us to have one banner per category.
Supose we have two categories `/foo` and `/foo/bar`. 
This PR would generate: 
`/foo`
`/foo/__client_side_search__`
`/foo/bar`
`/foo/bar/__client_side_search__`
Both `/foo/bar` and `/foo/bar/__client_side_search__` share the same static data, a.k.a banner
I think we still have some work to do. However, let's do this version and iterate over it
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/25)
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/320)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/458)
<em>Spread the …
=> Dynamic search static data

lerna.json, packages/gatsby-source-vtex/package.json, packages/gatsby-source-vtex/src/api.ts, packages/gatsby-source-vtex/src/gatsby-node.ts, packages/gatsby-source-vtex/src/staticPaths.ts, packages/gatsby-source-vtex/src/types.ts, packages/gatsby-source-vtex/src/utils.ts, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/SearchPage/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/gatsby-node.ts, yarn.lock
Add brand pages generation.
This PR moves the `getStaticPaths` parameter function from `gatsby-theme-store` to `gatsby-source-vtex` and adds a default behavior to getStaticPaths, so we don't need to write it into the store repo anymore. Note that the repo may still overwrite the `getStaticPaths` function.
This change allow other `source` plugins to define other staticPaths without relying solely on VTEX APIs. `gatsby-theme-store` nows only queries gatsby's graphql for staticPaths. This may also lead to faster build times, since all Network IO was moved to `node sourcing` step, that can now be run in parallel via `PARALLEL_SOURCING` flag
Also, this PR adds logic for brand page generation, by using a the `pageType` API. In the future, we may remove the need for the pageType API when the …
=> Feature | Brand page

lerna.json, packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-graphql/package.json, packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-nginx/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-plugin-theme-ui/package.json, packages/gatsby-source-vtex/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/ProductPage/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/components/ProductPage/SEO/__generated__/ProductPageSEOQuery.graphql.ts, packages/gatsby-theme-store/src/components/ProductPage/SEO/index.tsx, packages/gatsby-theme-store/src/components/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/components/SearchPage/SEO/SiteMetadata.tsx, packages/gatsby-theme-store/src/components/SearchPage/SEO/StructuredData.tsx, packages/gatsby-theme-store/src/components/SearchPage/SEO/__generated__/SearchPageSEOQuery.graphql.ts, packages/gatsby-theme-store/src/components/SearchPage/SEO/index.tsx, packages/gatsby-theme-store/src/templates/__generated__/ProductPageQuery.graphql.ts, packages/gatsby-theme-store/src/templates/__generated__/SearchPageQuery.graphql.ts, packages/gatsby-theme-store/src/templates/product.tsx, packages/gatsby-theme-store/src/templates/search.tsx, packages/lighthouse-config/package.json, packages/store-ui/package.json
This PR uses the catalog's `titleTag` and `metaTagDescription` as default title and description tags for both product and search.
Also, the template used for such a feature is the `titleTemplate` variable added in Gatsby's siteMetadata section
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/352)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/146)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/482)
=> Add title template with catalog

lerna.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/sdk/orderForm/Provider.tsx
If orderForm somehow fails to load, the orderFrom queue is never started and the page remains in an inconsistent state. 
This PR throws the error if anything bad happens with the orderForm request and the user is redirected to the `/500` page. 
Note that in the `/500` page, the error should not be thrown otherwise we risk displaying an empty page
Open a PR, block the orderForm request. You should be redirected to the `/500`  page.
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/376)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/513)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/233)
<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and reviewing …
=> Remove orderForm "mudinho"

lerna.json, package.json, packages/gatsby-plugin-nginx/package.json, packages/gatsby-plugin-nginx/src/constants.ts, packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-source-vtex/package.json, packages/gatsby-source-vtex/src/gatsby-node.ts, packages/gatsby-source-vtex/src/redirects.ts, packages/gatsby-source-vtex/src/types.ts, yarn.lock
Usually, VTEX customers need to add custom redirects to their store. This PR adds this first-party capability by making `gatsby-source-vtex` receive a `getRedirects` function. This `async function` receives no argument and must return a list of Redirects. This way, our customer may fetch these redirects list from anywhere he wants.
Just take a look in the attached PRs:
https://github.com/vtex-sites/btglobal.store/pull/270
https://github.com/vtex-sites/marinbrasil.store/pull/400
https://github.com/vtex-sites/storecomponents.store/pull/565
<em>Extra tip: adding …
=> Support Redirects

lerna.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-google-tag-manager/src/pixel/handler.ts, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/pages/index.tsx, packages/gatsby-theme-store/src/sdk/pixel/events.ts, packages/gatsby-theme-store/src/sdk/pixel/pixel.ts, packages/gatsby-theme-store/src/sdk/pixel/vtexrc/handler.ts, packages/gatsby-theme-store/src/templates/product.tsx, packages/gatsby-theme-store/src/templates/search.tsx
This PR adds PageType to PageView event on datalayer
PageType may be one of the following `'home' | 'fullText' | 'pdp' | 'plp'`
This way the user can verify each page on the GTM
=> Add PageType to PageView event

lerna.json, packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-graphql/package.json, packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-nginx/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-plugin-theme-ui/package.json, packages/gatsby-source-vtex/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/Footer.tsx, packages/lighthouse-config/package.json, packages/store-ui/package.json
Fix the footer menu link slug and name.
To fix the slug, just remove the unnecessary `/` character. To fix the name, used this [regex](https://regex101.com/r/VgZosd/2).
=> Fix Footer MenuLink slug and name

lerna.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/sdk/search/controller.ts, packages/gatsby-theme-store/src/sdk/search/useSearchFiltersFromPageContext.ts, packages/gatsby-theme-store/src/templates/search.tsx
Add root path to search logic. This should allow landing pages to keep their search context on faceted navigation
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/325)
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/416)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/662)
Open https://btglobal.vtex.app/sale and select a filter. After, open https://preview-325--btglobal.vtex.app/sale .Check that in the preview, the image keeps on the screen and that the url starts with `/sale`. Also, check that the canonical tags are correctly appearing
<em>Extra tip: …
=> Search | Faceted navigation

.gitignore, lerna.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/HomePage/BelowTheFoldPreview.tsx, packages/gatsby-theme-store/src/components/ProductPage/BelowTheFoldPreview.tsx, packages/gatsby-theme-store/src/components/SearchPage/BelowTheFoldPreview.tsx
I was following [this guide](https://web.dev/content-visibility/) on how to improve the browser's rendering  pipeline. 
Since we are already following the above/below the fold split of rendering I think we don't run into much trouble in here, however I thought it was good to give it a try. 
After this PR, I've got an average reduction of 50ms in rendering on btglobal
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/338)
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/425)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/686)
<em>Extra tip: adding …
=> Adds content-visibility auto to below the fold loader

lerna.json, packages/gatsby-source-vtex/package.json, packages/gatsby-source-vtex/src/gatsby-config.ts, packages/gatsby-source-vtex/src/gatsby-node.ts
To change the proxy and the redirect for the `/files` path, in order to be able to get files such as the CSS ones that are defined by customizing the checkout, which is done by Carrefour. Besides that, we add the proxy rule for the legacy extensions path, which was a redirect previously defined, but with no proxy related to it.
[Marin #435](https://github.com/vtex-sites/marinbrasil.store/pull/435) 
[Boti #355](https://github.com/vtex-sites/btglobal.store/pull/355)
=> Changing files redirect and adding legacy_extensions proxy

lerna.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/SearchSuggestions/Products/__generated__/ProductsSuggestionsQuery.graphql.ts, packages/gatsby-theme-store/src/components/SearchSuggestions/Products/hooks.ts
Solves the problem of having products that are not available in a specific region shown in the search autocomplete.
It adds the region context, in order to use the region ID in the query that gets the results for the search autocomplete. By doing that, it allows us to have the suggestions filtered by the region.
=> Adding region context to search suggestions

lerna.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/components/HomePage/SEO/useSiteLinksSearchBoxJsonLd.ts, packages/gatsby-theme-store/src/gatsby-browser.tsx, packages/gatsby-theme-store/src/gatsby-node.ts, packages/gatsby-theme-store/src/sdk/orderForm/LazyProvider.tsx, packages/gatsby-theme-store/src/sdk/pixel/vtexrc/Provider.tsx, packages/store-ui/package.json
This PR takes the great idea of @igorbrasileiro changes the webpack config so we no longer need the custom `require()` in gatsby-(browser|ssr). Also this PR removes the "browser" field in store-ui, making it a more suitable lib for being used in other projects
After these changes, bundle-stats reported a decrease of ~20Kb in initial bundle size for marinbrasil and 5Kb for btglobal
I think it would be nice if we do the same changes for all plugins that use gatsby-* APIs. However, for now I'm only considering these core packages 
https://github.com/vtex-sites/carrefourbrfood.store/pull/445
https://github.com/vtex-sites/btglobal.store/pull/476
https://github.com/vtex-sites/marinbrasil.store/pull/478 …
=> Remove custom browser config from package.json

.codesandbox/ci.json, .github/workflows/ci.yml, package.json, packages/gatsby-plugin-google-tag-manager/src/pixel/handler.ts, packages/gatsby-plugin-google-tag-manager/src/pixel/index.tsx, packages/gatsby-plugin-pixel-facebook/src/pixel/handler.ts, packages/gatsby-plugin-pixel-facebook/src/pixel/index.tsx, packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/index.ts, packages/lighthouse-config/package.json, packages/store-sdk/package.json, packages/store-ui/package.json, yarn.lock
The goal of this CI is to make it easier for you to test faststore packages without publishing to npm yet. 
Every `push` event generates a build in codesandbox. This build will publish a version in codesandbox registry. To acces the published version and use it in your prs:
1. Wait for the Codesandbox CI to finish its job
2. Click on the `here` link. This will take you to codesandbox
3. On the right hand side, you will find a box called `local install instructions`.
4. Copy the install instructions and paste on one of our store's repo.
The changes I had to do to make this CI to work is that I had to remove the `prepare` script for all packages to avoid building twice and thus breaking concurrent builds. Also, I've removed the github action build step, since we are already doing this on …
=> Add Codesandbox CI

.github/PULL_REQUEST_TEMPLATE.md
Many PRs in faststore are being opened without changing or adding anything to the default template description and text. 
This PR moves the help from our default PR template to a mardown comment so we don't open PRs with the default template text, being more obvious when someone is writing something or not
=> Simplify template

packages/gatsby-theme-store/src/sdk/lazyScript/useLazyScript.ts, packages/gatsby-theme-store/src/sdk/pixel/vtexrc/Provider.tsx
This PR makes it possible to add any attribute to `script` tags being added to our pages by the `useLazyScript` hook. 
It also enables CORS when we're adding our RC script to solve a more specific issue.
You can check [this deploy preview](https://sfj-a9656ef--storecomponents.preview.vtex.app/). There should be no issues pointed out in the console. Also, if you check the cache storage, specifically the `gatsby-plugin-offline-runtime-...` one, you should be able to find an entry for `rc/rc.js`, with a Response-Type set to `cors`. Before this PR, this value would be set to `opaque`.
- https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests
- https://fetch.spec.whatwg.org/#concept-request-mode
- https://developer.mozilla.org/en-US/docs/Web/API/Response/type
- …
=> Opt-in to CORS while registering rc.js script

packages/gatsby-plugin-nginx/src/gatsby-node.ts
I have a build that takes a long time in the post build stage, so I would like to know how long each plugin takes
=> feat: use activity timer to report on duration of building nginx config

packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-i18n/src/gatsby-node.ts, packages/gatsby-theme-store/src/gatsby-node.ts, packages/store-ui/package.json, yarn.lock
This PR upgrades react-intl to the latest version. This upgrade will prevent users from installing a new version of react-intl and missing our webpack optimization rules.
Also, this PR adds gatsby-link as a peerDependency of store-ui fixing duplicate packages issue
React-intl has a [guide on reducing bundle sizes](https://formatjs.io/docs/guides/advanced-usage#react-intl-without-parser-40-smaller) by pre-compiling messages. This guide has changed since last version and if users upgrade their react-intl version they may miss this optimization.
Open any deploy preview and check for bundle-stats.html that nothing new was added and gatsby-link was deduped
https://github.com/vtex-sites/marinbrasil.store/pull/505
https://github.com/vtex-sites/btglobal.store/pull/550 …
=> Upgrade React-intl and dedup packages 

packages/gatsby-plugin-cms/src/index.ts
The CMS doesn't show descriptions for objects, only for internal properties. So we don't need this as required.
=> Making CMS schema description optional

packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts, packages/gatsby-plugin-nginx/tsconfig.json
Nginx config generation for my site was taking **5 minutes**
After this patch its **2 seconds**
Uses a `set` instead of an `array` and does `set.has` instead of `array.find` in `storagePassTemplate`
`yarn workspace @vtex/gatsby-plugin-nginx test`
Has a performance regression test when generates a config with 10k files which used to take 25s to run and after the patch its 23ms
I also added a inline snapshot test for 'correctly generates basic nginx configuration'
=> feat: improve nginx config generation by orders of magnitude

packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
Stops serving nginx.conf
When nginx.conf is request a 404 page is returned.
=> Add deny rule for nginx.conf

packages/gatsby-plugin-nginx/README.md, packages/gatsby-plugin-nginx/src/gatsby-node.ts, packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/src/pluginOptions.ts, packages/gatsby-plugin-nginx/src/typings/types.d.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
This PR improves gatsby-plugin-nginx configurability by allowing it to:
1. Add custom server block options
2. Add custom http block options
3. Create redirects with more than one variable
The first and second improvements are easy to understand. Basically, there is a new option to add custom nginx rules to the http and server block options. This gives people using this plugin more flexibility in terms of how they use the plugin and their nginx in their infrastructure.
The third point is more interesting. Before this PR, one could only write redirects like this:
```
createRedirect('/foo/*', '/bar/:splat')
```
Note that `:splat` had to be written exactly like this. Creating redirects with a different name, say: `/bar/:rest` broke the plugin. This PR fixes this problem. Also, another problem …
=> Chore | Improve gatsby-plugin-nginx configurability

packages/gatsby-theme-store/src/views/product/SEO/useMetadata.ts
Removes image rescaling in metadata generation since we don't really need to rescale the images in metadata. Removing this should improve and help performance a little bit
=> Drop file-manager in metadata

lerna.json, packages/gatsby-plugin-thumbor/README.md, packages/gatsby-plugin-thumbor/gatsby-browser.js, packages/gatsby-plugin-thumbor/gatsby-node.js, packages/gatsby-plugin-thumbor/gatsby-ssr.js, packages/gatsby-plugin-thumbor/index.js, packages/gatsby-plugin-thumbor/package.json, packages/gatsby-plugin-thumbor/src/Provider.tsx, packages/gatsby-plugin-thumbor/src/index.ts, packages/gatsby-plugin-thumbor/src/useGetThumborImageData.ts, packages/gatsby-plugin-thumbor/src/useThumborImageData.ts, packages/gatsby-plugin-thumbor/src/useUrlBuilder.ts, packages/gatsby-plugin-thumbor/src/utils/getImageData.ts, packages/gatsby-plugin-thumbor/src/utils/urlBuilder.ts, packages/gatsby-plugin-thumbor/test/urlBuilder.test.ts, packages/gatsby-plugin-thumbor/tsconfig.json, yarn.lock
This PR adds the thumbor plugin to the monorepo. 
Thumbor plugin is basically an integration (urlBuilder) with `gatsby-plugin-image` that does all the heavy lifting for reponsive images. More info on how it works on the plugin's README.
It's still in wip, but boti already has a version running it 
https://github.com/vtex-sites/btglobal.store/pull/583
=> Feat | Thumbor plugin

packages/renovate-config/README.md, packages/renovate-config/package.json, packages/renovate-config/renovate.json
This PR adds a preset configuration for Renovate app, so our stores can use the same config source for their Renovate configuration.
I'm testing yet inside [this test repository](https://github.com/vtex-sites/renovatetest.store), but I need this new package published somewhere.
https://docs.renovatebot.com/configuration-options/
https://docs.renovatebot.com/config-presets/
=> Creation of a new plugin for Renovate preset config

packages/renovate-config/package.json, packages/renovate-config/renovate.json
When the auto-merge of PR fails when pipeline fails, adds VTEX team to review the PR.
=> Set store-framework team as reviewer when fail pipeline

packages/gatsby-source-vtex/src/api.ts, packages/gatsby-source-vtex/src/fetch.ts, packages/gatsby-source-vtex/src/gatsby-node.ts, packages/gatsby-source-vtex/src/staticPaths.ts
This PR:
1. Fixes products sourcing 
2. Add retries to graphql queries so we don't break the whole build if something goes wrong on our infra.
1. We were using Solr API for sourcing our products. Basically we make a search and fetch at about 2500 products. To speedup the fetching, we paginate the search and fetch the pages in parallel. Somehow, this API is not reliable for doing such pagination because it would return duplicated products among pages. This caused an unreliable build where consecutive builds would generate a different amount of pages. We fix this problem by using Inteligent Search (IS) instead of Solr.
2. We add retries to graphql's executor when a non empty `errors` array is returned or when an http level error occurs. …
=> Fix | Source products using intelligent search (IS) 

packages/gatsby-theme-store/src/components/Error/ErrorBoundary.tsx, packages/gatsby-theme-store/src/components/Error/ErrorHandler.tsx, packages/gatsby-theme-store/src/gatsby-browser.tsx
Fix being redirected to 500 page on a ChunkLoadError.
Today, whenever an error happens, we redirect the user to the 500 page. If the user refreshs way too fast or if the file is not available on the server anymore, webpack throws a `ChunkLoadError` and the user is redirected to the 500 page.
This PR solves this problem by refreshing the page when a ChunkLoadError happens on the React tree. 
Refresh like crazy the home page before and after this PR. You will notice that eventually, you will be redirected to the 500 page. After this PR this shouldn't happen
https://github.com/vtex-sites/marinbrasil.store/pull/524
https://github.com/vtex-sites/btglobal.store/pull/626
=> Handle chunkLoadError

.github/workflows/ci.yml, package.json, packages/gatsby-plugin-nginx/package.json, packages/store-ui/package.json
Add Bot for `size-limit`. 
`size-limit` is a tool for evaluating the size of packages. The ideia is to not explode the size of libs we use. 
We already have some packages that support this, however we don't really have a bot for checking `size-limit`. This PR adds this bot
We need eventually to remove all theme-ui related code from store-ui and than decrease the threshold that is really high (100Kb min + gzipped)
=> Size limit

packages/store-ui/src/atoms/Price/Price.stories.tsx, packages/store-ui/src/atoms/Price/Price.test.tsx, packages/store-ui/src/atoms/Price/Price.tsx, packages/store-ui/src/atoms/Price/index.ts, packages/store-ui/src/index.ts
This PR adds the Price atom to our store-ui library.
```tsx
import { Price } from '@vtex/store-ui'
import { useMemo } from 'react'
function useIntlFormatter(price: number) {
return useMemo(() => {
const formattedPrice = new Intl.NumberFormat('en-GB', {
style: 'currency',
currency: 'EUR',
}).format(price)
return formattedPrice
}, [price])
}
function useIntlPartsFormatter(price: number) {
return useMemo(() => {
return new Intl.NumberFormat('en-US', {
style: 'currency',
currency: 'USD',
})
.formatToParts(price)
.map((part) => {
const props = {
[`data-store-price-${part.type}`]: true,
} as Record<string, unknown>
if (part.type === 'integer') {
props.style = { fontWeight: 700 }
}
return (
<span key={part.type} {...props}>
{part.value}
</span>
)
})
}, [price])
}
function customFormatter(price: …
```
=> feat: Price atom

packages/gatsby-theme-store/src/components/Error/ErrorBoundary.tsx, packages/gatsby-theme-store/src/components/Error/ErrorHandler.tsx, packages/gatsby-theme-store/src/gatsby-browser.tsx
There was a bug when handling errors.
When a user entered in an invalid page, the [React error handler](https://github.com/vtex/faststore/blob/a796a8c3629a0378fc6220ecdfef5749978134e4/packages/gatsby-theme-store/src/components/Error/ErrorHandler.tsx#L43) takes the user to /500. However, if we do it too fast, webpack throws a ChunkLoad error. This error was caught in our [error handler](https://github.com/vtex/faststore/blob/a796a8c3629a0378fc6220ecdfef5749978134e4/packages/gatsby-theme-store/src/gatsby-browser.tsx#L94)  that made the page to reload.
This PR fixes this issue by only reloading the page in the react tree and only allowing at most 2 reloads. If all reloads fail, we redirect the user to the /500 page.
The reload count is keep using session storage and is cleared after 30 …
=> Reload at most twice

packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-graphql/package.json, packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-nginx/package.json, packages/gatsby-plugin-performance/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-plugin-theme-ui/package.json, packages/gatsby-plugin-thumbor/package.json, packages/gatsby-theme-store/package.json, packages/lighthouse-config/package.json, packages/renovate-config/package.json, packages/store-sdk/package.json, packages/store-ui/package.json
Add the "repository" field in package.json in `store-ui` package. Thus npm and gatsby can find plugins and their repos.
1. Go to [faststore repo](https://github.com/vtex/faststore).
2. Click on **packages** > **store-ui** > **package.json**
3. In the field `repository` should have the following to specify the directory:
```
"repository": {
"type": "git",
"url": "https://github.com/vtex/faststore",
"directory": "packages/store-ui"
},
```
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
=> Update url repository

packages/store-ui/src/index.ts
While building stores, we would get the following warnings:
```
warn export 'ButtonProps' (reexported as 'ButtonProps') was not found in './atoms/Button'
(possible exports: default)
warn export 'InputProps' (reexported as 'InputProps') was not found in './atoms/Input'
(possible exports: default)
warn export 'IconProps' (reexported as 'IconProps') was not found in './atoms/Icon'
(possible exports: default)
warn export 'PopoverProps' (reexported as 'PopoverProps') was not found in './atoms/Popover'
(possible exports: default)
warn export 'SearchInputProps' (reexported as 'SearchInputProps') was not found in
'./molecules/SearchInput' (possible exports: default)
warn export 'SearchFilterItem' (reexported as 'SearchFilterItem') was not found in
'./deprecated/SearchFilter/Accordion' (possible …
```
=> Fix `warn export <type> was not found in <file>`

packages/renovate-config/package.json, packages/renovate-config/renovate.json
This PR fixes the Renovate config to update only VTEX/Faststore dependencies and disables the auto-merge feature (Temporarily until we setup a solid E2E in our stores).
=> Fix renovate config

.github/workflows/internal-docs.yml, docs/e2e-testing.md
Currently, the faststore docs are spread over the Store Framework docs on the vtex-internal docs page. With the on-call protocol, we want to produce documentation for all the systems that the SF team takes care and keeping a folder for each one makes things more organized.
=> Move faststore docs to a folder inside Store Framework

packages/gatsby-source-vtex/src/gatsby-node.ts
Intelligent search data is still not reliable. Some fields, like spotPrice and image alt text are not resolved correctly. This PR uses the productOriginVtex option in search query to source product changes with the right values
Check that the spotPrice is correctly rendered by the store now on this product for marinbrasil. For this, open the product page at:
`/estante-para-livros-com-5-prateleiras-modulare-natural-tramontina-91620018/p`
Now, inspect source and look for the meta field "product:price:amount". Note that this property is now fixed with the value `130,66` instead of `139,00 `
=> fix: use origin vtex

packages/gatsby-theme-store/src/sdk/orderForm/controller/getOrderForm.ts
This PR prevents resetting the orderFormId on localStorage when the request to get orderform is canceled after an error at the store occurs. 
Steps:
1. Add some product to your cart
2. Force to cause an error while the fetch of orderform
3. Check if the cart contains your products
Stores:
https://github.com/vtex-sites/carrefourbrfood.store/pull/858
https://github.com/vtex-sites/btglobal.store/pull/666
https://github.com/vtex-sites/marinbrasil.store/pull/537
https://github.com/vtex-sites/storecomponents.store/pull/1002
=> Fix orderfrom from being reset

packages/gatsby-source-vtex/src/gatsby-node.ts, packages/gatsby-source-vtex/src/graphql/pagination/product.ts
Fixes 404 errors while fetching products. Also, adds an option to fetch less products for testing purposes
When we made builds on `carrefourbrfood`, we got a 404. This is because we were fetching too much products at once. Decreasing the number of products per fetch should solve this problem.
Also, this plugin adds a minProducts option to set the minimum amount of products to be fetched. This can help developing since we can fetch less products on "dev mode" and make a full build in production.
=> fix(gatsby-source-vtex): page size

packages/renovate-config/package.json, packages/renovate-config/renovate.json
Removing the automerge label from Renovate config, since we aren't doing automerge yet.
=> fix: Removing automerge PR label from renovate config

packages/gatsby-theme-store/src/sdk/search/converter/useSearchParamsFromURL.ts, packages/gatsby-theme-store/src/sdk/searchBar/controller/index.ts, packages/gatsby-theme-store/src/templates/search.browser.tsx
When we have a brand or landing page, the search goes to this page with wrong parameters in the stores URL.
This PR adds those parameters only if it's really a search page, not a brand or landing page.
=> fix(gatsby-theme-store): complex plp navigation

packages/gatsby-source-vtex/src/fetch.ts
As the title says
Before
After
=> fix: graphql error messages being swallowed up

packages/gatsby-theme-store/src/sdk/seo/product/useBreadcrumbJsonLd.ts, packages/gatsby-theme-store/src/sdk/seo/product/useMetadata.ts, packages/gatsby-theme-store/src/sdk/seo/product/useProductJsonLd.ts
While SSR, we generated canonical tags with the SSR host. The SSR host was `undefined` which made us to generate canonical link tags like:
`https://undefined/<pathname>`
To prevent this problem, we generate relative canonical tags with `/<pathname>` during SSR and hydrate it with `https://<host>/<pathname>` once the React hydration kicks in.
With this I hope to solve the problem of product pages having invalid canonicals.
You may be wondering now why don't we just fix the `host` value during SSR to the same domain as we are going to serve the production server. The response to this question is that we use lighthouse to test these urls in a different domain, and if lighthouse sees that the canonical points to a different domain, it will break with an error. To circumvent this issue we do …
=> fix(seo): Fix undefined host in canonical tags of product pages

packages/store-ui/src/atoms/Checkbox/Checkbox.test.tsx, packages/store-ui/src/atoms/Checkbox/Checkbox.tsx, packages/store-ui/src/atoms/Checkbox/index.ts, packages/store-ui/src/atoms/Checkbox/stories/Checkbox.mdx, packages/store-ui/src/atoms/Checkbox/stories/Checkbox.stories.tsx
Add the Checkbox atom to store-ui
=> feat(store-ui): Checkbox atom component

CONTRIBUTING.MD
=> doc: Updating contributing

packages/store-ui/src/atoms/Button/index.ts, packages/store-ui/src/atoms/Checkbox/Checkbox.tsx, packages/store-ui/src/atoms/Checkbox/index.ts, packages/store-ui/src/atoms/Icon/index.ts, packages/store-ui/src/atoms/Input/index.ts, packages/store-ui/src/atoms/Popover/index.ts, packages/store-ui/src/atoms/Price/index.ts, packages/store-ui/src/atoms/TextArea/TextArea.tsx, packages/store-ui/src/atoms/TextArea/index.ts, packages/store-ui/src/atoms/TextArea/stories/TextArea.stories.tsx, packages/store-ui/src/molecules/Bullets/Bullets.tsx, packages/store-ui/src/molecules/Bullets/index.ts, packages/store-ui/src/molecules/SearchInput/index.ts
This PR fixes a bullets iterator on Server Side Rendering. Also, I took the time to make the types API uniform by making every component to export types the same way.
I was getting this weird error when using the bullets component with Server Side Rendering. 
I figured out this was beacuse of the `.keys()` method not having an uniform API across environments, a.k.a. Node.JS and the browser. By changing to using the index iterator the problem was solved.
I'm using this component on the product image gallery at: 
https://github.com/vtex-sites/storecomponents.store/pull/1036
https://github.com/vtex-sites/btglobal.store/pull/712
https://github.com/vtex-sites/marinbrasil.store/pull/557/checks?check_run_id=3089658329
=> fix(store-ui): Fix bullets iterator

packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
Before this fix the new test would broke with:
-           "https://mylogs-proxy.endpoint.com:8088/logs$is_args$args",
+           "https://mylogs-proxy.endpoint.com$1/logs$is_args$args",
Meaning that this nginx plugin is replacing port number and not only `:splat` or `:*` values
Running yarn test on gatsby-plugin-nginx package
=> fix(gatsby-plugin-nginx): Fix proxy pass when toPath has port numbers on it

packages/gatsby-theme-store/package.json, packages/gatsby-theme-store/src/sdk/buyButton/useBuyButton.ts, packages/gatsby-theme-store/src/sdk/orderForm/useOrderItems.tsx, packages/store-ui/src/deprecated/Minicart/Drawer/Content/ItemInfo.tsx, packages/store-ui/src/deprecated/Minicart/Drawer/Content/Quantity.tsx, packages/store-ui/src/deprecated/Minicart/Drawer/Content/index.tsx, yarn.lock
This PR fixes an issue where users are redirected to checkout before the `AddToCartMutation` is completed. If the request was to be successful, users would only see the product after a page refresh. If it wasn't going to be successful, users would be redirected to the checkout and never see their product on the cart. If the request fails, users are not going to be redirected and they can try again by just clicking one more time.
This PR allows the cart to remain async when making operations that don't redirect the users to the checkout, such as adding products to the cart and seeing them on the minicart.
https://github.com/vtex-sites/marinbrasil.store/pull/556
=> fix(gatsby-theme-store): useBuyButton only redirects users to the checkout when product is added successfully

packages/gatsby-plugin-google-tag-manager/src/pixel/handler.ts, packages/gatsby-theme-store/src/components/ProductSummary/index.tsx, packages/gatsby-theme-store/src/components/Search/List/Page.tsx, packages/gatsby-theme-store/src/sdk/buyButton/useBuyButton.ts, packages/gatsby-theme-store/src/sdk/orderForm/useUpdateQuantityWithPixel.ts, packages/gatsby-theme-store/src/sdk/pixel/events.ts, packages/gatsby-theme-store/src/sdk/product/useBestSeller.ts, packages/gatsby-theme-store/src/sdk/product/useLink.ts, packages/gatsby-theme-store/src/sdk/search/useSearch.tsx, packages/store-ui/src/deprecated/SearchSuggestions/Products.tsx, packages/store-ui/src/deprecated/Shelf/Page.tsx, packages/store-ui/src/deprecated/Shelf/index.tsx
This PR fixes the data sent by the product click event and makes it ready to serve accurate SAE and GTM events.
The event data is handled by the `useLink` hook. There are default values, but people can override them whenever necessary.
https://github.com/vtex-sites/storecomponents.store/pull/1049
=> feat(gatsby-theme-store): fix product click event

packages/gatsby-plugin-cms/package.json, packages/gatsby-plugin-google-tag-manager/package.json, packages/gatsby-plugin-graphql/package.json, packages/gatsby-plugin-i18n/package.json, packages/gatsby-plugin-nginx/package.json, packages/gatsby-plugin-pixel-facebook/package.json, packages/gatsby-plugin-theme-ui/package.json, packages/gatsby-plugin-thumbor/package.json, packages/gatsby-source-vtex/package.json, packages/gatsby-theme-store/package.json
Prevent codesandbox bot to build the packages twice
Basically, Codesandbox's bot does the following commands:
```sh
lerna run build && lerna exec pack
```
The first command runs the build script for each package, whereas the second packs the built packages into a tarball. 
The problem with this approach is that while running `pack`, npm calls the `prepare` script. The prepare script was running `yarn build`, which rebuilt all packages again. This lead to longer than necessary build times in codesandbox CI and also caused inconsistencies since the `pack` command was run in parallel, not respecting the package's inter dependencies. This PR solves this problem by removing all `prepare` scripts. This is ok because our workflow on github actions do not use the prepare and runs build too.
Make …
=> fix(codesandbox): Prevent building twice

package.json
Store UI deploys are failing [in this PR](https://github.com/vtex/faststore/pull/828) because we need to build themes before building our Storybook. 
I'll change the Netlify build command after this merge.
This PR creates one script for building all of our themes and other to build our Storybook inside root `package.json`. 
Just run those scripts inside root path with `yarn build-themes` or `yarn build-storybook`
=> feat(core): Creates build scripts inside root package.json for themes and Storybook

packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-theme-store/src/sdk/seo/product/useMetadata.ts
Remove trailing slashes when generating redirects on the nginx plugin so paths like `[...].tsx` work just fine
https://github.com/vtex-sites/marinbrasil.store/pull/595
https://github.com/vtex-sites/btglobal.store/pull/781
https://github.com/vtex-sites/storecomponents.store/pull/1101
=> Remove trailing slashes

packages/gatsby-plugin-graphql/src/cache.ts, packages/gatsby-plugin-graphql/src/filesystem.ts, packages/gatsby-plugin-graphql/src/gatsby-node.ts, packages/gatsby-plugin-graphql/src/manager.ts, packages/gatsby-plugin-graphql/src/webpack.ts
When using this plugin, we get the warnings: 
```
success Rewriting compilation hashes - 0.019s
success Writing page-data.json files to public directory - 0.391s - 419/419 1070.34/s
warn Skipping query HomePageQuery since it was already defined. If this wasn't the intended
behavior please change your query operation name
warn Skipping query BrowserProductPageQuery since it was already defined. If this wasn't the
intended behavior please change your query operation name
warn Skipping query BrowserSearchPageQuery since it was already defined. If this wasn't the
intended behavior please change your query operation name
warn Skipping query ServerSearchPageQuery since it was already defined. If this wasn't the
intended behavior please change your query operation name
warn Skipping query …
```
=> fix(gatsby-plugin-graphql): Fix warnings and incremental builds

packages/gatsby-plugin-nginx/src/headers.ts, packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
This PR adds support to spread routes only.
Suppose we have the following taxonomy:
```
pages
...
│
├── {StoreCollection.slug}
│   └── [...].tsx
...
```
Currently, any page created will be available at, and only at: `/:slug/`. If the user enters in `/:slug` it will receive a 404. 
This PR solves this problem by making the route `/{StoreCollection.slug}/` also respond at `/:slug`.
Note that if the user has the following taxonomy:
```...
├── account.tsx
├── {StoreCollection.slug}
│   └── [...].tsx
│   └── index.tsx
...
```
Both account.tsx and index.tsx will still work because of route precedence. 
Make sure no route was lost on either of these stores:
https://github.com/vtex-sites/storecomponents.store/pull/1124
https://github.com/vtex-sites/marinbrasil.store/pull/610 …
=> fix(gatsby-plugin-nginx): Spread routes support

packages/gatsby-plugin-graphql/src/gatsby-node.ts, packages/gatsby-plugin-graphql/src/webpack.ts
Our graphql plugin generates special graphql artifacts after the building process. These files are located under the `__generated__` folder. 
The problem with these `__generated__` files is that when they are created inside the `pages` folder, Gatsby thinks they are valid components and create pages for these files, which, in turn, breaks the build. 
To address this issue, this plugin had a special case where it would move file from the pages folder to the `src` folder. At frst, this worked fine. However, as the app grow and more queries where created we ended up  with many folder on the root `src` folder, creating a huge entropy.
This PR fixes this side effect by allowing the creation of `__generated__` files inside `pages` folder and removing them with the `onCreatePage` hook. This …
=> feat(gatsby-plugin-graphql): Remove special case for the pages folder

packages/store-ui/src/atoms/Overlay/Overlay.test.tsx, packages/store-ui/src/atoms/Overlay/Overlay.tsx, packages/store-ui/src/atoms/Overlay/index.ts, packages/store-ui/src/atoms/Overlay/stories/Overlay.mdx, packages/store-ui/src/atoms/Overlay/stories/Overlay.stories.tsx, packages/store-ui/src/index.ts, themes/theme-b2c-tailwind/src/atoms/index.css, themes/theme-b2c-tailwind/src/atoms/overlay.css, yarn.lock
Adds Overlay atom: component, test, and story.
=> feat(store-ui): Overlay Atom

packages/store-ui/src/hooks/useSlider/useSlider.ts
fix the lint problem in useSlider. For some reason turn a boolean in a number using the Number function trigger the eslint rule `@typescript-eslint/restrict-plus-operands`. So, as `Number(true)` always 1, I check if the prop is true and add +1
=> fix(store-ui): lint problem in useSlider

packages/store-ui/src/molecules/Carousel/Carousel.tsx
When we use the Carousel twice in the same page, the ID label decreases our A11y points in Lighthouse.
=> fix(store-ui): Remove unnecessary ID and improve a11y

packages/gatsby-plugin-graphql/src/gatsby-node.ts, packages/gatsby-plugin-graphql/src/webpack.ts
gatsby-plugin-graphql generates artifacts on the same folder the reference file is located at. For instance, supose you have a file called `index.ts` inside the folder `pages`. Our graphql plugin will generate the following page structure:
```
| pages
|__ index.ts
|__ __generated__
|__ MyQuery.graphql.ts
```
Where MyQuery is the name of the query you've written inside `index.ts`. This works really well, however the way Gatsby (and Next) was built doesn't allow you to have these kind of assets inside the `pages` folder. 
I fixes this issue by removing these pages. However, gatsby cloud breaks with this. 
This PR proposes a fix by moving all queries into a folder at the root of the projecct called `__generated__`. All queries are generated inside this folder and we don't need to bother with …
=> chore: Move graphql generation to a single folder

packages/store-ui/src/atoms/Skeleton/Skeleton.test.tsx, packages/store-ui/src/atoms/Skeleton/Skeleton.tsx, packages/store-ui/src/atoms/Skeleton/index.ts, packages/store-ui/src/atoms/Skeleton/stories/Skeleton.mdx, packages/store-ui/src/atoms/Skeleton/stories/Skeleton.stories.tsx, packages/store-ui/src/index.ts, themes/theme-b2c-tailwind/src/atoms/index.css, themes/theme-b2c-tailwind/src/atoms/skeleton.css, themes/theme-b2c-tailwind/src/index.css
Add the Skeleton Atom to _store-ui_ with its story and test
https://github.com/vtex-sites/storecomponents.store/pull/1197
=> feat(store-ui): Add Skeleton Atom

packages/gatsby-plugin-cms/src/node-api/cms/fetchNodes.ts
This PR fixes an issue where users were unable to develop on a store that didn't have a CMS page yet
I just checked if the edge existed before getting the cursor
=> fix: users are unable to develop a store in an account without CMS pages

packages/gatsby-theme-store/src/sdk/region/Provider.tsx
This fixes an issue where `regionId` would be null on queries because it was being loaded lazily.
=> fix: synchronously reading regionId initial value

packages/gatsby-theme-store/src/sdk/region/controller.ts
Check if `window` is available before accessing it
=> fix: check if window is available before accessing it

packages/store-api/package.json, packages/store-api/src/__generated__/schema.ts, packages/store-api/src/platforms/vtex/clients/commerce/index.ts, packages/store-api/src/platforms/vtex/clients/commerce/types/OrderForm.ts, packages/store-api/src/platforms/vtex/clients/commerce/types/Simulation.ts, packages/store-api/src/platforms/vtex/clients/common.ts, packages/store-api/src/platforms/vtex/clients/search/index.ts, packages/store-api/src/platforms/vtex/index.ts, packages/store-api/src/platforms/vtex/loaders/index.ts, packages/store-api/src/platforms/vtex/loaders/simulation.ts, packages/store-api/src/platforms/vtex/loaders/sku.ts, packages/store-api/src/platforms/vtex/resolvers/aggregateOffer.ts, packages/store-api/src/platforms/vtex/resolvers/mutation.ts, packages/store-api/src/platforms/vtex/resolvers/offer.ts, packages/store-api/src/platforms/vtex/resolvers/product.ts, packages/store-api/src/platforms/vtex/resolvers/query.ts, packages/store-api/src/platforms/vtex/resolvers/validateCart.ts, packages/store-api/src/typeDefs/cart.graphql, packages/store-api/src/typeDefs/image.graphql, packages/store-api/src/typeDefs/index.ts, packages/store-api/src/typeDefs/mutation.graphql, packages/store-api/src/typeDefs/offer.graphql, packages/store-api/src/typeDefs/order.graphql, packages/store-api/src/typeDefs/organization.graphql, packages/store-api/src/typeDefs/product.graphql, packages/store-api/src/typeDefs/status.graphql, packages/store-api/test/index.test.ts, yarn.lock
This PR adds an optimistic cart implementation to store-api.
The optimistic cart we have works via state validation. This means that, we build a state of the cart on the browser, and then, the backend validates this state. If this state is valid, the backend signalizes this state is ok and nothing changes on the frontend. If, however, this state is not valid, a.k.a, this product is unavailable, a promotion was applied, etc, the backend sends the new cart state to the frontend. An example of this process can be seen below: 
To implement the cart, I used the schema.org's type `Order`. Also, another thing this PR brings is `input` fields. We didn't really use them before, but now I needed a standard for writing them. I added an `I` prefix to them, so writing an `input` for a `type` can be …
=> feat(store-api): Add cart to store-api

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/index.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/loaders/index.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/platforms/vtex/resolvers/query.ts, yarn.lock
When an SKU has sellers that are not available on the current sales channel, checkout breaks with 
```
Ocurrió un error de comunicación con el Catálogo de Productos
```
This PR fixes this problem
To fix the aforementioned problem, we need to simulate only the sellers available for that specific sales channel. Hopefully, there is an attribute in the SKU that does just that. The fix is based on using this field instead of all skus's sellers.
Also, another problem this PR fixes is when the product has an empty array of images. This breaks the frontend code since we always need at least one image to show the product. 
This problem happens on `exito` account. To see it working, go to https://github.com/vtex-sites/exito.store/pull/1
Also, to make sure no regressions were made: …
=> fix: Channel simulation

packages/ui/src/molecules/LoadingButton/stories/LoadingButton.stories.tsx, packages/ui/src/molecules/PriceRange/stories/PriceRange.stories.tsx
Every story that has only one default story and have two words in your name with CamelCase, like `PriceRange`, was displaying the story with a sub-story, when it has only one default story and it doesn't need a sub-story. Examples below:
Before: 
After:
=> fix(store-ui): Fix story title when CamelCase

packages/api/package.json, packages/api/src/platforms/vtex/resolvers/collection.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/utils/slugify.ts, yarn.lock
This PR makes base.store work on a few more accounts. The problem now was that the slugs generated from the slugify function are `Nullable`. This makes the router implementation resolve to the wrong page in certain paths, making PDPs unachievables .
To test it, checkout to the PR below and change the account to `exito`. After this, you should be able to enter pdps
https://github.com/vtex-sites/base.store/pull/109
=> fix: Filter collection slugs in api

packages/api/package.json, packages/sdk/package.json, packages/sdk/tsconfig.json, packages/ui/package.json, packages/ui/tsconfig.json
This PR uses tsdx's `browserslist` capabilities to target newer browsers on all `store-*` packages. This way, we hope to remove the need of unnecessary polyfills in our dependencies, like regenerator runtime etc.
By having our deps with newer es versions, we can transpile our dependencies when building the stores, so we can do better browser targeting and differential serving in our infrastructure. If you want to know more about this topic visit https://web.dev/publish-modern-javascript/
The table below shows some improvements while targeting newer browsers:
| Package | Before(Kb) | After(Kb) |
|:-------:|:----------:|:---------:|
|   SDK   |    6.78    |    3.11   |
|    UI   |    10.29   |    9.89   |
https://github.com/vtex-sites/base.store/pull/112
Also, for base.store, we had the …
=> chore: Use browserslist in api/ui/sdk

packages/api/src/platforms/vtex/clients/search/index.ts
API had a problem where it only accepted one type of facet being selected. When multiple were selected it chose one. 
This PR fixes this issue by not merging the facets, but using another algorithm.
Go to base.store and select multiple `sizes` in the plp for instance. Compare with both my preview and master. I my preview it should be working as expected.
https://github.com/vtex-sites/base.store/pull/113
Before after in the same path:
=> fix: facets selection

packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/src/typings/types.d.ts, packages/gatsby-plugin-nginx/src/utils/functions.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
- Enables support to augment the generate nginx locations by passing the value by the function `onGenerateNginxRewrites` which can augment the generated commands to nginx
Just run the tests or write more of them
=> Support to augment the nginx rewrites

packages/api/src/platforms/vtex/loaders/sku.ts, packages/api/src/platforms/vtex/utils/errors.ts, packages/api/src/platforms/vtex/utils/facets.ts
To better handle errors at stores, the API must specify which errors are internal and which ones are due to client errors.
This PR adds a `BadRequestError` class and throws it instead throwing `Error` when the error is due to the client.
=> chore(api): Improves error handling with BadRequestError

docs/components-architecture.md
Finding good references about accessibility isn't trivial, so knowing this, this PR adds accessibility references to **Component Architecture** documentation.
=> chore: Add accessibility references at component docs

packages/gatsby-plugin-nginx/src/gatsby-node.ts, packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/src/pluginOptions.ts, packages/gatsby-plugin-nginx/src/typings/types.d.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
Our current nginx config is generated for serving files that were touched by the Gatsby build. This is ok when you build the whole thing at once. However, when you do incremental builds you need be able to patch the build and serve these newly generated files. 
This PR addresses this issue by adding a hard coded rule in the end of `nginx.confg` that try for local files before returning a 404. The final rule is:
```
location / {
add_header Cache-Control "public, max-age=0, must-revalidate";
try_files $uri $uri/ $uri/index.html $uri.html =404;
}
```
Possible drawbacks of this solution is generating a security whole by serving files that should not be served. However, if the file should not be served, it should not be on the filesystem of the server in the first place.
Make sure everything …
=> chore(gatsby-plugin-nginx): Try local files before returning 404

packages/sdk/src/search/Provider.tsx, packages/sdk/src/search/serializer.ts, packages/sdk/src/search/useInfiniteSearchState.ts, packages/sdk/src/search/useSearchState.ts, packages/sdk/test/search/Provider.test.tsx, packages/sdk/test/search/serializer.test.ts, packages/sdk/test/search/usePagination.test.tsx
This PR changes the search serialization strategy. With this new strategy, I hope to better use the CDN by re-using the same html template for all search filters in a given collection 
Search state comes from the URL. This state contains which filters are applied, which sorting method is selected etc. To apply any change to this state, a navigation to a new URL is required. Serializing/Parsing is an important part of the search flow and can be done in multiple ways. Currently our state is totally serialized into the url using path segments. 
For instance, serializing the following search state
```json
{
"base":  "",
"selectedFacest": [{ "key": "category-1", "value": "women"}]
"sort": "score_desc",
"page": "0",
"term": null
}
```
would give us …
=> refactor(sdk): Search serialization

packages/ui/.storybook/main.js, packages/ui/package.json, yarn.lock
Upgrade Storybook from 6.3 to [6.4](https://storybook.js.org/blog/storybook-6-4/).
Most of this PR's file changes were done automatically by `npx sb automigrate`, as recommended in [the migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-63x-to-640). The only [extra step](https://github.com/vtex/faststore/pull/1053/commits/e2efb923fd939ad23e3195d8ddcec3e8ab2a828c) I needed to take was to fix the now [deprecated](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag) `--static-dir` (or `-s`) CLI flag that links to the `themes/` directory.
After the migration, the Storybook is still working fine. See the [preview link](https://deploy-preview-1053--faststoreui.netlify.app/).
- …
=> chore(ui): Upgrade Storybook from 6.3 to 6.4

README.md
It adds instructions on how to use [wml](https://github.com/wix/wml) to improve Faststore developer experience.
=> docs: Adds instructions on how to use wml to develop locally

packages/api/src/platforms/vtex/clients/search/types/AttributeSearchResult.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts
This PR fixes collection pages failing to load when they had no facets configured on the VTEX platform. The graphql schema expects a non-null facets array, so an exception was thrown when no facets were returned from the IS server.
A fallback was added so even if IS returns null, the faststore API will return an empty array.
=> fix: add fallback to prevent null facets attribute StoreSearchResult query

themes/theme-b2c-tailwind/src/molecules/index.css
Sorry! I probably made a mistake while merging [this](https://github.com/vtex/faststore/pull/1048/files#diff-bcac487ddf0a40be314da14a715f3226436d8d07cd6433fc4359ec4cadfe3f16L1)!  😓
This PR is to put back missing css imports on `/theme-b2c-tailwind/src/molecules/index.css`
=> Fix: Adds back missing css imports

docs/docs/reference/ui/molecules/Breadcrumb.mdx, docs/docs/reference/ui/molecules/LoadingButton.mdx, docs/docs/reference/ui/molecules/PriceRange.mdx, docs/docs/reference/ui/molecules/RadioGroup.mdx, packages/ui/src/index.ts, packages/ui/src/molecules/RadioGroup/RadioGroup.test.tsx, packages/ui/src/molecules/RadioGroup/index.tsx, themes/theme-b2c-tailwind/src/molecules/breadcrumb.css
Some components were not being exported by `@faststore/ui`. Thus, we have not add them to the React Live code editor. This PR fixes this issue by adding:
1. `Breadcrumb`
2. `LoadingButton`
3. `PriceRange`
4. `RadioGroup`.
Open the reference implementation on the deploy preview and make sure the live editor is working just fine
=> docs: Add missing components

docs/docusaurus.config.js
We were beign redirected to the wrong path when clicking on the button below. This PR fixes this path
=> fix(docs): editurl

packages/ui/src/molecules/RadioGroup/RadioOption.tsx
Noticed the following warning when running `yarn develop`:
```
⠸ Building modules
Circular dependency: src/index.ts -> src/molecules/RadioGroup/index.tsx -> src/molecules/RadioGroup/RadioOption.tsx -> src/index.ts
```
The `Radio` being imported was from `index` and changing it to `atoms/Radio` fixed it.
=> chore(ui): Fix a circular dependency

packages/graphql-utils/package.json, packages/ui/src/utils/toHaveNoIncomplete.ts
Make graphql-utils compatible with other frameworks
graphql-utils was exposign the index file via typescript. This is ok when using Gatsby, however, other frameworks like Next.JS do not compile node_modules and may break when using this package. To solve this problem I'm just exposing the js file only
=> fix: expose JS files only

packages/ui/src/molecules/Banner/BannerContent.tsx, packages/ui/src/molecules/SearchInput/SearchInput.tsx
- I wanted to add `role=search` to the `Form` component inside the `InputSearch`, but I noticed that the `props` are being 
applied to the `<Input>`. So, I thought it might be good to add it directly to this `InputSearch` component.
- The word button was unnecessarily repetitive, so I changed it to be more contextual to provide a better experience.
https://user-images.githubusercontent.com/3356699/146251127-db8d13d5-788a-4286-839d-747bdf9097ea.mov
- Also took the opportunity to remove the misused `role=region` for the `BannerContent` component.
- [ARIA: search role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/search_role)
=> Chore: Improves InputSearch usability

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Currently, the FastStore repo does not have issue templates. Those templates are helpful to give guidance to contributors, better address the issue they want to communicate, and help receive the right resources for the request.
When someone wants to open an issue, they will have the following template's options:
- Bug report
- Feature request
- Documentation request
- Question
[About issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
=> Update issue templates

packages/ui/src/organisms/Card/CardContent.tsx
- Changes `CardContent` component to `<section>` instead of using `role=region`
> Using the `<section>` element will automatically communicate a section has a role of region if it is given an accessible name. Developers should always prefer using the correct semantic HTML element, in this case `<section>`, over using ARIA ([role=region](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/region_role)).
I thought about 3 approaches that we could use to improve the accessibility of this component:
1. Removes the default `'aria-label': ariaLabel = 'Card content'`
- The ideal would be the user pass a different string here, but we aren't ensuring it. Typically a heading will be use inside it.
- Why not keep the default string? Considering that we are using this Card component …
=> Chore: Uses section instead of aria role on CardContent component

packages/ui/src/molecules/PaymentMethods/PaymentMethods.tsx
The payment methods component was returning an accessibility error on storybook:
To solve it, `aria-labelledby` was removed.
=> fix(ui): removing aria-labelledby from payment methods component

packages/api/src/platforms/vtex/resolvers/product.ts
After integrating the Breadcrumb component onto base.store, @israelswf and @lucasfp13 realized that the ordering of the categories on the breadcrumbs is reversed based on what comes from the API and what shows up on GraphQL. This PR reverts the `categoryTrees` before resolving the query.
Current API result:
```
...
"categoryTrees":[
{
"categoryNames":[
"Computer and Software",
"Gadgets"
],
"categoryIds":[
"9286",
"9292"
]
},
{
"categoryNames":[
"Computer and Software"
],
"categoryIds":[
"9286"
]
}
],
"images":[
{
"name":"deleniti",
"value":"http://storeframework.vteximg.com.br/arquivos/ids/187078/in.jpg?v=637755572312800000"
}
],
"name":"Licensed Rubber Salad Handcrafted"
...
```
Current GraphQL result:
```
{
"data": {
"storeProduct": {
"breadcrumbList": {
"itemListElement": [
{
"item": …
```
=> Fix ordering of breadcrumbList

docs/src/components/FeedbackForm/FeedbackForm.module.css, docs/src/components/FeedbackForm/FeedbackForm.tsx, docs/src/theme/DocItemFooter/index.js, docs/src/theme/DocItemFooter/styles.module.css
- Create the FeedbackForm component 
- Add the FeedbackForm component to DocItemFooter
Allows users to send documentation feedback. When a user sends feedback, a Google Sheets file is updated with a new row containing the following information: timestamp, feedback message, doc URL, helpful (yes | no)
1. Look for "Was this page helpful?" at the end of any doc page.
2. Submit the feedback.
3. Check for updates in the Feedback Form Google Sheets file (private).
=> Add FeedbackForm component to DocItemFooter

packages/gatsby-plugin-thumbor/src/index.ts, packages/gatsby-plugin-thumbor/src/useGetThumborImageData.ts, packages/gatsby-plugin-thumbor/src/useThumborImageData.ts
The typings of thumbor were not correct, since we don't accept the `server` as option from thumbor. This PR fixes this typing and export the right one
=> fix: Thumbor options

packages/api/src/platforms/vtex/loaders/sku.ts
The algorithm for the sku dataLoader was a little bit off. This PR fixes this problem by removing some edge cases that made errors like `Could not find sku for product …` from occuring
Link this PR with base.store and make sure you are able to open many different products
=> fix(api): Sku loader

packages/sdk/src/analytics/events/add_payment_info.ts, packages/sdk/src/analytics/events/add_shipping_info.ts, packages/sdk/src/analytics/events/add_to_cart.ts, packages/sdk/src/analytics/events/add_to_wishlist.ts, packages/sdk/src/analytics/events/begin_checkout.ts, packages/sdk/src/analytics/events/purchase.ts, packages/sdk/src/analytics/events/refund.ts, packages/sdk/src/analytics/events/remove_from_cart.ts, packages/sdk/src/analytics/events/select_item.ts, packages/sdk/src/analytics/events/select_promotion.ts, packages/sdk/src/analytics/events/view_cart.ts, packages/sdk/src/analytics/events/view_item.ts, packages/sdk/src/analytics/events/view_item_list.ts, packages/sdk/src/analytics/events/view_promotion.ts
This PR adds generics to the analytics events so users can control which type is used for the Item property. This makes it easier for additional properties to be included inside an item, which is a common use case.
It defaults to the regular Item type but allows users to override it to include additional properties.
it shouldn't affect how the code behaves, only the dev experience.
I'll link it here as soon as I have it
=> feat(sdk): add item generics to analytics types for easy customization

packages/api/src/platforms/vtex/resolvers/collection.ts
This PR fixes an issue with breadcrumb data on PLPs. 
Before this PR, we were just returning an empty list as the breadcrumb. After this PR, we use catalog data for filling the breadcrumb info.
Use the base.store PR linked below and check that you can run both `allCollection` and `collection` fields.
https://github.com/vtex-sites/base.store/pull/216
=> fix(api): Breadcrumb data on collection pages

packages/gatsby-plugin-nginx/src/headers.ts
Fixes an error at nginx plugin that prevented stores from building when using custom env var headers.
Uses the replace method in replacement to the replaceAll method that's causing the error probably because the node version doesn't include it yet.
=> fix(gatsby-plugin-nginx): replaceAll crashing build with env vars

packages/gatsby-plugin-cms/src/gatsby-node.ts, packages/gatsby-plugin-cms/src/node-api/cms/fetchNodes.ts, packages/gatsby-plugin-cms/src/node-api/cms/sourceNode.ts, packages/gatsby-plugin-cms/src/node-api/cms/types.ts, packages/gatsby-plugin-cms/src/utils/fetch.ts
This PR enables gatsby-plugin-cms to receive `webhookBody` params, fetch the values on the CMS API and return it to preview on webOps.
REST API example: https://storecomponents.myvtex.com/_v/cms/api/faststore/home/72de3769-347e-4734-855a-e5a4f072f66b?versionId=e2f4f2c0-9001-4f6b-b318-35f50ae2e3fb
1. clone this repo and branch
2. link it on your favorite account (you can try with storecomponents.store) using [wml](https://github.com/wix/wml)
3. run `yarn develop` on this folder to build the files and start the server on your store using `ENABLE_GATSBY_REFRESH_ENDPOINT=true`, you should see the home page from production.
4. to reproduce the preview, call your refresh endpoint using this values:
```bash
curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8000/__refresh -d …
```
=> chore(gatsby-cms-plugin): fetch content by ID using REST API from CMS for preview

packages/ui/src/molecules/Accordion/Accordion.test.tsx, packages/ui/src/molecules/Accordion/AccordionButton.tsx, packages/ui/src/molecules/Accordion/AccordionItem.tsx
This PR intends to add the `prefixId` attribute to the `AccordionItem` component.
This will avoid the problem of having duplicate `AccordionPanel` and `AccordionButton` IDs when having two accordions on the same page.
In a scenario where there is an `Accordion` being used in a filter component and another in a footer component:
=> chore(ui): Add prefixId attribute to AccordionItem

packages/lighthouse-config/src/index.ts
This PR adds budgets to lighthouse config.
=> feat: Add budgets lighthouse config

packages/api/src/platforms/vtex/resolvers/collection.ts, packages/api/src/platforms/vtex/resolvers/product.ts
Before|After
-|-
`/Kitchen-and-Home-Appliances` ([not working](https://base.vtex.app/Kitchen-and-Home-Appliances))|`/kitchen-and-home-appliances` ([working](https://base.vtex.app/kitchen-and-home-appliances))
Before|After
-|-
`/kitchen and home appliances` ([not working](https://base.vtex.app/kitchen%20and%20home%20appliances))|`/kitchen-and-home-appliances` ([working](https://base.vtex.app/kitchen-and-home-appliances))
[8d954a56253469514b1ffe7d2d8de29399db9db0](https://github.com/vtex-sites/base.store/commit/8d954a56253469514b1ffe7d2d8de29399db9db0)
- https://sfj-8d954a5--base.preview.vtex.app/kitchen-and-home-appliances/fridges breadcrumb displays a link to `/kitchen-and-home-appliances` (no `/Kitchen-and-Home-Appliances`).
- https://sfj-8d954a5--base.preview.vtex.app/ergonomic-wooden-ba …
=> fix(api): PDP and PLP breadcrumb list item's URL paths

packages/lighthouse-config/src/index.ts, packages/sdk/src/cart/Cart.tsx, packages/sdk/src/storage/useStorage.ts
This PR improves the useStorage hook by making it stable. This means that if you don't have any value stored on the persistent storage, it will not trigger a re-rendering of the React API and will use the `initialValue` instead, thus leading to a smaller footprint of the user's device and smaller TBTs
=> chore: stable useStorage hook

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/platforms/vtex/resolvers/productGroup.ts, packages/api/src/typeDefs/index.ts, packages/api/src/typeDefs/product.graphql, packages/api/src/typeDefs/productGroup.graphql, packages/api/src/typeDefs/propertyValue.graphql, yarn.lock
[Schema.org](https://schema.org/Product) Product schema has a built-in field called [additionalProperty](https://schema.org/additionalProperty). The intent of this field is to provide an API for extending the fields of a product without defining a custom schema. As far as I can tell, this is analogous to VTEX's [specification fields](https://help.vtex.com/tutorial/what-are-fields-or-specifications--2lB4AgibEseceMggKE2k2m). 
This PR adds `additionalProperty` to type StoreProduct with the goal of having feature parity with VTEX's `productSpecification` API so developers can use these properties in their stores to create different UI's
VTEX has two specifications. Product and SKU specifications. Luckily, schema.org has a very similar approach to the problem. Both `StoreProduct` (VTEX SKU) …
=> feat(api): Add additional property

packages/api/src/platforms/vtex/resolvers/query.ts
This PR fixes the error below:
```
ERROR
NotFoundError: Catalog returned FullText for slug: canyon. This usually happens when there is more than one category with the same name in the same category tree level.
at /Users/gimenes/Documents/code/vtex-sites/base.store/node_modules/@faststore/api/src/platforms/vtex/loaders/collection.ts:38:17
at processTicksAndRejections (node:internal/process/task_queues:93:5) {
locations: [ { line: 32, column: 3 } ],
path: [ 'allCollections', 'edges', 9, 'node', 'breadcrumbList' ]
}
```
We were receiving this error because the list of brands the api returns contains inactive brands. A simple filter solved the issue.
https://github.com/vtex-sites/base.store/pull/361
=> fix: filter active brands

packages/api/src/platforms/vtex/resolvers/product.ts
This PR fixes incorrect sku ids being returned on the sku field of StoreProduct. 
StoreProduct represents a sku on VTEX. StoreProductGroup represents a VTEX Product. As such, the `productID` and `sku` fields of StoreProduct must have the same value. This was the case on stores with one sku per product, but not on accounts where multiple skus are present on each product.
This PR uses the same logic for both `sku` and `productID` so that they always have the same value
Make sure that when adding a product to cart, this product shows on cart correctly.
=> fix: StoreProduct return wrong sku

packages/api/src/platforms/vtex/resolvers/searchResult.ts
This PR is based on [this comment](https://github.com/vtex-sites/base.store/pull/321#pullrequestreview-877461915) and aims to move some logic from the `Filter` component from the frontend to the backend (API):
- Sorts the facets values alphabetically
- Removes the `departamento` facet from the Collection (PLP) page.
=> feat: Moves some Filter logic to api

packages/ui/src/molecules/Breadcrumb/Breadcrumb.test.tsx
I totally missed the **GH Actions / Lint** warnings in https://github.com/vtex/faststore/pull/1143 and @eduardoformiga reminded me of that.
Go to https://github.com/vtex/faststore/pull/1159/files and there should be no warning on `packages/ui/src/molecules/Breadcrumb/Breadcrumb.test.tsx`.
- https://github.com/vtex/faststore/pull/1143/files#r813406187
- https://github.com/vtex/faststore/pull/1143/files#r813406441
=> chore(ui): Clean up some minor linter warnings from previous PR

packages/api/src/platforms/vtex/clients/fetch.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts
This PR makes the cart module to respect the inventory limits of a certain product.
Currently, when adding an unavailable product to card, the UI let's the counter to increase indefinitely without warning the user the product has limited inventory. This PR addresses this issue by limiting the amount of products the user can add to cart. Also, if the user adds more itens, a toast message is raised warning the user
Optimistic UI is a design pattern that improves greatly the UI responsiveness by not blocking the user/UI interaction while the server process requests. Our SDK's cart module is optimistic. This means that the user does not need to wait for the ecommerce platform to process anything before adding/removing items from cart.
To achieve an optimistic cart, the cart state is copied …
=> fix: Cart item availability

packages/api/src/platforms/vtex/loaders/simulation.ts
We were getting too many errors with the simulation API. This PR adds a limit to the amount of requests being made  concurrently. Also, this PR increases the batch size of the API so we need to make less requests overall.
For testing: take a look at:
https://github.com/vtex-sites/base.store/pull/385
=> chore: Add limit to simulation api

packages/sdk/src/session/Provider.tsx
Fix ContextValue setSession function type.
setSession function allows receiving partial session as parameter input, but the type says that need to pass session.
before:
```ts
export interface ContextValue extends Session {
setSession: (session: Session) => void
}
// ...
const value = useMemo(
() => ({
...session,
setSession: (data: Session) => setSession({ ...session, ...data }),
}),
[session, setSession]
)
```
after:
```ts
export interface ContextValue extends Session {
setSession: (session: Partial<Session>) => void
}
// ...
const value = useMemo<ContextValue>(
() => ({
...session,
setSession: (data) => setSession({ ...session, ...data }),
}),
[session, setSession]
)
```
After the fix, is possible to pass partial session:
```ts
const { setSession } = useSession()
setSession({ …
```
=> chore(sdk): Fix setSession function type to receive partial session

packages/api/src/platforms/vtex/resolvers/query.ts
The `allCollections` query always fails if the user asks for the `pageInfo.totalCount` field, that is because the resolver for that query would never return that field.
Now the resolver will return the number of valid collections in the store when a user asks for `pageInfo.totalCount`.
I used the local server to test it (spoilers 🤫 ).
=> fix(api): Add missing `totalCount` field to `pageInfo` in `allCollections` query

packages/api/src/platforms/vtex/utils/facets.ts
Allow users query a product by slug without any transformation.
Currently, we add a `skuId` in the end of the VTEX's product slug, i.e. the final faststore product path is something like: `${vtexSlug}-${skuId}`. Because of that, I added a transformation inside faststore api to remove this skuId before sending the request to vtex. Turns out, we don't use this `fetchBySlug` strategy anymore, but `fetchBySkuId`. This PR removes this unecessary transformation to allow developers to fetch a product by the old VTEX slug standard. This will be important for store migrations. 
Make sure everything is working as before on this link: https://github.com/vtex-sites/base.store/pull/394
=> chore: Remove slug transformation

packages/api/src/platforms/vtex/utils/facets.ts, packages/sdk/test/search/Provider.test.tsx, packages/sdk/test/search/serializer.test.ts
Fix price range tests
Filters are passed through the URL as follows:
?price=*:150&category-1=technology&facets=price%2Ccategory-1
https://base.vtex.app/technology/?price=*:150&category-1=technology&facets=price%2Ccategory-1
=> Fix range price facet

packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/test/vtex.aggregateOffer.test.ts
Moves computation from the frontend to the backend
As stated on [this comment](https://github.com/vtex-sites/base.store/blob/f0190f3cded3506f92b9061b8de96aaca62d8725/src/components/product/ProductCard/ProductCard.tsx#L56), this PR sorts offers by placing the best offers on the first bit of the offers array, allowing us to stop doing this computation on the frontend. This should reduce TBT
Tests included, but also, check the `base.store` preview: https://github.com/vtex-sites/base.store/pull/411
=> chore: Best offer first

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/typeDefs/index.ts, packages/api/src/typeDefs/person.graphql, packages/api/src/typeDefs/query.graphql
Allows returning null as profile. More info on why we are doing this change, at this PR:
https://github.com/vtex-sites/base.store/pull/418
=> chore: Nullable Profile

packages/sdk/src/cart/Optimistic.tsx, packages/sdk/src/storage/useStorage.ts
Improve the performance of useStorage hook.
The useStorage hook has an effect that fetches an item from the indexedDB, then update an internal state with this item. So, exists two tasks, one is a micro-task because is a promise and the other one belongs to the same task. The problem is these two tasks sometimes can create tasks that took more than 50ms and are considered Long Tasks.  Know this, this PR wraps the async promise and the set state inside a setTimeout. Why setTimeout, because it creates a new task. For more information about tasks and microtasks you can read this [article](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)
Take a look at the quantity of long tasks after the hydration
**Before**:
**After**:
Run PSI API for mobile 15 times and the result is …
=> feat(sdk): Improve useStorage and Optimistic revalidate effect

packages/ui/src/molecules/Breadcrumb/Breadcrumb.test.tsx, packages/ui/src/molecules/Breadcrumb/Breadcrumb.tsx
This PR fix a Breadcrumb bug. This bug occurs when a conditional rendering is called inside the Breadcrumb, even if the rendering is false the component renders the divider, like in the picture.
To fix this bug, the function` React.Children.toArray` was added, it converts from `ReactChildren` to `Array` and filters the `null` childrens
=> fix: fix breadcrumb component bug

packages/sdk/package.json, packages/sdk/src/search/useSearchState.ts, yarn.lock
This PR adds `setFacets` function to the search context. This function sets all selected facets without any processing, allowing full control of selected facets by the developer.
When creating a filter interface for mobile devices, we need to allow the final user to select multiple facets before applying them, all at once. This is usually accomplished by the developer managing which facets are selected in a state outside this module. Without `setFacets`, the developer had to do some magic by using `toggleFacets` function, which was not well suited for this task. `setFacets` allows the developer to use our module in a controlled way, setting all facets externally.
https://github.com/vtex-sites/base.store/pull/422
=> feat: setFacets

packages/ui/src/molecules/Dropdown/hooks/useDropdownPosition.ts
This PR Fixs ther `Dropdown` component in SSR, to fix this problem, before access de `document`, the `useDropdown` checks if document is not undefined.
=> fix: fix dropdown render in SSR

docs/docs/tutorials/cms/01 - Configuring your VTEX account.md
This PR updates vtex.admin-cms@0.x and vtex.admin-cms-graphql-rc@0.x to @1.x on faststore.dev docs.
It also updates the build URL to `/build-releases` since Releases is now the default option to build and publish on the CMS.
=> Update admin-cms and graphql-rc on faststore.dev

packages/api/mocks/CollectionQuery.ts, packages/api/package.json, packages/api/src/platforms/vtex/resolvers/collection.ts, packages/api/src/platforms/vtex/utils/slugify.ts, packages/api/test/__snapshots__/queries.test.ts.snap
This PR fixes slug mismatches, thus broken links, between `@faststore/api` and VTEX catalog.
It uses same, the battle tested, slugify function VTEX IO uses for slugifying links. This is now possbile thanks to Gatsby v4. 
> Note: If you are not using gatsby v4, please upgrade before updating this library.
Make sure all links on `base.store` are working as intended. Also, I have changed the category name from `Computer and Software` to `Computer & Software`. This change used to break other versions of `base.store`, however, now, it should be working.
BaseStore link: 
https://github.com/vtex-sites/base.store/pull/468
- Slugify implementation on VTEX IO: https://github.com/vtex/rewriter/blob/1ce2010783e0586cab42534ce2fb7a983d8a3a84/node/clients/catalog.ts#L72
=> fix: Uses catalog slugify

packages/ui/src/molecules/Banner/Banner.test.tsx, packages/ui/src/molecules/Banner/Banner.tsx
This PR intends to add the missing `otherProps` param to the `Banner` component.
=> Fix: Adds Banner's missing other props

docs/docs/reference/api/faststore-api.md
=> Update 'Extending the schema' API docs

packages/sdk/src/analytics/events/add_payment_info.ts, packages/sdk/src/analytics/events/add_shipping_info.ts, packages/sdk/src/analytics/events/add_to_cart.ts, packages/sdk/src/analytics/events/add_to_wishlist.ts, packages/sdk/src/analytics/events/begin_checkout.ts, packages/sdk/src/analytics/events/common.ts, packages/sdk/src/analytics/events/login.ts, packages/sdk/src/analytics/events/purchase.ts, packages/sdk/src/analytics/events/refund.ts, packages/sdk/src/analytics/events/remove_from_cart.ts, packages/sdk/src/analytics/events/search.ts, packages/sdk/src/analytics/events/select_item.ts, packages/sdk/src/analytics/events/select_promotion.ts, packages/sdk/src/analytics/events/share.ts, packages/sdk/src/analytics/events/signup.ts, packages/sdk/src/analytics/events/view_cart.ts, packages/sdk/src/analytics/events/view_item.ts, packages/sdk/src/analytics/events/view_item_list.ts, packages/sdk/src/analytics/events/view_promotion.ts, packages/sdk/test/analytics/__fixtures__/EventSamples.ts
This reverts commit 0e2befe3cb5dc99521a470c4096e31237b93a9c0.
The Analytics SDK types should be 100% compliant with Google Analytics 4, which means we can't add custom properties to events directly on the SDK. It's possible to do so in stores by extending the provided types. Also, collecting the URL on all events is redundant, since GA4 already collects this data automatically.
=> fix(sdk): Revert "feat: Add url to events (#1174)"

packages/api/src/platforms/vtex/clients/fetch.ts, packages/api/src/platforms/vtex/clients/index.ts, packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/clients/sp/index.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts
This PR integrates the VTEX Intelligent Search Analytics API with `@faststore/api`. More specifically, it integrates product queries with search.query event.
For intelligent search to work properly, some events must be send to their tracking endpoints `https://sp.vtex.com/event-api/v1`. A few of these events (`session.ping` and `search.click`) were already implemented on our starters. However, a missing event was `search.query`. This event is important for populating indices, like `Top Searches` and `Suggestions`. This event was hard to implement because some info was missing on the frontend. To address this issue, an integration on `@faststore/api` was proposed.
`@faststore/api` is a BFF GraphQL layer between the React frontend and the VTEX Intelligent Search API. Every time a search is …
=> feat: Add search event API

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/docs/tutorials/cms-storecomponents/Overview.mdx, docs/docs/tutorials/gatsby/03 - Creating your first SFJ store.mdx, docs/src/pages/sections/StarterSubmissionForm/StarterSubmissionForm.jsx, docs/src/pages/starters/gatsby.js, docs/src/pages/starters/nextjs.js, docs/static/data/starters.json
This PR adds the new Next.JS starter on the docs. Also, this PR changes the links to base.store to our new Gatsby.store
=> chore: Add new starters on the docs

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts, packages/api/src/typeDefs/query.graphql
The standardization of Search Suggestions (terms - autocomplete - and products).
```gql
{
search(term: "iphone") {
suggestions {
terms
products {
name
slug
}
}
}
}
```
https://github.com/vtex-sites/base.store/pull/437
=> feat: search suggestions

docs/docs/reference/ui/get-started-faststore-ui.md
This PR removes the Tailwind installation section from the _Get Started_ guide, preventing users from changing the styles in the starter's components.
P.S.: This is a step to introduce the global tokens documentation.
=> docs: remove Tailwind installation from docs

docs/blog/2022-05-02-cms.md
The team requested a small update to the `what should be done` section, instructing the install of the app that allows for authentication required for accessing the previews.
=> Adding information about authentication app

packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/platforms/vtex/resolvers/productGroup.ts
After changing to use the new intelligent search API, additional properties stopped being returned on Product and, and they were all moved to the ProductGroup. 
This PR fixes this regression by returning the sku specifications on `StoreProduct.additionalProperties` and product specifications on `StoreProductGroup.additionalProperties`
For testing and checking, please refer to the original PR: https://github.com/vtex/faststore/pull/1107
=> fix: missing additionalProperties 

packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts, packages/api/src/platforms/vtex/resolvers/offer.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/platforms/vtex/utils/enhanceCommercialOffer.ts, packages/api/src/platforms/vtex/utils/productStock.ts, packages/api/test/__snapshots__/queries.test.ts.snap, packages/api/test/vtex.aggregateOffer.test.ts
This PR fixes offer availability bug introduced on #1216
In `@faststore/api`'s schema, a Product has an AggregateOffer. This means that, for each VTEX SKU, we have an aggregate of all offers from all sellers for that specific SKU. 
It turns out, that after #1216, an SKU got all offers from all skus for that product. This lead to unavailable SKUS being marked as available. This PR fixes that by returning offers for that specific sku only/
- [gatsby.store](https://github.com/vtex-sites/gatsby.store/pull/31) 
- [nextjs.store](https://github.com/vtex-sites/nextjs.store/pull/22)
=> fix: Offer availability

packages/api/src/platforms/vtex/resolvers/offer.ts
When dealing with "Buy 2 Get 3" kind of promotions our code got crazy. This was because of a miss interpretation between of selling prices and prices. 
This PR fixes this issue.
You can use carrefourbrfood for testing this. Open `store.config.js`, change account to carrefourbrfood and use sales channel 2. After that, visit the following url: `/cafe-pilao-senseo-intenso-18-saches-8756201-2618/p`. Add 6 items on cart and make sure the promotion was applied correctly. 
- https://github.com/vtex-sites/nextjs.store/pull/32
- https://github.com/vtex-sites/gatsby.store/pull/42
=> fix: Promotions

packages/api/package.json, yarn.lock
DataLoader used to rely on `setImmediate` existing on the browser which caused a lot of errors as reported on https://github.com/graphql/dataloader/issues/249. This caused us to have an [unwanted dependency on base.store
](https://github.com/vtex-sites/base.store/blob/master/src/server/index.ts#L2-L6). They issue has since been fixed in [version 2.1.0](https://github.com/graphql/dataloader/blob/main/CHANGELOG.md#210
). And we can get rid of it.
Test if the preview works as it should.
https://preview-493--base.preview.vtex.app/
=> Update dataloader to 2.1.0

docs/docs/reference/ui/atoms/Slider.mdx, docs/docs/reference/ui/molecules/Accordion.mdx, docs/docs/reference/ui/molecules/Banner.mdx, docs/docs/reference/ui/molecules/PriceRange.mdx, docs/docs/reference/ui/molecules/Table.mdx, packages/ui/src/molecules/Table/Table.test.tsx, themes/theme-b2c-tailwind/src/atoms/slider.css, themes/theme-b2c-tailwind/src/molecules/accordion.css, themes/theme-b2c-tailwind/src/molecules/banner.css, themes/theme-b2c-tailwind/src/molecules/price-range.css, themes/theme-b2c-tailwind/src/molecules/table.css
I've noticed that some components' styles were broken in our [documentation](https://www.faststore.dev/reference/ui/atoms/Slider) and found that we missed some updates after the changes made on this [PR](https://github.com/vtex/faststore/pull/1093) a while ago. 
We changed multiple components' data attributes to enforce a new pattern, and we removed `store` from the inner components/elements' data attributes. Still, we forgot to update them in some places.
Note: The `Card` component is also broken but addressed on another [PR](https://github.com/vtex-sites/gatsby.store/pull/34)
This PR should fix some styles and updates some docs.
||Before|After|
|-|-|-|
|`Accordion`|![before-accordion](https://user-images.githubusercontent.com/3356699/167970791-79e36597-2076-4cdc-bd90-0ec6436b9d1b.png)|![ …
=> Fix: Components styles and update data attributes 

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/loaders/sku.ts, packages/api/src/platforms/vtex/resolvers/query.ts
- Send selectetFacets to product query.
- When working with regionalized navigation we must filter the results and product commercial offers based on the user region. This PR aims to fix this behavior by sending the facets to search API.
1. Configure the store as qavivara
2. Then make the following query with and withou regionId.
```
query {
product(locator: [{key:"id",value:"172733622"},{key:"channel",value:"{\"salesChannel\":\"1\",\"regionId\":\"v2.F2A698AC85828A338E568B47F5566397\"}"}]) {
offers {
lowPrice
offers {
availability
price
listPrice
seller {
identifier
}
}
}
}
}
```
With the region the product must return theia vailability as InStock.
- https://github.com/vtex-sites/gatsby.store/pull/45
- https://github.com/vtex-sites/nextjs.store/pull/37
@igorbrasileiro
=> Send selectedFacerts product query

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/resolvers/product.ts
Fix broken breadcrumb links
This PR uses VTEX Catalog's `slugify` function to generate breadcrumb links so we don't get 404s while navigating through the store.
1. Open the product `/tasty-frozen-computer-80186276/p` on any of our starters. 
2. Click on the first breadcrumb link (Kitchen & Home Appliances)
3. On production, you will get a 404. After this PR, you will get to the category page
- https://github.com/vtex-sites/nextjs.store/pull/44
- https://github.com/vtex-sites/gatsby.store/pull/50
=> fix: Breadcrumb broken links

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/types/OrderForm.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts, packages/api/src/platforms/vtex/resolvers/objectOrString.ts, packages/api/src/platforms/vtex/resolvers/offer.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/platforms/vtex/resolvers/productGroup.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/platforms/vtex/utils/enhanceCommercialOffer.ts, packages/api/src/platforms/vtex/utils/propertyValue.ts, packages/api/src/typeDefs/index.ts, packages/api/src/typeDefs/objectOrString.graphql, packages/api/src/typeDefs/product.graphql, packages/api/src/typeDefs/propertyValue.graphql
This PR adds support for attachments on FastStore API. Attachments are a way to customize a product. If a product is added to the cart with a different attachment, a new offer should be created for it. An offer should be considered the same as another one if and only if the attachments (and its value) are also equal.
The attachments are included under the `additionalProperty` field, where they can be filtered through `valueReference` comparison. They are received in the same format they're sent.
JSON variables of the graphql query to the validateCart mutation:
```json
{
"cart": {
"order": {
"orderNumber": "911b0ceef77e4b98b9ca250a5d2fab2b",
"acceptedOffer": [
{
"price": 602.78,
"listPrice": 834.97,
"seller": {
"identifier": "1"
},
"quantity": 1,
"itemOffered": {
"sku": "2000586",
"image": …
```
=> Feat(api): add attachments

packages/sdk/src/storage/useStorage.ts
Update useStorage hook on focus.
IndexedDB is consistent across multiple windows. Sadly, we don't have a way of hooking into indexedDB to know when it has changed or not with our current dependencies, `idb-keyval`. 
To make the app consistent across multiple tabs, I propose the `onFocus` trick.  The idea is to update the stored value on `useStorage` hook each time the tab is focused. This way, we ensure when the user sees a tab, it's in a consistent state.
Open two tabs and add items to cart. Make sure the two carts display the same products.
More info at: https://vtex.slack.com/archives/C01AKAJDUEQ/p1653391800179519
- https://github.com/vtex-sites/nextjs.store/pull/58
- https://github.com/vtex-sites/gatsby.store/pull/58
=> feat: useStorage update onFocus

packages/api/mocks/AllProductsQuery.ts, packages/api/mocks/ProductQuery.ts, packages/api/mocks/SearchQuery.ts, packages/api/mocks/ValidateCartMutation.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/utils/channel.ts, packages/api/src/platforms/vtex/utils/contex.ts, packages/api/src/platforms/vtex/utils/facets.ts, packages/api/test/mutations.test.ts, packages/api/test/queries.test.ts, packages/api/test/schema.test.ts
Fixes top search results
Some accounts require the `?locale` being passed to the search API for it to return anything as suggestions. This PR requires the locale to be passed to the api so we forward this data to the search API.
Change account to `casinofr` and make the following query:
```
query Suggestions($selectedFacets: [IStoreSelectedFacet!]!) {
search(first: 10, term:"", selectedFacets: $selectedFacets) {
suggestions {
terms
products {
name
}
}
}
}
```
Make sure that when 
```
{
"selectedFacets": [
{
"key": "locale",
"value": "fr-FR"
}
],
}
```
you receive results. With 
```
{
"selectedFacets": [],
}
```
you receive nothing
- https://github.com/vtex-sites/nextjs.store/pull/71
- https://github.com/vtex-sites/gatsby.store/pull/69
=> fix: Top searches

.codesandbox/ci.json, .github/workflows/ci.yml, .github/workflows/release.yml, docs/package.json, package.json, yarn.lock
Somehow, docussaurus increased their minimal nodejs dependencies to 16.14. Since codesandbox supports nodejs up to 16.13, we needed to hard pin docussaurus dependency until codesandbox release support to a newer nodejs version. In the meanwhile,  this PR increases NodeJS version from 14.x to 16.x everywhere it is able to, fixing the following problems:
=> fix: Increase NodeJS version

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts
We were using a method that did not support the right product's sales channel etc for suggesting products. This PR addresses this issue by using the right method
- https://github.com/vtex-sites/gatsby.store/pull/73
- https://github.com/vtex-sites/nextjs.store/pull/74
=> fix: Product Suggestions

packages/api/local/server.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts, packages/api/src/typeDefs/query.graphql, yarn.lock
Adds suggestion term's popularity count to GraphQL API
Currently, we can query for term suggestions and top searches. However, there's no way to know the occurrences of these terms. I propose changing `StoreSuggestions.term` from `string[]` to `Array<{value: string, count: number}>`. 
Try the following query:
```
query Suggestions {
search(first: 10, term: "") {
suggestions {
terms {
value
count
}
}
}
}
```
You should get something like:
```
{
"data": {
"search": {
"suggestions": {
"terms": [
{
"value": "salad",
"count": 473
},
{
"value": "monitor",
"count": 472
},
{
"value": "cotton",
"count": 467
}
]
}
}
}
}
```
- https://github.com/vtex-sites/nextjs.store/pull/73
- https://github.com/vtex-sites/gatsby.store/pull/71
=> feat: Search suggestions term count

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/typeDefs/propertyValue.graphql
When adding a product to cart with additionalProperties we were receiving the following error:
```
GraphQLError [Object]: Variable "$additionalProperty" got invalid value { propertyID: "4ba0a4d37b7f733da5ddb281ea50d883", name: "activeSubscriptions", value: "abonnements", valueReference: "SPECIFICATION" }; Field "propertyID" is not defined by type IStorePropertyValue.
```
This PR addresses this issue
- https://github.com/vtex-sites/nextjs.store/pull/75
- https://github.com/vtex-sites/gatsby.store/pull/74
=> fix: Cart item with additionalProperty

.github/workflows/ci.yml, .github/workflows/release.yml
Using turborepo cache at Vercel
=> feat: using cache

packages/sdk/src/cart/Cart.tsx, packages/sdk/src/search/Provider.tsx, packages/sdk/src/ui/Provider.tsx, packages/ui/src/atoms/Slider/Slider.tsx, packages/ui/src/atoms/Spinner/Spinner.tsx, packages/ui/src/molecules/Carousel/Carousel.tsx
Fix some typescript errors detected on the build
This PR adds the types to fix the errors
yarn build on the root
=> fix: some ts errors

packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts, packages/api/src/platforms/vtex/utils/productStock.ts
SKUs can have multiple sellers. We have an heuristic for choosing the best seller. This is written on [bestOfferFirst](https://github.com/vtex/faststore/blob/779174d8a957e2f339af68b7f65e26c330f1533d/packages/api/src/platforms/vtex/utils/productStock.ts#L14) function.This function sorts the smallest available spotPrice first. 
The issue we had is that AggregateOffers's low/hight price was returning the `sellingPrice` instead of the `spotPrice`, making the values inconsistent. 
This PR addresses this issue by making low/high price return the same properties used on `bestOfferFirst`
- https://github.com/vtex-sites/nextjs.store/pull/111
- https://github.com/vtex-sites/gatsby.store/pull/102
=> fix: Spot pricing sort for lowPrice/highPrice

packages/api/mocks/AllProductsQuery.ts, packages/api/mocks/ProductQuery.ts, packages/api/mocks/SearchQuery.ts, packages/api/mocks/ValidateCartMutation.ts, packages/api/src/platforms/vtex/clients/search/index.ts
Add fuzzy auto to search to handle misspelled query
=> Add fuzzy auto

packages/api/test/mutations.test.ts, packages/api/test/queries.test.ts
Testing `@faststore/api` has an issue where the mocked fetch is called less than the expected amount of times, making some tests break.
This is because we store our clients on the GraphQL `context`. Since these clients use `Dataloader`  and we were not recycling them on each tests, some requests were being cached and thus, the mocked fetch was called less than the right amount of times. 
This PR creates a `runner` function that re-creates the GraphQL context before each test so we have a more similar environment to the one we use in production, where a new context is created for each request
=> fix: api test inconsistencies

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/Portal.ts, packages/api/src/platforms/vtex/loaders/sku.ts, packages/api/src/platforms/vtex/resolvers/offer.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/resolvers/seo.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/platforms/vtex/utils/canonical.ts, packages/api/src/platforms/vtex/utils/facets.ts, packages/api/src/platforms/vtex/utils/orderStatistics.ts, packages/api/src/platforms/vtex/utils/sku.ts, packages/api/test/__snapshots__/queries.test.ts.snap
This PR implements [PDP slugs RFC](https://docs.google.com/document/d/1wrg-WYSLWlsdFqiuS845ZEdP94KNcbYuL9vJm4P_rAo/edit?usp=sharing). 
Both FastStore and VTEX's PDP's paths are under `/[slug]/p`. The difference is what's inside this slug. On VTEX, the slug is the slugified product name, whereas at FastStore: 
```
fastStoreSlug = `${vtexSlug}-${skuId}`
```
The goal of this PR is to implement a 301 redirect between `vtexSlug` -> `fastStoreSlug` so that stores migrating to FastStore from VTEX don't need to worry about SEO or analytics reports
The main idea for implementing this is to make `Query.product` accept the `slug` locator. This slug locator returns the product in case the slug is a `fastStoreSlug`. If the slug is a `vtexSlug` a `RedirectError` is thrown. This `RedirectError` is …
=> feat: Canonical PDP slugs

apps/docs/docusaurus.config.js, packages/api/src/__generated__/schema.ts, packages/api/tsconfig.json, packages/graphql-utils/tsconfig.json, packages/sdk/package.json, packages/sdk/tsconfig.json, packages/ui/package.json, packages/ui/tsconfig.json, yarn.lock
=> fix: add outdir to all tsconfig

packages/api/src/__generated__/schema.ts, packages/graphql-utils/tsconfig.json, packages/lighthouse/tsconfig.json
After changing TypeScript target, @faststore/graphql-utils started being built with `es modules`. This caused the following issue on the stores:
```
[BABEL]: Cannot use import statement outside a module (While processing: ~/vtex-sites/gatsby.store/node_modules/@faststore/graphql-utils/babel.js)
``` 
changing it to `commonjs` should fix the issue
=> fix: @faststore/graphql-utils

packages/ui/src/molecules/PriceRange/PriceRange.tsx
This PR intends to fix `PriceRange` track position for max absolute values higher than 100.
=> fix: `PriceRange` track position

.git-blame-ignore-revs
```
🧹  This is more for Git housekeeping than the FastStore itself.
```
Create a `.git-blame-ignore-revs` file to list commits that should be ignored from the blame view. This is useful to remove the noise introduced by aesthetic changes such as code formatting: when viewing the blame for a file, we can omit commits that only changed formatting/indentation so we can quickly see what matters.
I had [mentioned](https://github.com/vtex/faststore/pull/1369#pullrequestreview-1010810389) that https://github.com/vtex/faststore/pull/1369 was a good candidate to test this feature (that is relatively new in GH, not Git itself).
By adding a commit SHA/ID to be ignored in the `.git-blame-ignore-revs` file.
See how on _Before_ the changes from the commit "fix: prettier format files", which were only …
=> chore: Improve blame view by ignoring formatting from Prettier

.github/CODEOWNERS
A [@vtex/faststore][1] team (13 members) has been recently created so we can remove [@vtex/store-framework][2] (23 members) to keep things organized and avoid notifying unrelated people.
[1]: https://github.com/orgs/vtex/teams/faststore
[2]: https://github.com/orgs/vtex/teams/store-framework
=> chore: Remove @store-framework from CODEOWNERS (keep @faststore)

CONTRIBUTING.MD, apps/docs/docs/reference.md, generators/plopfile.ts, packages/graphql-utils/README.md, packages/ui/.storybook/main.js, packages/ui/.storybook/preview-head.html, packages/ui/.storybook/preview.js, packages/ui/package.json, yarn.lock
Housekeeping PR.
https://github.com/vtex/faststore/pull/1326
https://github.com/vtex/faststore/pull/1379
https://github.com/vtex/faststore/pull/1296
=> Chore: Housekeeping module name references

apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md
Our instructions on how to extend the base GraphQL schema from `@faststore/api` don't fully work on the current setup we have on `gatsby.store`. This PR updates them 😄 .
=> docs: Update docs on how to extend `@faststore/api`'s schema

packages/ui/src/atoms/Slider/Slider.tsx, packages/ui/src/molecules/PriceRange/PriceRange.tsx
This PR intends to add the `step` prop to the `Slider` component and be adjustable on starters. Also, it fixes `Slider`'s input range values to display only integer/precise number values.
Related to [`nextjs.store`'s PR #146](https://github.com/vtex-sites/nextjs.store/pull/146)
=> chore: `Slider` improvements

packages/ui/src/atoms/Slider/Slider.tsx
This PR intends to fix a `PriceRange` case that absolute values are decimals, breaking input integer values.
=> fix: Round `Slider` absolute values

packages/ui/src/atoms/Slider/Slider.tsx
This PR intends to fix `Slider` thumb elements position in DOM so then it can have customized behavior states on starters.
=> fix: `Slider` thumb elements position

packages/styles/src/molecules/index.css, packages/styles/src/molecules/product-title.css, packages/ui/src/index.ts, packages/ui/src/molecules/ProductTitle/ProductTitle.tsx, packages/ui/src/molecules/ProductTitle/index.tsx, packages/ui/src/molecules/ProductTitle/stories/ProductTitle.mdx, packages/ui/src/molecules/ProductTitle/stories/ProductTitle.stories.tsx
This PR is part of the Component Placement project, to bring some components from starters.
This PR places the `ProductTitle` component to Faststore with new data-attributes.
Tests will be implemented in next step of Component Placement 
[Move ProductTitle component to FastStore](https://vtex-dev.atlassian.net/browse/FS-358)
=> feat: Add ProductTitle Molecule

packages/styles/src/organisms/index.css, packages/styles/src/organisms/tiles.css, packages/ui/src/index.ts, packages/ui/src/organisms/Tiles/Tile.tsx, packages/ui/src/organisms/Tiles/Tiles.tsx, packages/ui/src/organisms/Tiles/index.ts, packages/ui/src/organisms/Tiles/stories/Tiles.mdx, packages/ui/src/organisms/Tiles/stories/Tiles.stories.tsx
Extract the `Tiles` and `Tile` component from the [starters](https://github.com/vtex-sites/nextjs.store/tree/81b2cbcae8157703130ab18356178cb15c8bcf12/src/components/ui/Tiles) and move it to the `@faststore/ui` package.
Run `yarn storybook` locally and check the [`Tiles` component page](http://localhost:6006/?path=/docs/organisms-tiles--tiles).
Its Storybook page:
The same component being used on the starter:
- https://github.com/vtex-sites/nextjs.store/pull/185 and the [deploy preview](https://preview-185--nextjs.preview.vtex.app/)
=> refactor: Import the `Tiles` & `Tile` components from the starter

package.json, yarn.lock
See [the last merge commit](https://github.com/vtex/faststore/commit/2ee105ca2c335e1a7dad60efa55f29cfdc587c22) in https://github.com/vtex/faststore/commits/main. Its **CD / FastStore (push)** check failed with an error [`lerna ERR! EPRESET Unable to load conventional-changelog preset 'conventionalcommits' (conventional-changelog-conventionalcommits)`](https://github.com/vtex/faststore/runs/7619824436?check_suite_focus=true#step:10:41).
We had recently changed the changelog preset from `angular` to `conventionalcommits` in https://github.com/vtex/faststore/pull/1425, but didn't get to test if it worked till now. _I think_ it may be because we didn't install this [`conventional-changelog-conventionalcommits`](https://github.com/conventional-changelog/conventional-changelog/tree/bfe3bf1c49d4a …
=> chore: Attempt to fix the publishing

packages/api/src/platforms/vtex/resolvers/collection.ts
This PR aims to solve issues users were facing trying to fetch the field `StoreCollection.breadcrumbList` for collection pages.
Adds a new check for collection pages in the step that precedes the requests we make to figure out the pagetype for a certain route, inside the `breadcrumbList` field resolver. 
Using the same test case from https://community.vtex.com/t/problemas-nas-rotas-de-collection-clusters/33353/4.
- Clone this branch locally;
- Update the account found at `src/packages/api/local/index.ts` to `homologappoffpremium`;
- Run `yarn develop` inside `src/packages/api`;
- Run the following query:
```graphql
{
collection(slug: "novidades-feminino") {
slug
seo {
title
description
}
meta {
selectedFacets {
key
value
}
}
breadcrumbList {
itemListElement {
name
item
position
} …
```
=> fix: Take collection pages into account on `slugifyRoot` function

packages/api/local/server.ts, packages/api/mocks/skuVariants.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/resolvers/productGroup.ts, packages/api/src/platforms/vtex/resolvers/skuVariations.ts, packages/api/src/platforms/vtex/utils/skuVariants.ts, packages/api/src/typeDefs/index.ts, packages/api/src/typeDefs/productGroup.graphql, packages/api/src/typeDefs/skuVariants.graphql, packages/api/test/vtex.skuVariants.test.ts
This PR adds a new attribute (`skuVariations`) to the `ProductGroup` type, that brings with it 4 new properties:
- `slugsMap`
- `availableVariations`
- `allVariantsByName`
- `activeVariations`
They should enable users to query data about SKU specification variants in a more convenient way. Specially handy for implementing SKU Selector components.
The new fields added to `ProductGroup` are all related to SKU variants.
**slugsMap** -> Maps property value combinations to their respective SKU's slug. Enables us to retrieve the slug for the SKU that matches the currently selected variations in `O(1)` time.
**activeVariations** -> SKU property values for the current SKU.
**availableVariations** -> Available options for each varying SKU property, taking into account the `dominantVariantName` …
=> feat: Add skuSelector-related properties to ProductGroup type

packages/api/src/platforms/vtex/resolvers/validateCart.ts
This PR improves the Cart UX by resolving edge cases related to cart item split.
Checkout API has a concept called orderForm. OrderForm has everything related to your current cart. It has, for instance, the items your are currently purchasing. These items are implemented using an array. For rendering the cart, you would only need to map through the array's items, rendering the products accordingly. If you follow this algorithm, however, you will end up with a poor UX because items can be split in the Checkout API, making you render the same product repeatedly.
Let's suppose your are buying a banana and a special promotion is applied, decreasing 50% the price of the second item purchased. By adding the second banana to cart, you would receive the following array back from Checkout API
``` …
```
=> fix: Join cart items 

packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/resolvers/product.ts, packages/api/src/typeDefs/product.graphql
This PR is a one liner that returns the product's release date using [schema.org's field](https://schema.org/Product) on Product entity. This should fix this [issue](https://vtex.slack.com/archives/C0164SHMAV9/p1659473353883529)
- nextjs.store https://github.com/vtex-sites/nextjs.store/pull/207
I tried adding this to gatsby too, however, gatsby library does not accept releaseDate as input
- [schema.org releaseDate field](https://schema.org/releaseDate)
=> feat: Product releaseDate

.github/workflows/release.yml, packages/gatsby-plugin-nginx/src/nginx-generator.ts, packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
As we're moving some redirects away from cloudfront, we might encounter cases where the header reaching the applications are too large. This raises the limit to a comfortable size.
We did this manually to solve issues on some clients and here on a [previous version](https://github.com/vtex/faststore/commit/55341290bd192b9e6de141cb08080ec2f9fc1017) of this plugin.
=> Add 32k header limit to nginx-generator

apps/docs/blog/2022-08-05-faststore.md, apps/docs/docs/how-to-guides/faststore-api/explore-the-faststore-api.mdx, apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md, apps/docs/docs/how-to-guides/faststore-api/fetching-api-data.mdx, apps/docs/docs/how-to-guides/faststore-api/using-graphiql-to-explore-the-faststore-api.mdx
The section names were inverted. Only Gatsby provides **GraphiQL** to explore the API via http://localhost:8000/__graphql. Our NextJS starter doesn't provide something similar, so the section about using **GraphQL Playground** is more suitable for it. 
I also suggested renaming the title to "GraphQL IDEs" instead of just "GraphiQL" because the latter is only used in Gatsby. 
@vtex/tech-writers feel free to revert/undo/add changes!
Before|After
-|-
[Link](https://faststore-git-docs-improvementextending-schema-ad066c-faststore.vercel.app/how-to-guides/faststore-api/using-graphiql-to-explore-the-faststore-api)|[Link](https://faststore-git-docs-graphql-ide-faststore.vercel.app/how-to-guides/faststore-api/using-graphiql-to-explore-the-faststore-api)
- …
=> docs: Fix NextJS and Gatsby sections on using a GraphQL IDE

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/typeDefs/mutation.graphql
This PR replicates session info on cart, making it possible for checkout to use the same zip code the user entered during the regionalization phase.
This PR adds a new argument to validateCart mutation called `session`. This is the same argument `validateSession` uses. With this info, we can use checkout's `addShippingAddress` mutation to add the user's session info to the orderForm, making:
1. Shopping flow consistent between storefront and checkout
2. Prices are regionalized 
Open your favorite starter and
1. Open store.config and switch storeframework to casinofr account, and session to:
```
session: {
currency: {
code: 'EUR',
symbol: '$',
},
locale: 'fr-FR',
channel: '{"salesChannel":"1","regionId":""}',
country: 'FRA',
postalCode: null,
person: null,
},
```
2. Visit …
=> feat: Cart with session info

packages/styles/src/molecules/gift.css, packages/styles/src/molecules/index.css, packages/ui/src/index.ts, packages/ui/src/molecules/Gift/Gift.test.tsx, packages/ui/src/molecules/Gift/Gift.tsx, packages/ui/src/molecules/Gift/GiftContent.tsx, packages/ui/src/molecules/Gift/GiftImage.tsx, packages/ui/src/molecules/Gift/index.tsx, packages/ui/src/molecules/Gift/stories/Gift.mdx, packages/ui/src/molecules/Gift/stories/Gift.stories.tsx
- Adds `Gift` component.
Run `yarn storybook` locally and check the [Gift component page](http://localhost:6006/?path=/docs/molecules-gift--gift).
[Gift - NextJS Storybook](https://nextjs-store-storybook-git-feat-fs-552-gift-component-faststore.vercel.app/?path=/docs/molecules-gift--default-story)
[FS - 552 Create Gift component](https://vtex-dev.atlassian.net/browse/FS-552?atlOrigin=eyJpIjoiYzc4ZThjZGQyMGYzNDRhNmJiOGRjODBmYmY4N2ZjYzgiLCJwIjoiaiJ9)
=> feat: Add `Gift` component

packages/styles/src/molecules/index.css, packages/styles/src/molecules/order-summary.css, packages/ui/src/index.ts, packages/ui/src/molecules/OrderSummary/OrderSummary.test.tsx, packages/ui/src/molecules/OrderSummary/OrderSummary.tsx, packages/ui/src/molecules/OrderSummary/index.tsx, packages/ui/src/molecules/OrderSummary/stories/OrderSummary.mdx, packages/ui/src/molecules/OrderSummary/stories/OrderSummary.stories.tsx
Adds OrderSummary component to FastStore UI
This component was migrated from nextjs.store. 
[See the starter PR](https://github.com/vtex-sites/nextjs.store/pull/238)
https://github.com/vtex-sites/nextjs.store/pull/238
=> feat: Adds OrderSummary component to FastStore UI

packages/styles/src/molecules/index.css, packages/styles/src/molecules/sku-selector.css, packages/ui/src/index.ts, packages/ui/src/molecules/SkuSelector/SkuSelector.test.tsx, packages/ui/src/molecules/SkuSelector/SkuSelector.tsx, packages/ui/src/molecules/SkuSelector/index.tsx, packages/ui/src/molecules/SkuSelector/stories/SkuSelector.mdx, packages/ui/src/molecules/SkuSelector/stories/SkuSelector.stories.tsx
Extract the `SkuSelector` component from our starter to `@faststore/ui`.
Run `yarn storybook` and check the new `SkuSelector` entry at http://localhost:6006/?path=/story/molecules-skuselector--sku-selector
- https://preview-240--nextjs.preview.vtex.app/apple-magic-mouse-99988212/p
- https://vtex-dev.atlassian.net/browse/FS-248 (internal)
- https://github.com/vtex-sites/nextjs.store/pull/240
=> refactor: Extract `SkuSelector` component from the starter

packages/styles/src/molecules/cart-item.css, packages/styles/src/molecules/index.css, packages/ui/src/index.ts, packages/ui/src/molecules/CartItem/CartItem.test.tsx, packages/ui/src/molecules/CartItem/CartItem.tsx, packages/ui/src/molecules/CartItem/CartItemActions.tsx, packages/ui/src/molecules/CartItem/CartItemContent.tsx, packages/ui/src/molecules/CartItem/CartItemImage.tsx, packages/ui/src/molecules/CartItem/CartItemPrices.tsx, packages/ui/src/molecules/CartItem/CartItemSummary.tsx, packages/ui/src/molecules/CartItem/CartItemTitle.tsx, packages/ui/src/molecules/CartItem/index.tsx, packages/ui/src/molecules/CartItem/stories/CartItem.mdx, packages/ui/src/molecules/CartItem/stories/CartItem.stories.tsx, packages/ui/src/molecules/QuantitySelector/stories/QuantitySelector.mdx
Extract the `CartItem` component from our starter to `@faststore/ui`.
Run `yarn storybook` and check the new `CartItem` entry at http://localhost:6006/?path=/story/molecules-cartitem--default.
Check https://sfj-4a90f81--nextjs.preview.vtex.app/4k-philips-monitor-99988213/p from https://github.com/vtex-sites/nextjs.store/pull/239. Add a product to the min-cart and you should see the `CartItem` being rendered in the sidebar.
- https://vtex-dev.atlassian.net/browse/FS-361 (internal)
- https://github.com/vtex-sites/nextjs.store/pull/239
=> refactor: Extract `CartItem` component from the starter

apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md
Correctly use resolvers in the schema extension.
Resolvers are being misused when merging schemas.
When you do this extension:
```ts
// src/server/index.ts file
const typeDefs = `
type Query {
numberSix: Int! # Should always return the number 6 when queried
numberSeven: Int! # Should always return 7
}
`
const resolvers = {
Query: {
numberSix() {
return 6
},
numberSeven() {
return 7
},
},
}
const nativeApiSchema = getSchema(apiOptions)
const mergedTypeDefs = mergeTypeDefs([getTypeDefs(), typeDefs])
const getMergedSchemas = async () =>
mergeSchemas({
schemas: [
await nativeApiSchema,
makeExecutableSchema({
resolvers,
typeDefs: mergedTypeDefs,
}),
],
resolvers,
})
export const apiSchema = getMergedSchemas()
```
so when you extend the schema and try to run your new query, you will get this …
=> docs: fix extending graphql example

packages/ui/src/molecules/Accordion/AccordionItem.tsx, packages/ui/src/molecules/Accordion/stories/Accordion.mdx, packages/ui/src/molecules/Table/Table.tsx
This PR improves extensibility of both table and accordion molecules.
It makes accordions items polymorphic, which means any HTML element (such as `article`) can be used to render the item.
I'll open a PR referencing this PR on the nextjs.store starter.
TBD
=> feat(ui): improve extensibility of table and accordion molecules

packages/ui/tsconfig.json
This PR fixes a bug introduced to the `TableProps` type in https://github.com/vtex/faststore/pull/1470 but that was possibly present before in other components. In the other PR, `TableProps` were changed so that they could extend all of `<table>` native HTML properties.
When I went to use these new props, I was faced with a new, unexpected required prop: `css`. That was weird because none of the native types introduced this variable.
Searching the internet, I found [this article](https://stackoverflow.com/a/71737324/6352590) explaining it was caused by Storybook types being considered by TS during the build process. So I should just exclude `.stories.tsx` in `tsconfig.json` and everything would work, except it was already being excluded 🤡 . 
So I went searching for any imports from …
=> fix(ui): fixes tsconfig.json to exclude storybook types inside .d.ts file

packages/api/src/directives/cacheControl.ts, packages/api/src/directives/index.ts, packages/api/src/index.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/typeDefs/query.graphql
This PR adds the `@cacheControl` directive to the graphql schema of `@faststore/api`
`@cacheControl` directive is implemented using graphql-tools package and allows three main arguments, `scope`, `sMaxAge` and `staleWhileRevalidate`
When the directive is found multiple times in the query execution, a no-cache strategy is used. This strategy uses the minimal number and scope. For instance, if two directives are found during the query execution, one with `sMaxAge=10` and another with `sMaxAge=100`, the final computed `sMaxAge` will be 10s. The same is valid for the scope, where `private` is preffered over `public`.
When no cacheControl is provided or when an error occurs, a `no-cache, no-store` should be returned
Open one of the starters below and make sure the responses for product queries …
=> feat: Add CacheControl GraphQL directive

packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts
This PR fixes wrong typings on the Search API. A nice side effect is fixing the following error:
```
error TypeError: Cannot read properties of undefined (reading 'misspelled')
at Object.products (//.cache/functions/graphql.js:29161:41)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
at async Promise.all (index 0)
at //.cache/functions/graphql.js:31422:23
at handler (//.cache/functions/graphql.js:32146:20)
at //node_modules/gatsby/src/commands/serve.ts:228:13 {
locations: [ { line: 9, column: 5 } ],
path: [ 'search', 'products' ]
}
```
=> fix: Wrong typings on search API

packages/api/src/platforms/vtex/clients/sp/index.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts
To generate the top searches results correctly, we need to feed the search system with searches being performed by real users on the website. The data generation was missing the user's locale, so when fetching top searches we received an empty result.
This PR adds the locale to the data feed so we can fetch the right top searches
Make sure you can see top searches results being returned after the upgrade
- https://github.com/vtex-sites/nextjs.store/pull/264
https://github.com/vtex/sae-analytics/blob/master/react/index.tsx#L130-L135
=> fix: Top searches locale

apps/docs/docs/reference/ui/molecules/SearchInput.mdx, packages/styles/src/molecules/search-input.css, packages/ui/src/molecules/SearchInput/SearchInput.test.tsx, packages/ui/src/molecules/SearchInput/SearchInput.tsx, packages/ui/src/molecules/SearchInput/stories/SearchInput.mdx
This PR intends to rename the `SearchInput`s form data-attribute to avoid duplicates in the stores.
=> fix: Rename `SearchInput`'s form data-attribute

packages/api/src/platforms/vtex/resolvers/validateCart.ts
This PR fixes a null pointer exception call on the update shipping data request. If the session was null or undefined, the `validateCart` mutation would try to update it anyways.
It checks if the session is null, and if so, returns the orderform, which was the previous behavior of the API.
=> fix: checks for session existance before trying to update shipping data

packages/api/src/platforms/vtex/resolvers/validateCart.ts
This PR fixes the following flow:
1. User adds item to cart
2. User goes to checkout
3. User fills shipping address
4. User goes back to the store and adds more items to cart
Before this PR, we only checked the difference between previous and current postal code. Turns out, that we also need to check for the validity of this postal code. This PR does just that and only changes the shipping address if it's defined, fixing the aforementioned issue.
The images bellow show the validateCart mutation before/after this PR is applied. To reproduce it, follow the flow described on the first section.
- https://github.com/vtex-sites/nextjs.store/pull/279
=> fix: Bad postal code on shipping data

packages/cli/package.json, packages/cli/src/commands/dev.ts, packages/cli/src/utils/root.ts, yarn.lock
This PR adds watch capability to the dev command.
It uses [chokidar](https://www.npmjs.com/package/chokidar), a library that wraps the default `fs.watch` function and fixes its issues. We followed the same logic [VTEX Toolbelt](https://github.com/vtex/toolbelt) uses to watch for file changes while a project is linked.
Currently, it does nothing with those changes besides logging it into the terminal.
Add a `console.log` call in the `queueChange` function to see the `path` variable. Build the project, add the bin folder to the PATH variable of your terminal and then execute `run dev` on your FastStore Store. Whenever you change your code, you'll be able to see the path of the file you changed logged in the terminal. The same is valid for file creation and removal.
=> feat: Add watch capability to dev command

packages/api/src/platforms/vtex/resolvers/validateSession.ts
This PR was created to address a problem found when defining a region with a sales channel. 
Without this change the result of the validateSession mutation for a given region and sales channel was:
```
{
"data": {
"validateSession": {
...
"channel": "{\"salesChannel\":\"4\",\"regionId\":\"U1cj\"}",
}
}
}
```
While with this change it returns the needed value:
```
{
"data": {
"validateSession": {
...
"channel": "{\"salesChannel\":\"4\",\"regionId\":\"U1cjdGF0YXV5c2FsdG87dGF0YXV5c2VsbGVyY3Jvc3NtZXJjYWRv\"}",
}
}
}
```
Before this change, the code was not taking in consideration the sales channel at the params to get the region.
- At `server.ts` use tata configuration as apiOptions:
```
const apiOptions = {
platform: 'vtex',
account: 'tatauy',
locale: 'en-US',
environment: …
```
=> Fix: Takes sales channel in consideration when getting region

.codesandbox/ci.json, packages/cli/src/commands/dev.ts, packages/cli/src/utils/directory.ts, packages/cli/src/utils/generate.ts
This PR makes the faststore dev command run a NextJS development server on the starter.
It calls bun develop in the generated folder as a subprocess, which gives us a live store.
Run this CLI (`yarn add https://pkg.csb.dev/vtex/faststore/commit/3d59496/@faststore/cli` and then `yarn dev`) on the [starter.store](https://github.com/vtex-sites/starter.store) repo. You should see a local NextJS development server spawned.
=> feat: adds develop command when running faststore dev

packages/cli/src/commands/build.ts
Adds build command to the CLI
It calls the generate function and spawns the build process.
Run yarn add `https://pkg.csb.dev/vtex/faststore/commit/f5b0b51/@faststore/cli` and then `yarn build`. The build process should run and you should be able to see the build inside the `.faststore/.next` folder.
=> Feat: add build command

packages/cli/src/commands/start.ts
Adds start command to the CLI
It checks if the `.faststore` folder exists and spawns the `serve` process.
Run yarn add `https://pkg.csb.dev/vtex/faststore/commit/2724d45/@faststore/cli` and then `yarn start`. The local server should be spawned and you should be able to browse your production build at `localhost:3000`.
=> feat: adds start command to serve stores

apps/docs/docs/reference/ui/atoms/Badge.mdx, apps/docs/docs/reference/ui/atoms/Button.mdx, apps/docs/docs/reference/ui/atoms/Checkbox.mdx, apps/docs/docs/reference/ui/atoms/Radio.mdx, apps/docs/docs/reference/ui/molecules/CheckboxField.mdx, apps/docs/docs/reference/ui/molecules/IconButton.mdx, apps/docs/docs/reference/ui/molecules/RadioField.mdx, apps/docs/src/css/custom.css
To improve the readability of the example provided in our documentation. I added specific classes to style the overview section instead of using inline CSS.
Before|After|
|-|-|
|<img width="664" alt="image" src="https://user-images.githubusercontent.com/3356699/205959452-16fd9215-786e-42f0-ade1-1f6b7c67021a.png">|<img width="608" alt="image" src="https://user-images.githubusercontent.com/3356699/205959541-b8091d79-0638-4fb9-b845-d055899595fe.png">|
=> Docs: Adds overview section classes

packages/cli/package.json, packages/cli/src/utils/generate.ts, yarn.lock
This PR aims to use chalk lib to make our faststore cli messages beautiful.
It also organizes the messages and sorts some imports alphabetically.
|Before|After|
|-|-|
|<img width="575" alt="Screen Shot 2022-12-08 at 20 13 13" src="https://user-images.githubusercontent.com/11325562/206586563-1ba8f428-747b-4d56-be7f-8dad35cda408.png">|<img width="544" alt="Screen Shot 2022-12-08 at 20 12 25" src="https://user-images.githubusercontent.com/11325562/206586483-ef6677dd-b53d-4751-9c7c-303b57f4ca97.png">|
- you can run locally by running `yarn build` inside the cli package, adding the bin folder to your `$PATH`, and running `run dev` inside the `starter.store`.
Chalk - https://github.com/chalk/chalk
Starter store - https://github.com/vtex-sites/starter.store
=> Feat: Beautify CLI messages with chalk

packages/components/src/molecules/SelectField/SelectField.tsx
This PR intends to fix `nextjs.store` integration tests by passing `data-testid` to the right component in `SelectField`.
[Nextjs.store PR #323](https://github.com/vtex-sites/nextjs.store/pull/323)
=> fix: Starter's Integration tests

packages/cli/src/utils/generate.ts
When the `src/theme/soft-blue.scss` file does not exist it causes an error in the console:
```cmd
error - Error: ENOENT: no such file or directory, copyfile '/src/theme/soft-blue.scss' -> '.faststore/src/customizations/themes/index.scss'
```
So I solved that problem and added some validations, like:
When you have the file, but it has not been added to the store.config.js file, the terminal displays this message:
```cmd
info - The theme needs to be added to the config file to be applied
```
When you don't have the file, but it is added to store.config.js, the terminal displays this message:
```cmd
info - The soft-blue theme was added to the config file but the soft-blue.scss file does not exist in the themes folder
```
When the file exists and has been added to the configuration, the …
=> fix: cli copy theme

apps/docs/docs/reference/ui/organisms/Hero.mdx, packages/ui/src/components/organisms/Hero/styles.scss
follow-up of https://github.com/vtex/faststore/pull/1556
- Adds missing style
- Fixes Hero image example
- Updates Hero doc page
|Before|After|
|-|-|
|<img width="853" alt="image" src="https://user-images.githubusercontent.com/3356699/208460424-1700b365-fbac-43de-9462-ea016e13a687.png">|<img width="801" alt="image" src="https://user-images.githubusercontent.com/3356699/208460614-908632f9-ff29-4d47-b74b-2cad79e58c5b.png">
You can test through the [preview link](https://faststore-git-fix-hero-component-faststore.vercel.app/reference/ui/organisms/Hero)
=> Fix: `Hero` component

apps/site/pages/components/molecules/table.mdx, packages/ui/src/components/molecules/Table/styles.scss
Tiny fix to support colored tables with only 1 row.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/11613011/210876718-98c5f924-dd3f-4886-a88f-ba8e382f886e.png)|![image](https://user-images.githubusercontent.com/11613011/210876597-00193f1d-6864-46de-8e07-4c9307f1866c.png)|
=> Chore: Updates `Table` Colored Variant

packages/ui/src/components/molecules/AggregateRating/AggregateRating.tsx, packages/ui/src/components/molecules/OrderSummary/OrderSummary.tsx
This PR intends to fix the `OrderSummary` and `AggregateRating` interfaces, extending them from the HTML `ul` element instead of `ListProps`.
This is necessary because each of these components works like regular lists, they use the `List` component, but they have their own specificities and don't require to extend from our base `List` component.
[chore: Replace Table using FSUI #341](https://github.com/vtex-sites/nextjs.store/pull/341)
=> fix: `OrderSummary` and `AggregateRating` interfaces

apps/site/pages/components/atoms/button.mdx, apps/site/pages/components/atoms/label.mdx, apps/site/pages/components/atoms/select.mdx, apps/site/pages/components/molecules/checkbox-field.mdx, apps/site/pages/components/molecules/discount-badge.mdx, apps/site/pages/components/molecules/input-field.mdx, apps/site/pages/components/molecules/radio-field.mdx, apps/site/pages/components/molecules/select-field.mdx, apps/site/pages/components/molecules/tag.mdx, apps/site/pages/components/molecules/toggle-field.mdx, apps/site/pages/components/molecules/toggle.mdx, apps/site/pages/components/organisms/hero.mdx
- Adds missing `Hero` component doc page
- Updates docs overview section (with code example tabs)
[Hero doc page preview](https://faststore-site-git-docs-add-hero-component-doc-faststore.vercel.app/components/organisms/hero)
=> Docs: Adds `Hero` component doc + Updates docs overview section

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/Region.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/resolvers/offer.ts, packages/api/src/platforms/vtex/resolvers/validateSession.ts, packages/api/src/platforms/vtex/utils/channel.ts, packages/api/src/platforms/vtex/utils/facets.ts, packages/shared/tsconfig.json
This PR makes it possible to use `@faststore/api` by selecting a specific seller. This seller is kept both during add to cart and navigation.
A new dimension was added to `channel` called `seller`.  When `seller` is selected, all navigation will be done given this seller. Add to cart will also use the given seller from session.
To convert your store to this behavior, check out how it's done in [here](https://github.com/vtex-sites/casinofr.store/blob/f6a1bfc653d209caed33fd3e41f6b41326d9ad74/src/components/regionalization/contexts/RegionalizationContext.tsx#L123) 
Open this [preview](https://sfj-f6a1bfc--casinofr.preview.vtex.app/). Select a give store. Make sure prices and cart are kept consistent across the buying process.
- https://github.com/vtex-sites/nextjs.store/pull/294
=> feat: Add seller dimension to channel

packages/api/src/platforms/vtex/utils/sku.ts
Error 
Sometimes the items returned by the product query flow don't have sellers, and this function is broken with the error aforementioned on [this line](https://github.com/vtex/faststore/blob/main/packages/api/src/platforms/vtex/utils/sku.ts#L22). 
More details about how to debug [here in this document](https://docs.google.com/document/d/1MTLWhGS5f97YoHtvEOTD2EAONQIOZGcAq-sJVwr5qPc/edit).
More details about how to debug [here in this document](https://docs.google.com/document/d/1MTLWhGS5f97YoHtvEOTD2EAONQIOZGcAq-sJVwr5qPc/edit).
=> fix: checks best sku existence

packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts, packages/api/src/typeDefs/query.graphql, yarn.lock
This PR solves blank intelligent search reports
Returns necessary info so the event can be sent on the front end, instead of the API. This makes for more accurate events, fired the correct amount of times with the appropriate data attached to them.
Filter network calls by "sp" and use the search bar on the website. You should see events with the term and other query information.
https://github.com/vtex-sites/nextjs.store/pull/373
=> fix: add metadata to search query

apps/site/components/Icon/Icon.tsx, apps/site/components/Icon/IconList.tsx, apps/site/components/Icon/icon.module.css, apps/site/components/Icon/index.ts, apps/site/pages/components/atoms/icon.mdx, apps/site/pages/docs/_meta.json, apps/site/pages/docs/icons.mdx
- Adds missing Icon component [doc page](https://faststore-site-git-doc-icon-doc-page-fs-862-faststore.vercel.app/components/atoms/icon)
=> docs: Adds `Icon` component page

packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts
Note: the description below has been copied from #1647. We couldn't easily merge #1647 because it had been made over the `main` branch instead of `1.x` and editing the target branch introduced many conflicts.
---
We're trying to get the `redirect` property as the example below:
``` curl
curl --location --request GET 'https://carrefourbrfood.vtexcommercestable.com.br/api/io/_v/api/intelligent-search/product_search/?query=4k' \
```
```json
{
"products": [],
"recordsFiltered": 0,
"fuzzy": "0",
"operator": "and",
"redirect": "https://www.carrefour.com.br/busca/4K", # This property
"translated": false,
"pagination": {
"count": 1,
"current": {
"index": 0
},
"before": [],
"after": [],
"perPage": 0,
"next": {
"index": 0
},
"previous": {
"index": 0
},
"first": {
"index": 0
},
"last": {
"index": 0 …
```
=> feat: Add initial support to Intelligent Search redirects

packages/api/src/platforms/vtex/resolvers/validateCart.ts
This PR fixes an inconsistency in the validateCart mutation. If you had added an item to the cart while it was available for your region, then you changed to a region where the item would be unavailable, the API would still return available offers for the item.
This happened because while we were using the Intelligent Search to fetch the items, we were not passing the right region parameters to it (because it was not in the context storage). To avoid future discrepancies, I've also added the locale parameter.
Adds the channel (which contains the region) and locale to the context storage.
Go to https://sfj-9bb2a74--jamstacktata.preview.vtex.app/suprema-de-pollo-en-bandeja-600-g-3883/p and add it to the cart
Now go to the Locator again and choose "Artigas". On the PDP and minicart you can …
=> Fix/add context variables cart mutation 1.x

packages/api/src/platforms/vtex/resolvers/validateCart.ts
This PR fixes an inconsistency in the validateCart mutation. If you had added an item to the cart while it was available for your region, then you changed to a region where the item would be unavailable, the API would still return available offers for the item.
This happened because while we were using the Intelligent Search to fetch the items, we were not passing the right region parameters to it (because it was not in the context storage). To avoid future discrepancies, I've also added the locale parameter.
Adds the channel (which contains the region) and locale to the context storage.
Go to https://sfj-9bb2a74--jamstacktata.preview.vtex.app/suprema-de-pollo-en-bandeja-600-g-3883/p and add it to the cart
Now go to the Locator again and choose "Artigas". On the PDP and minicart you can …
=> fix(api): add context variables cart mutation

packages/core/.husky/pre-commit, packages/core/package.json
Fix husky + lint-staged that runs pre-commit lints for core packages.
|Before|After|
|-|-|
|<img width="833" alt="Screenshot 2023-03-15 at 16 57 30" src="https://user-images.githubusercontent.com/11325562/225429287-ca4e4c1a-b7ac-4921-927a-b667fe24b431.png">|<img width="833" alt="Screenshot 2023-03-15 at 16 57 37" src="https://user-images.githubusercontent.com/11325562/225429495-12efa3bb-bbac-41df-9b86-c7623b93553f.png">|
Should should also see this scripts running pre commits:
- run `yarn` command.
- you should see the pre commit lint tasks after a commit as well 😉 
https://github.com/typicode/husky/issues/851
=> Fix: husky pre-commit script + Lint-stage

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/resolvers/skuVariations.ts, packages/api/src/typeDefs/skuVariants.graphql
This PR sets dominantVariantName as optional in slugsMap and availableVariations.
When the dominantVariantName tVariant is not passed, the first variant will be used as the dominant.
This change is necessary because sometimes we haven't the dominantValue to set in a query dynamically so the firs option solve this problem.
=> feat: change dominantVariant to optional

apps/site/components/utilities/propsSection.ts, apps/site/package.json, apps/site/pages/components/molecules/accordion.mdx, yarn.lock
This PR adds automatic `PropSection` feature.
It also adds this feature to `Accordion` Component.
In some cases, the lib used to get the props ([react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript)) do not manage to extract all props from components. **In this case we need to mock the values (e.g. Polymorphic AccordionItem)**.
1. We need to use Next.js `getStaticProps` so that we can run functions from the server side as `fs` and `path` from node.
2. Then, we use the ([react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript)) to parse each component props from @faststore/components inside the faststore monorepo `node_modules` based on the path from the current markdown component. 
|From|To|
|-|-| …
=> Feat: Automatic `PropSection`

apps/site/components/PropsSection/PropsSection.tsx, apps/site/components/PropsSection/props-section.module.css, apps/site/components/utilities/propsSection.ts, apps/site/package.json, apps/site/pages/components/atoms/badge.mdx, apps/site/pages/components/atoms/button.mdx, apps/site/pages/components/atoms/checkbox.mdx, apps/site/pages/components/molecules/accordion.mdx, packages/components/src/atoms/Badge/Badge.tsx, yarn.lock
This PR updates our `PropsSection` to list all the props of a component.
For now, only these components have the new `PropsSection`:
**Atoms**
- [Badge](https://faststore-site-git-feat-props-section-fs-748-faststore.vercel.app/components/atoms/badge#props)
- [Button](https://faststore-site-git-feat-props-section-fs-748-faststore.vercel.app/components/atoms/button#props)
- [Checkbox](https://faststore-site-git-feat-props-section-fs-748-faststore.vercel.app/components/atoms/checkbox#props)
**Molecules**
- [Accordion](https://faststore-site-git-feat-props-section-fs-748-faststore.vercel.app/components/molecules/accordion#props)
- [Nordhealth](https://nordhealth.design/components/badge/)
- [Radix UI](https://www.radix-ui.com/docs/primitives/components/dialog#api-reference)
=> Feat: Updates `PropsSection`

apps/site/components/utilities/propsSection.ts, apps/site/pages/components/molecules/discount-badge.mdx
Follow-up of https://github.com/vtex/faststore/pull/1673
The component path was incorrect when the component name has more than 1 word, so it couldn't find the component, and the props list returned empty. 
Solution: Convent string path to PascalCase
Before:
`faststore/node_modules/@faststore/components/src/molecules/Discount-badge/DiscountBadge.tsx`
After
`faststore/node_modules/@faststore/components/src/molecules/DiscountBadge/DiscountBadge.tsx`
[Discount Badge](https://faststore-site-git-fix-automatic-props-faststore.vercel.app/components/molecules/discount-badge#props) props should display correct in the page
=> Fix: Automatic props PropSection path

apps/site/pages/components/organisms/payment-methods.mdx, packages/ui/src/components/organisms/PaymentMethods/styles.scss
The `--fs-payment-methods-flag-height` token was missing. So the flags images was not showing when using safari.
Before|After
|-|-|
|![image](https://user-images.githubusercontent.com/3356699/228670879-b8f6d768-e932-487b-bf6f-c9da6642a373.png)|![image](https://user-images.githubusercontent.com/3356699/228670755-95de3b21-38e0-41a7-aa9e-3339ca4427e5.png)
Also:
- Updates flag width size
- Adds `PaymentMethods` props list to its documentation page.
1. Open the [doc preview link](https://faststore-site-git-fix-payment-methods-flag-size-faststore.vercel.app/components/organisms/payment-methods#usage) using Safari
2. You should see the flags images.
=> Fix: `PaymentMethods` Flag size

packages/cli/src/utils/generate.ts
Improves the resiliency of `mergeCMSFiles`, by checking if the file CMS exists before attempting to read it, and showing an error if the JSON file is malformed.
On a new fork of [starter.store](https://github.com/vtex-sites/starter.store), run `yarn dev` then create an empty `cms` folder. It should break the `dev`. Restart it and create an empty `cms/faststore/sections.json`. It will break the `dev` command as well.
Now install the version of this commit, and remove the files created in the previous steps. Then repeat steps above and you should get no errors.
=> Improve resiliency of mergeCMSFile

packages/core/src/components/sections/BannerText/BannerText.tsx
This PR intends to pass down the `colorVariant` to the `BannerText` component.
Everything should work as before.
=> fix: Send missing `colorVariant` attribute to `BannerText`

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/Region.ts, packages/api/src/platforms/vtex/resolvers/validateSession.ts, packages/api/src/typeDefs/session.graphql, packages/sdk/src/session/index.ts, packages/sdk/test/session/index.test.tsx
The validateSession was not accepting and handling geoCoordinates for regionalization. At VTEX we can do a regionalization using zipCodes or geoCoordinates and that's a common scenarium when we are using seller Whitelabels because they're logistics are usually set up using geoCoordinates to improve precision.
The geoCoordinate is saved at indexedDB:
//default session inside faststore.config.js
Pass the "geoCoordinates":{"latitude": {{Float}} , "longitude": {{Float}} } at the validateSession:
It also works for ZipCodes as before:
It's import to mention that we are using a market protocol latitude (north or south) always precedes longitude (east or west) but to call the checkout we have to invert the notations:
-
=> add geoCoordinates to calculate regionalization

apps/site/components/SectionItem/section-item.module.css, apps/site/pages/components/atoms/button.mdx, apps/site/pages/components/molecules/icon-button.mdx, apps/site/pages/components/molecules/navbar-links.mdx, apps/site/pages/components/molecules/region-bar.mdx, apps/site/pages/components/molecules/search-input-field.mdx, apps/site/pages/components/organisms/image-gallery.mdx, packages/components/src/atoms/Button/Button.tsx, packages/components/src/molecules/Alert/Alert.tsx, packages/components/src/molecules/IconButton/IconButton.tsx, packages/components/src/molecules/InputField/InputField.tsx, packages/components/src/molecules/LinkButton/LinkButton.tsx, packages/components/src/molecules/RegionBar/RegionBar.tsx, packages/components/src/molecules/SearchInputField/SearchInputField.tsx, packages/core/src/components/common/Footer/section.module.scss, packages/core/src/components/region/RegionButton/RegionButton.tsx, packages/core/src/components/sections/BannerNewsletter/section.module.scss, packages/core/src/components/ui/Button/ButtonSignIn/ButtonSignIn.tsx, packages/ui/src/components/atoms/Button/styles.scss, packages/ui/src/components/molecules/Accordion/styles.scss, packages/ui/src/components/molecules/Alert/styles.scss, packages/ui/src/components/molecules/Banner/styles.scss, packages/ui/src/components/molecules/BuyButton/styles.scss, packages/ui/src/components/molecules/InputField/styles.scss, packages/ui/src/components/molecules/LinkButton/styles.scss, packages/ui/src/components/molecules/NavbarLinks/styles.scss, packages/ui/src/components/molecules/RegionBar/styles.scss, packages/ui/src/components/molecules/SearchInputField/styles.scss, packages/ui/src/components/organisms/Hero/styles.scss, packages/ui/src/components/organisms/ImageGallery/styles.scss
This PR is a huge fix on all elements related to our Button. 
`fs/components` and `fs/ui`
`fs/core`
In order to respect LH min sizing of 48x48px, we needed to create a wrapper (`data-fs-button-wrapper`) for the button to have a button small that really looks small. Some images for reference:
| `lh-checks-2` | `this branch` |
|-|-|
|<img width="780" alt="image" src="https://user-images.githubusercontent.com/11613011/236031619-b2b7947d-05d2-4464-aed9-37e1eee8e6f6.png">|<img width="780" alt="image" src="https://user-images.githubusercontent.com/11613011/236031845-fda5ec70-627c-462a-8a52-df910494f57f.png">|
|<img width="754" alt="image" src="https://user-images.githubusercontent.com/11613011/236032220-59dafc61-9cce-4f33-98ac-42982ab4312e.png">|<img width="754" alt="image" …
=> Fix: `Button` sizing respecting Lighthouse limit

packages/api/mocks/RedirectQuery.ts, packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/typeDefs/query.graphql, packages/api/test/__snapshots__/queries.test.ts.snap, packages/api/test/queries.test.ts, packages/api/test/schema.test.ts
This PR adds a query to solve redirects when performing a search.
In case of VTEX platform, this is solved by the IS api.
When performing a search if a term or facet has a redirect, the value of the `redirect` field should be an URL; this can later be used to redirect the user to an internal or external URL.
From VTEX admin:
It get solved as:
- Run the `@faststore/api` package individually.
- Browse [localhost/graphql](http://localhost:4000/graphql)
- Run the redirect query with a term that is active in `/admin/search/v4/redirects/`
- For storeframework, you can use the term `tech`
PR related at vtex-sites: https://github.com/vtex-sites/nextjs.store/pull/382
PR related 2.x: https://github.com/vtex/faststore/pull/1749
=> feat: implement redirect query

packages/core/cms/faststore/sections.json
This PR intends to fix the missing `IncentivesHeader` section after renaming to `Incentives`.
=> fix: Renames `IncentivesHeader` section to `Incentives`

packages/core/cms/faststore/content-types.json, packages/core/src/pages/index.tsx
remember to CMS sync after this PR is merged
|Before|After|
|-|-|
|<img width="1028" alt="Screenshot 2023-05-12 at 12 32 01" src="https://github.com/vtex/faststore/assets/11325562/b3eb278f-948e-4b43-8a8d-97b73fc9c438">|<img width="1027" alt="Screenshot 2023-05-12 at 12 32 11" src="https://github.com/vtex/faststore/assets/11325562/21285b72-2f69-4317-baf9-8696d61d410b">|
We are not using this content type anymore. Now we use the Global Sections.
create a new workspace, run CMS sync and check the pages in admin, Global Alert should be gone.
=> fix: removes global alert content type and page + fix core build.

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/ShippingData.ts
Fix the shipping data request when the geoCoordinate is null
Checkout awaits an empty array so for the address used if there is no geoCoordinate we transform it into an empty array.
https://developers.vtex.com/docs/api-reference/checkout-api#post-/api/checkout/pub/orderForm/-orderFormId-/attachments/shippingData
Validation to use the checkout correct format.
You can run locally this version and use the modal component at check it works
Do the same process in master and see it breaks the shipping attachment at the Order Form.
=> transform null in expected empty array

apps/site/components/utilities/propsSection.ts, apps/site/pages/components/molecules/checkbox-field.mdx, packages/components/src/molecules/CheckboxField/CheckboxField.tsx
- Adds Checkbox Field's component props
P.s.: In the `propsSection.ts` file I added `?` to try to prevent the error when `dirs[1]` is undefined. This way, if `dirs[1]` is undefined, `componentNameWithoutExtension` will also be undefined.
- Check if the props list is appearing according. You can check through [preview](https://faststore-site-git-checkbox-field-docs-update-faststore.vercel.app/components/molecules/checkbox-field).
=> Docs: Checkbox Field component props

packages/core/cms/faststore/sections.json, packages/core/src/pages/[...slug].tsx
1. You can test it running core package locally: `yarn dev`.
2. Add the Hero as a draft in PLP page some workspace (https://formspace--storeframework.myvtex.com/admin/new-cms/faststore/plp/edit/568e09a3-03cf-48ce-9a0c-363008ad8681/).
3. Click in the preview link (use the same content-type and versionId etc for localhost).
4. browse to a new PLP and see the changes without publish.
PR: https://github.com/vtex-sites/starter.store/pull/58
=> Feat: Hero from CMS in PLP

packages/core/cms/faststore/sections.json
Removes required props from the Call to Action inside the Hero. Is not required for PLP pages.
=> chore: removes required button props

apps/site/pages/components/organisms/payment-methods.mdx
- Fixes the paymentMethod component [page](https://evergreen.faststore.dev/components/organisms/payment-methods) that is broken.
- Updates examples and types in the page
You should be able to see the PaymentMethods [doc page](https://faststore-site-git-docs-fix-payment-methods-faststore.vercel.app/) and the props section should be updated.
=> docs: Fixes payment flags doc page

apps/site/pages/docs/_meta.json, apps/site/pages/docs/component-customization/override-component.mdx, apps/site/pages/docs/reference-guides/list-of-available-native-sections.mdx, apps/site/pages/docs/reference-guides/list-of-overridable-components-for-each-native-section.mdx
This PR adds the `Reference` section to the documentation
The Reference section will store docs such as:
- List of available natives sections
- List of overridable components for each native section
- Best Practices, like Debugging best practices
- etc
🔗 [Preview](https://faststore-site-git-reference-guides-faststore.vercel.app/docs/reference-guides/list-of-available-native-sections)
=> Doc: Add Reference section

packages/api/src/__generated__/schema.ts, packages/core/cms/faststore/sections.json, packages/core/src/components/cms/GlobalSections.tsx, packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/sections/CrossSellingShelf/CrossSellingShelf.tsx, packages/core/src/components/sections/ProductShelf/ProductShelf.tsx, packages/core/src/components/sections/Section/section.scss, packages/core/src/components/ui/ProductShelf/Overrides.tsx, packages/core/src/components/ui/ProductShelf/ProductShelf.tsx, packages/core/src/components/ui/ProductShelf/index.ts, packages/core/src/pages/[...slug].tsx, packages/ui/src/components/molecules/Carousel/styles.scss
This PR intends to adjust the `ProductShelf` and the related components to support incoming data from CMS.
- Build the store locally (`yarn workspace @faststore/core dev`);
- Access http://localhost:3000/api/preview?contentType=page&documentId=bd9e01c6-534e-4e54-aa76-f864dcbad024&versionId=dfa86048-f354-11ed-83ab-122449db511d
CMS: https://arthurspace--storeframework.myvtex.com/admin/new-cms/faststore/page/edit/bd9e01c6-534e-4e54-aa76-f864dcbad024/
=> feat: Adjust `ProductShelf` for CMS

packages/cli/src/utils/directory.ts, packages/cli/src/utils/generate.ts, packages/core/next.config.js
To ensure that our starter works on Windows computers.
I've had to do two different things. One was to use the `path` library to manipulate filenames and paths, instead of directly using `/`. The other was to explicitly add the node_modules to the SASS load path, so our library can use 
Find a windows machine, fork the starter, use this PR's version of faststore/core and faststore/cli and run it. It should work just fine.
```package.json
"@faststore/core": "https://pkg.csb.dev/vtex/faststore/commit/c66c0743/@faststore/core",
....
"@faststore/cli": "https://pkg.csb.dev/vtex/faststore/commit/c66c0743/@faststore/cli",
```
You can use the starter PR and test de scripts locally as mentioned in starter PR.
https://github.com/vtex-sites/starter.store/pull/56
NA
=> Windows-fix: use path instead of `/` for handling paths

apps/site/pages/components/atoms/input.mdx, apps/site/pages/components/atoms/select.mdx, apps/site/pages/components/molecules/alert.mdx, apps/site/pages/components/molecules/breadcrumb.mdx, apps/site/pages/components/molecules/buy-button.mdx, apps/site/pages/components/molecules/icon-button.mdx, packages/components/src/molecules/Breadcrumb/Breadcrumb.tsx, packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx, packages/components/src/molecules/Breadcrumb/BreadcrumbPure.tsx
- Adds props to the following components:
- Check if the props list is appearing according. You can check through the following links:
🔗 [Input](https://faststore-site-git-docs-props-update-faststore.vercel.app/components/atoms/input)
🔗 [Select](https://faststore-site-git-docs-props-update-faststore.vercel.app/components/atoms/select)
🔗 [Alert](https://faststore-site-git-docs-props-update-faststore.vercel.app/components/molecules/alert)
🔗 [Breadcrumb](https://faststore-site-git-docs-props-update-faststore.vercel.app/components/molecules/breadcrumb)
🔗 [Buy Button](https://faststore-site-git-docs-props-update-faststore.vercel.app/components/molecules/buy-button)
🔗 [Icon Button](https://faststore-site-git-docs-props-update-faststore.vercel.app/components/molecules/icon-button)
=> add props to component

packages/api/mocks/SellersQuery.ts, packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/types/Region.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/typeDefs/query.graphql, packages/api/test/__snapshots__/queries.test.ts.snap, packages/api/test/queries.test.ts, packages/api/test/schema.test.ts
For some segments (such as grocery) the customer can choose the store he wants to receive the order when entering the site. For this, it is necessary to provide the region API information for consultation and as this route was already implemented in the client to generate the regionId for validateCart I built a query just to query the regionId as the list of sellers for when necessary to display this list in store.
This PR will enable the first stage of Casino's modal logistics selection.
It is just a query so pass a postalCode or a geoCoordinates with a country of your choise!
yarn dev at the package API:
```
query {
sellers(postalCode:"35004",country:"USA", salesChannel:"1") {
id
sellers {
id
name
}
}
}
```
The return should be the id that identifies that region (regionId) and a list of …
=> add sellers informations query

packages/core/cms/faststore/sections.json, packages/core/src/Layout.tsx, packages/core/src/components/cart/CartSidebar/CartSidebar.tsx, packages/core/src/components/cms/GlobalSections.tsx
Create CMS sections for `CartSidebar` and integrate the data.
After the merge
- Run the core package locally: `yarn dev`
- Use my dev workspace in draft version of `Global Section` page, and add a new `Cart Sidebar` Section: https://formspace--storeframework.myvtex.com/admin/new-cms/faststore/globalSections/edit/a56db112-87a6-40d5-a4d5-f6df686f93d0/
- Check the preview.
TBD after the merge of this PR
=> Feat: Adds `CartSidebar` Section

packages/lighthouse/src/index.ts
relaxing this rule, but we need to revisit afterward (rollback and investigate).
=> chore: relax bf-cache rule to use warn instead of error

packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts
unavailable products should not display in the search query
Only skus that have sellers with an item available are returned in the search result. Then a check is added to see if the product is in stock.
If you look, the product with the slug `polo-ralph-lauren-casaco-de-moletom-com-logo-2952809-130634` is no longer displayed, because both of its offers are `https://schema.org/OutOfStock`.
Before
After
Rules for picking the best SKU for the product used in FastStore:
1. Checks if it has stock (AvailableQuantity > 0)
2. It takes the SKU of the seller that has the lowest price (spotPrice) that is not sera, but if the price is different from number it is converted to zero to help with the mathematical calculation.
3. Offers are ordered by availability, so those that have stock are always in …
=> fix: search result must remove products out of stock

apps/site/pages/components/atoms/skeleton.mdx, apps/site/pages/components/molecules/product-title.mdx, apps/site/pages/components/molecules/select-field.mdx, packages/components/src/molecules/ProductTitle/ProductTitle.tsx
Adds Skeleton, ProductTitle and SelectField component's props
You should be able to see the:
- Skeleton [doc page](https://faststore-site-git-docs-fs-937-adds-props-faststore.vercel.app/components/atoms/skeleton) props section updated.
- ProductTitle [doc page](https://faststore-site-git-docs-fs-937-adds-props-faststore.vercel.app/components/molecules/product-title) props section updated.
- SelectField [doc page](https://faststore-site-git-docs-fs-937-adds-props-faststore.vercel.app/components/molecules/select-field) props section updated.
=> Docs: Adds Skeleton, ProductTitle and SelectField props

packages/core/cms/faststore/sections.json, packages/core/package.json, packages/core/src/components/sections/BannerNewsletter/BannerNewsletter.tsx, packages/core/src/components/sections/Newsletter/Newsletter.tsx, packages/core/src/components/ui/Newsletter/Newsletter.tsx, packages/core/src/components/ui/Newsletter/index.ts, yarn.lock
[⚠️ This PR is a reference to that and was created to avoid the lint error
](https://github.com/vtex/faststore/pull/1773)
Adjusts Newsletter and BannerNewsletter section for CMS.
- Publish BannerNewsletter and Newsletter in CMS.
- `yarn dev`.
- Check the CMS preview.
=> Feat: Adds `Newsletter` Section from CMS

packages/cli/src/commands/build.ts
This PR fixes an issue where builds that failed (when `yarn build` failed) were interpreted as a success by the build pipeline because the `@faststore/cli` package didn't return the appropriate status.
It now checks for the status of the `yarn build` call and exits the process if it finds it has thrown an error. 
Follow the instructions on the PR below
https://github.com/vtex-sites/starter.store/pull/77
=> fix: cli build error now exits with proper status

apps/site/pages/docs/component-customization/creating-a-new-section.mdx, packages/cli/src/commands/cms-sync.ts
Create a new command on Faststore CLI called `cms-sync` in order to prevent the user from entering the temporary folder so that the script can run.
```cmd
faststore cms-sync
```
running the script above
=> feat: new command to cms sync

packages/cli/src/commands/build.ts, packages/cli/src/utils/directory.ts, packages/cli/src/utils/generate.ts, packages/core/cms-webhook-urls.json
This PR intends to generate the store's CMS webhook URLs JSON file (used by Releases) through the store's config.
Currently, the store needs to create a `cms-webhook-urls.json` containing the webhook URLs to be triggered in the build step. With these changes, this will be done through the store's config (`faststore.config.js` file) by adding the `vtexHeadlessCms` property.
https://github.com/vtex-sites/starter.store/pull/78
=> feat: Generates CMS webhook URLs json file from the store's config

packages/core/src/components/ui/Newsletter/Newsletter.tsx
Behaviour now without the icon at the CMS:
https://files.slack.com/files-pri/T02BCPD0X-F05CZJ57T3Q/image.png
This PR prevent the render to break because the Icon now it´s not mandatory at the CMS.
=> add conditional for the icon

packages/core/cms/faststore/content-types.json, packages/core/src/components/cms/GlobalSections.tsx, packages/core/src/components/templates/LandingPage/LandingPage.tsx, packages/core/src/components/templates/LandingPage/index.ts, packages/core/src/components/templates/ProductListingPage/ProductListingPage.tsx, packages/core/src/components/templates/ProductListingPage/index.ts, packages/core/src/pages/[...slug].tsx, packages/core/src/pages/api/preview.ts, packages/core/src/pages/index.tsx, packages/core/src/pages/l/[page].tsx, packages/core/src/sdk/error/MissingContentError/MissingContentError.ts, packages/core/src/sdk/error/MissingContentError/index.ts, packages/core/src/sdk/error/MultipleContentError/MultipleContentError.ts, packages/core/src/sdk/error/MultipleContentError/index.ts, packages/core/src/server/cms.ts
This Pull Request adds the Landing Page creation feature to faststore
Now the developer can create a new LandingPage in Admin CMS, and this page will be available in _/slug_ path, based in configs.
You can to add a new Landing Page in https://storeframework.myvtex.com/admin/new-cms/faststore/
To add sections
To config the path of this Landing Page
After publish the new page you will can access this landing page by path
he landing pages, PLPs (Product Listing Pages), and Category pages currently share the same path structure. As a result, when a Landing Page is created with a path that matches a PLP, the Landing Page takes priority and the PLP will not be displayed.
=> Feat: adds landing page feature

apps/site/pages/docs/getting-started/4-faststore-cli.mdx
The PR is to address the issue with the FastStore commands installed via `npm`. They are not functioning correctly in the root directory. Updates the commands to work in the root.
🔗 [Preview](https://faststore-site-git-fix-cli-commands-faststore.vercel.app/docs/getting-started/4-faststore-cli)
=> Docs: review CLI guide 

package.json, yarn.lock
This will get rid of the following warning when running the starter
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#b
```
=> Update browserslist to get rid of warning

packages/api/package.json
When we run the `yarn dev` script on the root, the turbo will run all `dev` package scripts. But the dev script from the `api` package modifies the bundle, so he fails when the `core` package tries to run.
So I rename the script in order to avoid modifying the bundle.
=> fix: script name

packages/api/src/platforms/vtex/clients/commerce/index.ts
Adjust the orderForm that is returning to FS so we were getting it from the checkout.
Edge case: When the user has a session already with an orderForm at portal and the checkout is passing the orderFormId param so the field public will be with the correct orderForm but the previous field will be with the cookie value set with an old orderForm.
What happens is that when the user goes back to the FS he will change the cart for an old orderForm making an unexpected behaviour
- Create a cart and go to the checkout:
`https://secure.vtexfaststore.com/checkout?orderFormId=96c7973b68804795acc398bc6352e026#/cart
```
`
You should have smt like this:
https://secure.vtexfaststore.com/api/sessions?items=*
{
"id": "279c0685-9348-47ad-9630-9b7aeb946e34",
"namespaces": {
"account": {
"id": {
"value": …
```
=> get orderFormId from from the public field

packages/core/src/components/ui/ProductGallery/ProductGallery.tsx
- Fixes `Showing results for: ` title style. Added missing `data-fs-content="product-gallery"` to header.
|Before|After|
|-|-|
|<img width="961" alt="image" src="https://github.com/vtex/faststore/assets/3356699/8087b4c4-6556-4f50-8890-1aaea321893d">|<img width="961" alt="image" src="https://github.com/vtex/faststore/assets/3356699/b2106c14-c76f-410b-a559-bae7b9007c02">
1. Run yarn dev on `faststore/core` application or use the starter preview
2. Search for a term, e.g.: `shirt`. You should see the `Showing results for: shirt` title aligned with the Filters component, as shown in the image above. 
[Starter Preview](https://starter-git-fix-product-gallery-title-faststore.vercel.app)
=> Fix: ProductGallery Title style

apps/site/pages/docs/headless-cms-integration/1-configuring-the-vtex-account.mdx
This PR intends to add a recommendation for macOS users while installing the CMS plugins.
Preview: https://faststore-site-git-docs-improve-recommendations-faststore.vercel.app/docs/headless-cms-integration/1-configuring-the-vtex-account#step-1---setting-up-the-command-line-environment
=> Docs: Add recommendation for mac users while installing cms plugins

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/Session.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts
Change to fix bug created by the PR 1871
https://github.com/vtex/faststore/pull/1871
Fix the value returned by the getOrderNumberFromSession so it should return:
```
{
public: { orderFormId: { value: '4d93b6f616604ec58bd016eb266a2eb2' } }
}
```
And we should use the namespaces.public?.orderFormId?.value if its available otherwise it should return undefined and the orderNumber will be the one from the local Storage.
Before this function was not returning the namespace needed for the sync to happen.
Create the vtex_session cookie at the localhost and test doing changes at the cart (deleting the checkout cookie / adding items etc)
https://github.com/vtex/faststore/assets/67066494/891efeac-7ec1-473a-8000-6af869fe9544
=> add checkout namespace

packages/components/package.json, packages/ui/package.json
This PR adds exports definitions to `package.json`. This allows for the `@faststore/ui` and `@faststore/components` packages to be imported from Jest tests and be transpiled to CommonJS.
We only included the definition for the ESM files, which were not sufficient for users importing from CommonJS files. We still export ESM files as the `main` and `require` exports, which means they'll have to transpile it to CommonJS, but it will be usable.
I investigated the possibility of exporting these packages as CommonJS natively as well, but I don't think it's worth it. We'd have to support it and all kinds of errors could come from this, especially the [dual package harzard](https://nodejs.org/api/packages.html#dual-package-hazard).
For using Jest for these packages, enable transpilation by …
=> chore(ui): add exports to package json

packages/cli/src/commands/build.ts, packages/cli/src/utils/generate.ts, packages/core/cypress.json, packages/core/faststore.config.js
Today, we copy the Cypress folder from `.faststore` to the store root folder, then our CI runs Cypress inside the root Cypress folder.
With this PR, we use the root Cypress folder as custom tests, so we copy them to `.faststore` and run Cypress inside the .faststore folder.
https://github.com/vtex-sites/starter.store/pull/136
Just check the Integration Tests CI results or edit README to trigger the CI again.
=> Feat: (Experimental) Copying Cypress folder from store to .faststore

apps/site/pages/components/molecules/search-dropdown.mdx, apps/site/pages/components/organisms/navbar.mdx, packages/ui/src/components/molecules/SearchDropdown/styles.scss, packages/ui/src/components/organisms/Navbar/styles.scss
Currently, using https://starter.vtex.app in the safari browser, the search input is not being displayed and the user cannot use it.
**Currently**
|Desktop|Mobile|
|-|-|
We have introduced the `overflow-x: clip` property, but it works as expected in Safari. We need to change our approach to have the search input inside the [Navbar](packages/ui/src/components/organisms/Navbar/styles.scss). 
For now, I'm just hiding the Cart Toggle button to avoid this issue.
Open the [preview](https://starter-git-fix-search-input-safari-faststore.vercel.app) in `Safari` browser and try to use the search input, you should see the dropdown working as expected.
**Fixed**
|Desktop|Mobile|
|-|-|
Starter: https://github.com/vtex-sites/starter.store/pull/120
- …
=> Fix: Search input is not being displayed on safari

apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
Added in the **Before you start** section the requirement for stores using Legacy CMS Portal technology. The store edition 5.x could not be installed as the documentation suggests, but rather 3.x.
Preview: https://faststore-site-git-review-go-live-faststore.vercel.app/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account#before-you-start
=> Doc: Update go-live step 5 for Legacy CMS stores

packages/core/src/server/index.ts
Set getTypeDefs as default on getCustomSchema prop
=> fix: set getTypeDefs as default os getCustomSchema prop

packages/api/src/platforms/vtex/clients/commerce/index.ts
Authenticated user are receiving 500 at the validateCartMutations when shipping informations are set at the session:
The checkout needs to know that the request is coming from someone authenticated so we must pass the VtexIdclientAutCookie_store cookie
Example of request:
```
curl --location 'https://casinofrqa.vtexcommercestable.com.br/api/checkout/pub/orderForm/5c96cd8602ad4531a978d576adb228b7/attachments/shippingData' \
--header 'Content-Type: application/json' \
--data '{
"logisticsInfo": [
{
"itemIndex": 0,
"selectedDeliveryChannel": "pickup-in-point",
"selectedSla": "Drive (01ff7b40-ffba-45b9-bc44-d76a0d1b46fb)",
"deliveryWindow": {}
},
{
"itemIndex": 1,
"selectedDeliveryChannel": "pickup-in-point",
"selectedSla": "Drive (01ff7b40-ffba-45b9-bc44-d76a0d1b46fb)",
"deliveryWindow": {} …
```
=> Fix: Allow update shippingData for loggedIn User

packages/components/src/molecules/ProductTitle/ProductTitle.tsx
This PR aims to improve `ProductTitle`'s accessibility, as reported on: https://github.com/vtex/faststore/issues/1935
|Product Title Addendum|
|-|
|<img width="397" alt="Screenshot 2023-08-11 at 19 02 47" src="https://github.com/vtex/faststore/assets/11613011/0e2c1baf-8a0f-4b2c-acf6-56d761aa1bad">|
Changing `Product Title Addendum`'s  `<p>` tag to a regular `<div>` fixes the error.
The store should look the same.
Issue: [Improve ProductTitle Accessibility #1935](https://github.com/vtex/faststore/issues/1935)
=> fix: Improves `ProductTitle` Accessibility

packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/platforms/vtex/utils/shouldUpdateShippingData.ts
Updating shipping information must occur within the context of the new OrderForm (post adding or removing items)
This PR aims to correct sending the selectedSLA to the OrderForm when the delivery configuration has a mandatory minimum value in its settings.
The logic for updating shipping occurred within getOrderForm with the initial orderForm context. This logic is now separate and is done right after the changes are made in FastStore at the orderForm level.
Configure a minimum cart value for a shipping method and validate that before the change, when this value was reached in the first request, no SLA was sent and only in the second request was this information entered.
Now, as soon as the minimum value is reached within the new orderForm context, the shipping information is already set …
=> Fix: Update Shipping Data from OrderForm

packages/core/src/sdk/analytics/index.tsx, packages/core/src/typings/global.d.ts
The Analytics team asked us to expose the store account and engine in a global window variable.
Run the store and check if there's a `window.VTEX_METADATA` defined in the console.
https://github.com/vtex-sites/starter.store/pull/149
=> feat: Expose account and engine in Window variable

apps/site/components/ExtendableQueryTable/ExtendableQueryTable.tsx, apps/site/components/ExtendableQueryTable/index.ts, apps/site/pages/docs/api-extensions.mdx
This PR creates the "Consume new fields from pages" session in api extension documentation
[Link to Documentation](https://faststore-site-git-docs-documents-extension-ap-f66250-faststore.vercel.app/docs/api-extensions#consume-new-fields-from-pages)
[Task](https://vtex-dev.atlassian.net/browse/FS-1268)
=> Docs: Create fragments session in documentation

packages/ui/src/components/molecules/SkuSelector/styles.scss
Before: 
After:
Run the Store and check a product that has SKUs. You can copy/paste to multiply the HTML elements, so you can see the overflow behavior when we have a lot of SKUs.
https://github.com/vtex-sites/starter.store/pull/150
Fixes https://github.com/vtex/faststore/issues/1910.
=> fix: SKU overflow in PDP

packages/core/src/components/sections/Footer/Footer.tsx
As reported in that issue https://github.com/vtex/faststore/issues/1901, we're rendering nested `<footer>` elements.
Following our defaults, I'm wrapping our section with the Section component, instead of a `<footer>` element.
Run the store and check if there's a nested footer like the issue exemplifies. 
https://github.com/vtex-sites/starter.store/pull/151
https://github.com/vtex/faststore/issues/1901
=> fix: Nested footer elements

apps/site/pages/components/molecules/sku-selector.mdx
Fixes `SkuOptions` props description.
[Preview](https://faststore-site-git-docs-fix-sku-selector-props-faststore.vercel.app/components/molecules/sku-selector#skuoptions)
https://github.com/vtex/faststore/issues/1945
=> Docs: Fixes props description

packages/components/src/molecules/ProductCard/ProductCardContent.tsx, packages/core/faststore.config.js, packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
The default value for the `hideUnavailableItem` is `false` in the [Intelligent Search](https://developers.vtex.com/docs/api-reference/intelligent-search-api#get-/product_search/-facets-) but in our [faststore.config.js](https://github.com/vtex-sites/starter.store/blob/b92dd359f1fb5245257e03d7f3634fd28459d112/faststore.config.js#L14) we are setting it as `true`.This wasn't clear for some users who weren't finding products they added. 
We decided keeping this value default as `false` would be better. In doing so, we need to adjust our current interface, showing unavailable/out-of-stock products.
|PLP|PDP|
|-|-|
To have consistency in our interface, we made some adjusts:
- Hide product's price in `ProductCart` when the product is unavailable
- Although our lib has the …
=> Chore: Sets `hideUnavailableItem` to false as default 

packages/components/package.json, packages/ui/package.json
This PR has the same purpose as #1924 which was reverted by #1931. Read it's description to learn more about it.
The difference between this PR and #1924 is that we're now exporting CommonJS and ESM definitions for the `ui` and components `packages`. This allows us to define the `main` property on `package.json` pointing to the CommonJS version, which allows jest to correctly recognize this dependency without needing to transform it.
If any user of this package uses this through modern js, it is imported as an ESM package (because of the `module` and `exports` definitions). The two packages are bundled and tree-shaken by webpack anyway, so it doesn't affect performance.
I've also experimented using `tsup` to bundle the package, but ended up facing tree-shaking problems and other …
=> chore: fix package json exports

lerna.json
Fixes failed CI/CD runs on release commits.
It is not necessary to run CI/CD on those commits, since they are only a version bump that is already incorporated by the PR merge commit.
Merge this PR :confia:
https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
=> fix: don't run ci cd on release commit - it already runs on the PR merge commit

packages/core/src/pages/api/health/live.ts, packages/core/src/pages/api/health/ready.ts
Adds back liveness and readiness probes to core
Our CI/CD pipeline needs this endpoint to scale properly.
Run the local server and hit http://localhost:3000/api/health/ready and http://localhost:3000/api/health/live you should get an 'Ok' message from both of them.
N/A
=> Add liveness and readiness probes

packages/cli/src/commands/build.ts
This PR intends to make the `cms-webhook-urls` file visible on the CI/CD's pipeline context after the build step.
=> fix: Send `cms-webhook-urls` file to the pipeline

packages/components/src/atoms/Slider/Slider.tsx
This PR aims to improve `PriceRange`'s accessibility, as reported on: https://github.com/vtex/faststore/issues/1937
|Slider|
|-|
|<img width="1553" alt="image" src="https://github.com/vtex/faststore/assets/11613011/14f1a755-8d72-4e67-beab-ff6dfa68e038">|
Moving Slider's `otherProps` from `data-fs-slider-thumb="left"` to `data-fs-slider` fixes the error.
The store should look the same.
Issue: [Improve PriceRange Accessibility #1936](https://github.com/vtex/faststore/issues/1937)
=> Fix: Improves `PriceRange` accessibility

packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx, packages/components/src/molecules/Dropdown/DropdownButton.tsx, packages/ui/src/components/molecules/Breadcrumb/styles.scss
This PR aims to improve `Breadcrumb`'s accessibility, as reported on: https://github.com/vtex/faststore/issues/1936
|DropdownButton|
|-|
|<img width="241" alt="image" src="https://github.com/vtex/faststore/assets/11613011/f31512b7-e889-4e49-a7b2-97f40f6299bc">|
Adding a aria-label to `DropdownButton` fixes the error.
The store should look the same.
Issue: [Improve Breadcrumb Accessibility #1936](https://github.com/vtex/faststore/issues/1936)
=> Fix: Improves `Breadcrumb` accessibility

apps/site/pages/docs/go-live/1-setting-up-vtex-account-for-faststore.mdx
I noticed that after installnig the `faststore` CLI plugin we weren't instructing our users to run the setup command, as we [did in v1](https://v1.faststore.dev/how-to-guides/platform-integration/vtex/setting-up-an-account). This PR intends to fix this.
=> Add missing setup on Account Setup

packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx, packages/core/src/customizations/GlobalOverrides.tsx, packages/core/src/customizations/components/overrides/ThirdPartyScripts.tsx, packages/core/src/customizations/scripts/ThirdPartyScripts.ts, packages/core/src/customizations/scripts/ThirdPartyScripts.tsx
Handle third-party scripts
1. In the FastStore client, add a new file name `ThirdPartyScripts.ts` within the `src/scripts` directory.
2. Define a function named ThirdPartyScripts.
```
const Component1 = () => {
return <script type="text/javascript" dangerouslySetInnerHTML={{__html:"console.log('hello from a third-party script')"}}/>
}
const ThirdPartyScripts = () => { 
return (<> 
<Component1/>
<Component2/>
<ComponentX/>
</>)
}
export default ThirdPartyScripts
```
The script is injected using the PartyTown framework dependency to avoid blocking the main tread
=> Third-Party Script Management Proposal

packages/api/src/platforms/vtex/resolvers/validateCart.ts
Currently, the prices of the products are displayed incorrectly, sometimes a cent below, sometimes a cent above
The value already calculated by the server is taken, which is in priceDefinitions to avoid calculating and losing the decimals
Preview with beta package: https://github.com/vtex-sites/casinofr.store/pull/986
=> fix: minicart price round

packages/core/cms/faststore/sections.json, packages/core/src/components/navigation/Navbar/Navbar.tsx, packages/core/src/components/navigation/NavbarSlider/NavbarSlider.tsx, packages/core/src/components/sections/Footer/Footer.tsx, packages/core/src/components/sections/Navbar/Navbar.tsx
Add Link URL to Footer's and Navbar's Logo image on CMS Mapping
- Enables edit Link URL in the Navbar's logo, the default is `/`.
- Adds Link URL to Footer's logo, the default is `/`.
- Adds Link Title field to Logo Link 
TO-DO:
1. Run locally on source: `yarn workspace @faststore/core dev`
2. Use this dev workspace in draft version of Global Section page:
- https://fanny--storeframework.myvtex.com/admin/new-cms/faststore/globalSections/edit/a56db112-87a6-40d5-a4d5-f6df686f93d0/
- Edit Navbar's logo using `Link URL` and `Link Title` fields
- Edit Footer's logo using `Link URL` and `Link Title` fields
3. Save and click on `Preview` 
4. You should be able to see your changes in the localhost.
[WIP]
=> Chore: Adds Logo link fields on Navbar and Footer on CMS

apps/site/pages/docs/faststore-config-options.mdx, packages/core/faststore.config.js, packages/core/src/sdk/analytics/platform/vtex/search.ts, packages/core/src/utils/getCookie.ts
- Sets FS session identifiers cookies under store domain.
- We aim to use these cookies for sending events to the IS platform.
Sets `vtex-faststore-anonymous` and `vtex-faststore-session` under `https://vtexfaststore.com` domain, so we can retrieve these identifiers on `secure.vtexfaststore.com`.
- We can simulate it locally (using localhost), make the following change on `src/sdk/analytics/platform/vtex/search.ts` file: 
1. Change 
```js
document.cookie = `${key}=${value}; max-age=${expiresSecond}; domain=${urlDomain.hostname}; path=/;`
```
to 
```js
document.cookie = `${key}=${value}; max-age=${expiresSecond}; path=/`</code>
```
2. Run `yarn develop`
3. Type `apple` in the search 
4. Open `Storage -> Cookies`. You should be able to see the FS cookies.
5. Go to `Network` tab and filter …
=> chore: Sets FS session cookies

apps/site/pages/docs/customizing/mixins-breakpoints.mdx
The import path for `utilities` is wrong.
The correct path should be: `@import "@faststore/ui/src/styles/base/utilities";`
- Following the [guide](https://faststore-site-git-docs-fix-utilities-import-path-faststore.vercel.app/docs/customizing/mixins-breakpoints#customizing-breakpoints). You should be able to override the Breakpoints and Mixins as expected.
https://github.com/vtex/faststore/pull/1917
=> Docs: Fixes utilities import path

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/platforms/vtex/utils/getCookies.ts
The session must update every time so this PR fix the person identification flow at FastStore.
Remove the Session Cookie logic from FS
Log in and the vtexAuthCookie will exist -> The client will be identified
Log out and the vtexAuthCookie wont exist -> The client wont be identified
=> Fix/fs person identification 

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/src/platforms/vtex/utils/getCookies.ts
The session must update every time so this PR fix the person identification flow at FastStore.
Remove the Session Cookie logic from FS
Log in and the vtexAuthCookie will exist -> The client will be identified
Log out and the vtexAuthCookie wont exist -> The client wont be identified
=> Fix/fs person identification 1.x

packages/core/generate.sh
tweaks the yarn graphql-codegen command from generate.sh
run yarn generate in the core package.
=> chore: adds yarn graphql-codegen command instead of graphql-codegen

packages/core/src/pages/[...slug].tsx
fix the problem, when a page is created in headless cms with more than one path parameter, '/first/second'
in the getStaticProps function it was changed so that the slug is built both for the page search in the cms and for the plp
Just create a new landing page in the cms with more than one parameter in the path.
=> fix: search for the entire slug intead of just the first one

apps/site/pages/docs/api-extensions.mdx, packages/core/index.ts, packages/core/src/components/sections/CrossSellingShelf/CrossSellingShelf.tsx
Exports the `useProductsQuery` from `@faststore/core` package.
Also it implements small quick wins.
=> Feat: exports `useProductsQuery` hook

packages/cli/src/commands/generate-graphql.ts, packages/core/package.json, packages/core/src/server/generator/schema.ts
=> Chore: uses `graphql-codegen` from core

apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx, apps/site/pages/docs/headless-cms-troubleshooting/error-installing-headless-cms.mdx
To recommend that Windows users enable Developer Mode when running FastStore projects. 
Preview:
- [Setting Up the Project](https://faststore-site-git-docs-windows-requirement-faststore.vercel.app/docs/getting-started/2-setting-up-the-project#enabling-developer-mode-windows-users)
- [Error installing the Headless CMS plugin of VTEX IO CLI](https://faststore-site-git-docs-windows-requirement-faststore.vercel.app/docs/headless-cms-troubleshooting/error-installing-headless-cms)
This suggestion is based on @icazevedo's experience with another tool ([Volta](https://docs.volta.sh/guide/getting-started)), which, like FastStore, relies on symlinks during development. Enabling Developer Mode helps prevent errors during development and provides the necessary permissions and privileges, as …
=> Docs: adding recommendation for Windows user

packages/core/cms/faststore/sections.json, packages/core/src/components/product/NotAvailableButton/NotAvailableButton.tsx, packages/core/src/components/product/NotAvailableButton/index.ts, packages/core/src/components/sections/ProductDetails/Overrides.tsx, packages/core/src/components/sections/ProductDetails/ProductDetails.tsx, packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx, packages/core/src/typings/overrides.ts
Previously on FastStore
- https://github.com/vtex/faststore/pull/1962
> Although our lib has the [OutOfStock](https://www.faststore.dev/components/organisms/out-of-stock) component, it's not fully integrated into our application, so we will temporarily remove it until implemented.
Then after it, we decided on use a `Not Available` product option.
Also, this PR aims to deal with this issue
- https://github.com/vtex/faststore/issues/1977
|Before|After|
|-|-|
|<img width="416" alt="Screenshot 2023-09-19 at 13 04 20" src="https://github.com/vtex/faststore/assets/11325562/9573b7bf-4f0d-48f6-a367-732b491141eb">|<img width="412" alt="Screenshot 2023-09-19 at 13 03 16" src="https://github.com/vtex/faststore/assets/11325562/e83d5cca-adc4-49a0-b1fb-7b7c94a2538f">|
It shows the Selector even when …
=> Chore: Not Available product

packages/core/package.json
This PR enables sideEffects optimization by webpack. This reduces first load bundle size and significantly improves navigation between pages by reducing the bundle downloaded when navigating between pages. 
The sideEffects optimization works by analyzing which parts of side-effect free packages are used by the store and removing the rest. This optimization was already enabled for packages that explicitly define they are side-effect free. By setting `sideEffect` as `false` in the package.json file, we assure anyone using `@faststore/core` it is a side-effect free package & signal to webpack it should analyze every package for side-effect free code & CSS, which allows it to remove unused code from the final bundle.
Usually, this comes at the cost of increased build times. I tested it to see …
=> perf(core): add sideEffects false

packages/core/src/pages/[slug]/p.tsx
This PR intends to set a unique `key` prop for each PDP to reset the entire component tree’s state.
As an example of wrong state behavior we have the `QuantitySelector` quantity counter that's not resetting when navigating between PDPs. Currently, if the user increase the product's quantity then clicks on any product inside the "People also bought" section (on the current PDP) the counter isn't reset.
- Go to any PDP;
- Increase the product's quantity;
- Click on any product inside the "People also bought" section".
The product's quantity should be 1.
https://github.com/vtex-sites/starter.store/pull/209
=> chore: Specifies a unique `key` for each PDP

packages/core/src/pages/[...slug].tsx
- Fix PLP bug when navigating through different PLPs w/ additional pages. The loaded pages in the PLP are not being reset, and there are no products to show; it displays a list of the Product's card skeleton.
|Bug - Before|
|-|
|![bug-plp-before](https://github.com/vtex/faststore/assets/3356699/04e3fb12-73f3-4e90-890e-fd991678514f)|![bug-plp-fix](https://github.com/vtex/faststore/assets/3356699/306d3920-fe9a-4c95-8d66-9bc9dc1bc1fa)|
|After|
|-|
|![bug-plp-fix](https://github.com/vtex/faststore/assets/3356699/306d3920-fe9a-4c95-8d66-9bc9dc1bc1fa)|
- Adds key prop to identify the different PLP pages and mount it again.
Use this preview link: https://starter-git-fix-plp-plp-reset-page-fs-1280-faststore.vercel.app
1. Click on the `Office` category in the Navbar
2. Click twice on the `Load …
=> fix: PLP when navigating through different PLPs w/ additional pages

yarn.lock
This PR upgrades protobufjs sub-dependency to incorporate the fix introduced in https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.2.4, which was a vulnerability in the package.
Updated the version `yarn.lock` uses to resolve the package.
Check yarn.lock. Alternatively, install the packages and see the installed version in node_modules.
https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.2.4
https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563
https://github.com/advisories/GHSA-h755-8qp9-cq85
=> fix: upgrade protobufjs to avoid vulnerability

packages/core/src/components/ui/ShippingSimulation/useShippingSimulation.ts
Fix `ShippingSimulation` when has zip code from session and clear the shipping simulation.
Before
https://github.com/vtex/faststore/assets/11325562/b3c526f5-d4b5-4294-bf88-ec6e15665483
After
https://github.com/vtex/faststore/assets/11325562/c5b4fb94-12c4-418e-884a-a0464f99b897
=> Fix: `ShippingSimulation` when exists zip code from session

packages/api/package.json, packages/api/src/platforms/vtex/utils/enhanceSku.ts, packages/api/src/platforms/vtex/utils/sanitizeHtml.ts, packages/core/src/components/ui/ProductDescription/ProductDescription.tsx, packages/ui/src/components/organisms/ProductDetails/styles.scss, yarn.lock
This PR adds support for HTML in product descriptions.
FastStore API sanitizes the product description in the backend. This ensures no possibly vulnerable tags, such as `script` tags are sent and executed on the frontend.
The frontend now inserts the description as innerHTML, which allows it to be properly rendered.
Browse the two deploy previews below. Note on how one of the product descriptions, the HTML renders as text, and, in the other that uses this version of the packages it is interpreted as actual HTML.
https://sfj-5d275d1--starter.preview.vtex.app/unbranded-frozen-pizza-1670312/p
https://starter.vtex.app/unbranded-frozen-pizza-1670312/p
https://www.npmjs.com/package/sanitize-html
=> feat(api): sanitize product description

packages/core/next.config.js, packages/sdk/src/search/useInfiniteSearchState.ts
1. Attempts to fix scroll position when going back from the PDP to PLP 
reported issue: https://github.com/vtex/faststore/issues/1972
_Scenario_: On PLP, click on `Load more products`, select a product, go to product's PLP and go back to PLP using browser's back button.
|Before - PLP drops user at bottom of the page|
|-|
|![plp drops users on the bottom](https://github.com/vtex/faststore/assets/3356699/352c7d87-4437-4cdb-a7a1-53bbb993109c)|
|FIx - PLP saves last state (open pages) and keep previous scroll position|
|-|
|![plp saves last state (open pages) and keep previous scroll position](https://github.com/vtex/faststore/assets/3356699/26d1d98b-ff6b-41f9-93b6-ce5f867f0d52)|
2. Enables scroll restoration on the application
|Before - not using scroll restoration| Enable scroll …
=> Fix: Scroll restoration and pages states on PLP when back from PDP

package.json, packages/api/src/platforms/vtex/utils/sanitizeHtml.ts, yarn.lock
This PR fixes [this](https://github.com/vtex/faststore/actions/runs/6458890810/job/17533535581) issue that happened while publishing packages due to incompatible `eslint-plugin-prettier` versions with prettier 3.x.
In #2050 I upgraded the prettier version to 3.x. That caused the issue because `tsdx` has a dependency on an old `eslint-plugin-prettier` version, which is incompatible with `prettier@3`. I'm rolling back the upgrade and fixing the prettier version on the major `2` which makes it difficult for others to make the same mistake as me.
In the future, we remove all uses of `tsdx` as it is no longer supported and has gone 3 years without updates. 
By merging this!
https://github.com/prettier/eslint-plugin-prettier/issues/562
Thanks @hellofanny for noticing the error and investigating …
=> fix: rollback prettier to 2ˆ to fix publishing issues

packages/ui/src/styles/base/layout.scss
The current tablet version has a content bleed and adds an extra space on the right.
|Before|After|
|-|-|
|<img width="574" alt="image" src="https://github.com/vtex/faststore/assets/11613011/3888db0d-bab6-4922-81ce-7533f67460bd">|<img width="574" alt="image" src="https://github.com/vtex/faststore/assets/11613011/c7cd49e2-a7cf-4c2d-9177-709849eefef9">|
`faststore/core` application:
1. Run `yarn dev`
2. Check `Homepage` on table view
`WIP`
=> Fix: Content bleed on tablet views

packages/core/src/components/search/SearchTop/SearchTop.tsx
Fix this problem when there is no top terms.
=> fix: adds empty array as default top term value

packages/cli/src/commands/build.ts
The faststore.config.js file from the `.faststore` folder was being copied to the starter after the build, which caused it to throw errors because it couldn't find default definitions for the config or the copied starter config present inside `.faststore`.
Lighthouse was not working because of this.
This PR makes the CLI not copy the `.faststore/faststore.config.js` file to the starter after the build.
Run `yarn build` on the starter. You shouldn't see any changes in the starter's `faststore.config.js` file.
https://github.com/vtex-sites/starter.store/pull/232
The integration tests are failing due to an unsupported workflow on webops. Lighthouse actually started working after this change!
=> chore: remove copying faststore config during build

packages/core/src/pages/404.tsx
display the correct missing URL when hitting a 404 page
https://github.com/vtex/faststore/issues/2064
use `asPath` which Next provides as the alias for that particular 404 response
1. visit path which doesn't exist
2. see that the URL is displayed in the body of the page
=> display correct missing route in 404 page

apps/site/pages/docs/faststore-config-options/custom-cypress-test.mdx, packages/cli/src/commands/test.ts, packages/cli/src/utils/generate.ts
This PR intends to fix some details regarding stores' custom Cypress tests.
https://github.com/vtex-sites/starter.store/pull/237
=> fix: Custom Cypress tests

apps/site/components/Carousel/CarouselSimpleUsage.tsx, apps/site/components/Carousel/CarouselUsage.tsx, apps/site/components/Carousel/carousel-item.module.css, apps/site/components/OverviewSection/overview-section.module.css, apps/site/components/ProductShelf/ProductShelfCarouselUsage.tsx, apps/site/components/ProductShelf/ProductShelfUsage.tsx, apps/site/pages/components/molecules/carousel.mdx, apps/site/pages/components/organisms/product-shelf.mdx, packages/components/src/molecules/Carousel/Carousel.tsx, packages/components/src/molecules/Carousel/CarouselItem.tsx, packages/core/src/components/sections/ProductShelf/section.module.scss, packages/core/src/components/skeletons/ProductShelfSkeleton/ProductShelfSkeleton.tsx, packages/core/src/components/ui/Carousel/Carousel.tsx, packages/core/src/components/ui/ProductShelf/ProductShelf.tsx, packages/ui/src/components/molecules/Carousel/styles.scss
**Carousel**
- Adjust Carousel bugs (bullets quantity and arrows visibility)
- Removes carousel item width (now is set via JS)
One of the bug related to bullets quantity & scroll, it's happening in the following scenario:
- `itemsPerPage = 5`, but only 1.5 items are visible within the slide, and the scroll is not functioning as expected.
|bug| now|
|-|-|
|![before - bug](https://github.com/vtex/faststore/assets/3356699/e5aac439-de66-4323-80fc-31bfb4926a80)|![after](https://github.com/vtex/faststore/assets/3356699/1304f60f-6f7a-4e0b-9495-93d24d03d2f6)|
To prevent confusion, we are displaying the items in an overlapped manner. This allows users to reconsider the value set for `itemsPerPage` given  the component's structure. We also added a note for this case in our …
=> Chore: Carousel/ProductShelf components tweaks

packages/core/src/components/ui/ProductShelf/ProductShelf.tsx
follow up of https://github.com/vtex/faststore/pull/2088
- Adds missing `itemsPerPage` prop to carousel 😬
=> fix: Passes missing `itemsPerPage` prop

packages/core/src/pages/s.tsx
Refers to https://github.com/vtex/faststore/issues/2093
Removes duplicated h1 tag in search results page 
1. Navigate to the search results page
2. Only one h1 tag should appear
=> fix: Removes duplicate h1 on search page

turbo.json
Fix the errors that sometimes happened when running `yarn dev` on the root.
The problem was happening because sometimes the file `api.cjs.development.js` from the API wasn't available yet when the dev command from the core workspace was run. 
Since this dependency exists, we should prevent this issue by building the API before running the core. 
That's what this turbo config does, adds the API's `build` dependency to core's `dev` command.
`yarn dev` on the root should work fine.
- [Turbo docs: task dependencies](https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#from-arbitrary-workspaces)
- [Slack thread](https://vtex.slack.com/archives/C03L3CRCDC4/p1699551581633499?thread_ts=1699537104.296799&cid=C03L3CRCDC4)
=> Chore: Add API dep to core's dev command on turbo config

packages/core/src/components/cart/CartSidebar/section.module.scss, packages/core/src/components/common/Alert/section.module.scss, packages/core/src/components/common/Toast/section.module.scss, packages/core/src/components/navigation/NavbarSlider/section.module.scss
- Adds missing `@component` layer to sections (Alert, CartSideBar, Toast)
- Enables styling sections through theme
Previously, when attempting to override a style using section data-attr as mention in the [doc](https://www.faststore.dev/docs/customizing/components#customizing-a-component-within-a-section) for the sections listed above it was not working as expected. The `@theme` layer should precedence the others layers.
1. Try using this [branch](https://github.com/vtex-sites/starter.store/pull/252) on starter
2. Modify `custom-theme.scss` to change those sections styles, example:
```
// Alert
[data-fs-alert] {
background-color: pink;
}
// CartSideBar
[data-fs-cart-sidebar] {
background-color: lightblue;
}
// Toast
[data-fs-toast] {
background-color: salmon;
}
```
You should be able to …
=> chore: Adds missing components layer

packages/core/src/pages/[slug]/p.tsx
This PR allows the state and overall page structure to be preserved while navigating between SKUs of the same product.
All SKUs of a product have the same canonical URL. We use that canonical path as key for the page component, so React understands it should preserve state and overall page structure when navigating between pages with the same canonical URL, that is, SKUs of the same product.
This means quantity selector should preserve the quantity when navigating between SKUs of the same product, but restart it when navigating to another product.
Go to a PDP, navigate between SKUs and check the key property of the Page component in the React Components extension inspector.
Try it locally
https://github.com/vtex/faststore/pull/2043
=> fix: use canonical as key for pdp pages

packages/core/src/pages/[slug]/p.tsx
- Make the component BannerText available in the Product Details Page.
- When trying to add a BannerText component in a Product Details Page, you get this error, and the component doesn't render 
- After this PR, the component should render and this message shouldn't appear in the console.
=> Added BannerText to allowed sections in pdp

packages/core/next.config.js
This PR adds support for Next.js [rewrites](https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites). 
It works just like Next.js. Read their [docs](https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites). If importing rewrites from a file, there's the same limitation as for redirects, that is, the file must be under the `./src` folder.
See the PR in the deploy preview bellow. Access `/test/my-office`. It is configured to point to `/office`.
https://github.com/vtex-sites/starter.store/pull/261
https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites
#2069
=> feat: add rewrites support

packages/cli/src/utils/generate.ts
The recent change to support copying the contents of the `/public` dir during build allows users to customize the `robots.txt` file, but doesn't enable the users to upload a standard XML sitemap which the `robots.txt` file can link to.
Adds `xml` to the list of filetypes.
Add an `xml` file to the `public` dir and run a build. Visit `localhost:3000/{newFileName}.xml` and see that it is served as expected.
=> Feat: add XML to list of public filetypes copied during build

apps/site/pages/docs/building-sections/creating-a-new-section.mdx
I spent a good 10 minutes trying to debug a cryptic error from the   `faststore cms-sync` command only to find that following the docs would yield an error. This fixes it.
=> Wrap content-type in `[]`

packages/cli/src/utils/generate.ts
support ICO file copy as well, so that FastStore applications can select their own favicon.
adds "ico" extension to allow list
modify `favicon.ico` in app's `/public` dir, run build, verify that change is propagated through to favicon in browser
=> Feat: add ICO extension support to public files copy

apps/site/pages/docs/getting-started-requirements.mdx, apps/site/pages/docs/getting-started/1-faststore-onboarding.mdx, apps/site/pages/docs/headless-cms-integration/1-configuring-the-vtex-account.mdx, apps/site/pages/docs/headless-cms-overview.mdx
This PR adds a new requirement to start the Onboarding: ensure the account has the hCMS app and its dependencies installed to prevent build failures during Onboarding due to content duplication.
I also removed the mentions about the `publishing` status in CMS, which is no longer available. Check [this commit](https://github.com/vtex/faststore/pull/2114/commits/d32a1e7a650b9af0b67970cdb1bc2b314d9c3f12) to review.
You can follow the instructions available in the [doc](https://faststore-site-git-docs-onboarding-requirements-faststore.vercel.app/docs/getting-started-requirements#install-the-headless-cms-and-dependencies). 
[Requirements: Install the Headless CMS and dependencies](https://faststore-site-git-docs-onboarding-requirements-faststore.vercel.app/docs/getting-started-requirements#inst …
=> Docs: add Headless CMS onboarding requirements

apps/site/pages/docs/faststore-config-options/custom-cypress-test.mdx
This PR intends to improve the `Custom Cypress test` docs.
=> docs: Custom Cypress test doc improvements

CONTRIBUTING.MD
The contributing file it was outdated. This PR attempts to update this file with up-to-date instructions to help contributors. 
- [Preview](https://github.com/vtex/faststore/blob/7527986698b7c0e37a17be702b2695f2ee7b515a/CONTRIBUTING.MD)
Should we add a page on https://www.faststore.dev/docs with this guide?
=> docs: Updates contributing file

packages/core/src/components/common/Alert/Alert.tsx
Attempt to avoid type error: (when upgrading `@types/react` package)
We are receiving a string as prop from CMS, so it makes sense to be a string prop in the common alert.
actually, there is a ` TODO: Remove it? It's not being used`  - should we just remove this prop?
Everything should work as before, but the build should not fail.
https://github.com/vtex-sites/starter.store/pull/272
=> fix: Changes prop type to string instead of react node

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/components/src/hooks/UIProvider.tsx
Fix a loop bug on toast: when adding more units than the max allowed for a product, a toast was shown and the cart was changed automatically decreasing the quantity to the max, but the toast kept being shown because the orderform would still have the message.
Also fixed another bug on toast: when adding a product and then changing the zip code that doesn't deliver that product, the toast wasn't being shown.
For the first case: [cleaning the orderform messages](https://developers.vtex.com/docs/guides/clear-orderform-message-field-from-cart) `clearOrderFormMessages(orderNumber, ctx)` fixes the loop.
For the second case: making `validateCart` check changes in the orderform messages field fixes the issue. The toast in this case will only stop being shown if the user changes the zip code to a …
=> fix: Toast bugs

packages/core/src/components/ThirdPartyScripts/GoogleTagManager.tsx, packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
This PR fixes an issue where it wasn't possible to see events at the GTM Preview while debugging.
It no longer forwards `dataLayer.push` calls to partytown when the `gtm_debug` query string is enabled.
Open tagmanager.google.com and choose the `GTM-PGHZ95N` container. Now, click in preview and put the deplooy preview link below. Navigate the store and see the events being shown in the GTM preview tab.
https://github.com/vtex-sites/starter.store/pull/280
=> fix: see events in GTM preview

packages/api/src/platforms/vtex/resolvers/searchResult.ts, packages/sdk/src/search/facets.ts, packages/sdk/test/search/Provider.test.tsx
Fix filters behaviour when removing the first filter selected at a search page
The user should be able to remove the first filter selected.
For other types of pages the validation work because you already have a pre-selected filter.
Ex: 
https://storeframework.vtex.app/office
**You have when first filter selected:** https://storeframework.vtex.app/office?category-1=office&category-2=chairs&facets=category-1%2Ccategory-2&sort=score_desc&page=0
So the first filter that is the context will always be the index 0.
But for search pages this logic fails.
Ex:
https://storeframework.vtex.app/s?q=tasty&sort=score_desc&page=0
**You have when first filter selected:** 
https://storeframework.vtex.app/s?q=tasty&category-2=appliances&facets=category-2&sort=score_desc&page=0
The first filter is the index …
=> Fix: Remove First Selected Filter at Search Page

turbo.json
- Moves env variable from dependsOn, to avoid the following message:
> [DEPRECATED] Declaring an environment variable in "dependsOn" is deprecated, found $BASE_SITE_URL. Use the "env" key or use `npx @turbo/codemod migrate-env-var-dependencies`.
=> chore: moves env variable from dependsOn (turbo.json)

packages/core/faststore.config.default.js, packages/core/package.json, packages/core/src/pages/_app.tsx, yarn.lock
FastStore stores use NextSEO's default robot tags. This PR allows stores to opt-out of the robot tags and write their own.
Solves #2139 
Check the deploy preview [of this PR](https://github.com/vtex-sites/starter.store/pull/294) and see that there are no robot tags.
[Next SEO](https://github.com/garmeeh/next-seo)
=> Add experimental flag to allow stores to disable NextSEO robots

packages/api/src/platforms/vtex/resolvers/searchResult.ts
Address this issue
- https://github.com/vtex/faststore/issues/2132
While in search Page and PLP, FastStore API products search query was getting always the first `item` (sku) from the `product.items`. In this case, we should get the best item (item available with smallest value).
|Before|After|
|-|-|
|<img width="1642" alt="Screenshot 2023-11-30 at 19 29 12" src="https://github.com/vtex/faststore/assets/11325562/89c546bc-49b2-4d7b-b660-0c6685059fae">|<img width="1603" alt="Screenshot 2023-11-30 at 19 27 11" src="https://github.com/vtex/faststore/assets/11325562/978beba9-6a6f-4929-ba45-41c17d0fa3b8">|
Check the preview link from starters store, with the tests mentioned [in the issue](https://github.com/vtex/faststore/issues/2132).
Preview 
- https://sfj-4b57e5c--starter.preview.vtex.app/
- …
=> fix: pickBestSku instead of first sku in products query

.codesandbox/ci.json, .github/workflows/ci.yml, .github/workflows/release.yml, package.json, packages/api/jest.config.js, packages/api/mocks/AllProductsQuery.ts, packages/api/package.json, packages/api/src/index.ts, packages/api/src/typeDefs/index.ts, packages/api/test/__snapshots__/mutations.test.ts.snap, packages/api/test/__snapshots__/queries.test.ts.snap, packages/api/tsconfig.json, packages/api/tsdx.config.js, packages/cli/package.json, packages/components/package.json, packages/core/package.json, packages/sdk/jest.config.js, packages/sdk/package.json, packages/ui/package.json, turbo.json, yarn.lock
This PR exists to allow for the use of newer tech such as node 18 and its cookies helper functions, useful for #2133 
This PR removes `tsdx` from `@faststore/api` and upgrades `node` to `v18.19.0` in all packages.
FastStore API now uses `tsc` for bundling and dev mode (following what we did for UI and Components packages), and uses `tsx` for running a local dev server. Because `tsc` only handles `.ts` and `.js` files, we now have to manually copy the `.graphql` typeDefs files. We now use jest directly to run FastStore API tests.
All packages now use Node 18, which is the latest LTS node version at the moment. This means that `@faststore/core` will no longer be compatible with previous versions of node, as we prepare for a full node migrations in the FastStore platform at December 13. …
=> chore: remove tsdx and upgrade to node 18

package.json, yarn.lock
Fix CD
Updates lerna so it no longer depends on prettier@2.
Merge this 😆 (rly tho)
https://github.com/aws-amplify/amplify-js/pull/12605
=> fix: broken cd pipeline because of old lerna dependency

.github/workflows/ci.yml, package.json
Once we updated to the latest version of turbo, we needed to have updated the remote cache settings. This PR proposes that.
=> fix: turborepo cache

packages/core/src/components/ui/Button/ButtonSignIn/ButtonSignIn.tsx
Remove orderFormId param from /account and /login
This param should not be sent when the user is navigating to those pages.
Go to my account and check if the param is passed at the URL.
https://github.com/vtex/faststore/assets/67066494/51ff8f80-6407-4344-97ee-d51ce26da189
[Preview](https://github.com/vtex-sites/starter.store/pull/310)
The logic to get this param and add to the session was removed at this PR:
https://github.com/vtex/admin-faststore/pull/25
=> Remove: OrderFormId param from my account / login

packages/core/src/components/product/ProductCard/ProductCard.tsx
This PR attempts to fix scenario when there is no discount applied in the product, and sale price is > listing price.
_I wonder if this logic should be inside the `ProductCardContent` component (fs/ui library) or in the core. Any thoughts?_
When no discount applied, we should not display the `DiscountBadge` component.
1. Go to homepage -> Look for `Apple Magic Mouse` in the Most Wanted section.
2. The `infinity` badge should not appear.
[FS-1482](https://vtex-dev.atlassian.net/browse/FS-1482?atlOrigin=eyJpIjoiMWU1MGFjYTZkY2RiNDY2MGE0NGI4ZDZiNmZjODRkMWEiLCJwIjoiaiJ9)
[FS-1482]: https://vtex-dev.atlassian.net/browse/FS-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Display discount badge only when has discount

packages/sdk/src/search/useSearchState.ts, packages/sdk/test/search/serializer.test.ts, packages/sdk/test/search/useSearchState.test.ts
When clicking on a suggested product link in the search the user would be redirect to `/s/?term=blabla`. Because of how our nginx is configured, this trailing `/` would redirect the user to the cluster URL and would show a `Your connection is not private` error.
Stop appending `/` to the URL.
Go to the preview link, start a search and click on a "Top Search" suggestion. You should see the search page without any problems.
=> Stop appending `/` to search state base path

packages/core/cms/faststore/sections.json
This PR intends to add missing toast attributes for the `BannerNewsletter` section.
Check the PDP preview on CMS using the workspace `lucasportela`
=> fix: `BannerNewsletter` toast attributes

packages/core/src/components/templates/LandingPage/LandingPage.tsx, packages/core/src/pages/[...slug].tsx
This is a fix for https://github.com/vtex/faststore/issues/2144. Making it so the default behavior for landing pages that don't have a canonical set in the store's hCMS is to have `canonical` set to their full URL path.
When rendering a landing page that doesn't have a set `canonical` URL set via hCMS, instead of setting the `canonical` prop from `NextSeo` to `storeConfig.storeUrl` this PR makes it so `canonical` is set to `${storeConfig.storeUrl}/${slug}`, where slug is the path of the page being rendered.
Go to the Vercel deploy preview commented below and check for `<head>` tags at `/testing-new-landing`. Here's a comparison between the current behavior and the updated one, in the same landing page:
**current behavior**
**updated behavior**
=> [TCM-196] Update default canonical URLs for landing pages

apps/site/pages/docs/api-extensions/extending-api-schema.mdx, apps/site/pages/docs/api-extensions/extending-queries-using-fragments.mdx, apps/site/pages/docs/api-extensions/troubleshooting.mdx
- Fixes api extension troubleshooting link path in the doc
[Preview](https://faststore-site-git-docs-updates-troubleshooting-link-faststore.vercel.app/docs/api-extensions/extending-api-schema)
=> docs: Fixes api extension troubleshooting link path

packages/core/src/components/templates/ProductListingPage/ProductListingPage.tsx
The canonical URL on PLP shouldn't have a query-string.
=> fix: canonial url on plp

packages/core/next.config.js
This PR makes the NextJS i18n config from the `next.config.js` dynamic.
It will fix SEO issues when the store is created using different languages.
Setting the `session.locale` param on the `faststore.config.js` file will update the `i18n (locales array and defaultLocale param)` configs on the `next.config.js` file.
| Set locale as `fr-FR` | Preview |
|------|------|
| ![image](https://github.com/vtex/faststore/assets/57547336/671f6bd5-95d1-4ab4-bcad-0face004a503) | ![image](https://github.com/vtex/faststore/assets/57547336/f24b630b-d781-4daf-b29c-743f7b50b943) |
| Set locale as `pt-BR` | Preview |
|------|------|
| ![image](https://github.com/vtex/faststore/assets/57547336/3dccbac1-a10f-4279-95cb-65472b9cdef4) | ![image](https://github.com/vtex/faststore/assets/57547336/98a2fe95-8487-43dd …
=> fix: dynamic nextjs i18n config

packages/cli/src/commands/build.ts, packages/cli/src/utils/generate.ts, packages/core/next.config.js
This PR intends to improve the `@faststore/cli` build time setting Next's `output` config to trace files/folders outside the `.faststore` working dir (user's `node_modules`, for instance).
Run `yarn build` or `yarn dev` and check if `@faststore/cli` steps don't take much time to be performed.
https://github.com/vtex-sites/starter.store/pull/366
- [Next.js `output`options](https://nextjs.org/docs/pages/api-reference/next-config-js/output#caveats)
=> chore: Improve `@faststore/cli` build time

apps/site/pages/docs/api-extensions/api-extensions-improvements.mdx
Moves api extensions improvements guide to api-extensions folder
Docs Preview: https://faststore-site-git-docs-rename-guide-faststore.vercel.app/docs/api-extensions/api-extensions-improvements
=> docs: Moves to api-extensions folder

.github/workflows/ci.yml, package.json, packages/graphql-utils/src/index.ts
- Updates eslint-config version in package.json
- We're getting errors like this one when running yarn:
https://ci.codesandbox.io/status/vtex/faststore/pr/2215/builds/467587
You shouldn't get any error after running `yarn --force` or `yarn`. (Installing all the packages dependencies)
WIP
=> Fix: Updates eslint-config version

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
- Updates github actions actions/checkout@v2 and actions/setup-node@v2 to v4
- Updates code-ql action  to v3 (code-ql action v2 will be deprecated)
Everything should look like before with no error when running these actions.
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> Chore: Updates GH actions versions

packages/cli/src/utils/directory.ts
This PR fixes a bug where the generated gql function was being copied to the wrong directory.
It fixes the getRoot function in case the cwd of the process is the .faststore folder. It is not aware of that possibility, and accurately returns the project root in those cases, so the dir variables declared after it have the right information.
Run yarn dev while overriding fragments from the store!
🚧
=> fix(cli): getRoot accurately returns project root

packages/core/package.json
This PR enables imports from `@faststore/core/api` on stores using `moduleResolution: bundler` in their `tsconfig.json`.
It works by adding the export to FastStore Core's `package.json`.
Change the module resolution to "moduleResolution: bundler" in a store and try importing the `gql` function from `@faststore/core/api`
=> fix: add api to core exports and fix compatibility with moduleResoluion bundler

apps/site/pages/docs/headless-cms-overview.mdx
Since the [new user permission added to the Headess CMS](https://help.vtex.com/announcements/headless-cms-new-authorization-requirement--7G056zzZmGFBztkRqhpUgj), this PR updates the hCMS doc to reflect this change.
P.S.: The same content is also being updated in the [Developer Portal](https://github.com/vtexdocs/dev-portal-content/pull/980).
=> Docs: new Headless CMS user permissions

packages/core/src/sdk/cart/useCheckoutButton.ts
To ensure smooth functionality across different environments, such as localhost and development setups, it's crucial to include the necessary parameters for checkout. 
This practice maintains the integrity of the store-to-checkout flow. While in the final environment structure, domain and subdomain configurations enable seamless checkout using the cookie implementation, it becomes essential to explicitly pass parameters during testing to uphold the continuity of the process.
Add ?orderFormId param when using localhost or vtex.app env.
Go to the checkout using vtex.app env or localhost and check the parameter passing at the URL.
Final env will always use the cookie.
https://github.com/vtex-sites/starter.store/pull/382
https://github.com/vtex/faststore/assets/67066494/666205f8-6e8a-49ca-bab4 …
=> Feat: Add orderFormId path param for dev env

packages/core/cms/faststore/content-types.json, packages/core/cms/faststore/sections.json
This PR makes use of a new feature recently added to hCMS: Section and Content Type scopes. This is a feature that allows developers to prevent certain sections from being added to documents of any type, hopefully preventing changes made via hCMS from breaking live pages due to a new section being added and not rendering correctly. 
An example of a use case for this would be developing components that only work on PDPs, such as a `ProductDetails` section that requires information about a product to function correctly (via contexts or any other way). Yes, the developer should probably implement a fallback in their code to simply render `null` or something else if no product information is available, but using `scopes` and `requiredScopes` would make it even safer, since they could just add …
=> [TCM-184] Add `scopes` and `requiredScopes` to CMS files

packages/core/faststore.config.default.js, packages/core/src/components/cms/GlobalSections.tsx, packages/core/src/components/templates/LandingPage/LandingPage.tsx, packages/core/src/pages/[...slug].tsx, packages/core/src/pages/[slug]/p.tsx, packages/core/src/pages/index.tsx, packages/core/src/pages/s.tsx, packages/core/src/server/cms.ts, turbo.json
We need to stop getting the latest CMS page because of caching issues, so we're going to retrieve the contents during the build time and using those versions to request the necessary pages by version ID.
This PR uses the versionId to retrieve CMS page data, maintaining the previous way of getting the latest version as fallback.
=> feat: Get CMS Pages by Version ID with fallback

packages/cli/src/utils/generate.ts, packages/core/src/sdk/graphql/prefetchQuery.ts, packages/core/src/sdk/graphql/request.ts, packages/core/src/sdk/graphql/useLazyQuery.ts, packages/core/src/sdk/graphql/useQuery.ts, packages/core/src/server/index.ts, packages/core/tsconfig.json, packages/graphql-utils/package.json, yarn.lock
This PR fixes an issue where incompatible types between the return type of the `gql` function and the `useQuery_unstable` experimental hook would prevent the store from building.
It also fixes the issue where the module resolution for `@faststore/core` exports would sometimes be referencing the exports from the `.faststore` folder, which could lead to issues and inaccurate types.
It works by better specifying the `useQuery` type for the operation, and by removing exports from `.faststore/package.json` file. To compensate for that, path aliases were added for `@faststore/core` exports in `tsconfig.json`, so the `.faststore` uses its own definitions of the exports when building.
Define a query with `gql` and call it using `useQuery_unstable`. There should be no errors. Then, build the …
=> fix: useQuery types & module resolution

packages/core/src/components/navigation/NavbarSlider/NavbarSlider.tsx
Fix error preventing the store from building
Fixes props used on the overrides for the NavbarSliderHeader. Changes it to right props.
=> fix: navbar slider header props override pointing to another component

packages/api/src/platforms/vtex/utils/skuVariants.ts
The goal of this PR is to allow merchants to pick different SKU selector images for different SKU specifications. The current solution only allows one image to be picked for all Specifications. So a product with more than one Specification would look like this:
If this PR gets merged, given the two Specifications (Material and Size) and properly labeled images (`skuvariationmaterial` and `skuvariationsize`) merchants can pick different images for each variation, the end result being:
The name of the label and the fact that it has to be allinasingleword is a limitation of how the Catalog image uploader handles non-alphanumeric characters.
Go to the [starter deploy preview](https://sfj-2f52717--starter.preview.vtex.app/awesome-chair-99988217/p) and look for Awesome Chair. You should see …
=> Allow different images per specification

packages/cli/jest.config.js, packages/cli/package.json, packages/cli/src/__mocks__/hcms.ts, packages/cli/src/commands/cms-sync.ts, packages/cli/src/utils/generate.ts, packages/cli/src/utils/hcms.test.ts, packages/cli/src/utils/hcms.ts, yarn.lock
This PR updates the process of merging `content-types.json` and `sections.json` files from `@faststore/core` and local user files. It adds an extra validation step, so that users are aware of the changes they're about to make to hCMS configuration, and adds a deduping step to override definitions from `@faststore/core` in a predictable way.
Running all the way:
```
➜  hearstqa.store git:(feat/scoped-sections) ✗ yarn cms-sync --dry-run
yarn run v1.22.19
$ faststore cms-sync --dry-run
success - Temporary folder .faststore created
success - Core files copied
success - Public files copied
success - Starter files copied
success - Cypress test files copied
success - menshealth theme has been applied
success - CMS webhook URLs file created
You are about to override default content-types: …
```
=> [TCM-248] Add deduping and confirmation steps to `cms-sync` command

packages/api/src/platforms/vtex/utils/skuVariants.ts, packages/components/src/molecules/SkuSelector/useDefineVariant.ts
When implementing the Variant Swatch Image I noticed that if a SKU Selector had only one option the image would not appear. Upon inspecting this hook I noticed that if there's ony one image the code would infer they were all the same and only show the label, but there's the special case of only one image. This PR fixes this.
Go to the preview and see the [awesome-chair](https://sfj-5b2ff3a--starter.preview.vtex.app/awesome-chair-99988218/p) product and switch to the Plastic or Iron material SKUs. You should see an image on the Size selector. On the starter store [awesome-chair](https://starter.vtex.app/awesome-chair-99988218/p) will **not** show the image.
=> Fix SKU selector

packages/core/src/pages/api/preview.ts
It has been reported that when you're previewing one page of a given content-type, all the pages of the same content-type will have the same content because we're not setting the path of the preview properly. 
This PR aims to fix it, by using the same information we use to define landing page URLs
1. Point the preview to the linked starter deploy preview
1. Preview a landing page on our test account
2. See that it has the changes you're making
3. Navigate to another landing page. See its correct data.
4. Point the preview to the main starter domain.
5. Preview your changes. See that it affects all pages.
[NextJS Documentation](https://nextjs.org/docs/pages/building-your-application/configuring/preview-mode#specify-the-preview-mode-duration)
=> Set previewData path when previewing pages

apps/site/theme.config.tsx
This PR updates the announcement bar in `faststore.dev` informing users about the FastStore content migration to the [Developer Portal](https://developers.vtex.com/docs/guides/faststore/docs-what-is-faststore).
=> Docs: Update the announcement bar for the FastStore content migration

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/index.ts, packages/api/test/mutations.test.ts, packages/api/test/queries.test.ts, packages/api/test/schema.test.ts, packages/core/@generated/graphql.ts, packages/core/faststore.config.default.js, packages/core/src/server/options.ts
Add a config to allow replacing other subDomain prefixes for the forwardedHost to be sent.
The client configs an array that contains the subDomain prefixes at faststore.config:
```
api: {
storeId: 'storeframework',
workspace: 'master',
subDomainPrefix: ['www', 'shop'],
environment: 'vtexcommercestable',
hideUnavailableItems: false,
incrementAddress: true,
}
```
With that in case of the host is https://www.vtexfaststore.com we should send .vtexfaststore.com
in case its https://shop.vtexfaststore.com we should send .vtexfaststore.com
Add the subDomainPrefix to the array list and access a domain with the current version and check the host where the checkout cookie was created.
=> Add: subDomainPrefix as a store config

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts, packages/api/test/mutations.test.ts, packages/api/test/queries.test.ts, packages/api/test/schema.test.ts, packages/core/@generated/graphql.ts, packages/core/faststore.config.default.js, packages/core/src/server/options.ts
Add a fallback for the orderNumber from orderFormId from the cookie.
When a user creates a cart at a subDomain from FastStore the cookie is sharable between those.
The behaviour today:
- OrderForm A at cookie created at the subDomain
- User goes to FastStore
- isStable = true (no eTag) and orderNumber would be null since there is nothing at the local cart
- ValidateCart delete all items from OrderForm A
Behaviour after this change:
- OrderForm A at cookie created at the subDomain
- User goes to FastStore
- isStable = true (no eTag) and orderNumber do not get the value from the local cart so the fallback is the value from the cookie orderForm A
- ValidateCart returns the same orderForm setting the eTag to it
You can simulate this behaviour as following:
- Create the cart at FS
- Delete the …
=> Get order number from checkout cookie

packages/api/src/platforms/vtex/resolvers/validateCart.ts
The validateCart creates the orderForm without the customData the first time it happens at the site because the orderNumber still do not exist at the cookies or at the cartStorage.
With this change when the orderForm is being created by FastStore we will set the new orderForm already with the customData.
The problem is that when the client just entered the site the first validateCart Mutation will only set the cookie but if the second validate Cart Mutation already is an add to Cart the orderForm will have isStale true because the customData was not set at the first request and the items wont be added. The second request would work but it causes an experience problem for the client. 
Run the code locally and try the request of the validateCart to create the orderForm:
```
curl --location …
```
=> update validateCart logic

packages/api/src/platforms/vtex/resolvers/validateSession.ts
Fix the postalCode for regions like UK.
Today the postalCode when it has an input like "SE10 0GP" will:
const postalCode = String(oldSession.postalCode ?? '').replace(/\D/g, '')
// output "100"
With this change the output will be:
const postalCode = String(oldSession.postalCode ?? '')
// output "SE10 0GP"
The client should send the input for the postalCode and we should not do any replace to edit it because we have different rules depending on the country.
For UK:
Example WITH space:
https://demogrocery.vtexcommercestable.com.br/api/checkout/pub/regions?country=GBR&postalCode=SE10 0GP ✅ 
Example WITHOUT space:
https://demogrocery.vtexcommercestable.com.br/api/checkout/pub/regions?country=GBR&postalCode=SE100GP ❌ 
For Portugal:
Example WITH "-": …
=> remove logic from postalCode

packages/cli/package.json, packages/cli/src/commands/dev.ts, yarn.lock
Env vars aren't available on development. So in this pr, I allow to load `vtex.env` in the process.env in development.
All env var in `vtex.env` are available on `process.env` during development.
Create a custom env var in `vtex.env` and try to use it on your store.
=> Load environments variables in dev

packages/api/src/platforms/vtex/resolvers/validateCart.ts
Fix the validateCartMutation for cases where:
- No orderNumber is sent **and** 
- No cookie is sent to the context
Now we validate if theres any cookie inside the headers before calling the function that will parse it to avoid breaking the request.
Call it at the final env in those conditions:
```
curl --location 'https://www.vtexfaststore.com/api/graphql?operationName=ValidateCartMutation&operationHash=87e1ba227013cb087bcbb35584c1b0b7cdf612ef' \
--header 'accept: */*' \
--header 'accept-language: pt-BR,pt;q=0.9' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'origin: https://www.vtexfaststore.com' \
--header 'pragma: no-cache' \
--header 'referer: https://www.vtexfaststore.com/~partytown/partytown-sandbox-sw.html?1711550070899' \
--header …
```
=> Bug Fix: Validate for order or cookie empty context 

packages/cli/src/utils/hcms.test.ts, packages/cli/src/utils/hcms.ts
Fixing a bug on how files for hCMS are being generated. If a store did not define their own `content-types.json` or `sections.json` files, the default content from `@faststore/core` would be ignored when `faststore cms-sync` is executed.
- Clone a store's repo, or the starter.
- Install `@faststore/cli` version from the Deploy Preview below.
- Run `faststore cms-sync --dry-run` (to not actuality sync the files), without creating a `/cms` folder or creating one that's laking either `content-types.json` or `sections.json`.
- Check the generate files at .faststore. They should not contain empty arrays.
Motivated by: https://vtex.slack.com/archives/C0164SHMAV9/p1710332274381219.
=> [TCM-328] Prevent generated files for hCMS from being empty

packages/cli/src/commands/cms-sync.ts, packages/cli/src/utils/generate.ts
The releases/CMS team reported that Sometimes, we do not get the webhook call at the end of the publishing.
This PR aims to ensure the generation of the cms webhook file using the `generate` method.
This file has been generated in the cms-sync command since [this PR](https://github.com/vtex/faststore/pull/2240/files).
- https://github.com/vtex-sites/starter.store/pull/420
=> chore: ensure generate the cms webhook file in generate method

packages/components/jest.config.js, packages/components/package.json, packages/components/src/molecules/CheckboxField/CheckboxField.tsx, packages/components/test/molecules/CheckboxField/CheckboxField.test.tsx, yarn.lock
Our `CheckboxField` was inconsistent with its documentation. It was not accepting the `checked`, `disabled`, and `partial` props from Checkbox. This PR fixes this.
As a bonus, I've added Jest and React Testing Library so we can start adding those tests to our components. I've first created a failing test and then implemented the props.
Just run `yarn test` and you should have all success specs.
For some reason we don't use the `CheckboxField` on our starter.
=> Fix missing Checkbox props on CheckboxField component

packages/core/src/components/sections/CrossSellingShelf/OverriddenDefaultCrossSellingShelf.ts, packages/core/src/customizations/src/components/overrides/CrossSellingShelf.tsx
The override component `__experimentalProductCard` doesn't work because overriden definitions of `CrossSellingShelf` section doesn't extend `ProductShelf` section overriden definitions.
The proposal follows a pattern already coded at [OverriddenDefaultProductGallery.ts](https://github.com/vtex/faststore/blob/main/packages/core/src/components/sections/ProductGallery/OverriddenDefaultProductGallery.ts) and [OverriddenDefaultProductShelf.ts](https://github.com/vtex/faststore/blob/main/packages/core/src/components/sections/ProductShelf/OverriddenDefaultProductShelf.ts).
Extends `CrossSellingShelf` section overriden definitions with `ProductShelf` section overriden definitions.
Override `CrossSellingShelf` section creating a file `src/components/overrides/CrossSellingShelf.tsx` like this: …
=> feat: allows to override ProductCard of CrossSellingShelf

packages/core/@generated/graphql.ts, packages/core/src/components/product/ProductGrid/ProductGrid.tsx
Add priority to the 1st product's image on a PLP. It was motivated by a store that was having the performance score penalized on lighthouse because its LCP was the first product on the PLP. 
We haven't had found this issue before because our starter has a hero image on PLP (that already has the priority set). 
On the `ProductGrid` component we send the `loading` prop as `eager`  through the `ProductCard` component when it's the first product, then on the [Image](https://github.com/vtex/faststore/blob/76e80ae902be812e237519520a1b7159f4dab63f/packages/core/src/components/ui/Image/Image.tsx#L17) component the priority will be added.
1. Run `yarn dev` and go to http://localhost:3000/technology
2. Inspect the page and check that only the first product's image has the priority set as `high`: …
=> chore: add priority to the first product's image on PLP

packages/ui/src/components/molecules/Carousel/styles.scss
The Carousel Icons styles where affecting other unrelated icons inside the `ProductCard`, so I fixed the specificity of the code.
|Before|After|
|-|-|
|<img width="1392" alt="image" src="https://github.com/vtex/faststore/assets/11613011/a5d42191-6a66-4d4b-ac3e-b78f35bdc355">|<img width="1392" alt="image" src="https://github.com/vtex/faststore/assets/11613011/0ee707b5-cafa-403f-bac9-6c0afe0f1a34">|
1. Change line 120 on `packages/core/src/components/product/ProductCard/ProductCard.tsx` to `onButtonClick={() => {}}`
2. Run `yarn dev`
3. Go to homepage and hover a Carousel
=> [patch] fix: `Carousel` icon color cascade

packages/core/app/fs-next-update/page.tsx, packages/core/app/layout.tsx, packages/core/next-env.d.ts, packages/core/next.config.js, packages/core/tsconfig.json
This PR aims to: 
run locally and you should see the initial structure under: http://localhost:3000/fs-next-update
Next 13 file conventions
https://nextjs.org/docs/app/api-reference/file-conventions/layout
CSS order issues:
[[NEXT-1308] Css is imported multiple times and out of order in /app dir · Issue #51030 · vercel/next.js](https://github.com/vercel/next.js/issues/51030#issuecomment-2005254907) 
[Verify CSS import ordering · Issue #16630 · vercel/next.js](https://github.com/vercel/next.js/issues/16630) 
[CSS "@import <file> layer()" isn't working · Issue #55763 · vercel/next.js](https://github.com/vercel/next.js/issues/55763) 
[[NEXT-1308] Css is imported multiple times and out of order in /app dir · Issue #51030 · vercel/next.js](https://github.com/vercel/next.js/issues/51030#issuecom …
=> Feat: Next 13 initial setup

packages/api/src/platforms/vtex/clients/commerce/index.ts
Small fix to allow graphiQl playground to run locally
On the `packages/api` directory, run `yarn dev:server`
The playground should be available at `localhost:4000/graphql`
=> Fix validation to enable playground to run locally

packages/core/app/layout.tsx
This PR intends to set the default SEO metatags for the root `layout.tsx` file.
- Run the local server (`yarn turbo run dev --filter=@faststore/core`);
- Make sure that all the current pages are working as expected (`/`, `/office` and some `/<slug>/p`);
- Make sure `/fs-next-update` is rendering (blank) without errors and both `<meta "robots">` and `<meta "googlebot">` exist with the `noindex,nofollow` tags.
- https://nextjs.org/learn-pages-router/seo/crawling-and-indexing/metatags
- https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-3-migrating-nexthead
- https://nextjs.org/docs/app/api-reference/functions/generate-metadata#robots
=> feat: Next 13 root `layout.tsx` default SEO metatags

packages/core/@generated/graphql.ts, packages/core/src/sdk/search/state.ts
Fix bugs related to the addition of fuzzy parameters to the URL on PLP (category page and search page). See jira tasks on the references section below.
By using the `replace` function instead of `push` we are able to update the URL adding the fuzzy parameters to it without triggering the navigation. Thus, it doesn't re-render the page and it doesn't affect the back button to previous page.
It happens because the `replace` doesn't add the new URL as a new entry on the `history` stack.
Test a category page (example: `/office`) and test search also. Both pages should have its URL updated to add the fuzzy and operator params, but shouldn't re-render. Also, if you click the browser return button you should go to the previous page (Home, for example, if you were on the Home page and then went …
=> Fix: use router replace to change URL and fix fuzzy bugs

packages/core/package.json, packages/core/src/experimental/index.ts, packages/core/src/experimental/server/index.ts, packages/core/tsconfig.json
- https://github.com/vtex/faststore/pull/2242
introduces a problem:
We are exporting a server function in the experimental module, and then when we try to use other functions from this file in the starter, like some hook/component/function, we get some errors like:
I think this is happening because this is not tree-shakable, and then the execute function comes together with the module.
In that way, we export the server functions to their module: `@faststore/core/experimental/server`.
I use the codesandbox version from this PR in a starter PR for which we are testing API Extension and section Overrides.
- https://github.com/vtex-sites/starter.store/pull/199
(see [this commit](https://github.com/vtex-sites/starter.store/pull/199/commits/e27d2fe2f05053efe754abe1176e9f16156c68a3)).
=> Fix: exports server functions on its own module

packages/core/package.json, packages/core/src/server/cms/index.ts, packages/core/test/server/cms/index.test.ts, yarn.lock
Currently, when trying to load contentTypes from the Headless CMS we just fetch the first page and ignore the hasNextPage response from the cmsClient.
This PR changes that to load all publishedContentTypes before returning. This might be troublesome if a given account has thousands of content types of the same type (PLP, for instance). We can either increase the page size to make fewer requests or investigate if we can move the filtering to the CMS Client.
I've added tests, but this can be replicated by copying the `server/cms/index.ts` code to a store's node_modules folder and you should see the effect.
=> Fetch multiple CMS template pages instead of just the first

packages/core/src/components/sections/ProductDetails/DefaultComponents.ts, packages/core/src/components/sections/ProductDetails/ProductDetails.tsx, packages/core/src/typings/overrides.ts
This PR intends to enable override for `ProductDescription` component and props in `ProductDetails` section.
You can override `ProductDescription` using `__experimentalProductDescription`.
In `packages/core/src/customizations/src/components/overrides/ProductDetails.tsx`
change the following code:
```
const override: SectionOverride = {
section: SECTION,
components: {
__experimentalProductDescription: {
props: { descriptionData: [{ title: 'Title', content: 'Some content' }] },
},
},
}
```
- Follow this doc: https://developers.vtex.com/docs/guides/faststore/overrides-component-props;
- Check the Overrides migration from V1 to V2 to ensure you are creating the override in the correct way.
https://github.com/vtex-sites/starter.store/pull/446
Using the changes of the PR above, you can test by …
=> feat: Enable `ProductDescription` override in `ProductDetails` section

packages/core/src/server/cms/index.ts, packages/core/test/server/cms/index.test.ts
Reverts the cache approach when fetching multiple hCMS pages.
It looks like the cache strategy used in this PR
- https://github.com/vtex/faststore/pull/2314
It is bringing some issues for clients.  So This PR aims to revert this logic.
=> Fix: Reverts multiple fetch cms pages cache strategy

packages/core/cms/faststore/sections.json, packages/core/src/components/navigation/Navbar/Navbar.tsx, packages/core/src/components/search/SearchInput/SearchInput.tsx, packages/core/src/components/sections/Navbar/Navbar.tsx
Add placeholder at the search input to enable users to change the default text:
https://github.com/vtex/faststore/assets/67066494/5da24c43-3be5-4934-ae7e-4b354cf1485b
Change the placeHolder at the CMS inside the navbar and look at the preview.
Sync the new section or you can use this account:
https://bibi--bibi.myvtex.com/admin/new-cms/faststore/globalSections/edit/72531e4c-c99f-11ee-8452-1249c7739e6b
Change the account and workspace for bibi.
=> Add: Placeholder text for Search NavBar

packages/core/src/sdk/search/state.ts
Fix the blink for Dunnes project when the param is added at the URL:
https://github.com/vtex/faststore/assets/67066494/65af813c-d604-4594-b04c-cd61340ea76a
Added `window.history.replaceState({}, '', newUrl)` to stop the page from reloading unnecessarily.
Core Before:
https://github.com/vtex/faststore/assets/67066494/571673df-e4bc-4da4-9874-939fe13ec492
Core After:
https://github.com/vtex/faststore/assets/67066494/56ee0b93-1ba3-4a93-8fab-6715745ee18c
Beta package:
https://partnerintegrationbra-clvfdw8vd00danzcdwpy08ig3-rd740v8hj.b.vtex.app/
Enter a category like clothing:
https://partnerintegrationbra-clvfdw8vd00danzcdwpy08ig3-rd740v8hj.b.vtex.app/clothing 
No specific reference here :)
=> Fix URL update to prevent page reloads

packages/cli/src/commands/build.ts
When we use the public folder in the root from the starter, maybe to add a new favicon, the build from projects from FSW does not load other files, like the `icons.svg`. This PR aims to copy back the public folder from `.faststore/public` to the `public` folder from the root directory after the build command so that the build can leverage all files over there.
see the starter PR
- https://github.com/vtex-sites/starter.store/pull/471
preview: https://starter-enk8eefs6-faststore.vercel.app/
Please take a look at the different favicon and also the icons that are being loaded.
The previous preview without the changes from this PR with the favicon but without the icons:
https://starter-1sjtb4i7u-faststore.vercel.app/
with favicon + Without icons /  with favicon + with icons
- …
=> fix: copy public folder back to root dir (fix vercel build)

packages/core/src/sdk/search/state.ts
Reverts vtex/faststore#2334
When adding a new filter and refreshing the page the state is kept the same without changes.
https://github.com/vtex/faststore/assets/67066494/9ef74a81-e893-42ae-bb08-9c1279edc603
=> Revert "Fix URL update to prevent page reloads"

packages/core/src/components/ThirdPartyScripts/vtex.tsx
Fix ActivityFlow integration on FastStore by adding the non-standard `an` attribute to the initializing script of ActivityFlow.
Run the core locally and see that the `pageView` event has the correct `accountName`
=> Add `an` attribute to activity-flow initializer script

packages/api/package.json, packages/components/package.json, packages/ui/package.json
Bash's `&` operator runs what's to the left of it on the background. Usually it's used together with the `wait` command. This was not the case. I **believe** that this command running in the background was what was causing the intermitent issue we had. Whenever the esnext build finished before the commonjs one, the process would end and kill the background process.
The side effect of this changes is that we add a couple of seconds to the overall build time.
A simplified example of this behavior can be found by running the following script:
```sh
#!/bin/bash
backgroundChild() {
sleep 10
echo "Background Child function is done."
}
foregroundChild() {
sleep 3
echo "Foreground Child is done."
}
echo "Parent running"
backgroundChild &
foregroundChild
```
and notice that we never see …
=> Stop running commonjs build in the background

packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts, packages/api/src/platforms/vtex/resolvers/offer.ts, packages/api/src/platforms/vtex/utils/taxes.ts
Add Optional Chaining in Faststore Tax calculation
Related with this [#2363](https://github.com/vtex/faststore/issues/2363)
=> fix: Adjust price with taxes

packages/components/src/molecules/SkuSelector/useSkuSlug.ts
Fix the scenario when there is more than one SKU variation with the same substring.
When there is more than one SKU variation with the same substring, we use the  `getBestMatchVariation()` function to exact match instead of using `includes().`
you can use the version XXX in your store to validate it.
tickets
https://vtexhelp.zendesk.com/agent/tickets/1033578
https://vtexhelp.zendesk.com/agent/tickets/1047992
related
- https://github.com/vtex/faststore/pull/2353
=> fix: SKU Selector not choosing correct SKU when having similar variations

packages/core/src/sdk/analytics/platform/vtex/search.ts
While investigating why some events weren't being triggered and tracked on IS Analytics page, @chrsmutti suggested that the proper behavior is to refresh or extend the cookie duration every time a search is made. 
If the cookie is not expired, we set it again, with the same value, and the same expiry in seconds.
Run core locally, do a search, see the cookie value and its expiry date. Wait for some time, make another search, and see if the cookie value stays the same but the expiry date should have moved forward.
=> Refresh cookie on search

.gitignore, packages/cli/src/commands/build.ts, packages/cli/src/commands/cms-sync.ts, packages/cli/src/commands/dev.ts, packages/cli/src/commands/generate-graphql.ts, packages/cli/src/commands/start.ts, packages/cli/src/commands/test.ts, packages/cli/src/utils/directory.test.ts, packages/cli/src/utils/directory.ts, packages/cli/src/utils/generate.ts, packages/core/postinstall.js, packages/core/src/server/generator/schema.ts, packages/core/src/server/index.ts
To allow FastStore to be run from a monorepo we need to add this path argument so the FastStore CLI can locate the directory where the actual customizations are.
After https://github.com/vtex/faststore/2366 and https://github.com/vtex/faststore/2368 this PR just adds the arg to the OCLIF command class and pass it down to the code, to be used with `withBasePath`.
=> Add `path` arg to all commands

packages/sdk/src/search/serializer.ts, packages/sdk/src/search/useSearchState.ts, packages/sdk/src/types.ts, packages/sdk/src/utils/format.ts, packages/sdk/test/search/serializer.test.ts
URL params are stripped out on inbound PLP links when the app rebuilds the URL from state. This is undesirable for end users who need to add params to their links - e.g. referral or UTM tracking codes.
Any params that are not included in the state allow list are grouped into a `passThrough` field in the state, and added back when the URL is rebuilt.
1. Visit a PLP link with a URL param: `/my-cool-category?foo=bar`
2. Validate that the additional param is preserved after URL state updates
I'm happy to adjust naming or implementation, this set of changes was the result of a spike into preserving UTM params on inbound links.
=> fix: Pass Through PLP URL Params

packages/components/src/molecules/OrderSummary/OrderSummary.tsx, packages/components/src/molecules/ProductCard/ProductCardContent.tsx
This PR intends to update the props descriptions for [OrderSummary](https://developers.vtex.com/docs/guides/faststore/molecules-order-summary) and [ProductCard](https://developers.vtex.com/docs/guides/faststore/molecules-product-card).
This PR fixes some typos in the `OrderSummary` and `ProductCard` props description. However, the main fixes are related to the taxes related props as you can see in the following screenshot:
https://vercel.live/open-feedback/faststore-site-git-chore-update-props-description-faststore.vercel.app?via=pr-comment-visit-preview-link&passThrough=1
Dev Portal PR (updating the documentation): https://github.com/vtexdocs/dev-portal-content/pull/1298#pullrequestreview-2178476553
=> chore: update OrderSummary and ProductCard props description

packages/core/src/sdk/analytics/platform/vtex/search.ts
The `vtex.sae-analytics` will start using the same name
`vtex-search-{anonymous,session}` for cookies created in the Store
Framework context. Keeping this consistent across storefronts will
enable easier management of the cookies required by the platform.
The same as #2012, but now the cookie names are: `vtex-search-anonymous` and
`vtex-search-session`.
Run core locally, do a search, see the cookie name.
https://github.com/vtex/sae-analytics/pull/26
=> Rename vtex search cookie to keep it uniform

packages/api/src/platforms/vtex/utils/skuVariants.ts, packages/components/src/atoms/Button/Button.tsx
Makes the sku selector follow the order of the admin
Same adjust was done while ago to IO!
The code needs to validates if it's number prior sorting this. For example, if you sort `a - b` for sizes, you will have different orders, mostly thinking in cross language.
e.g, sorting sizes in PT:
G - M - P 
Commit in IO: https://github.com/vtex-apps/store-components/blob/2fe597cf00b0d2968487189f99ccaf80b73e5da6/react/components/SKUSelector/components/SKUSelector.tsx#L247
This [product](https://vysk.myvtex.com/adidas-womens-microdot-polo-night-indigo/p): admin / IO / stable / fast.
After fix:
=> feat: Change order of sku selector

packages/api/src/platforms/vtex/utils/skuVariants.ts, packages/api/test/vtex.skuVariants.test.ts
This PR intends to fix the SKU variants sort implementation. It will preserve Admin's variants order for cases that variants are not numbers. (e.g. Sizes: ['S', 'M', 'L'] should be rendered as it is)
Example:
`{
Size: [
{
...,
label: 'Size: L',
value: 'L'
},
{
...,
label: 'Size: M',
value: 'M'
},
{
...,
label: 'Size: S,
value: 'S'
},
]
}`
The expected result is to keep this order:
But for the following case:
`{
Size: [
{
...,
label: 'Size: 2',
value: '2'
},
{
...,
label: 'Size: 3',
value: '3'
},
{
...,
label: 'Size: 1',
value: '1'
},
]
}`
The result should be sorted, so Sizes: [1, 2, 3]
Run `yarn test` and check the results.
#2374
=> fix: Sku variants sort

packages/cli/src/utils/commands.ts
It fixes a critical issue reported on Windows, reported by a Hearst developer while attempting to run `faststore dev` on their Windows machine:
Related thread on Slack: https://vtex.slack.com/archives/C06E1DCFPCZ/p1722283695110209
It adds `shell: true` to the command spawn to ensure that the script must be run under the scope of a `shell`. Discussion can be found here: https://stackoverflow.com/a/54515183 as well as the doc specs: https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback
- On a Windows machine, run `yarn faststore dev` under your test store, with the CLI version available from this PR
- Repeat the previous step for Mac and Linux
Related issue: https://stackoverflow.com/a/54515183
Doc specs: …
=> fix(cli/dev): ensure `shell: true` is passed when spawning `na`

packages/core/src/components/navigation/Navbar/Navbar.tsx, packages/core/src/components/navigation/NavbarSlider/NavbarSlider.tsx, packages/core/src/components/sections/Navbar/DefaultComponents.ts, packages/core/src/experimental/index.ts, packages/core/src/typings/overrides.ts
During the development of the B2B Self Management feature, we need to customize and add new behaviors to the "My Account" button, making it open a modal instead of going to the `/account` page. While most of this development will happen in an external library, the ability to override this button is important for us. 
This PR enables just that, the ability to completely override the default SignIn / My Account button.
=> Enable sign in Button override

packages/cli/src/commands/dev.ts, packages/cli/src/utils/generate.ts
Some package managers (pnpm) use symlinks to be faster and more space conscious. This adds the dereference: true option to all the copySyncs we have.
[Node's FS documentation on cpSync](https://nodejs.org/api/fs.html#fscpsyncsrc-dest-options).
[fs-extra's docs](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy-sync.md)
=> Allow copy functions to follow symlinks

packages/cli/src/utils/generate.ts, packages/core/src/components/cms/SectionBoundary.tsx, packages/core/src/components/common/Footer/Footer.tsx, packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx, packages/core/src/components/search/SearchInput/SearchInput.tsx, packages/core/src/components/search/Sort/Sort.tsx, packages/core/src/components/templates/LandingPage/LandingPage.tsx, packages/core/src/components/templates/ProductListingPage/ProductListing.tsx, packages/core/src/components/ui/Image/loader.ts, packages/core/src/components/ui/ImageGallery/ImageGallery.tsx, packages/core/src/components/ui/Newsletter/NewsletterAddendum.tsx, packages/core/src/customizations/src/dynamicContent/index.ts, packages/core/src/pages/[slug]/p.tsx, packages/core/src/sdk/analytics/index.tsx, packages/core/src/sdk/error/ErrorBoundary/ErrorBoundary.tsx, packages/core/src/sdk/overrides/overrides.ts, packages/core/src/sdk/product/useProductGalleryQuery.ts, packages/core/test/utils/multipleTemplates.test.ts, packages/core/tsconfig.json
Strict mode in TypeScript is a way to opt into a more strict type-checking behavior to catch more potential issues at compile time. When enabled, it activates a set of stricter type-checking options that enforce more constraints on your code. Here's how it works and what it does:
**No Implicit Any (noImplicitAny)**: This prevents variables and parameters from defaulting to the any type when TypeScript is unable to infer a more specific type. This helps catch cases where you might have forgotten to specify a type or TypeScript can't infer one for you.
To enable strict mode, you can set "**strict": true** in your `tsconfig.json` file. This is equivalent to enabling all of the above options individually.
The idea of ​​this initiative is to enable rule by rule incrementally so that it is …
=> feat: noImplicitAny

packages/cli/src/commands/build.ts, packages/cli/src/utils/commands.ts, packages/cli/src/utils/directory.ts, packages/cli/src/utils/generate.ts, packages/core/next-env.d.ts, packages/core/next-seo.config.ts, packages/core/src/pages/_app.tsx, packages/core/tsconfig.json
create a metatag in build time in order to know when the build was created.
using the faststore cli we generate a date and insert on store html
finding the `data-generated-at` metatag on source code.
=> metatag generated at

packages/core/next-env.d.ts
#2417 follow-up.
Adds generated-at metatag on source code to identify when the build was created.
=> release: FastStore core v3.0.94

packages/core/src/sdk/auth/index.ts, packages/core/src/sdk/product/useLocalizedVariables.ts, packages/core/src/sdk/session/index.ts
The `ClientManyProductsQuery` was being fetched twice with almost the same parameters, the only difference was the `hasOnlyDefaultSalesChannel` introduced on this [PR](https://github.com/vtex/faststore/pull/2282) and used only by the `useAuth` hook. 
It doesn't need to be sent on the `ClientManyProductsQuery`, only on the `ValidateSession` mutation.
These other queries were also being affected: `ClientSearchSuggestionsQuery`, `ClientProductGalleryQuery` and `ClientProductQuery`.
It filters the `hasOnlyDefaultSalesChannel` key out of the `channel` object in the `useSession` before sending it on the query.
Running `yarn dev` and checking on the PDP that the `ClientManyProductsQuery` is not duplicated and is not sending the `hasOnlyDefaultSalesChannel` on `channel`.
| -|-| …
=> Fix: duplicated ClientManyProductsQuery

packages/api/mocks/AllProductsQuery.ts, packages/api/mocks/ProductQuery.ts, packages/api/mocks/RedirectQuery.ts, packages/api/mocks/SearchQuery.ts, packages/api/mocks/ValidateCartMutation.ts, packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/resolvers/searchResult.ts, packages/api/src/platforms/vtex/utils/facets.ts, packages/api/src/typeDefs/query.graphql, packages/core/@generated/gql.ts, packages/core/@generated/graphql.ts, packages/core/src/sdk/product/useProductGalleryQuery.ts, packages/core/src/sdk/search/state.ts
This PR reverts the following PRs:
- https://github.com/vtex/faststore/pull/2307
- https://github.com/vtex/faststore/pull/2204
Also, it resolves the conflicts from the current main branch.
We are removing the reload issue caused by the use of fuzzy logic and operators in handling IS requests. 
The team will try another approach to address the usage of fuzzy logic and operators in IS requests allowing the search engine decide the best parameters for the search.
You can run the project locally and double-check if the PLP/Search page just loads once.
Also, you can use the preview URL from starter PR:
PLP: https://sfj-728d5af--starter.preview.vtex.app/office
Search: https://sfj-728d5af--starter.preview.vtex.app/s?q=shirt&sort=score_desc&page=0
- …
=> Fix: Rollback fuzzy params in PLP 

packages/api/mocks/ValidateCartMutation.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/loaders/sku.ts, packages/api/src/platforms/vtex/resolvers/validateCart.ts
In this PR we add the `show-invisible-items` param to IS api in order to enhance the invisible SKU
=> Fix: Add 'show-invisible-items' parameter to IntelligentSearch API

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/utils/facets.ts
This PR intends to add support to receive the `regionId` from the PDP query.
The `product` resolver will consider the `regionId` sent through the PDP query and will send it as facet to the IS request.
- Install the last `@faststore/api` version generated by CodeSandbox;
- Send the `regionId` key/value inside the `ServerProductQuery`'s `locator` variable.
=> feat: Consider `regionId` from PDP query

packages/api/src/platforms/vtex/resolvers/validateCart.ts
Fix the validateCart mutation resolver that is overriding the orderForm for items that should be splitted.
When adding different assembly options for the same product, it must be kept separate in the orderForm. To prevent this merge, the parentItemIndex field is checked to see if that item is associated with the assembly of another item.
In https://devjoelson--jwpepperdev.myvtex.com/1309475/p
Add different combinations to your cart, for example:
As a result, we will have the same product duplicated in the cart:
When we copy and paste the cookie from orderForm to faststore, it should not change the cart as it does in this example:
and then, when updating the cart in IO, we have the change that shouldn't happen:
=> fix: validateCart mutation merging orderForm items with assemply options

packages/api/mocks/AllProductsQuery.ts, packages/api/mocks/ProductQuery.ts, packages/api/mocks/RedirectQuery.ts, packages/api/mocks/SearchQuery.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/index.ts, packages/api/test/mutations.test.ts, packages/api/test/queries.test.ts, packages/api/test/schema.test.ts, packages/core/src/server/options.ts
Make the `simulationBehavior` param from IS configurable through the faststore.config file.
When the `simulationBehavior` is present on the config file it'll be used on the IS fetch, example: 
`https://{{account}}.vtexcommercestable.com.br/api/io/_v/api/intelligent-search/product_search/category-1/office/trade-policy/1?page=1&count=12&query=&sort=&fuzzy=auto&locale=en-US&hideUnavailableItems=false&simulationBehavior=skip`
Otherwise, if it's not present, it'll continue working as it already was:
`https://{{account}}.vtexcommercestable.com.br/api/io/_v/api/intelligent-search/product_search/category-1/office/trade-policy/1?page=1&count=12&query=&sort=&fuzzy=auto&locale=en-US&hideUnavailableItems=false`
Run `yarn dev` and ensure it's working as expected. Then, add the `simulationBehavior` …
=> Feat: Make simulationBehavior search param configurable

packages/core/src/components/region/RegionModal/RegionModal.tsx
This PR attempts to fix type errors related to this component in some customer's stores.
```
./src/components/region/RegionModal/RegionModal.tsx:76:10
Type error: Right operand of ?? is unreachable because the left operand is never nullish.
```
=> fix: adds optional icon to icon prop

apps/site/pages/components/molecules/card.mdx, packages/components/jest.config.js, packages/components/jest.setup.ts, packages/components/package.json, packages/components/test/molecules/Card/Card.test.tsx, packages/components/test/molecules/CheckboxField/CheckboxField.test.tsx, packages/components/tsconfig.json, yarn.lock
- Setup `@testing-library/jest-dom` to help to test our components when checking an element's attributes, its text content, its css classes...
- Adds `Card` component tests
- Introduces accessibility tests:  This won't guarantee that what we're building is accessible, but it's a first step towards it. 🥳 
- Updates `CheckboxField` component test 
TODO: Document 
Currently, our components library do not have tests, but we want to introduce them for upcoming components. For existing components, we will gradually add tests retroactively.
1. navigate to `packages/components` -> run `yarn install`
2. run `yarn test`, you will be able to see the tests running
_____
3. removing `<Label>` component from `CheckboxField`, when running the step 2, you will get: …
=> Feat: Adds jest-axe and Card component test

packages/cli/README.md, packages/cli/src/commands/create.ts, packages/cli/src/index.ts
Just to rename the `init` command to `create` to adhere to the new specification
=> chore: rename init command to create

packages/core/src/Layout.tsx, packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts, packages/sdk/src/analytics/events/page_view.ts, packages/sdk/src/analytics/wrap.ts, packages/sdk/src/index.ts
Trigger some critical events for analytics tools. They are:
| TOPIC | BEHAVIOR | NOTES |
|--------|--------|--------|
| 01.CE - page_view | not fired on first page, second page, third page, etc. | only fired after purchase |
| 03.CE - view_item_list | duplicate |   |
| 05.CE - add_to_cart | did not fire after adding to cart on item page | did fire on cart page |
| 05.CE - add_to_cart_enriched | did not fire after adding to cart on item page | did fire on cart page |
| 07.CE - GA4 - view_item | did not fire after viewing pdp |   |
=> feat: trigger critical events for analytics

packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts
Add `sendPageViewEvent`  to `useEffect` dependencies to fix eslint warning
=> feat: add sendPageViewEvent to useEffect dependencies

packages/core/next.config.js, packages/core/src/components/sections/Hero/Hero.tsx
This PR is part of the Performance epic and aims to add a new `deviceSizes` with a size of `412`. This is the size used for `Moto G Super`, the mobile device used in the PageSpees Insight (PSI).
It also changes the `Hero` Image size to fit a better config related to the LCP metric.
=> Feat: adds new `deviceSizes` and adjust `Hero` Image

packages/components/src/organisms/PaymentMethods/PaymentMethods.tsx, packages/core/cypress/integration/a11y.test.js, packages/core/cypress/integration/analytics.test.js, packages/core/cypress/integration/seo.test.js, packages/core/faststore.config.default.js, packages/core/src/components/common/Footer/Footer.tsx, packages/core/src/components/common/Footer/FooterLinks.tsx, packages/core/src/components/common/Footer/FooterSocial.tsx, packages/core/src/components/sections/Incentives/Incentives.tsx, packages/core/src/components/ui/Incentives/Incentives.tsx, packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx, packages/lighthouse/src/index.ts, packages/ui/src/components/atoms/Incentive/Incentive.tsx, turbo.json
- Updates pdp product link for tests and updates tests to adapt to new product
The product we were testing is OutOfStock and does not have the expected ID. We switched to another product and updated the other tests accordingly."
- Puts back `cy.checkA11y` for home page, collection page and product page. (a11y.test.js)
- Fix automatic accessibility issues & improves overall
This PR, should fix the failing tests below:
1. You can test using this [PR](https://github.com/vtex-sites/starter.store/pull/535), the integration test all should be passing.
2. Run the core locally, then run `yarn test`. All the tests should pass.
https://github.com/vtex-sites/starter.store/pull/535
https://dequeuniversity.com/rules/axe/4.10/region?application=AxeChrome
=> Fix: Integration and enable back accessibility tests 

packages/core/src/pages/_document.tsx
This PR is part of the Performance epic and aims to add `preconnect` and `dns-prefetch` to the `vtexassets` so that it can establish network connections early to improve perceived page speed
- https://github.com/vtex-sites/starter.store/pull/551
https://web.dev/articles/preconnect-and-dns-prefetch?hl=pt-br
=> Feat: adds preconnect and dns-prefetch

packages/api/src/platforms/vtex/utils/slugify.ts
Fix the breadcrumb list when there is a category with pipe `|` in its name. 
Removes the `|` from the `slugify` function. 
Example: the category `vitrola | receiver` would be slugified to `vitrola---receiver` instead of `vitrola-|-receiver` and it would go to a not found page.
I've changed the category `Chairs` to use a pipe (`Furniture | Chairs`). So if you run the code and access this PDP page `/gorgeous-cotton-shirt-19863970/p`, you should be able to click on the breadcrumb link to this category and go to its page without getting a 404. 
https://github.com/vtex-sites/starter.store/pull/561
- [Slack thread](https://vtex.slack.com/archives/C051B6LL91U/p1726495723479679)
=> fix(api): slugify breaking category with pipe in its name

packages/core/src/pages/index.tsx
We had already removed this section from CMS, but it remained in the code.
By default we already have the `Newsletter` section in homepage, and  `BannerNewsletter` section should be in the PDP.
|Before| After|
|-|-|
|<img width="500" alt="before_homepage" src="https://github.com/user-attachments/assets/92ec8754-9629-4bd1-8144-fa6fb4d39959">|<img width="500" alt="no_bannernewsletter_homepage" src="https://github.com/user-attachments/assets/ce8e2fc2-50fb-48a9-9600-5bd7384afc2d">
Removed from CMS:
No other unused section was detected. BannerNewsletter still being used in PDP as expected.
Run `yarn dev` in the core, in the homepage you shouldn't be able to see the `BannerNewsletter` section
https://github.com/vtex-sites/starter.store/pull/557
https://vtex-dev.atlassian.net/browse/SFS-1453
=> Chore: Removes `BannerNewsletter` section from home

packages/cli/src/commands/build.ts, packages/cli/src/commands/dev.ts, packages/cli/src/commands/start.ts, packages/cli/src/utils/directory.test.ts, packages/cli/src/utils/directory.ts
To work with the Platform CLI, the FastStore CLI commands needs to accept more arguments. I've added such arguments but they are not being used, so this should not affect current behavior in any way.
Install the version generated by the codesandbox and call all commands :)
[Code](https://github.com/vtex-sites/starter.store/pull/566) | [Store (Vercel)](https://starter-rnshhkjja-faststore.vercel.app/) | [Store (Homebrew)](https://sfj-164c14b--starter.preview.vtex.app/)
[FastStore Platform Spec](https://github.com/vtex/faststore-platform/blob/main/docs/specification.md)
=> chore: adjust CLI to meet FSP Spec

packages/core/src/components/cms/ViewportObserver.tsx, packages/core/src/components/product/ProductGrid/ProductGrid.tsx, packages/core/src/components/ui/ProductGallery/ProductGallery.tsx, packages/core/src/components/ui/ProductGallery/ProductGalleryPage.tsx
This PR introduces the `ViewportObserver` component, which will be used in future tasks as part of our performance improvement initiative.
We'll primarily use it on mobile devices to prevent sections outside the viewport from being rendered initially. It checks whether a component or section is within the viewport, based on a specified height. We're using Moto G Power devices as the reference for this.
To facilitate the test for our future tasks, I have added a `debug` mode prop, so we can enable it for testing.
In this case, we can identify if the component is IN or OUT the viewport. **This is only for the initial render.**
1. go to `core/src/components/product/ProductGrid/ProductGrid.tsx`, add `debug` prop to following component:
```
<ViewportObserver name="UIProductGrid-out-viewport" …
```
=> Feat: Adds intersection (ViewportObserver) component

packages/cli/package.json, packages/cli/src/utils/dependencies.ts, packages/cli/src/utils/generate.ts, packages/core/discovery.config.default.js, packages/core/next.config.js, yarn.lock
This PR aims to experimentally allow the store to enable the use of preact instead of react, keeping react as the default behavior. The objective is to reduce the size of the package used in the project and thus improve performance.
When **preact** is enabled, all necessary **preact** dependencies are installed and preact settings are also added to `next.config`.
- Install this preview version of CLI in the starter
- Enable preact in `discovery.config.js` 
```
experimental: {
nodeVersion: 18,
cypressVersion: 12,
preact: true
}
```
- Run `yarn dev` or `yarn build`
- Validate if all necessary **preact** dependencies are installed
- Validate if the build size improves when running `yarn build`
- Validate if the store is working.
=> feat: enable preact experimental feature

packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/sections/Hero/Hero.tsx
Adds `LazyLoadingSection` component, it will be responsible for lazy loading Sections that are out of the viewport.
* It achieves this by:
* 1. Using the IntersectionObserver API for Sections below the fold.
* 2. Checking the UI context for Sections that are not in the viewport, such as the CartSidebar and RegionModal.
We will be implementing this in the `RenderSectionsBase` as part of our upcoming tasks. This component is not being applied in isolation due to concerns about increased Cumulative Layout Shift (CLS).
1. You can use this [preview link](https://starter-git-feat-lazy-loading-section-sfs-1508-faststore.vercel.app/), where the `LazyLoadingSection` is temporary applied or locally add it in `RenderSectionsBase` component.
``` 
<SectionBoundary key={`cms-section-${name}-${index}`} …
```
=> Feat: adds LazyLoadingSection component - perf

packages/cli/src/commands/build.ts
To fix the build of accounts using the discovery-only repo.
Instead of blindly moving `.faststore/.next` to the same place, we first check if we're trying to move it to the same place. If it is, we just skipping copy altogether.
Do the onboarding and change the repo to use this preview URL.
TBD
=> fix: don't move .next directory if it is in the correct place

packages/api/src/platforms/vtex/resolvers/validateCart.ts
Solves the bug when I have the same item with attachment without necessarily having the same number of attachments
The validation done previously was always returning false, now it returns correctly
Add products with assembly, but do not add the same total amount of assembly
- Available prefixes: `feat`, `fix`, `chore`, `docs`, `style`, `refactor` and `test`
=> fix: has child items logic on validate cart (bug)

apps/site/middleware.ts, apps/site/pages/components/molecules/dropdown.mdx, packages/components/src/atoms/Button/index.ts, packages/components/src/molecules/Dropdown/Dropdown.tsx, packages/components/src/molecules/Dropdown/DropdownButton.tsx, packages/components/src/molecules/Dropdown/DropdownItem.tsx, packages/components/src/molecules/Dropdown/DropdownMenu.tsx, packages/components/src/molecules/Dropdown/contexts/DropdownContext.ts, packages/components/src/molecules/Dropdown/hooks/useDropdown.ts, packages/components/src/molecules/Dropdown/hooks/useDropdownItem.ts, packages/components/src/molecules/Dropdown/hooks/useDropdownPosition.ts, packages/components/src/molecules/Dropdown/hooks/useDropdownTrigger.ts
Improve the Dropdown by adding new options and expanding its usability. In this PR, properties like `asChild`, `alignment`, and `dismissOnClick` have been added. There are no breaking changes, but properties related to icons in `DropdownButton` and `DropdownMenuItem` were marked as deprecated, as these functionalities can now be configured directly within the component content.
As part of the refactor of the `DropdownButton` and `DropdownMenuItem` components, new hooks were created that encapsulate logic, enabling new components to be created with a fresh structure while maintaining functionality. The new hooks are `useDropdownItem` and `useDropdownTrigger`.
A new property called `align` has been added to the `DropdownMenu`. This property allows the `DropdownMenu` to align with the …
=> Feat: Improve Dropdown Component

packages/core/src/components/navigation/Navbar/Navbar.tsx, packages/core/src/components/sections/Navbar/DefaultComponents.ts, packages/core/src/components/sections/Navbar/section.module.scss, packages/core/src/components/sections/RegionBar/RegionBar.tsx
- Fix CLS (Cumulative Layout Shift) for `RegionBar` (it was introduced when we change to use `isMobile` hook to render the section, although using the `display-mobile` won't remove the component from the dom, I opted to put it back to avoid the CLS)
|Mobile| Desktop|
|-|-|
- Uses dynamic import to `Navlinks` 
- Uses `useScreenResize` hook on `Navbar` component to avoid components duplication and render depending on the device
- Uses dynamic import for `NavbarSlider` internal components
- Mobile
|Starter | CLS fixes + navbar improvements|
|-|-|
- Desktop
|Starter | CLS fixes + navbar improvements|
|-|-|
|<img width="1008" alt="desk-starter" src="https://github.com/user-attachments/assets/68c8da9d-839e-415b-b4c0-39fd4e423019">|<img width="1011" alt="desk-perf" …
=> Chore: Fix CLS issues and Navbar dynamic imports 

packages/components/src/molecules/QuantitySelector/QuantitySelector.tsx
Resolves the bug that when typing letters in the quantity input a "NaN" error appears
I validated the function to change the input to remove any non-numeric value
Go to the product page and try to enter a value other than a number in the quantity input
https://newswarovskiargentina-cm2bukmqh008u9fpvz46jty9h-rarbnwb8d.b.vtex.app/5662923-conjunto-stilla-tallas-mixtas-multicolor-bano-tono-oro-rosa-11436/p
- Available prefixes: `feat`, `fix`, `chore`, `docs`, `style`, `refactor` and `test`
=> fix: NaN when string is inputed on quantity input

packages/core/src/components/cms/GlobalSections.tsx, packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/common/Toast/Toast.tsx
- Loads `Toast` using dynamic import.
- Imports `Toast` in `RenderSections` instead of `GlobalSections`
**note**: Unlike the [POC](https://github.com/vtex/faststore/pull/2404/files#diff-b45ed72491ecc419d59ca49fa8b4fc7a45deb55758a6a401f3c8401c11114227R113-R120), the Toast component does not use <LazyLoadingSection>. In the PLP, the Toast needs to be imported along with the `QuantitySelector` (within the viewport) to address scenario 2 (refer to item 2 for how to test).
We are aiming to optimize the performance  loading components only when they are needed, rather than at the initial page load.
|starter|preview|
|-|-|
|<img width="500" alt="image" src="https://github.com/user-attachments/assets/5525b2e3-0b5e-418e-bd45-8fd63d28f24b">|<img width="500" alt="image" …
=> Chore: Applies next/dynamic for Toast

packages/core/src/components/navigation/Navbar/Navbar.tsx
Fixes Navbar resizes
|before|after - expected|
|-|-|
=> fix: Revert Navbar isMobile changes

packages/core/src/components/navigation/Navbar/Navbar.tsx, packages/core/src/components/navigation/NavbarLinks/NavbarLinks.tsx, packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx, packages/core/src/components/search/SearchInput/SearchInput.tsx
- Uses dynamic to import `SearchDropdown` and `UISearchInputField`
**note**: I'm not using dynamic import for UISearchInput because the searchRef is used in the [useOnClickOutside](https://github.com/vtex/faststore/blob/5cbeb9bb9b67371aa23b6e5ca51d582629dfb6d3/packages/core/src/sdk/ui/useOnClickOutside.ts#L13). If the component isn’t rendered yet and we click on the screen, the ref isn’t available, which could cause an error. To avoid changing the code and introducing this issue, I've chosen not to use dynamic import here. Any other opinion here?
Test using the [preview](https://sfj-91e9bbc--starter.preview.vtex.app) or running local
-  you should be able to see the magnify glass icon button
- click on it and search for a term
- this should have the same behavior as before (excluding a …
=> Feat: Applies next/dynamic for SearchInput & adjustments

packages/cli/src/utils/generate.ts, packages/core/src/middleware__DISABLED.ts
This task will allow enabling the redirects middleware within **@faststore/core** during the build process based on a flag. 
The idea is to enable this functionality only for projects that have the flag `ENABLE_REDIRECTS_MIDDLEWARE` saved in the env vars and which are hosted by homebrew. In the future, we intend to have control of this feature through webops. 
Next steps: 
- Set this flag in a pipeline env var.
- Implements dynamoDB client (Reference: https://github.com/vtex/faststore/pull/2517)
The key is the name of the file: **middleware__DISABLED.ts**
This middleware is disabled by default. Only stores that are in **homebrew** and want this functionality will be able to enable it via a feature flag. When the flag is active, the CLI at build time will check whether the …
=> Sfs 1755 generate middleware in build time

packages/core/src/components/sections/BannerText/DefaultComponents.ts
This PR is part of the performance initiative and aims to apply next/dynamic to BannerText's internal components.
The pages should render as before, this PR is only to prepare the components for the time that we're gonna render based on the ViewportObserver/LazyLoadingSection.
- https://github.com/vtex-sites/starter.store/pull/608
Preview
https://sfj-fc3bf86--starter.preview.vtex.app/
POC PR
- https://github.com/vtex/faststore/pull/2404
=> feat: next/dynamic in `BannerText` internal components SFS-1518

packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
This PR is part of the performance initiative and aims to apply `next/dynamic` to `CartSidebar` internal components.
The CartSidebar should render as before. You should see the JS from internal components loading on demand. This PR is also to prepare the components for the time that we will render based on the ViewportObserver/LazyLoadingSection.
- https://github.com/vtex-sites/starter.store/pull/609
Preview
- https://sfj-b6dcbf1--starter.preview.vtex.app/
POC PR
- https://github.com/vtex/faststore/pull/2404
=> feat: next/dynamic in `CartSidebar` internal components SFS-1517

packages/core/src/components/cms/global/Components.ts
This PR is part of the performance initiative and aims to split the global sections into its own file.
Let's initially separate the components of each page type into their own files; this will help organize the import of components by page type (in other tasks) and opens up the possibility of only importing customized components based on the page type in the future, instead of all components, as we currently do. 
The idea is to stop using the `GlobalSections` component in the tree of each page, but since we are not doing this for all pages yet, we’ll keep it temporarily. We will only remove the use of this component on the homepage (in another task). Once we’ve done this for all pages, we can remove this component entirely, but we will keep the function `getGlobalSectionsData`. …
=> feat: split the global sections in own file

packages/core/src/components/sections/ProductShelf/DefaultComponents.ts, packages/core/src/components/ui/ProductShelf/ProductShelf.tsx
Depends on 
- https://github.com/vtex/faststore/pull/2558
This PR is part of the performance initiative and aims to apply `next/dynamic` to `ProductShelf` internal components.
The `ProductShelf` should render as before. 
- https://github.com/vtex-sites/starter.store/pull/613
Preview
https://sfj-5f82a4c--starter.preview.vtex.app/
POC PR
- https://github.com/vtex/faststore/pull/2404
=> Feat: next/dynamic `ProductShelf` Section and internal components.

packages/core/src/pages/api/preview.ts
This PR intends to fix the Headless CMS release preview not working due to missing support for `releaseId` query string param.
With these changes, the function will pick each param, check for missing (required or optional) ones and filter undefined keys (`versionId` or `releaseId`).
On Admin, check some account with existing Release and try opening the release preview.
[VTEX Headless CMS API doc](https://developers.vtex.com/docs/api-reference/headless-cms-api#get-/_v/cms/api/-projectId-/-content-type-/-document-id-?endpoint=get-/_v/cms/api/-projectId-/-content-type-/-document-id-)
=> fix: Support `releaseId` query string param for Headless CMS previews

packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx, packages/core/src/components/ThirdPartyScripts/vtex.tsx
Remove vtexaf initialization from Partytown.
=> fix: Update VTEX script initialization and remove unused parameters

packages/cli/src/utils/generate.ts
feat: add preact support for projects with legacy store config  (faststore.config.js)
I created a function that returns new (discovery.config.js) or legacy (faststore.config.js) store config file
Enable preact flag using `faststore.config.js` and `discovery.config.js`. Both should work.
Check the documentation for more details: https://developers.vtex.com/docs/guides/faststore/managing-performance-improving-store-performance-with-preact
=> feat: add preact support for projects with legacy store config

packages/components/src/hooks/index.ts, packages/components/src/hooks/useSKUMatrix.ts, packages/components/src/index.ts, packages/components/src/organisms/SKUMatrix/SKUMatrix.tsx, packages/components/src/organisms/SKUMatrix/SKUMatrixSidebar.tsx, packages/components/src/organisms/SKUMatrix/SKUMatrixTrigger.tsx, packages/components/src/organisms/SKUMatrix/index.ts, packages/components/src/organisms/SKUMatrix/provider/SKUMatrixProvider.tsx, packages/ui/src/components/organisms/SKUMatrix/styles.scss, packages/ui/src/styles/components.scss
Este PR conta com a construção dos componentes do SKUMatrix: `SKUMatrix`,  `SKUMatrixTrigger`,  `SKUMatrixSidebar`
Além dos componentes, também foi desenvolvido um `SKUProvider`, que gerencia todo o estado interno do SKUMatrix. Esse estado inclui abrir e fechar o `SlideOver`, controlar as quantidades de itens a serem adicionados ao carrinho, e retornar a lista de variações dos produtos. Para o correto funcionamento da funcionalidade do `SKUMatrix`, este wrapper precisa estar presente. Para evitar o uso isolado do `SKUMatrixSidebar` ou do `SKUMatrixTrigger`, há uma validação implementada no hook `useSKUMatrix`.
O hook `useSKUMatrix`, que é responsável por fazer o consumo do `SKUMatrixProvider `e retornar todas as propriedades, para que os componentes da cadeia possam fazer uso. A validação …
=> feat: sku matrix ui and components

packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx, packages/core/src/components/search/SearchDropdown/index.ts, packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx, packages/core/src/sdk/analytics/platform/vtex/search.ts, packages/core/src/sdk/analytics/types.ts
This PR intends to add the sending of `search.autocomplete.click` event when searching and clicking on autocompleted terms or suggested products.
When searching and clicking on both autocompleted term or suggested product, a function called `sendAutocompleteClickEvent` will be called and will send the IS event.
Use the search input to search for "app" and if you click on an autocompleted term or a suggested product, a `search.autocomplete.click` event should be sent in the `Network` tab.
vtex-sites/starter.store#623
Check the `Search Click` object in [IS Events API](https://developers.vtex.com/docs/api-reference/intelligent-search-events-api-headless#post-/event).
=> feat: Send `search.autocomplete.click` IS event (SFS-1815)

packages/core/src/pages/_document.tsx
It's allow to identify the storefront version
=> feat: add meta tag for storefront in document head

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/resolvers/skuVariations.ts, packages/api/src/typeDefs/skuVariants.graphql, packages/core/@generated/gql.ts, packages/core/@generated/graphql.ts, packages/core/src/sdk/product/useAllVariantProducts.ts
Este PR conta com a construção da nova query, que será utilizada pelo SKUMatrix e por toda a geração dos novos tipos. 
Criamos um hook chamado `useAllVariantProducts`, responsável por fazer a request e devolver os dados formatados, conforme esperado pelo `SKUMatrixSidebar`. Para consumir esse hook, é necessário passar algumas propriedades, das quais podemos destacar o **_callBack_** e **_enabled_**.
- **callBack**: é uma função que será executada apenas quando a requisição tiver sucesso e retornar todos os dados. Esse método irá retornar os dados totalmente formatados seguindo o formato pré-estabelecido no componente `SKUMatrixSidebar`
- **enabled**: é um booleano (verdadeiro/falso). Ele irá informar para query se o `SKUMatrixSidebar `está aberto ou não. A requisição só será feita se o …
=> feat: sku matrix packages api

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr.yml
Create a workflow with a job to validate PR title. The title should follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification. 
Available types:
```
- fix
- feat
- chore
- docs
- style
- refactor
- test
- ci
```
Change the title of this PR and refresh the page. When I update the title, I need to refresh the page to see the job running again. It looks like a visual issue.
=> ci: create a job to validate the PR  title

packages/components/src/molecules/ProductCard/ProductCardContent.tsx, packages/core/cms/faststore/sections.json, packages/core/src/components/product/ProductCard/ProductCard.tsx, packages/core/src/components/product/ProductGrid/ProductGrid.tsx, packages/core/src/components/ui/ProductGallery/ProductGallery.tsx, packages/core/src/components/ui/ProductGallery/ProductGalleryPage.tsx, packages/ui/src/components/molecules/ProductCard/styles.scss
Enable Ad label indicator in `ProductCard`. 
Since products are duplicated in the Product Gallery, it's important to clearly indicate which products are sponsored. This will help prevent users from finding the duplication confusing. Additionally, we want to provide an easier way to customize the sponsored label. To achieve this, we're adding the label to the ProductCard and enable text customization via the CMS.
|Before|After|
|-|-|
TODO: 
Changing the label via CMS, the default text is `Sponsored`
|Admin|Store|
|-|-|
1. Run the store locally
2. On `discovery.config.js`file, update `showSponsored` setting. 
```
// Platform specific configs for API
api: {
...
showSponsored: true,
}
```
3. Change via CMS, you can use my test account …
=> feat: add ads label product card

packages/core/src/components/product/ProductGrid/ProductGrid.tsx, packages/core/src/components/ui/ProductGallery/ProductGalleryPage.tsx, packages/core/src/sdk/search/Sentinel.tsx
This PR intends to fix the `Sentinel` behavior by turn it a wrapper for the `ProductGrid` component, also preventing the loop of requests happening when the user load more pages (by clicking on the `Load more products` button).
Currently, `Sentinel` is being rendered as a side `<div />` with the `ProductGrid` component, disabling us to control the visibility of viewport elements properly.
*Before*
**(The red line is the `Sentinel`)**
With these changes, the `Sentinel` will wrap the `ProductGrid`, thus having the same height, enabling the use of `threshold` option (see the API options [`here`](https://github.com/thebuilder/react-intersection-observer?tab=readme-ov-file#options)) to trigger the next page (and replace the `page` query parameter) only when necessary.
*After*
Test the …
=> fix: `Sentinel` rendering and wrong PLP's pagination behavior (#2585)

packages/core/cms/faststore/sections.json, packages/core/src/components/sections/ProductDetails/DefaultComponents.ts, packages/core/src/components/sections/ProductDetails/ProductDetails.tsx, packages/core/src/components/sections/ProductDetails/section.module.scss, packages/core/src/components/ui/SKUMatrix/SKUMatrixSidebar.tsx, packages/core/src/sdk/cart/useBuyButton.ts, packages/core/src/typings/overrides.ts
Este PR conta com a implementação do `SKUMatrix` na ProductDetails. 
Dentro do @faststore/core na pasta ui, foi criada uma abstração do `SKUMatrixSidebar`. Toda a lógica de captura dos dados e formatação do mesmo é feita nessa abstração.
Para fazer a requisição dos dados, foi criado uma nova query. Para utiliza-la basta chamar o hook useAllVariantProducts (toda a construção dessa nova query está presente no PR #2504 ). Para consumir esse hook, é necessário passar algumas propriedades, das quais podemos destacar o callBack e enabled.
Dentro dessa abstração do `SKUMatrixSidebar`, deve haver o consumo do contexto do `SKUMatrix`. O contexto que irá controlar todos os estados, como por exemplo, informar ao contexto a lista das variações do produto. Como essa abstração que ficará responsável …
=> feat: sku matrix packages core

packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts
Change the moment in which the page_view event is sent. It was previously being sent only during a page change, so it wasn't sent on the initialization of the page.
Instead of watching the `routeChangeComplete` route event, now it sends the page_view event when the page is loaded.
Check on the starter preview that the store is working as expected.
The real impact of this change will be tested in the next PR, in which the RC events will start to be sent.
https://sfj-59f6820--starter.preview.vtex.app/ ([PR](https://github.com/vtex-sites/starter.store/pull/631))
- [GA page view](https://developers.google.com/analytics/devguides/collection/ga4/views)
- [Jira task](https://vtex-dev.atlassian.net/browse/SFS-1798)
- [Slack thread](https://vtex.slack.com/archives/C03L3CRCDC4/p1733837843137469)
=> fix(sdk): page view event trigger

packages/core/src/components/product/ProductGrid/ProductGrid.tsx
- Check the expected behaviours for `ProductGrid` on mobile
- Update comments for better clarity 
In mobile:
Only two items in the `ProductGrid` is being rendered in the first moment.
Also the first two items' image has `fetchpriority="high"`
After scrolling, the remaining items are rendered as they come into the viewport.
1. Run the project locally
2. Test on a mobile device or resize the screen to match a mobile screen size
3. Navigate to a PLP page (Office category) and verify the behaviour described in the previous section
WIP
[SFS-1862](https://vtex-dev.atlassian.net/browse/SFS-1862)
[SFS-1862]: https://vtex-dev.atlassian.net/browse/SFS-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update comments on ProductGrid for better clarity

packages/ui/package.json
Due https://github.com/vtex/faststore/pull/2588
The build should not fail because of package size limit
=> chore: increases ui package size

packages/core/discovery.config.default.js, packages/core/src/customizations/src/redirects/index.ts, packages/core/src/pages/[...slug].tsx, packages/core/src/sdk/redirects/index.ts
The implementation of the redirects feature in FastStore appears as a strategic solution to facilitate the migration of old stores to our platform. 
The idea of ​​this feature is to run the redirect in the **getStaticProps** function when a certain page is not found. In other words, before rendering a **not found (404)** result to the user, we check if there is a redirect associated with the pathname requested by the user.
Since the pathname is not found (404). The redirect flow follows two steps. First it goes through a customization function called **matcher**. If the matcher cannot resolve the redirects, we validate whether a redirect exists in the **rewriter** database.
- **Matcher**: Optional function that can be implemented via customization. Some pathnames can be resolved via …
=> feat: add new redirects feature

packages/core/src/Layout.tsx, packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts, packages/core/src/sdk/analytics/platform/vtex/index.ts, packages/core/src/sdk/analytics/platform/vtex/rc.ts, packages/core/src/sdk/analytics/platform/vtex/search.ts, packages/core/src/sdk/analytics/types.ts, packages/sdk/src/analytics/events/page_view.ts
Add VTEX RC Events to FastStore.
- HomeView
- CategoryView
- DepartmentView
- InternalSiteSearchView
- ProductView
- OtherView
The events weren't being sent to RC using the arguments expected by RC, so now the new `handleEvent` function does that - depending on the type of the page, it'll send the correct page view event to RC.
Run `yarn dev` on this branch and watch the Network tab for the `v8` request. I'll add some screenshots below to demonstrate:
| Event | Screenshot |
| --- | --- |
| homeView | <img width="1438" alt="homeView" src="https://github.com/user-attachments/assets/36006b36-226f-4742-b166-54b8120d2d07" /> |
| productView | <img width="1435" alt="productView" src="https://github.com/user-attachments/assets/27be74bc-2595-4da1-b72c-f6e5254def10" /> |
| categoryView | <img …
=> feat: handle RC Events 

.github/workflows/pr.yml
Add the `deps` and `deps-dev` scopes to the PR title validation, so it can be used on the dependabot PRs that updates the deps versions.
Adding this new scope [this](https://github.com/vtex/faststore/actions/runs/12278625904/job/34260726276?pr=2589) type of error won't happen on dependabot PRs:
The `deps-dev` scope is for updates on devDependencies.
- https://github.com/vtex/faststore/pull/2580
=> chore: add deps and deps-dev scopes to PR title validation

packages/core/src/components/cms/RenderSections.tsx
This removes the logic that dynamically loads the sections that depend on the `useUI()` hook: `CartSidebar` and `RegionModal`. We decided to try to load them at another moment (//TODO: create a task for it) instead of on click.
Try to load the respective sections `CartSidebar` and `RegionModal` using the [preview link](https://sfj-2714681--starter.preview.vtex.app/).
You can see that both sections are being loaded in the initial loading now. Instead of loading after clicking on the respective buttons that trigger the sections.
- https://github.com/vtex-sites/starter.store/pull/639
- preview https://sfj-2714681--starter.preview.vtex.app/
=> fix: removes `useUI()` dependents sections from `LazyLoadingSection`

packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx
This PR is part of the performance initiative and aims to lazy load `BreadcrumbBase` internal components.
Since the `BreadcrumbBase` component is inside the `components` package, and Next isn't on this package, instead of using the `dynamic` function from `next/dynamic` it uses `lazy` and `Suspense` from React.
The breadcrumb should continue to work as before. The difference should be that the internal components (related to Dropdown) are dynamically imported.
You can test it using the [preview](https://sfj-135f210--starter.preview.vtex.app/) and accessing the [Handmade Cotton Computer](https://sfj-135f210--starter.preview.vtex.app/handmade-cotton-computer-21395412/p) product, which has a long list of breadcrumbs - that way the breadcrumb gets collapsed and the Dropdown components are …
=> feat: Dynamically import `BreadcrumbBase` internal components

packages/core/src/components/templates/SearchPage/SearchWrapper.tsx
This PR intends to fix the infinite scroll behavior when a search's total pages is different from the current state's total pages.
Currently, if the current state's total pages are 3, for example, and a product search returns results with only 1 page the previous total pages will be considered, rendering skeletons and pages wrong.
It will reset the infinite scroll (always to the first page) if after a product search the total pages number is less than the previous total pages number.
Navigate to the `Office` PLP, load more than 2 pages then search for `apple` (in the search input). No skeletons or more than 1 page should be rendered.
https://github.com/vtex-sites/starter.store/pull/644
=> fix: Reset infinite scroll if search's total pages is less than current state's total pages

packages/core/src/sdk/performance/useTTI.ts
- The fs home is not rendering in Safari.
- `requestIdleCallback` is not available in Safari. 
- This PR creates a polyfill for it
=> fix(sdk): safari rendering

packages/cli/src/utils/generate.ts, packages/core/discovery.config.default.js, packages/core/src/experimental/searchServerSideFunctions/getServerSideProps.ts, packages/core/src/experimental/searchServerSideFunctions/getStaticProps.ts, packages/core/src/experimental/searchServerSideFunctions/index.ts, packages/core/src/pages/s.tsx
This POC is an alternative to indexing search pages using [server side rendering](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props). As the search page is dynamic and we need to set the title and description based on the search term, we chose to use server side rendering as it is the most suitable for this type of situation.
**Like SSG,[ Server-Side Rendering](https://nextjs.org/docs/basic-features/pages#server-side-rendering) (SSR) is pre-rendered, which also makes it great for SEO. Instead of being generated at build time, as in SSG, SSR's HTML is generated at request time. This is great for when you have pages that are very dynamic.**
https://nextjs.org/learn-pages-router/seo/rendering-and-ranking/rendering-strategies
We use the …
=> feat: search page with SSR

packages/components/src/organisms/SKUMatrix/SKUMatrixSidebar.tsx, packages/core/src/components/ui/SKUMatrix/SKUMatrixSidebar.tsx, packages/ui/src/components/organisms/SKUMatrix/styles.scss
We should not use next/image dependency in our components package.
note: We agreed that this component does not fit within our components library, we should move it to core.
Adds `ImageComponent` that can use to render the image. Then we can use the next/image in core.
1. run the application locally or use this [preview](https://starter-371nj2xzn-vtex.vercel.app/headphone-default-99988229/p)
2. go to Headphone Default plp -> check if the SkuMatrixSidebar image is rendered as expected using next/image
[WIP]
[SFS-2025](https://vtex-dev.atlassian.net/browse/SFS-2025?atlOrigin=eyJpIjoiYmMxNzE0YzAzZDFmNDNkMDg5ZjY1ZmU5MDZjOTE3MzEiLCJwIjoiaiJ9)
[SFS-2025]: https://vtex-dev.atlassian.net/browse/SFS-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Removes next/image dependency from ui/component SKUMatrixSidebar

packages/core/discovery.config.default.js, packages/core/src/pages/s.tsx
This PR aims to enable the `noindex` prop from NextSeo from the discovery.config value. 
The default value is true as was previously, but the stores can switch to false as needed.
You can switch the value from `discovery.config.js `-> `seo.search.noIndex` and check the value from the meta tag related.
Preview with noindex true
https://storeframework-cm652ufll028lmgv665a6xv0g-8keew9na7.b.vtex.app/s?q=headphone&fuzzy=0&operator=and&facets=fuzzy%2Coperator&sort=score_desc&page=0
Preview with noindex false
https://storeframework-cm652ufll028lmgv665a6xv0g-kqsnuywde.b.vtex.app/s?q=headphone&fuzzy=0&operator=and&facets=fuzzy%2Coperator&sort=score_desc&page=0
- https://github.com/vtex-sites/starter.store/pull/667
| [Preview with noindex true](https://storeframework-cm652ufll028lmgv665a6xv0g-8keew9 …
=> feat: enables search page seo `noIndex` from config

.gitignore, biome.json, package.json, packages/core/package.json, packages/storybook/.storybook/main.js, packages/storybook/.storybook/preview.js, packages/storybook/.storybook/styles.scss, packages/storybook/package.json, packages/storybook/stories/badge.stories.tsx, packages/storybook/stories/button.stories.tsx, packages/storybook/tsconfig.json, yarn.lock
- Create a new storybook package.
- Configure storybook styles.
- Add three samples stories.
=> chore: add storybook initial config

packages/core/discovery.config.default.js, packages/core/src/pages/s.tsx
This PR aims to enable the `nofollow` prop from NextSeo from the
discovery.config value.
The default value is true as was previously, but the stores can switch
to false as needed.
You can switch the value from `discovery.config.js `->
`seo.search.noFollow` and check the value from the meta tag related.
- https://github.com/vtex-sites/starter.store/pull/675
| [nofollow true](https://storeframework-cm652ufll028lmgv665a6xv0g-dgphn5fzx.b.vtex.app/s?q=headphone&fuzzy=0&operator=and&facets=fuzzy%2Coperator&sort=score_desc&page=0) | [nofollow false](https://storeframework-cm652ufll028lmgv665a6xv0g-7mt68ho4g.b.vtex.app/s?q=headphone&fuzzy=0&operator=and&facets=fuzzy%2Coperator&sort=score_desc&page=0) |
| <img width="1274" alt="Screenshot 2025-01-30 at 12 08 55" …
=> feat: enables search seo `noFollow` from config

packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/cms/ViewportObserver.tsx
Enable the store to decide if a new custom section will skip lazy loading. 
It's important because otherwise all sections are inside the `LazyLoadingSection` and `ViewportObserver` for performance purposes, which makes the section structure not show on the first HTML - that being said, sometimes it's important to appear on the first HTML for SEO purposes.
If the section has a property called `skipLazyLoadingSection` set to `true` it'll bypass `LazyLoadingSection`.
I've added a custom section called `Custom H1` in the `playground.store`, this section is composed by a simple h1 that shows the collection name. It's already added to the PLP template on hCMS there, so you can test it through https://sfj-6854f82--playground.preview.vtex.app/just-arrived - a collection page on `playground`.
| | …
=> feat: enable lazy loading skip on custom sections

package.json
The husky is not working properly
In Husky, adding the `prepare` script in your package.json is necessary because it ensures that Husky installs its Git hooks correctly after running npm install or yarn install.
https://typicode.github.io/husky/get-started.html
https://github.com/typicode/husky/issues/1016
- Change a file 
- `git add .`
- `git commit`
You should see the husky working
=> fix: husky config

packages/core/cms/faststore/content-types.json, packages/core/discovery.config.default.js, packages/core/src/pages/index.tsx, packages/core/src/server/cms/index.ts
Adds `name` and `publisher` properties to website schema
Allow adding the following [WebSite](https://schema.org/WebSite) schema proprieties:
- name: website name.
- publisher: the publisher of the creative work. (We are allowing a publisherId `@id` to identifier reference to the publisher. E.g.: #website)
Users can add data either through the headless CMS interface or by editing the `discovery.config.js` file.
> Note: Data from the headless CMS takes precedence over data from `discovery.config.js`.
1. Go to [preview](https://starter-git-test-seo-website-update-vtex.vercel.app/) link, inspect and look for `WebSite`
2. Copy the generated script and paste [here](https://validator.schema.org) to check if is a valid schema:
OR
1. Test in `storeframework` account, go to CMS admin, changes the …
=> chore: Updates `website` structured data

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/ProductRating.ts, packages/api/src/platforms/vtex/clients/commerce/types/ProductReview.ts, packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts, packages/api/src/platforms/vtex/utils/adaptObject.ts, packages/api/src/platforms/vtex/utils/camelToSnakeCase.ts
To add the Reviews & Ratings API integration through commerce client
Adds 3 new calls to the client:
- client.commerce.rating (retrieves rating information for a specific product)
- client.commerce.reviews.list (retrieves all reviews for a specific product)
- client.commerce.reviews.create (creates a new review for a specific product)
Creates a `.ts` file on the root folder of the project and adds the following code:
```typescript
import { getContextFactory, Options } from "./packages/api/src/platforms/vtex";
const apiOptions = {
platform: 'vtex',
account: 'storeframework',
locale: 'en-US',
environment: 'vtexcommercestable',
channel: '{"salesChannel":"1"}',
showSponsored: false,
} as Options
const apiCtx = getContextFactory(apiOptions)
const commerceApiClient = apiCtx({}).clients.commerce …
```
=> feat: increments commerce client

packages/components/src/molecules/Rating/Rating.tsx, packages/ui/src/components/molecules/Rating/styles.scss
This pull request introduces adjustments to the **Rating component** for the new **Reviews & Ratings** section. 
It updates the colors for both the default and actionable versions, using `main-2` for active stars and `neutral-4` for empty stars.
Additionally, it includes the addition of a `disabled` style for the actionable rating.
[Preview](https://starter-git-feat-rating-field-vtex.vercel.app/review-and-ratings-playground)
[JIRA TASK: SFS-2077](https://vtex-dev.atlassian.net/browse/SFS-2077)
[Figma](https://www.figma.com/design/YXU6IX2htN2yg7udpCumZv/Reviews-%26-Ratings?node-id=131-49445&t=97j1KIeA0brteiq8-4)
Default
Actionable
=> feat: adjust rating styles

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/types/ProductReview.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/typeDefs/productReview.graphql, packages/api/src/typeDefs/query.graphql, packages/api/test/schema.test.ts, packages/core/test/server/index.test.ts
To add reviews query resolver on graphQL
It defines a few new types and adds a new query resolver called: `reviews` wich retrieves an array of reviews for a specific product.
For input we have:
- productId (`required`)
- after and first for pagination, (both are `optional`)
- sort (`optional`)
- rating (`optional`)(for filtering)
run the api graphql server locally with the following command:
```bash
yarn dev:server
```
and make a query call
[JIRA TASK: SFS-2094](https://vtex-dev.atlassian.net/browse/SFS-2094)
=> feat: reviews query resolver

packages/components/src/molecules/CheckboxField/CheckboxField.tsx, packages/ui/src/components/molecules/CheckboxField/styles.scss
This pull request adds styles and an error text for the CheckboxField component. Additionally, it adjusts the styles of the CheckboxField label. This new styling will be used in the modal for adding a review to a product in the new Reviews and Ratings section.
I added the `error` and `alignment` props to the `CheckboxField` component. The `alignment` prop is used to vertically align the checkbox, with the default value set to `center`. 
Additionally, the `label` was not previously styled, so I added styles to it based on the Figma to ensure the label is displayed correctly.
[Preview](https://starter-git-chore-add-checkbox-cli-vtex.vercel.app/review-and-ratings-playground)
[JIRA TASK: SFS-2073](https://vtex-dev.atlassian.net/browse/SFS-2073) …
=> feat: add checkbox field error variant

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/errors.ts, packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/resolvers/createProductReview.ts, packages/api/src/platforms/vtex/resolvers/mutation.ts, packages/api/src/platforms/vtex/utils/cookies.ts, packages/api/src/typeDefs/mutation.graphql, packages/api/src/typeDefs/productReview.graphql, packages/api/test/schema.test.ts, packages/core/test/server/index.test.ts
>⚠️ THIS PR DEPENDS ON [PR#2647](https://github.com/vtex/faststore/pull/2647) ⚠️
To add a reviews mutation resolver on graphQL for allowing a new review to be created
It defines a few new types and adds a new mutation resolver called: `createProductReview`
run the api graphql server locally with the following command:
```bash
yarn dev:server
```
and make a query call
[JIRA TASK: SFS-2095](https://vtex-dev.atlassian.net/browse/SFS-2095)
[API Reviews Docs](https://developers.vtex.com/docs/api-reference/reviews-and-ratings-api#post-/reviews-and-ratings/api/review) 
=> feat: reviews mutation resolver

packages/components/src/index.ts, packages/components/src/molecules/Modal/ModalFooter.tsx, packages/components/src/molecules/Modal/index.tsx, packages/ui/src/components/molecules/Modal/styles.scss
This pull request adds the ModalFooter compound component. This component will be used inside the Modal in initially in the Modal to add a new review in the new Reviews and Ratings section.
You need to use `<ModalFooter />` inside the Modal and pass to it action buttons. The ModalFooter is already spacing out the buttons and is wrapping by default. You can pass `direction` prop to it, and it can be `vertical` or `horizontal` and it is `horizontal` by default.
[Preview](https://starter-git-feat-preview-modal-footer-vtex.vercel.app/modal-footer)
[JIRA TASK: SFS-2080](https://vtex-dev.atlassian.net/browse/SFS-2080)
[Figma](https://www.figma.com/design/YXU6IX2htN2yg7udpCumZv/Reviews-%26-Ratings?node-id=131-66913&t=hvdVQfzTmgTLIa32-4)
=> feat: create modal footer compound component

packages/core/cms/faststore/content-types.json, packages/core/discovery.config.default.js, packages/core/src/pages/index.tsx, packages/core/src/server/cms/index.ts
- Adding [Organization](https://developers.google.com/search/docs/appearance/structured-data/organization) structured data in homepage
> Adding organization structured data to your home page can help Google better understand your organization's administrative details and disambiguate your organization in search results.
Allow adding the following [Organization](https://schema.org/Organization) schema proprieties:
- url: the URL of the website of your organization. This helps Google uniquely identify your organization.
- sameAs: The URL of a page on another website with additional information about your organization, if applicable. For example, a URL to your organization's profile page on a social media or review site. You can provide multiple sameAs URLs.
- logo: A logo url that is …
=> feat: Adding organization structured data json

packages/components/src/index.ts, packages/components/src/molecules/Tooltip/Tooltip.tsx, packages/components/src/molecules/Tooltip/index.ts, packages/ui/src/components/molecules/Tooltip/styles.scss, packages/ui/src/styles/components.scss
This pull request adds the Tooltip atom component. This component will be used in the ReviewCard for displaying reviews of a product in the new Reviews and Ratings section.
This PR introduces a new molecule component, `Tooltip`, which allows customization of its behavior and appearance. The component includes default values for some of its props: `placement` is `"top"`, `dismissable` is `false`, and `maxWidth` is `300`. 
When `dismissable` is enabled, the tooltip uses an `IconButton` for the dismiss action.
[Preview](https://starter-git-chore-add-tooltip-cli-vtex.vercel.app/review-and-ratings-playground)
[JIRA TASK: SFS-2070](https://vtex-dev.atlassian.net/browse/SFS-2070)
[Figma](https://www.figma.com/design/YXU6IX2htN2yg7udpCumZv/Reviews-%26-Ratings?node-id=131-64437&t=0rv1XYm6XsgBeDwA-4 …
=> feat: add tooltip component

packages/core/src/components/templates/ProductListingPage/ProductListingPage.tsx, packages/core/src/pages/[slug]/p.tsx
This PR intends to set `item` as full store's page URL (PLP and PDP) for `BreadcrumbList`'s item list elements.
The `collection` and `product` data is built in `@faststore/api`. The `breadcrumList` attribute consists of `item`, `name` and `position`. The `item` is the pathname of that specific page, so it is in the relative path form.
We should use URL's absolute path, so we have to prepend the `storeUrl` (production domain) to a correct structured data.
- Get the [preview URL](https://storeframework-cm652ufll028lmgv665a6xv0g-355x7sm3b.b.vtex.app/), navigate to a PLP or PDP, inspect the page and look for `BreadcrumList`;
- Copy the generated script and perform the Google Rich Test to validate the schema: https://search.google.com/test/rich-results.
PDP
PLP …
=> chore: `BreadcrumbList` using full page URL for PDP and PLP

packages/core/package.json
- Adds yarn version to volta config.
After the changes in core we added the ppm version but we haven't set any version to yarn.
TODO: check faststore cli
- Update the package.json of the starter.store with this codesanbox version
- Attempts to run `yarn build`
- You should be able to build the project without the previous error
=> fix: add yarn to volta config

packages/core/src/server/cms/index.ts
- https://github.com/vtex/faststore/pull/2668
introduces a bug in its last commit. This PR removes the checking for the MissingContentError in getPage
=> fix: removes MissingContentError checks in getPage 

packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx
Fix an issue happening when overriding the `BuyButton` component of the `ProductDetails` section: when the user change tabs it resets the state.
It's related to how React handles with state. In this [doc](https://react.dev/learn/preserving-and-resetting-state) there is more info about it, but the main point here is that React doesn't recommend nesting component functions, so I've removed the nested `AddToCartButton` definition.
I've used the `playground` store because it already has a custom BuyButton, so I added a Counter in this override to test the change.
To test it, click on the "Click here to increment!" and change browser tabs, after coming back to the tab it should've maintained the state (the counter).
In this preview you can see the issue happening: …
=> fix: Product Details' Buy Button excessive state reset

packages/api/src/platforms/vtex/resolvers/product.ts
Fix the breadcrumb list construction. It was including the similar categories, which is not correct.
The main point of this PR is the `findMainTreeIndex` function that finds the index of the main category tree that matches the product's category ID. Having this index is possible to build the correct breadcrumb list, using only the "main" categories, not the similar ones.
Example:
For the `storeframework` account's product `Gorgeous Cotton Car`, I've added the similar category `/Computer & Software/Smartphones/`. In that case, the categories, categoryId and categoriesIds would be:
categories -> `[ '/Office/Furniture | Chairs/', '/Office/', '/Computer & Software/Smartphones/', '/Computer & Software/']`
categoryId -> `'9296'` 
categoriesIds -> `['/9282/9296/', '/9282/', '/9286/9291/', …
=> fix: Do not include similar categories in the breadcrumb list

packages/core/src/components/sections/Breadcrumb/section.module.scss, packages/core/src/components/sections/Navbar/section.module.scss, packages/core/src/styles/global/index.scss, packages/ui/src/components/molecules/Dropdown/styles.scss, packages/ui/src/components/organisms/Navbar/styles.scss
- Fix Breadcrumb section display on pages
When scrolling the page, either the RegionBar or the Breadcrumb was displayed. In addiction, the Breadcrumb section was not appearing on PLP/search pages.
- Fix the Breadcrumb Dropdown Menu style 
|Before - PDP |After - PDP|
|-|-|
|<img width="500" alt="image" src="https://github.com/user-attachments/assets/849956cc-d601-4fa0-8d22-f4241aa18589" />|<img width="500" alt="image" src="https://github.com/user-attachments/assets/60953a1e-2100-4f17-a3a2-c013b9e13882" />|
|Before - Dropdown Menu | After - Dropdown Menu|
|-|-|
|<img width="500" alt="image" src="https://github.com/user-attachments/assets/a3b01428-5ac8-4491-b67a-8e1de23ffc98" />|<img width="500" alt="image" src="https://github.com/user-attachments/assets/5ec9d767-6e8d-4988-a2da-37bc5a7d2390" …
=> fix: Breadcrumb display and it style

packages/core/src/pages/[slug]/p.tsx
This PR intends to fix the `product_search` request being made on PDP when `enableClientOffer` is disabled.
Navigate to PDP and check if no `product_search` request is being made.
=> fix: Get offer url only if `enableClientOffer` is enabled

packages/core/discovery.config.default.js, packages/core/src/sdk/session/index.ts, packages/sdk/src/store/persisted.ts
Add in `discovery.config.js` the config that will be used for the new feature Delivery Promise and update code related to validate session to change the `postalCode` to the default one if it's null or empty.
If the session's `postalCode` is null or empty, it changes to the initial/default one configured in `discovery.config.js` in the `session` object.
In the starter preview's `discovery.config.js` file, I've added `90210` as the default postal code and enabled the deliveryPromise feature. Then if you test the preview you should see this postal code in the IndexedDB of the browser's devtools.
You can also test that it'll be updated to the default postal code if the postal code in the IDB is null or empty previously for some reason (like if you had already accessed the store before this …
=> feat: [Delivery Promise] Default postal code

packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
We accidentally removed this component in the previous version v3.15, so I'm putting it back.
Navigate to Headphone Default product and you should be able to see the `Select multiple` button and open the modal.
PDP
[WIP]
=> fix: Adds back SKUMatrix to PDP

packages/core/src/components/sections/Breadcrumb/Breadcrumb.tsx, packages/core/src/components/sections/Breadcrumb/DefaultComponents.ts, packages/core/src/components/ui/Breadcrumb/Breadcrumb.tsx, packages/core/src/typings/overrides.ts
- We were not using the `Breadcrumb` component from the [core](https://github.com/vtex/faststore/blob/main/packages/core/src/components/ui/Breadcrumb/Breadcrumb.tsx). 
I'm not sure if it was a mistake when handling this component override in the Breadcrumb section or was intentional. But the Home icon/link that we previously is implemented in the breadcrumb core component. So in order to display it, we have to use the component from core.
|before|after|
|-|-|
|<img width="500" alt="before breadcrumb" src="https://github.com/user-attachments/assets/3405b84f-3bed-4ec3-868e-39a8ed7e38db" />|<img width="500" alt="after breadcrumb" src="https://github.com/user-attachments/assets/e66aab8a-4d85-44a6-b658-e3c63632d4ad" />|
- Run core locally or use this preview …
=> fix: override to use core breadcrumb component

packages/components/src/organisms/RatingSummary/RatingSummary.tsx, packages/core/src/components/sections/ReviewsAndRatings/DefaultComponents.ts, packages/core/src/components/sections/ReviewsAndRatings/ReviewsAndRatings.tsx, packages/core/src/components/ui/ReviewsAndRatings/ReviewsAndRatings.tsx, packages/core/src/typings/overrides.ts
This pull request includes some changes to the `RatingSummary` component and its integration within the `ReviewsAndRatings` section, like adding a callback for the create review button, dynamically importing the `RatingSummary` component, and updating the `ReviewsAndRatings` section to use the new properties and overrides.
Enhancements to `RatingSummary` component:
* Added `onCreateReviewClick` callback property to `RatingSummaryProps` to handle create review button clicks. [[1]](diffhunk://#diff-3842b6542c4617b9089bcfe95aae46869139ddb93e8dcd66334f2e63bea0f669R43-R46) [[2]](diffhunk://#diff-3842b6542c4617b9089bcfe95aae46869139ddb93e8dcd66334f2e63bea0f669R96) [[3]](diffhunk://#diff-3842b6542c4617b9089bcfe95aae46869139ddb93e8dcd66334f2e63bea0f669L110-R115)
Integration of `RatingSummary` in …
=> fix: declare RatingSummary in section components

package.json, pnpm-lock.yaml
Updating axios version to `^1.8.2` in order to avoid security vulnerability
Apparently we have a transitive dependency -> lerna -> nx -> axios
**We strongly recommend that our clients update to this version as well.**
Reference:
https://github.com/vtex/faststore/security/dependabot/261
=> chore(deps): bump axios to ^1.8.2 to address security vulnerability

packages/core/discovery.config.default.js, packages/core/src/pages/[slug]/p.tsx
This PR adds SEO specifics (`title` and `description` templates) for PDPs.
The store will be able to define both `title` and `description` templates through the `discovery.config.js` file.
Check if the metatags for` title` and `description` are being built correctly on a PDP, that is with the shape defined at `discovery.config.default.js` file.
vtex-sites/starter.store#724
=> feat: Add SEO specifics for PDP

packages/core/src/pages/s.tsx
This PR intends to fix the behavior when users search for term with whitespaces and those whitespaces are considered as canonical.
It replaces the whitespaces with `+`, the same way the page does for the url.
It will work for stores that enabled the experimental flag:
`experimental: {
...,
enableSearchSSR: true,
},
`.
Search for terms with whitespaces and check the search page's `canonical` if it uses `+` instead.
vtex-sites/starter.store#726
=> fix: Prevent whitespaces in Search page's `canonical`

biome.json
This pull request includes a small change to the `biome.json` file. The change adds the `pnpm-lock.yaml` file to the list of ignored files.
=> fix: add pnpm-lock.yaml to ignored files in biome.json

packages/core/discovery.config.default.js, packages/core/src/components/ui/Image/loader.ts
This pull request introduces a new feature to enable a custom image loader based on a configuration setting. The main changes include adding a new configuration option and implementing two loader functions to handle different image loading strategies.
New feature implementation:
* [`packages/core/discovery.config.default.js`](diffhunk://#diff-4da6f8e98efa58c9a40ce9b654b9bfeecb6813091999cdea3d2408679d1bf3d3R119): Added a new configuration option `enableVtexAssetsLoader` to control the use of the VTEX assets loader.
Image loader enhancements:
* [`packages/core/src/components/ui/Image/loader.ts`](diffhunk://#diff-73ffbd4b30ea7347ce7cc718527810b0f8b51f897bcf48efdd48fbe36652afdaR10-R15): Modified the `customImageLoader` function to use either `fileServerLoader` or `thumborLoader` based on the …
=> feat: add support for VTEX assets loader in image component

packages/ui/src/components/organisms/ProductGallery/styles.scss
In some LH runs, we catch Layout Shift in the PLP (related to the ProductGrid + Load More Button) that can affect +- 20 score points. This PR aims to fix it.
| ![Screenshot 2025-03-12 at 17 55 32](https://github.com/user-attachments/assets/e8b30e08-b2ad-4665-80b0-b56d05833e75)| ![Screenshot 2025-03-12 at 17 55 41](https://github.com/user-attachments/assets/e4c5a8f6-cd4f-459b-8700-01fc70b74598) |
=> fix: PLP layout shift

packages/core/index.ts, packages/core/src/customizations/src/myAccount/navigation.ts, packages/core/src/sdk/account/getMyAccountRoutes.ts
Create a helper to return the my account routes. The default and the customizations routes.  
The My Account Menu Will use this helper to render the menu itens. 
Create a folder called myAccount/navigation.ts. 
Só we can create a new menu item like this: 
```
export default getMyAccountRoutes({
routes: [
{
title: "Shopping List",
route: "account/shopping-list",
},
],
});
```
=> feat: getMyAccountRotes sdk

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/test/mocks/AllProductsQuery.ts, packages/api/test/mocks/ProductQuery.ts, packages/api/test/mocks/RedirectQuery.ts, packages/api/test/mocks/SearchQuery.ts, packages/api/test/mocks/ValidateCartMutation.ts
The cookie information (especially vtex_segment) is relevant for intelligent search, this PR forwards them on the request headers. 
1. Make a search
2. Check the request Headers.Cookie on the Search request
3. You should see several cookies sent
Preview: https://starter-git-test-segment-vtex.vercel.app/
=> fix: pass cookies to intelligent search requests

packages/cli/src/utils/directory.ts, packages/cli/src/utils/plugins.ts
This PR adds support for creating new APIs in Faststore from plugins.
During the development of the Buyer Portal plugin, we identified the need to define API routes within the plugin structure. Since plugins already support creating new pages in Faststore, we extended this capability to allow the creation of API routes as well.
Some use cases for creating new API routes include:
- Adding new integrations with backend services within Faststore
- Defining API routes that can access HTTP-only hooks in the Faststore domain
- Enabling plugins to expose custom business logic via API endpoints
> [!NOTE]
> This pull request does not aim to add the API Override functionality to plugins. Developing this feature would require addressing specific challenges, such as orchestrating GraphQL requests to …
=> feat: Add plugins apis support

packages/components/src/atoms/Skeleton/Skeleton.tsx, packages/core/src/components/sections/ReviewsAndRatings/DefaultComponents.ts, packages/core/src/components/skeletons/RatingSummarySkeleton/RatingSummarySkeleton.tsx, packages/core/src/components/skeletons/RatingSummarySkeleton/index.ts, packages/core/src/components/ui/ReviewsAndRatings/ReviewsAndRatings.tsx, packages/core/src/typings/overrides.ts
This PR adds the `RatingSummarySkeleton` component.  
When `isValidating` from `usePDP` is `true`, the skeleton will be displayed until the data is ready.  
Load a product page and check if the skeleton is shown before being replaced by the `RatingSummary` with the updated product rating data.
[Preview](https://starter-git-feat-rating-summary-skeleton-vtex.vercel.app/)
[JIRA SFS-2321](https://vtex-dev.atlassian.net/browse/SFS-2321)
[FEATURE BRANCH](https://github.com/vtex/faststore/pull/2676)
=> feat: create RatingSummarySkeleton

packages/api/src/platforms/vtex/resolvers/validateSession.ts, packages/core/src/components/region/RegionModal/RegionModal.tsx, packages/core/src/sdk/geolocation/useGeolocation.ts
This PR intends to ensure all location data (`postalCode`, `geoCoordinates` and `country`) is being synchronized when needed.
It updates geo coordinates when users set a postal code and ensure location data won't be overwritten if users grant geo location consent late.
- Enable Delivery Promise on discovery.config;
- Open the localhost store on anon tab (to ensure no stale data);
- First, consent geo location data from popup and look to the IDB `fs::session` value, it should fill `geoCoordinates` data after `useGeolocation` hook execution;
- Then try to set a postal code, the `postalCode` should be set and `geoCoordinates` should be different now (based on the postal code);
- Another test: open another anon tab and, while the popup asking for geo location consent set a postal code. Then, …
=> chore: Ensure session with location data

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/loaders/sku.ts, packages/api/src/platforms/vtex/resolvers/query.ts
This PR intends to manually disable the `hideUnavailableItems` flag for cases that the product is unavailable for certain regions.
it will manually pass `hideUnavailableItems: false` to the `product_search` request to the IS. By doing that and only if the merchant checks the option to show unavailable items on Catalog config (Admin), the PDP will always be accessible, even though the product is not available. So the store will need to handle the unavailable information (unavailable labels, no prices and disable buy button).
Currently we do not have a testing store with regionalization features, but you can validate on Starter store if the pages are working as they should with and without postal code being set.
vtex-sites/starter.store#738
Check the **RFC FastStore PDP regionalization** …
=> feat: Manually disable `hideUnavailableItems` flag for PDP queries

packages/core/src/sdk/redirects/index.ts
Avoid calling the redirect service when the pathname is from an asset.
I create this REGEX to validate the files extentions: 
`const ASSET_FILE_REGEX = /\.(js|css|png|jpg|jpeg|svg|gif|webp|ico|json|map)$/i`
=> fix: call redirect-evaluate only for pages

packages/cli/src/utils/templates/myAccountPage.ts, packages/core/src/components/account/MyAccountLayout/MyAccountLayout.tsx, packages/core/src/components/account/MyAccountLayout/index.ts, packages/core/src/components/account/MyAccountLayout/styles.scss, packages/core/src/components/account/MyAccountMenu/MyAccountMenu.tsx, packages/core/src/components/account/MyAccountMenu/index.ts, packages/core/src/components/account/MyAccountMenu/styles.scss, packages/core/src/components/account/index.ts, packages/core/src/components/account/section.module.scss, packages/core/src/pages/account/profile.tsx, packages/core/src/pages/account/security.tsx, packages/core/src/pages/account/user-details.tsx
To implements My Account menu
Creates an Avatar component to be used on this menu and futurely on other components
Creates a MenuLayout component and a Menu component. 
The MenuLayout uses the Menu component inside and receives the page to be rendered as children
The menu itens and it's related routes comes from `src/customizations/src/myAccount/navigation` 
>[!IMPORTANT]
> The pages are mocks only. The subject of this PR is only the Menu structure
[PREVIEW](https://starter-git-feat-my-account-menu-vtex.vercel.app/account)
[JIRA-SFS-2310](https://vtex-dev.atlassian.net/browse/SFS-2310)
[MyAccount RFC](https://docs.google.com/document/d/17qlQerzx3cva2dupafbEaJhsu_aLLuxFf6IniVIwRBM/edit?tab=t.0#heading=h.tglo77yl0lf5)
=> feat: my account menu

packages/core/src/sdk/redirects/index.ts
Fix the redirect destination. Vercel was throwing an error when the search term had non ascii characters.
Encodes the redirect destination.
You can test using this repo to test locally, but the error isn't being thrown locally.
You can test using the previews, I've created one [**with** the fix](https://github.com/vtex-sites/starter.store/pull/745) and one [**without** the fix](https://github.com/vtex-sites/starter.store/pull/747). Both of them have the `enableRedirects` active and have the same matcher configured.
**Without** the fix: https://starter-h6x15or7b-vtex.vercel.app/busca/tasty-wôoden-bacón
**With** the fix: https://starter-m0b8fpkw8-vtex.vercel.app/busca/tasty-wôoden-bacón
=> fix: Encode redirect destination

packages/core/src/sdk/redirects/index.ts
Validate response status before parsing to json. 
"The ok read-only property of the Response interface contains a Boolean stating whether the response was successful (status in the range 200-299) or not." Reference: https://developer.mozilla.org/en-US/docs/Web/API/Response/ok
Check if the **response.ok** is true before trying to parse.
=> fix: validate response status before parsing to json

packages/core/src/components/ThirdPartyScripts/vtex.tsx
Fix how we inform the account name to rc, so the rc can correctly read the accountName of FastStore stores.
PS: rc will fix the way it reads account info on FastStore stores
|before|now|
|-|-|
|<img width="500" alt="image" src="https://github.com/user-attachments/assets/c7a0deb8-04bf-41a8-b5e5-00986fede176" />|<img width="500" alt="image" src="https://github.com/user-attachments/assets/49e3d413-9773-4ed1-bc52-bf9ab7be47b8" />|
1. Run the store
2. check for v8 events, the accountName should be in the payload.
inc-2496
=> fix: loading rc with accountName 

packages/cli/src/utils/createNextjsPages.ts, packages/core/discovery.config.default.js, packages/core/src/pages/account/index.tsx, packages/core/src/pages/account/profile.tsx
Create a experimental flag to enable faststore my-account
When the user tries to access the /account, he will be redirect to /account/profile if the flag is enabled. 
Go to starter, add a flag `enableFaststoreMyAccount: true` in storeConfig. Try to access `/account` path. You should be redirected to `/account/profile`.
=> feat: flag to enable faststore my account

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/Session.ts, packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/resolvers/validateSession.ts, packages/core/src/server/options.ts
Update the Session with postal code, country, and geo-coordinates. 
The Intelligent Search will use this for the Delivery Promise feature. FastStore updates the session with the location information and IS access it.
The update is a PATCH request to the Session Manager API. The fields that IS will use from the session are `postalCode`, `geoCoordinates` and `country`, inside the `public` namespace.
Run this code (or use the preview link below) and test changing the postal code and/or using a default one.
The fields inside public namespace of the session should be updated accordingly.
To check it you can run this request:
```curl
curl --location 'https://storeframework.vtexcommercestable.com.br/api/sessions?items=public.postalCode,public.geoCoordinates,public.country' \
--header 'Cookie: …
```
=> feat: Update Session with location info

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/test/integration/queries.test.ts, packages/api/test/mocks/AllProductsQuery.ts, packages/api/test/mocks/ProductQuery.ts, packages/api/test/mocks/RedirectQuery.ts, packages/api/test/mocks/SearchQuery.ts, packages/api/test/mocks/ValidateCartMutation.ts, packages/core/discovery.config.default.js, packages/core/src/pages/api/graphql.ts
Add GraphQL cache control configuration and handling using experimental flags.
You should change the experimental flag in `discovery.config` inside the `experimental`.
`maxAge` value different from 0 enables the cache in GET requests.
```js
graphqlCacheControl: {
maxAge: 5 * 60, 
staleWhileRevalidate: 60,
},
```
`maxAge` value 0 disables cache
```js
graphqlCacheControl: {
maxAge: 0, // 0 disables cache
staleWhileRevalidate: 60,
},
```
POST request didn't use cache.
// TODO create docs related with this feature flag. @mariana-caetano
=> feat: add API GraphQL cache control using flags

packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
This PR aims to prevent multiple `view_cart` events from being sent to GA.
It turns the items and gifts array's stringified before passing to the `useCallback` dependency of `sendAnalyticsEvent.` to prevent circular dependencies and send wrong values to GA.
I also tested these arrays with `useMemo` but it didn't work as expected.
You can run it locally by adding gtm_debug=true as a query string and seeing the `dataLayer` object in the console.
Example:
http://localhost:3000/?gtm_debug=true
Before: multiple view_cart being triggered.
After: 1 view_cart event being triggered after each interaction (add to cart, remove to cart).
|<img width="1113" alt="Screenshot 2025-04-08 at 16 04 04" src="https://github.com/user-attachments/assets/171624a3-63ef-4d40-a …
=> fix: multiple view_cart events

packages/components/src/molecules/Modal/Modal.tsx, packages/components/src/organisms/RegionModal/RegionModal.tsx, packages/core/cms/faststore/sections.json, packages/core/discovery.config.default.js, packages/core/src/Layout.tsx, packages/core/src/components/region/RegionModal/RegionModal.tsx, packages/core/src/components/region/RegionModal/useRegionModal.ts, packages/core/src/constants.ts, packages/core/src/sdk/geolocation/useGeolocation.ts, packages/ui/src/components/organisms/RegionModal/styles.scss
This PR implements the scenario where no address is available and the location is set as mandatory on `discovery.config`
**note**: The region modal and the flow implemented in this PR differ from the previous prototype. But I've already aligned with @renatamottam (design team) and she will update the figma file. (The main difference is that we won't be using the `Set Location` button, we agreed to use the `Apply` from the input field)
We also made a fix in the current flow of the default `RegionModal`. 
- It won't automatically close if the added postalCode is invalid and not applied.
Adds `buttonActionText` field in hCMS (the default is `Apply`)
| hCMS | RegionModal|
|-|-|
|<img width="500" alt="image" src="https://github.com/user-attachments/assets/64b8aa01-a5e7-48a0-95fe-4d742d8b2f8d" …
=> feat: Displays region modal if no addresses and location is mandatory

packages/core/src/pages/[slug]/p.tsx
This PR intends to add redirects support for PDPs in the same way we do for PLPs.
See #2583 for further details.
It performs the redirect in the `getStaticProps` function when a certain page is not found and there is a registered redirect for that. Before rendering a `404 Not Found` result to the user, we will check if there is a redirect associated to the pathname requested by the user.
- Use the starter deploy preview;
- Navigate to `.../ergonomic/p` then you should be redirected to `.../ergonomic-granite-mouse-57815628/p`;
vtex-sites/faststoreqa.store#764
=> feat: Add PDP redirects support

packages/core/src/sdk/product/useProductGalleryQuery.ts
This PR aims to send the `intelligent_search_query` only when fuzzy and operator param exist in the URL, preventing the sending 2 events.
it checks the existence of fuzzy and operator in the URL before sending the event.
You can run it locally by adding gtm_debug=true as a query string and seeing the `dataLayer` object in the console while searching products using search page.
Example:
http://localhost:3000/s?q=shirt&facets=fuzzy%2Coperator&sort=score_desc&page=0&gtm_debug=true
Before: 2 events
After: 1 event
|<img width="1566" alt="Screenshot 2025-04-09 at 12 54 52" src="https://github.com/user-attachments/assets/2a4a6fda-86cd-4ee4-9ab2-6e56dc89451b" />|<img width="1893" alt="Screenshot 2025-04-09 at 12 54 37" …
=> feat: only send is query event when url has fuzzy and operator

packages/core/src/pages/api/graphql.ts
properly end response for unsupported HTTP methods in GraphQL API
=> fix: properly end response for unsupported HTTP methods in GraphQL API

packages/core/vtex.env
The right value for this flag should be 1 according to NEXT doc.
https://nextjs.org/telemetry#:~:text=NEXT_TELEMETRY_DISABLED
=> fix: update telemetry configuration to use integer

packages/core/src/pages/account/index.tsx
This PR aims to move the redirect logic from my account to the Server Side.
If the flag enableFaststoreMyAccount: true, you should see the new myAccount page.
If the flag enableFaststoreMyAccount: false, you should be redirected to the new myAccount page (/account/profile).
| Flag enabled | Flag disabled |
|<img width="1266" alt="Screenshot 2025-04-10 at 19 56 18" src="https://github.com/user-attachments/assets/4703f5da-22ff-49f9-b720-f0997f745808" />|<img width="1282" alt="Screenshot 2025-04-10 at 19 49 21" src="https://github.com/user-attachments/assets/daa6c0ca-741c-4fec-96e9-55c161e1d7a4" />| 
Change the value of the flag and access: http://localhost:3000/account
PR
- https://github.com/vtex-sites/faststoreqa.store/pull/765
Preview
flag is disabled …
=> feat:  MyAccount redirects using SSR - SFS-2440

packages/core/src/components/product/ProductGrid/ProductGrid.tsx, packages/core/src/components/ui/ProductGallery/ProductGalleryPage.tsx, packages/core/src/sdk/analytics/hooks/useViewItemListEvent.ts, packages/core/src/sdk/product/ProductSentinel.tsx, packages/core/src/sdk/product/viewItemListQueue.ts, packages/core/src/sdk/search/Sentinel.tsx
**Suggestion: review this PR using the `Hide white space` option.**
This PR aims to send the `view_item_list` event only when the item is in the viewport of `ProductGallery` instead of sending all items even when not in the viewport.
It creates a new `ProductSentinel` component that uses the viewport observer from the 'react-intersection-observer' lib and a debounce to group all new products in the viewport.
We don't need to remove objects from the event or add the product that was already in the viewport, only the new ones.
You can run it locally by adding gtm_debug=true as a query string and seeing the `dataLayer` object in the console while scrolling in the PLP.
Example:
http://localhost:3000/office?gtm_debug=true
Before: All PLP products were sent.
After: as the scroll was being …
=> feat: GA `view_item_list` event only when item is in viewport of `ProductGallery`

packages/core/src/sdk/search/useSuggestions.ts
Fix this kind of error in `ClientSearchSuggestionsQuery` .
`GraphQLError [Object]: Variable "$term" of required type "String!" was not provided.
at getVariables (eval at compileVariableParsing (/var/task/node_modules/graphql-jit/dist/variables.js:103:19), <anonymous>:197:21)
at ClientSearchSuggestionsQuery (/var/task/node_modules/graphql-jit/dist/execution.js:159:31)`
=> fix: term required in `ClientSearchSuggestionsQuery` (useSuggestions)

packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/test/mocks/AllProductsQuery.ts, packages/api/test/mocks/ProductQuery.ts, packages/api/test/mocks/RedirectQuery.ts, packages/api/test/mocks/SearchQuery.ts, packages/api/test/mocks/ValidateCartMutation.ts
Use the `allowRedirect` facet from IS. 
The default value would be `false` so it won't affect the IS products return. 
It'll be `true` for the request we make when checking if there is some redirect configured for that search term on IS (it's configured through Admin).
When there is a `redirect` value in the return of the IS req, the IS doesn't return the list of products, so the `allowRedirect = true` causes an issue for searches inside a carousel, for example. 
I've configured the landing page `/test-lari-lp-redirect` which has a shelf. The shelf uses the `nike` search term. I've also configured the redirect for the term `nike` to go to the `/technology` page.
- Without this PR the `/test-lari-lp-redirect` doesn't display the shelf because the search is empty. …
=> feat: explicitly add allowRedirect to IS req

packages/core/src/pages/api/graphql.ts
This PR aims to add error log, and also `.end()` responses with error status, preventing timeouts.
=> fix: log error and properly end response in GraphQL handler

packages/core/src/experimental/myAccountSeverSideProps.ts, packages/core/src/pages/account/index.tsx, packages/core/src/pages/account/orders/[id].tsx, packages/core/src/pages/account/profile.tsx, packages/core/src/pages/account/security.tsx, packages/core/src/pages/account/user-details.tsx
This PR aims to move the getServerSideProps from each my account page to its own implementation instead of a general one.
This PR also adds `user-details` and `security` pages with own SSR functions.
This should work as before.
The order ID should now come from SSR instead of the client (`useRouter`).
- https://github.com/vtex-sites/faststoreqa.store/pull/772
preview:
https://starter-ceshp4j3i-vtex.vercel.app/account/profile
=> feat: use ssr in my account routes

packages/core/src/experimental/index.ts
Export hooks and context from `usePageProductsQuery` so stores can import them from `@faststore/core/experimental`
- [Jira task](https://vtex-dev.atlassian.net/browse/SO-454)
=> chore: export usePageProductsQuery hooks

packages/storybook/stories/tooltip.stories.tsx, packages/ui/src/components/molecules/Tooltip/styles.scss
Fixes tooltip indicator position (indicator style)
|before|after|
|-|-|
=> fix: Tooltip positions

packages/core/src/experimental/myAccountSeverSideProps.ts, packages/core/src/pages/account/index.tsx, packages/core/src/pages/account/orders/[id].tsx, packages/core/src/pages/account/orders/index.tsx, packages/core/src/pages/account/profile.tsx, packages/core/src/pages/account/security.tsx, packages/core/src/pages/account/user-details.tsx, packages/core/src/utils/myAccountRedirect.tsx
This pull is to centralize and streamline the feature flag check and redirection logic for my account feature.
* Added `getMyAccountRedirect` in `src/utils/myAccountRedirect.tsx`. This function checks if the Faststore My Account feature is enabled and determines the appropriate redirection destination based on the feature flag and query parameters.
* Updated the `getServerSideProps` function in multiple pages (`account/index.tsx`, `account/orders/[id].tsx`, `account/orders/index.tsx`, `account/profile.tsx`, `account/security.tsx`, `account/user-details.tsx`) to use `getMyAccountRedirect` for handling redirection logic. This ensures consistent behavior across all pages.
you can enable or disable the `enableFaststoreMyAccount` flag in discovery.config.js and try to access any my account …
=> feat: feature flag all my account pages

packages/core/src/components/templates/SearchPage/SearchWrapper.tsx, packages/core/src/sdk/product/useProductGalleryQuery.ts
This PR intends to fix the blinking content on Search page when searching for terms.
We check if the query should be refetched and now we render the `EmptySearch` component only for cases we don't have any product data to show.
- Do a search for terms like `ergonomic`, `apple` and `unbranded` and check if the page content does not blink anymore.
vtex-sites/faststoreqa.store#775
=> fix: Search page blink

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/PickupPoints.ts, packages/api/test/unit/platforms/vtex/clients/commerce.test.ts
This PR intends to add the `pickupPoints` route to the Checkout client on `@faststore/api`.
There is two scenarios:
- If `geoCoordinates` param is present, the request is made using its value;
- If no `geoCoordinates`, so `postalCode` and `country` will be used to make the request.
=> feat: List pickup points

packages/components/src/molecules/Modal/Modal.tsx, packages/components/src/molecules/Popover/Popover.tsx, packages/components/src/organisms/RegionModal/RegionModal.tsx, packages/core/src/components/region/RegionPopover/RegionPopover.tsx, packages/ui/src/components/molecules/Popover/styles.scss
1. Sets input focus on `RegionModal`
2. Sets input focus on `RegionPopover`
3. Fix Popover` z-index` priority
1.  When opening the `RegionPopover`, if no zip code set the focus should be on the input field instead of the closing button.
2. When opening the `RegionModal`, the focus should be on the input field instead of the closing button.
3. Popover should be under the `Navbar` head when scrolling.
Run the project locally or use the [preview link ](https://storeframework-cm652ufll028lmgv665a6xv0g-fw7dvhgml.b.vtex.app)
1. If the Popover appears, the initial focus should be on the input field
1.a scroll the page, the popover should appear under the Navbar header.
3. Click to edit zip code, when the `RegionModal` appears, the focus should be on the input field …
=> fix: Region Modal / Region Popover element focus & z-index

packages/api/src/platforms/vtex/resolvers/userOrder.ts
removes the beginning of the friendly name
before
=> chore: removes weird label from friendly name

packages/api/local/server.ts
This PR aims to pass the headers (+cookies) to the FastStore API graphql dev server.
Now, all the headers, including cookies, are passed through the dev server.
`pnpm dev:server` in the FastStore API package.
=> chore: pass headers to playground graphql

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/search/index.ts, packages/api/src/platforms/vtex/clients/search/types/ProductCountResult.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/typeDefs/query.graphql, packages/api/test/integration/schema.test.ts, packages/core/@generated/gql.ts, packages/core/@generated/graphql.ts, packages/core/src/components/region/RegionModal/useSetLocation.ts, packages/core/src/sdk/product/index.ts, packages/core/test/server/index.test.ts
This PR intends to handle the scenario when shoppers are setting postal code and there is no available products for that specific location.
For all Delivery Promises scenarios, when shoppers are setting their postal code an input error should be displayed if there is no available products for that location.
- If there is a testing postal code with no products available you can use it on `RegionModal` or `RegionPopover`;
- Or for local environment you can change the condition at `useSetLocation` hook to mock the `no products` scenario;
vtex-sites/faststoreqa.store#788
=> feat: Check products availability when setting postal code

packages/core/src/sdk/analytics/platform/vtex/search.ts, packages/core/src/utils/getBaseDomain.ts
After an investigation, we noticed that for some scenarios the search cookies are not being sets in the correct domain so it's not accessible in the subdomain as expected.
PS: this won't be an issue when using unification domain.
Some stores uses different url settings and we should cover it to set the cookie in the right domain.
Examples:
const example1 = {
storeUrl: 'https://vtexfaststore.com/',
secureSubdomain: 'https://secure.vtexfaststore.com/',
}
const example2 = {
storeUrl: 'https://www.vtexfaststore.com/',
secureSubdomain: 'https://secure.vtexfaststore.com/',
}
const example3 = {
storeUrl: 'https://www.arte.com.br/',
secureSubdomain: 'https://securee.arte.com.br/',
}
const example4 = {
storeUrl: 'https://www.pepper.com',
secureSubdomain: 'https://secure.www.pepper.com/',
}
const …
=> fix: Sets domain search cookies

packages/api/src/__generated__/schema.ts, packages/core/@generated/graphql.ts, packages/core/cms/faststore/sections.json, packages/core/src/components/region/RegionModal/RegionModal.tsx, packages/core/src/components/region/RegionModal/useRegion.ts, packages/core/src/components/region/RegionPopover/RegionPopover.tsx, packages/ui/src/components/molecules/Popover/styles.scss
This PR intends to apply some code refactor and receive the `no products available` error scenario.
Remember to apply `cms-sync` to a dev workspace to validate the new error message from hCMS.
vtex-sites/faststoreqa.store#791
=> chore: `No products available` label from Headless CMS and code refactor

packages/core/src/sdk/error/MissingContentError/MissingContentError.ts, packages/core/src/sdk/error/MultipleContentError/MultipleContentError.ts
Fix discovery.config import
It was being imported as `discovery.config.default`, but it should get from `discovery.config` otherwise it won't get the store configurations.
=> fix: discovery config import

packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountOrderDetails.tsx, packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountStatusCard/MyAccountStatusCard.tsx, packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountStatusCard/index.ts, packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountStatusCard/styles.scss, packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountStatusCard/useConnectorPositioning.ts, packages/core/src/components/account/orders/MyAccountOrderDetails/section.module.scss
To implements the Status card on Order Details page
creates a new component called `MyAccountStatusCard` that receives the order status as props
The current status the component populates the state machine
[PREVIEW](https://sfj-750696f--faststoreqa.preview.vtex.app/)
[FEATURE BRANCH](https://github.com/vtex/faststore/tree/feat/my-account-release-2)
[FIGMA](https://www.figma.com/design/JppevzwPSV58ud0JDCFE7o/My-Account?node-id=832-50457&t=8JNRc3sBFjsCOPao-0)
[JIRA SFS-2423](https://vtex-dev.atlassian.net/browse/SFS-2423)
=> feat: order details status card

packages/cli/src/commands/build.ts
This PR provides a new flag to the faststore/cli build command where enforces that versions of our packages   `'@faststore/core', '@faststore/components', '@faststore/api', '@faststore/cli'` wouldn't be used with packages over http like the codesandbox pr versions used to test. This flag can be set to false to skip the check.
=> chore: adding flag to the build command that would prevent verification of deps

packages/api/src/platforms/errors.ts, packages/api/src/platforms/vtex/resolvers/query.ts, packages/core/src/components/account/MyAccountLayout/styles.scss, packages/core/src/pages/account/403.tsx, packages/core/src/pages/account/orders/403.tsx, packages/core/src/pages/account/orders/[id].tsx
Add 403 (Forbidden) error page to My Account module to handle unauthorized access attempts.
- If call error is "acesso negado" returns status code 403
- Created 403 error page for MyAccount
1. Open
2. Try to access a protected My Account route without proper authentication
3. Verify that you are redirected to the 403 error page
4. Check that the page:
- Shows a forbidden access message
- Uses the standard My Account layout
- Displays navigation menu correctly
- Maintains consistent styling with other account pages
- https://github.com/vtex-sites/faststoreqa.store/pull/804
- https://sfj-792c1d5--faststoreqa.preview.vtex.app/
- [SFS-2408](https://vtex-dev.atlassian.net/browse/SFS-2408)
[SFS-2408]: https://vtex-dev.atlassian.net/browse/SFS-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> feat: order not found

packages/core/cms/faststore/content-types.json, packages/core/cms/faststore/sections.json, packages/core/src/components/search/Filter/FilterDeliveryOption.tsx, packages/core/src/components/search/Filter/FilterDesktop.tsx, packages/core/src/components/search/Filter/FilterSlider.tsx, packages/core/src/utils/globalSettings.ts
In the PLP filters, the option for delivery method "pickup anywhere" should only be displayed when the store has configured it to be shown. 
It'll be configurable through hCMS and its default is false. We'll recommend to enable it for B2B stores.
You can change the config through the hCMS, it is in the Global Sections > Settings tab:
In the preview you should see the Pickup all filter (remember to set a postal code to see the filters) in the PLP only if the config is **true**.
https://vendemo-cm9sir9v900u7z6llkl62l70j-7cu2o2niz.b.vtex.app/
| Desktop | Mobile |
| ---- | ---- |
| <img width="560" alt="Screenshot 2025-05-19 at 20 57 35" src="https://github.com/user-attachments/assets/0ad25c8d-0ebb-45a6-9d34-ff8e353648eb" /> | <img width="215" alt="Screenshot 2025-05-19 at 20 57 52" …
=> chore: Pickup All config

packages/components/src/hooks/UIProvider.tsx, packages/components/src/hooks/index.ts, packages/components/src/organisms/Filter/FilterSlider.tsx, packages/core/cms/faststore/content-types.json, packages/core/cms/faststore/sections.json, packages/core/src/components/region/RegionSlider/RegionSlider.tsx, packages/core/src/components/region/RegionSlider/index.ts, packages/core/src/components/region/RegionSlider/section.module.scss, packages/core/src/components/search/Filter/FilterDeliveryOption.tsx, packages/core/src/components/search/Filter/FilterDesktop.tsx, packages/core/src/components/search/Filter/FilterSlider.tsx, packages/core/src/utils/globalSettings.ts, packages/ui/src/components/organisms/FilterSlider/styles.scss
Create the Region Slider component to be used for setting and changing the location (postal code).
It's triggered when the shopper clicks on the "Set location" button in the PLP filters and when they click on the postal code link in the PLP filters. The first one is the set location type of this Region Slider, and the second is the change location type.
I've added a new state in the UIProvider and functions to handle its change for the Region Slider.
In the preview, test both the set and change location scenarios:
When no postal code is defined yet, the "Set location" button is displayed in the PLP filters.
When the shopper clicks this button, a slideover is displayed to set the postal code.
| Desktop | Mobile |
| ---- | ---- |
| <img width="1505" alt="Screenshot 2025-05-19 at 13 42 54" …
=> feat: Add Region Slider to set/change location

packages/cli/src/commands/build.ts
This PR intends to prevent errors to happen when checking `@faststore` dependencies on starters.
It throws warnings instead errors to the CLI execution.
=> fix: Prevent `checkDeps` error

packages/cli/src/utils/generate.ts, packages/core/src/pages/_app.tsx, packages/core/src/styles/main.scss
`@layer theme` was not being recognized and was getting overridden. The order of the stylesheet imports was affecting this behavior, so I extracted the imports into a separate file to prevent further issues.
|before|after|
|-|-|
|<img width="895" alt="image" src="https://github.com/user-attachments/assets/ba987dd3-1fcf-4576-8ce2-5a6f0b89a7bc" />|<img width="1795" alt="image" src="https://github.com/user-attachments/assets/56ad5ef7-c0b4-4a43-9233-0dcabfa692b5" />|
- Check this [preview](https://sfj-a2c90e3--faststoreqa.preview.vtex.app), the theme should be applied and override the base styles.
[PR](https://github.com/vtex-sites/faststoreqa.store/pull/814)
=> fix: theme styles import

packages/api/src/platforms/vtex/resolvers/query.ts, packages/api/src/platforms/vtex/resolvers/validateSession.ts, packages/api/src/platforms/vtex/utils/cookies.ts
Show user name when its not a b2b account
Check if isRepresentative is false and get user name from license-manager api
Sigin with a b2c account
=> fix: my account account name b2c

packages/core/src/components/search/Filter/FilterDeliveryMethodFacet.tsx, packages/core/src/components/search/Filter/FilterDesktop.tsx, packages/core/src/components/search/Filter/FilterSlider.tsx
Renames the `FilterDeliveryOption` component to clarify that it relates to delivery methods.
=> chore: Renames to avoid mixing delivery methods with delivery option

packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx, packages/core/src/components/search/SearchInput/SearchInput.tsx, packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
Fix the params when sending events that affects the IS report conversion data.
- When sending `search.autocomplete.click` events, we were using the wrong `text` parameter. We should be sending the searched `term` instead.
1. Search for a term and clicks enter, you'll be redirected to a search page with the list of products (PLP), click on the product.
- type the term `headphone`
- while typing some events `search.autocomplete.query` will be sent, when clicking on enter, `search.query` event should be sent with `text: "headphone"`
- On the PLP page, clicking on the product `Aedle VK-1 L Headphone` should trigger a `search.click` event with `text: "headphone"` (where text should match the searched term)
2. Search for a term and clicks on a suggested product.
- type the term `awesome`, while …
=> fix: Search events params to track conversion

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/clients/commerce/types/Session.ts, packages/api/src/platforms/vtex/resolvers/validateSession.ts
Show user name instead of contract name in side menu
Use `shopper.firstName` from session api in b2b object in `validateSession`
[SFS-2576](https://vtex-dev.atlassian.net/browse/SFS-2576?atlOrigin=eyJpIjoiOGFlMGExZDIyOTYwNDBiYmFiYzdiY2I1NDU5NWRlMzEiLCJwIjoiaiJ9)
[SFS-2575]: https://vtex-dev.atlassian.net/browse/SFS-2575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SFS-2576]: https://vtex-dev.atlassian.net/browse/SFS-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add shopper first name to userName in b2b object in session

packages/core/src/sdk/analytics/platform/vtex/search.ts, packages/core/src/utils/getBaseDomain.ts
- Re-applies changes from https://github.com/vtex/faststore/pull/2811
- Consider unified domain (store / secure) and when no secureDomain
How to test?
- This version is currently being used in https://homebrewqa.fast.store
- Open https://homebrewqa.fast.store in an incognito tab or remove all the cookies in the browser 
- Type anything in the SearchInput
- Check if `vtex-search-session` and `vtex-search-anonymous` cookies are being created with `.homebrewqa.fast.store` domain
=> fix: search cookie domain

packages/cli/src/utils/templates/myAccountPage.ts, packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/region/RegionModal/RegionModal.tsx, packages/core/src/components/region/RegionPopover/RegionPopover.tsx, packages/core/src/components/search/Filter/FilterDesktop.tsx, packages/core/src/components/search/Filter/FilterSlider.tsx, packages/core/src/components/templates/LandingPage/LandingPage.tsx, packages/core/src/components/templates/ProductListingPage/ProductListing.tsx, packages/core/src/components/templates/ProductListingPage/ProductListingPage.tsx, packages/core/src/components/templates/SearchPage/SearchPage.tsx, packages/core/src/components/templates/SearchPage/SearchWrapper.tsx, packages/core/src/pages/404.tsx, packages/core/src/pages/500.tsx, packages/core/src/pages/[...slug].tsx, packages/core/src/pages/[slug]/p.tsx, packages/core/src/pages/account/403.tsx, packages/core/src/pages/account/404.tsx, packages/core/src/pages/account/orders/[id].tsx, packages/core/src/pages/account/orders/index.tsx, packages/core/src/pages/account/profile.tsx, packages/core/src/pages/account/security.tsx, packages/core/src/pages/account/user-details.tsx, packages/core/src/pages/checkout.tsx, packages/core/src/pages/index.tsx, packages/core/src/pages/login.tsx, packages/core/src/pages/s.tsx, packages/core/src/sdk/overrides/PageProvider.tsx, packages/core/src/utils/globalSettings.ts
Make `RegionModal` and `RegionPopover` have access to global settings (hCMS -> Global Sections -> Settings)
The Global Settings was created to remove duplications of messages in hCMS. `RegionModal`, `RegionPopover` and filter componentes have some messages in common that were being duplicated across sections and pages in hCMS.
`FilterDesktop` and `FilterSlider` had already been modified to use global settings in a previous PR, but they were only in the context of PLP and Search pages, which is different from `RegionModal` and `RegionPopover` that are global sections. Therefore, in this current PR was necessary some changes related to page context, which involved adding `PageProvider` to ALL pages (that's why there is a lot of modified files) passing the globalSettings as its context.
The …
=> chore: use global settings in RegionPopover and RegionModal

packages/ui/src/components/molecules/Table/styles.scss
Fix the Shipping Simulation table style that was breaking when the text in a cell was too big.
Fixing the table width and setting an overflow-x of auto fixed the issue.
An example of this was happening in the `vendemo` account. There is a pickup point configured there with a long ID.
| ---- | ---- |
| <img width="320" alt="Screenshot 2025-07-02 at 11 46 19" src="https://github.com/user-attachments/assets/2e5aa477-7ad0-4e36-89b5-bdf1fa435e2e" /> | <img width="326" alt="Screenshot 2025-07-02 at 11 44 56" src="https://github.com/user-attachments/assets/485baa5d-98bb-4483-86dd-d8fea5eb585a" /> |
https://github.com/user-attachments/assets/108bfa35-cc5a-4529-9e36-12aac23fe878
https://github.com/user-attachments/assets/2a3a1faf-644c-4721-b465-534fd372beb6
- Preview: …
=> fix: Shipping Simulation table style

packages/core/package.json, packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/cms/global/Components.ts, packages/core/src/components/common/PreviewTag/PreviewTag.tsx, packages/core/src/components/common/PreviewTag/index.ts, packages/core/src/components/common/PreviewTag/section.module.scss, packages/core/src/pages/[...slug].tsx, packages/core/src/pages/api/preview.ts, packages/core/src/server/content/service.ts, packages/core/src/server/content/types.ts, packages/core/src/server/content/utils.ts, pnpm-lock.yaml
This PR includes changes that allow the user to navigate the store, seeing all the changes made on a CP branch. It allows the user to preview the entire store at a time, instead of only a single page.
Introduces global preview mode for CP branches with consistent draft content navigation.
**Key behaviors:**
- Activating preview on any page enables global preview mode for the entire store
- All navigation shows draft content from the branch where available
- Pages without branch changes show published version
- Navigation from published pages to changed pages automatically loads draft content
**Related changes:**  
- [Minor refactor to the `service.ts` file to improve the code readability](https://github.com/vtex/faststore/pull/2885/files#diff-63a7f8cba93bce2eb5ed6be3a1bcf1fbde76d643b165ae2 …
=> feat: implement CP branch preview support

packages/api/src/platforms/vtex/index.ts, packages/api/src/platforms/vtex/loaders/sku.ts, packages/api/test/integration/mutations.test.ts, packages/api/test/integration/queries.test.ts, packages/api/test/integration/schema.test.ts, packages/core/discovery.config.default.js, packages/core/src/server/options.ts
The intention of this PR is to add the `enableUnavailableItemsOnCart` feature flag to enable merchants to handle scenarios where items become unavailable for some reason (e.g. after changing pickup point) on the client-side.
It adds the feature flag to be read from `discovery.config` API flags, but with default value set to `false`.
- Check if all `@faststore/api` tests are passing;
- Perform cart actions (add/remove items) and it should behave as before, nothing should change with `enableUnavailableItemsOnCart: false`;
- The `enableUnavailableItemsOnCart: true` scenario will not work for FastStore for now because our default behavior is to let the backend handle unavailable itens on cart.
vtex-sites/faststoreqa.store#837
=> feat: Allow unavailable items on cart

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/platforms/vtex/resolvers/mutation.ts, packages/api/src/platforms/vtex/resolvers/setPassword.ts, packages/api/src/platforms/vtex/utils/buildFormData.ts, packages/api/src/typeDefs/mutation.graphql, packages/api/src/typeDefs/password.graphql, packages/api/test/integration/schema.test.ts, packages/core/@generated/graphql.ts, packages/core/test/server/index.test.ts
This pull request introduces a new feature to enable users to set or update their passwords, along with the necessary GraphQL schema updates, resolver implementation, and utility functions. The changes span multiple files and include updates to the API, client, and test layers.
* Implemented the `setPassword` resolver to handle password update requests, validate inputs, and call the corresponding client method.
* Registered the `setPassword` resolver in the `Mutation` object.
* Added a `setPassword` method to the `VtexCommerce` client for making API requests to update user passwords.
* Created a utility function `buildFormData` to construct form data from key-value pairs, used in the `setPassword` client method.
**PR Title and …
=> feat: add mutation to set new password

packages/core/src/components/search/Filter/FilterDesktop.tsx, packages/core/src/components/search/Filter/FilterSlider.tsx, packages/core/src/sdk/deliveryPromise/index.ts, packages/core/src/sdk/deliveryPromise/useDeliveryPromise.ts
With these changes the `pickup-all` facet will be displayed only when there are pickup points available.
- Enable `Pickup All` in the Global Sections on Headless CMS;
- Set a postal code without pickup points, `55014-740`;
- The `pickup-all` facet should not be displayed on PLP.
https://vendemo-cm9sir9v900u7z6llkl62l70j-icpdr5ohx.b.vtex.app/
=> fix: Prevent displaying `pickup-all` facet when there are no pickup points

packages/core/index.ts, packages/core/src/experimental/index.ts
With these changes, Delivery Promise 1.2 stable and experimental features will be available from `@faststore/core` and `@faststore/core/experimental` import.
=> chore: Export Delivery Promise features

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/types/PickupPoints.ts, packages/api/src/typeDefs/pickupPoints.graphql, packages/core/@generated/gql.ts, packages/core/@generated/graphql.ts, packages/core/src/components/ui/PickupPoints/PickupPointCard.tsx, packages/core/src/sdk/deliveryPromise/queries.ts, packages/core/src/sdk/deliveryPromise/useDeliveryPromise.ts
When we changed the API (from Checkout to Logistics) we removed the info related to the address state of the pickup points, because Logistics wasn't returning this info. But in the latest deploy they added this info so we can add it back!
Just adding state back 
Check that the state appears in the Pickup Point Card in the list:
PR:
Preview:
[Jira task](https://vtex-dev.atlassian.net/browse/SFS-2678)
=> chore: add Pickup Point's address state back

packages/core/cms/faststore/sections.json, packages/core/src/components/cms/RenderSections.tsx
This PR intends to remove `RegionSlider` section props as we won't use it.
=> fix: Remove `RegionSlider` section props

packages/core/src/components/cms/RenderSections.tsx, packages/core/src/components/cms/global/Components.ts, packages/core/src/components/cms/home/Components.ts, packages/core/src/components/cms/plp/Components.ts, packages/core/src/components/cms/search/Components.ts, packages/core/src/components/region/RegionModal/RegionModal.tsx, packages/core/src/components/region/RegionPopover/RegionPopover.tsx, packages/core/src/components/region/RegionSlider/RegionSlider.tsx, packages/core/src/components/sections/Alert/Alert.tsx, packages/core/src/components/sections/BannerNewsletter/BannerNewsletter.tsx, packages/core/src/components/sections/BannerText/BannerText.tsx, packages/core/src/components/sections/Breadcrumb/Breadcrumb.tsx, packages/core/src/components/sections/CrossSellingShelf/CrossSellingShelf.tsx, packages/core/src/components/sections/EmptyState/EmptyState.tsx, packages/core/src/components/sections/Footer/Footer.tsx, packages/core/src/components/sections/Hero/Hero.tsx, packages/core/src/components/sections/Incentives/Incentives.tsx, packages/core/src/components/sections/Navbar/Navbar.tsx, packages/core/src/components/sections/Newsletter/Newsletter.tsx, packages/core/src/components/sections/ProductDetails/ProductDetails.tsx, packages/core/src/components/sections/ProductGallery/ProductGallery.tsx, packages/core/src/components/sections/ProductShelf/ProductShelf.tsx, packages/core/src/components/sections/ProductTiles/ProductTiles.tsx, packages/core/src/components/sections/RegionBar/RegionBar.tsx, packages/core/src/components/templates/LandingPage/LandingPage.tsx, packages/core/src/pages/404.tsx, packages/core/src/pages/500.tsx, packages/core/src/pages/[slug]/p.tsx, packages/core/src/pages/login.tsx, packages/core/src/utils/cms.ts
This PR makes it so FastStore Core is capable of rendering components based on data from the CMS, using `$componentKey`s to identity each component. It also adds the `$componentKey`s to each component, based on their new schemas (for Content Platform) added in [this PR](https://github.com/vtex/faststore/pull/2742).
The implementation here is backwards compatible, so during the existing rendering flow a new check was added to look for the `$componentKey` property in a section's data. Also, for each component that renders a section, the `$componentKey` property was added, then, when indexing all available components, the new property will now be used if its present. To keep backwards compatibility, the `$componentKey`s are matching the names of the components.
Since this change should be …
=> feat: [CP-407] Add support for rendering components based on their $componentKey

packages/core/src/pages/[slug]/p.tsx
Instead of using the product name and product long description, we could use the SEO customized information that is filled in the Admin (if available)
We did this change to prioritize the SEO fields from IS before #2701
```
title: isVariantOf.productTitle || isVariantOf.productName,
description: isVariantOf.metaTagDescription || isVariantOf.description,
```
You should see the `productTitle`  and `metaTagDescription` if they exist instead of the description and productName in PDP SEO data.
|before|after|
|-|-|
note: `productTitle` and `metaTagDescription` is not being returned from IS from all accounts.
TBD
[slack ticket](https://vtex.slack.com/archives/C051B6LL91U/p1752072991619379)
=> fix: Using SEO product name and description input if available

packages/components/src/organisms/SKUMatrix/SKUMatrixSidebar.tsx, packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx, packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx, packages/core/src/components/sections/Navbar/Navbar.tsx
With these changes, all Quick Order props should be optional.
=> fix: Quick Order typings

packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/MyAccountFilterSlider.tsx
When the filter drawer is open and submit without expanding date facet, it doesnt have ref track to get the values.
Use ? operator to only get if it does have value.
Open the search filter and try do submit without opening the date accordion.
=> fix: use ? operator to get  dateRangeFacet

packages/sdk/src/store/optimistic.ts
This PR fixes the validation cart and session mutations behavior after some errors, such as internet connection issues.
Before:
https://vtex.slack.com/archives/C051B6LL91U/p1755264051698289?thread_ts=1755264007.074619&cid=C051B6LL91U
After:
https://vtex.slack.com/archives/C051B6LL91U/p1755807381785019?thread_ts=1755264007.074619&cid=C051B6LL91U
`validateCart` depends on the session in its request.
`validateSession` sometimes becomes `undefined` when there is an error, such as internet connection issues.
That way, the mutation becomes desynchronized and stops working.
Also, looks like when an error exists in the `queue.then(handler)`, the `store.subscribe` method breaks, making the validateCart stop running. Just including a catch makes it work as expected.
You can test locally, simulating …
=> fix: validate mutations after offline network

packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/core/src/pages/index.tsx
Uses AppKey and AppToken in the Masterdata Shopper entity API.
It also improves shopper search to include userId normalized (without hiphens) and normal.
Follow [this doc](https://docs.google.com/document/d/1cGxnlFxtO4bzZL0PBBOyjd4F6v8cRzKmn2K-KWDhDPY/edit?tab=t.0) to create roles + app key/token + secrets.
You can just enter the order details page and check if you can see the page normally.
reach out to me :) 
Doc: https://docs.google.com/document/d/1cGxnlFxtO4bzZL0PBBOyjd4F6v8cRzKmn2K-KWDhDPY/edit?tab=t.0
=> feat: Add appkey and apptoken to VtexCommerce and Page components

packages/api/src/__generated__/schema.ts, packages/api/src/platforms/vtex/clients/commerce/index.ts, packages/api/src/typeDefs/query.graphql, packages/core/@generated/graphql.ts, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/MyAccountFilterFacetPendingApproval/MyAccountFilterFacetPendingApproval.tsx, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/MyAccountFilterFacetPendingApproval/index.ts, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/MyAccountFilterFacetPendingApproval/styles.scss, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/MyAccountFilterSlider.tsx, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/section.module.scss, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrders.tsx, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountSelectedTags/MyAccountSelectedTags.tsx, packages/core/src/pages/account/orders/index.tsx, packages/core/src/sdk/search/useMyAccountFilter.ts
Adds a new "Pending Approval" filter to the MyAccount orders page, allowing users to quickly filter orders that require their approval.
- New toggle filter: Added "Pending Approval" as the first filter option in the orders filter slider
- Toggle switch: Users can turn on/off the filter to show only pending approval orders
- URL integration: Filter state is reflected in the URL (?pendingApproval=true)
- Selected tag: When active, shows "Pending my approval" tag below the search bar
- Go to /account/orders
- Open filter slider and verify "Pending Approval" is the first option
- Toggle the switch and click "Apply"
- Check URL - should include ?pendingApproval=true
- Verify tag appears - "Pending my approval" tag should show below search bar
- Test removal - click "×" on tag or "Clear All" to …
=> feat: add filter and selected tag for pending approval

packages/cli/src/commands/cms-sync.ts, packages/cli/src/utils/hcms.ts
Fix default project name on CMS sync.
Uses the default 'faststore' project name whenever reading the `contentSource.project` from the config file.
Use the version on this PR and run cms-sync locally.
=> fix: CMS Sync with default contentSource.project

packages/api/src/platforms/vtex/resolvers/product.ts
As the title says, change `gtin` to use `ean` when it exists, so in the product structured data this will be the value used.
Use `ean` when it's not an empty string, otherwise continue as it was.
I've added a value (`123`) to EAN in the account `storeframework` for the SKU 9009169.
So in the preview is possible to see that the gtin value in the product structured data will match this value I've added.
https://github.com/vtex-sites/faststoreqa.store/pull/867
- Before the change: https://storeframework-cm652ufll028lmgv665a6xv0g-111qh27dk.b.vtex.app/
- After the change: https://storeframework-cm652ufll028lmgv665a6xv0g-o0o8ntomd.b.vtex.app/
- [Jira task](https://vtex-dev.atlassian.net/browse/SO-518)
=> chore: Change gtin to use ean when it exists

packages/api/src/platforms/vtex/resolvers/validateSession.ts
This PR aims to remove the facets from the search params sent to `validateSession`.
[reference](https://vtex.slack.com/archives/C069MDTR51Q/p1756378519479289)
=> fix: remove facets parameter from validate session

packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrders.tsx, packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/MyAccountListOrdersTable.tsx
With these changes, we are hiding the `Placed by` column from Orders list and filters for now until we have a cost-effective way to get the shopper name from API.
- Check the orders list and its filters, they should not display any info or perform any actions related to the purchaser.
=> fix: Hide `Placed by` column from orders list and filters
