vtex/faststore

- packages/gatsby-theme-vtex/src/components/BuyButton.tsx
- packages/gatsby-theme-vtex/src/sdk/buyButton/useBuyButton.ts
This PR adds buy button hook so implementers can easily create buy button layouts
PRs:
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/92)
[faststore](https://github.com/vtex-sites/storecomponents.store/pull/286)
> Buy Button

- packages/gatsby-plugin-graphql/src/manager.ts
Shadowing graphql queries was not working properly. This PR fixes this issue by allowing query overwrites
> Fixes graphql

- lerna.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-source-vtex/src/utils.ts
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/HomePage/__generated__/SiteMetadataQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/ProductPage/__generated__/AsyncProductQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/ProductSpecification/__generated__/ProductSpecificationQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/Search/List/__generated__/SearchQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/SearchSuggestions/Autocomplete/__generated__/AutocompleteSuggestionsQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/SearchSuggestions/Products/__generated__/ProductsSuggestionsQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/SearchSuggestions/TopSearches/__generated__/TopSearchesSuggestionsQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/Shelf/__generated__/ShelfQuery.graphql.ts
- packages/gatsby-theme-vtex/src/sdk/localization/__generated__/DefaultCurrencyQuery.graphql.ts
- packages/gatsby-theme-vtex/src/templates/__generated__/ProductPageQuery.graphql.ts
- packages/gatsby-theme-vtex/src/templates/__generated__/SearchPageQuery.graphql.ts
In this PR we add subcategories in the department query.
[See in the Marin Brasil store how we use that.](https://deploy-preview-75--marinbrasil.netlify.app/)
> SubCategories in Departament query

- lerna.json
- packages/gatsby-theme-vtex/i18n/messages/en.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/Search/Controls/FiltersButton.tsx
- packages/gatsby-theme-vtex/src/components/Search/Controls/SortSelect.tsx
- packages/gatsby-theme-vtex/src/components/Search/Controls/index.tsx
- packages/gatsby-theme-vtex/src/components/__generated__/FooterQuery.graphql.ts
- packages/store-ui/package.json
- packages/store-ui/src/SearchControls/Select.tsx
This PR adds i18n for the serach page
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/110)
[faststore](https://github.com/vtex-sites/storecomponents.store/pull/303)
> i18n for Search Page

- packages/gatsby-theme-vtex/src/components/Minicart/Drawer/Footer.tsx
Our infra requires the extra / in the end
> Make it work in our infra

- lerna.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/gatsby-node.ts
This PR uses vtexcommercestable as proxy for vtex checkout and order placed. This way we have an already working site
> Use checkout order placed

- packages/gatsby-theme-vtex/src/sdk/mask/declarations.d.ts
No need to release new version.
> [chore] Adding declaration file

- pull_request_template.md
We believe that documentation is essential for an educated decision flow — for internal and external developers. This is an invite to share the whys and make everybody an owner of the motivation and possibilities.
Today our technical writing team needs to investigate the technologies we use to create features, components, protocols, and etc. It takes time and VTEX's TW team is small by now.
We are also nearby the Fast Store open beta reality and we need to provide independence for our partner's developers to work with the new workflow.
It's a template with tips about what to write in each section. The main goal is to make us all go beyond the descriptions and start to explain more.
Use it and send feedback to @VictoriaMolgado (@molgado on Slack).
- Does it fit in your daily work?
- What …
> documentation-template

- packages/gatsby-plugin-vtex-nginx/src/nginx-generator.ts
Deploy preview using a beta of this PR: https://vtex-sites-marinbrasil-store-125.vtex.app/
> Support regex captures in redirects

- lerna.json
- packages/store-ui/package.json
- packages/store-ui/src/FloatingActionButton/index.tsx
- packages/store-ui/src/FloatingActionButton/theme.ts
Floating Action Button was actually a link. This PR solves this issue by turning it into a button.
> Floating Action Button as Button

- packages/gatsby-theme-vtex/src/components/ProductPage/SEO/useStructuredProduct.ts
Sometimes, product queries can result in no sellers being queried. This makes the page to break. This PR solves this problem by not producing any rich results when no seller is available, thus not breaking the page
> Expect null Sellers

- lerna.json
- package.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/sdk/buyButton/useBuyButton.ts
- packages/gatsby-theme-vtex/src/sdk/orderForm/Provider.tsx
- yarn.lock
This PR adds a loading state to buy button so we can add a visual feedback to the user when the user is adding an item to cart.
The useBuyButton hook now returns a new property called "loading". This property is true when the buy button is clicked, and returns to false when the addToCart request is processed by the order form queue
To test, take a look at our store's implementation
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/338)
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/143)
> Buy Button loading state

- packages/gatsby-theme-vtex/src/components/Error/Error.tsx
- packages/gatsby-theme-vtex/src/components/Error/ErrorBoundary.tsx
- packages/gatsby-theme-vtex/src/components/Error/ErrorHandler.tsx
- packages/gatsby-theme-vtex/src/templates/product.tsx
- packages/gatsby-theme-vtex/src/templates/search.tsx
Add error handling to our Product and Search pages
New components:
- DefaultErrorHandler
- Error (should be shadowed by the store)
> Dealing with errors

- packages/gatsby-theme-vtex/src/components/ShippingSimulator/hooks/__generated__/ShippingQuery.graphql.ts
- packages/gatsby-theme-vtex/src/sdk/newsletter/useNewsletter.ts
- packages/gatsby-theme-vtex/src/sdk/shelf/__generated__/ProductRecommendationsQuery.graphql.ts
[PR Marin](https://github.com/vtex-sites/marinbrasil.store/pull/148)
[DP Marin](https://preview-148--marinbrasil.vtex.app/)
> Adding useNewsletter hook

- lerna.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-plugin-vtex-nginx/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-transformer-vtex-cms/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- packages/store-ui/src/ProductQuantity/NumericStepper.tsx
- packages/store-ui/src/ProductQuantity/Title.tsx
In this PR we fix the need for the label in Product Quantity.
https://github.com/vtex-sites/marinbrasil.store/pull/168
> Fix Product Quantity Label

- packages/gatsby-plugin-theme-ui/src/typings/@theme-ui/css.d.ts
> Add missing file

- lerna.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/Error/Error.tsx
- packages/gatsby-theme-vtex/src/components/Error/ErrorHandler.tsx
- packages/gatsby-theme-vtex/src/components/Layout.tsx
- packages/gatsby-theme-vtex/src/components/__generated__/FooterQuery.graphql.ts
- packages/gatsby-theme-vtex/src/gatsby-browser.tsx
- packages/gatsby-theme-vtex/src/pages/404.tsx
- packages/gatsby-theme-vtex/src/pages/account.tsx
- packages/gatsby-theme-vtex/src/pages/index.tsx
- packages/gatsby-theme-vtex/src/pages/login.tsx
- packages/gatsby-theme-vtex/src/pages/preview.tsx
- packages/gatsby-theme-vtex/src/templates/product.tsx
- packages/gatsby-theme-vtex/src/templates/search.tsx
This PR adds error boundary to all pages. Also, this PR adds the layout to the error handler
> Adds error boundary

- lerna.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/SearchBar/Input.tsx
https://github.com/vtex-sites/marinbrasil.store/pull/187
> Closing the Suggestions popover whenever the page changes

- lerna.json
- packages/gatsby-theme-vtex/package.json
- packages/store-ui/package.json
- packages/store-ui/src/ProductQuantity/NumericStepper.tsx
- packages/store-ui/src/ProductQuantity/useNumericStepper.ts
Makes numeric stepper to work with keyboard input
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/201)
> Fix numeric stepper

- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/SearchSuggestions/Products/__generated__/ProductsSuggestionsQuery.graphql.ts
- packages/gatsby-theme-vtex/src/components/SearchSuggestions/Products/hooks.ts
Not using product origin VTEX makes some inconsistencies happen on search. This PR fixes these problems because it uses product origin vtex in all searches
> Product origin VTEX in search dropdown

- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/gatsby-node.ts
Uses VTEX sitemap as this store's sitemap
> Add proxy headers to sitemap

- package.json
- packages/gatsby-theme-vtex/src/pages/index.tsx
- packages/gatsby-theme-vtex/src/templates/product.tsx
- packages/gatsby-theme-vtex/src/templates/search.tsx
- packages/gatsby-theme-vtex/typings/index.d.ts
- yarn.lock
> Fixes SEO components for Rich Results

- lerna.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-plugin-vtex-nginx/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-instore/src/typings/index.d.ts
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/Minicart/index.tsx
- packages/gatsby-theme-vtex/src/gatsby-browser.tsx
- packages/gatsby-theme-vtex/src/sdk/buyButton/useBuyButton.ts
- packages/gatsby-theme-vtex/src/sdk/minicart/index.tsx
- packages/gatsby-theme-vtex/src/sdk/minicart/useMinicart.ts
- packages/gatsby-transformer-vtex-cms/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- yarn.lock
We transferred the minicart status control to a provider and added a new attribute in the `userBuyButton` hook to open the minicart when true.
Context
https://github.com/vtex-sites/marinbrasil.store/pull/212
> Open Minicart when click on the Buy Button

- lerna.json
- packages/gatsby-theme-vtex/package.json
- packages/store-ui/package.json
- packages/store-ui/src/ProductQuantity/NumericStepper.tsx
Prevents double click on input selector
> Prevent double click

- lerna.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/Minicart/Drawer/Content.tsx
- packages/gatsby-theme-vtex/src/components/Minicart/Drawer/index.tsx
- packages/store-ui/package.json
- packages/store-ui/src/Minicart/theme.ts
> Increase minicart image quality

- packages/store-ui/src/createTheme.ts
- packages/store-ui/src/theme.ts
Reverts vtex/faststore#399
Something is not right with the changed types
> Revert "Fix createTheme typings"

- lerna.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-plugin-vtex-nginx/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/components/Minicart/Drawer/Content.tsx
- packages/gatsby-theme-vtex/src/components/Minicart/Drawer/Image.tsx
- packages/gatsby-transformer-vtex-cms/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
Change the size of minicart image
I created a component to image on the minicart
open the minicart
> Minicart Image

- packages/store-ui/package.json
- yarn.lock
> Upgrade Reakit

- docs/architecture.md
This PR declares the future architecture I think this repo should follow. In this proposition, I create different packages than the ones that current exists and I try to explain a little bit their responsibility and what they contain.
I hope that you, dear reviewer, comment on each missing aspect of this, always evolving, future.
> Add packages architecture future

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-vtex/package.json
- packages/gatsby-theme-vtex/src/gatsby-browser.tsx
- packages/gatsby-theme-vtex/src/typings/intersection-observer.d.ts
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- yarn.lock
Fix the IntersectionObserver error
Verify IntersectionObserver exists natively or using the polyfill
Access Marin Brasil in an iPhone with safari.
> IntersectionObserver polyfill

- docs/architecture.md
Fix url of the store UI pattern doc
> Store UI Pattern url

- lerna.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/Auth/Providers/EmailAndPassword/SignUpForm.tsx
- packages/gatsby-theme-store/src/sdk/auth/useOnLoginSuccessful.ts
- packages/gatsby-theme-store/src/sdk/session/useSession.ts
As correctly stated by @klzns , we need to add "for" in labels.
> Add htmlFor in labels

- lerna.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/Auth/Providers/EmailAndPassword/EmailForm.tsx
- packages/gatsby-theme-store/src/components/Auth/Providers/EmailAndPassword/SignInForm.tsx
- packages/gatsby-theme-store/src/components/Auth/Providers/EmailAndPassword/SignUpForm.tsx
- packages/gatsby-theme-store/src/components/Auth/Providers/EmailVerification/AccessCodeForm.tsx
- packages/gatsby-theme-store/src/components/Auth/Providers/EmailVerification/EmailForm.tsx
- packages/gatsby-theme-store/src/sdk/auth/Service/validateAccessKey.ts
- packages/gatsby-theme-store/src/sdk/auth/Service/validatePassword.ts
- packages/gatsby-theme-store/src/sdk/auth/useOnLoginSuccessful.ts
- packages/gatsby-theme-store/src/sdk/session/useSession.ts
This PR fixes more issues with the login API.
Basically, what solved was to re-create the session after the login was sucessfull. Also, I have added a few more checks to know if the login was successful or not.
> Fixes auth service

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/ShippingSimulator/hooks/useShippingSimulator.ts
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
https://github.com/vtex-sites/marinbrasil.store/pull/247
> Reverting lint fix on useShippingSimulator that caused a loop

- README.md
- Adds the `gatsby-theme-store` package.
- Creates a description for each package.
Preview [here](https://github.com/vtex/faststore/blob/931bc4d15d0a086d68e6fea89417fb809b5d1feb/README.md)
> Updates README's Packages section

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-cms/src/gatsby-node.ts
> [CMS] change contentTypes.json format

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/lighthouse-config/src/index.ts
- packages/store-ui/package.json
Use the PSI config in our lhci
looking at lhci in pull requests from stores
looking at lhci in pull requests in https://github.com/vtex-sites/marinbrasil.store/pull/270
https://github.com/GoogleChrome/lighthouse
https://github.com/GoogleChrome/lighthouse-ci
https://developers.google.com/speed/docs/insights/v5/about
> Lighthouse CI as Page Speed Insight

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-cms/src/gatsby-node.ts
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
> Fix CMS type name

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-cms/src/gatsby-node.ts
- packages/gatsby-source-vtex/package.json
- packages/gatsby-source-vtex/src/gatsby-node.ts
- yarn.lock
We don't need tokens for the CMS API anymore
> Remove auth from cms

- lerna.json
- packages/gatsby-theme-store/package.json
- packages/store-ui/package.json
- packages/store-ui/src/Breadcrumb/index.stories.tsx
- packages/store-ui/src/InfoCard/Image.tsx
- packages/store-ui/src/InfoCard/index.stories.tsx
- packages/store-ui/src/Slider/hooks/useSlider.ts
- packages/store-ui/src/Slider/index.stories.tsx
- packages/store-ui/src/utils/debounce.ts
- packages/store-ui/src/utils/throttle.ts
Our storybook wasn't running because of some typing and import/export errors. Those changes will fix.
Open the `store-ui` package and run the storybook with `yarn storybook`.
PS.: The storybook still needs some implementations, stylings and new components.
> fix storybook build errors

- docs/data-fetching.md
- docs/data-structure.md
- docs/wip/data-fetching.md
As the title says.
[Preview](https://github.com/vtex/faststore/blob/8ebbb07c28412b87220b76917857af204bf9ac13/docs/wip/data-fetching.md)
> Docs: Add data-fetching docs

- docs/shadowing.md
> Update and rename docs/wip/theme-shadowing.md to docs/shadowing.md

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/Search/List/__generated__/SearchQuery.graphql.ts
- packages/gatsby-theme-store/src/sdk/orderForm/controller/__generated__/AddToCartMutation.graphql.ts
- packages/gatsby-theme-store/src/sdk/orderForm/controller/__generated__/UpdateItemsMutation.graphql.ts
- packages/gatsby-theme-store/src/templates/__generated__/SearchPageQuery.graphql.ts
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- yarn.lock
gatsby has already published several versions with corrections and improvements, so this PR has the purpose of updating gatsby.
https://www.gatsbyjs.com/docs/reference/release-notes/
> Upgrade Gatsby version

- README.md
To make the docs more easily discoverable.
> Add docs table of contents to README

- docs/wip/sonarqube.md
Preview [here](https://github.com/vtex/faststore/blob/ff61bda0c76eaf4cff5b586d868e824e0508581c/docs/wip/sonarqube.md)
> SonarQube documentation

- docs/how-to-rollback.md
- docs/wip/how-to-rollback.md
Document the rollback process
This is only valid when we are using VTEX to build the stores, not Netlify
> Documenting rollback in faststore

- README.md
There are some common problems that can occur while developing in FastStore, so I'm adding a Troubleshooting section.  
Plus, I added a Table of Contents too.
> adding table of contents and troubleshooting session

- lerna.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/HomePage/SEO/__generated__/HomePageSEOQuery.graphql.ts
- packages/gatsby-theme-store/src/components/ProductPage/SEO/Canonical.tsx
- packages/gatsby-theme-store/src/components/ProductPage/SEO/StructuredData.tsx
- packages/gatsby-theme-store/src/components/ProductPage/SEO/__generated__/StructuredProductFragment_product.graphql.ts
- packages/gatsby-theme-store/src/components/ProductPage/SEO/useStructuredProduct.ts
- packages/gatsby-theme-store/src/templates/__generated__/ProductPageQuery.graphql.ts
Adds breadcrumb structured data to the product page
> SEO | Product Breadcrumb

- lerna.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/sdk/graphql/useQuery.ts
> Fix | SWR defaults

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
Releasing a version of this #504
> Release: 0.251.0

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/lighthouse-config/src/index.ts
- packages/store-ui/package.json
In this PR we turn assertions a param on lighthouse config
> Lighthouse Assertions as Params

- CONTRIBUTING.MD
> Add contributing

- packages/store-ui/src/Auth/Providers/EmailAndPassword/Button.tsx
- packages/store-ui/src/Auth/Providers/EmailAndPassword/SignInForm.tsx
- packages/store-ui/src/Carousel/ArrowRight.tsx
- packages/store-ui/src/Carousel/Page.tsx
- packages/store-ui/src/Carousel/PaginationDots.tsx
- packages/store-ui/src/Carousel/index.tsx
Those changes fix the circular dependency error from store-ui, in our Auth and Carousel components.
> Fix - Circular dependencies

- lerna.json
- packages/gatsby-theme-store/package.json
- packages/store-ui/package.json
- packages/store-ui/src/Login/Logo.tsx
As title says, this PR adds alt to login logo
> Add alt to login logo

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- yarn.lock
> Fix trailing comma and update packages versions

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/sdk/buyButton/useBuyButton.ts
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- yarn.lock
addToCart mutation doesn't accept price as a variable. This contribution fixes this problem
> Fix add to cart

- docs/wip/seo.md
As title says, this PR adds docs for the seo part
> SEO | docs

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-nginx/src/nginx-generator.ts
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-source-vtex/src/gatsby-node.ts
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
> Fix x-forwarded-host

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/Minicart/Drawer/Content.tsx
- packages/gatsby-theme-store/src/components/Minicart/Drawer/index.tsx
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
Uses sellingPrice instead of price for minicart so we actually get the selling price of the product instead of the price
> Minicart | Use Selling Price

- packages/gatsby-theme-store/src/sdk/product/constants.ts
Somehow the not found image became tramontina's logo. This PR replaces this image with a more appropriate one
https://storecomponents.vtexassets.com/assets/faststore/images/product-not-found___896e5a25304827218d2e6b1c18e1f3ed.jpeg
> Replace not found image

- packages/gatsby-source-vtex/src/gatsby-node.ts
> Remove via

- lerna.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-source-vtex/src/gatsby-node.ts
> Add via to missing fields

- packages/gatsby-plugin-nginx/src/nginx-generator.ts
> Fix nginx location regex

- packages/gatsby-plugin-google-tag-manager/src/pixel/handler.ts
Uses the same pattern as internalSiteSearchView of VTEX IO
> Internal site search view

- lerna.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/Error/ErrorHandler.tsx
- packages/gatsby-theme-store/src/pages/500.tsx
- packages/gatsby-theme-store/src/sdk/uuid.ts
There was an infinite loop in error handling while generating fake errorIds. This PR fixes this issue
Open the production url, [/500](https://btglobal.vtex.app/500). You will see the errorId going crazy. The PRs below should fix this issue
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/249)
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/389)
[storecomponents](https://github.com/vtex-sites/storecomponents.store/pull/528rl)
> Fix infinite loop

- lerna.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-google-tag-manager/src/gatsby-node.ts
- packages/gatsby-plugin-google-tag-manager/src/pixel/index.tsx
- packages/gatsby-plugin-google-tag-manager/src/pixel/types.ts
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-pixel-facebook/src/gatsby-node.ts
- packages/gatsby-plugin-pixel-facebook/src/pixel/index.tsx
- packages/gatsby-plugin-pixel-facebook/src/pixel/types.ts
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/sdk/once.ts
Add pixels only on production hosts so we don't mess up with the metrics on our test urls
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/391)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/251)
[storecomponents](https://github.com/vtex-sites/storecomponents.store)
> Pixel on allowed hosts only

- .github/workflows/publish-master.yml
> permission to push in master branch

- packages/gatsby-plugin-nginx/src/nginx-generator.ts
Uses relative redirects instead of absolute ones
> add absolute_redirect false

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/SearchBar/index.tsx
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- packages/store-ui/src/SearchBar/Button.tsx
Allow to send an icon prop to the search bar button
New prop to Search bar component:
```jsx
<SearchBar
placeholder="Pesquise por produtos ou marcas"
aria-label="Pesquise por produtos ou marcas"
icon={<MagGlass />}
/>
```
This snippet was extracted from this [file](https://github.com/vtex-sites/carrefourbrfood.store/blob/6b8512bb7df3b8200741e1b4783ed8025b9c5492/src/%40vtex/gatsby-theme-store/components/Header.tsx)
> Add icon prop to Search bar button

- CONTRIBUTING.MD
Fix instruction of CONTRIBUTING.md
> Fix contributing command

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- packages/store-ui/src/index.tsx
- yarn.lock
This PR adds a Modal component from `**react-modal**` library in our Store UI.
> Modal component in store UI

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/SearchBar/index.tsx
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- packages/store-ui/src/SearchBar/Button.tsx
> fix: type of searchbar icon

- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
> fix: remove gitHead

- lerna.json
- packages/gatsby-plugin-cms/package.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-graphql/package.json
- packages/gatsby-plugin-i18n/package.json
- packages/gatsby-plugin-nginx/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-plugin-theme-ui/package.json
- packages/gatsby-source-vtex/package.json
- packages/gatsby-theme-store/package.json
- packages/lighthouse-config/package.json
- packages/store-ui/package.json
- yarn.lock
> fix: remove messageformat and upgrade react intl

- packages/store-ui/src/index.tsx
> Adding tooltip export from reakit

- lerna.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/sdk/search/controller.ts
The PR #594 didn't fix all cases, missing the laanding page. This PR fixes this last edge case
> Search | Fix root path in landing page

- lerna.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/sdk/search/controller.ts
[marinbrasil](https://github.com/vtex-sites/marinbrasil.store/pull/418)
[btglobal](https://github.com/vtex-sites/btglobal.store/pull/327)
> Fix full text path navigation

- lerna.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/components/SearchSuggestions/Products/__generated__/ProductsSuggestionsQuery.graphql.ts
- packages/gatsby-theme-store/src/components/SearchSuggestions/Products/hooks.ts
- packages/gatsby-theme-store/src/components/SearchSuggestions/index.tsx
* Adding region context to search suggestions
* Adding missing variable on query
* Removing unused import
* Changing generated query
* Release: 0.290.1-fabi.0
* Reviewer's suggestions
* Reviewer's suggestions
* Release: 0.290.1-fabi.1
<em>Extra tip: adding references to related issues or mentioning people important to …
> Feature/region id on search suggestions (#604)

- packages/gatsby-theme-store/src/sdk/newsletter/README.md
When someone wants to use the newsletter, it is necessary to configure the Master Data. So I created the documentation about that.
> docs: get started with newsletter

- README.md
Updating troubleshoot section.
> README | Update Troubleshoot section

- .github/workflows/internal-docs.yml
Following the steps in https://github.com/vtex/internal-docs#how-to-use
https://internal-docs.vtex.com/
> Integrate our docs to Internal Docs

- packages/gatsby-theme-store/src/sdk/buyButton/useBuyButton.ts
Add product name and image of a new product to be added to orderform
useBuyButton will receive productName and product image url.
Go to [storecomponents](https://sfj-baaa60e--storecomponents.preview.vtex.app/) and add a product to minicart.
> Add product name and images when add new item to orderform

- .github/workflows/internal-docs.yml
> Avoid running on PRs that don't change docs

- README.md
- docs/wip/getting-more-help.md
Improve the documentation through the addition of a "Getting Help" section on README
Check the README!
Read it and check if everything is good!
None!
> Add "Getting help" section on README

- lerna.json
- packages/gatsby-plugin-google-tag-manager/package.json
- packages/gatsby-plugin-pixel-facebook/package.json
- packages/gatsby-theme-store/package.json
- packages/gatsby-theme-store/src/sdk/search/useRegionalizedSearch.ts
There was a problem in my last PR where stores that didn't use region were getting redirected to region-based urls. This PR fixes this problem
> HotFix | Region

- .github/workflows/publish.yml
> remove custom branch

- packages/gatsby-plugin-cms/src/gatsby-node.ts
For the relay style pagination to work, we need to add some relay style pagination required fields. This should allow cms to fetch more than 100 pages.
> Add required fields for relay style pagination

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
This PR aims to solve two problems. The first one is avoiding building twice the same code on master. The secoond one is to avoid running the CI workflow twice on master too
> Change CI/CD

- .github/workflows/release.yml
> WIP | fix 403 on lerna publish

- packages/gatsby-plugin-nginx/src/nginx-generator.ts
update nginx config to generate json logs
Update nginx plugin to create json logs
Generate nginx configuration and verify logs are formatted as json
> nginx json logs

- packages/store-ui/package.json
- packages/store-ui/src/Auth/Providers/EmailAndPassword/Button.tsx
- packages/store-ui/src/Auth/Providers/EmailAndPassword/EmailForm.tsx
- packages/store-ui/src/Auth/Providers/EmailAndPassword/SignInForm.tsx
- packages/store-ui/src/Auth/Providers/EmailAndPassword/SignUpForm.tsx
- packages/store-ui/src/Auth/Providers/EmailVerification/AccessCodeForm.tsx
- packages/store-ui/src/Auth/Providers/EmailVerification/Button.tsx
- packages/store-ui/src/Auth/Providers/EmailVerification/EmailForm.tsx
- packages/store-ui/src/Auth/Providers/Facebook/Button.tsx
- packages/store-ui/src/Auth/Providers/Google/Button.tsx
- packages/store-ui/src/LocalizedLink/index.tsx
- packages/store-ui/src/LocalizedLink/path.ts
- packages/store-ui/src/LocalizedLink/useLocalizedPath.ts
- packages/store-ui/src/Minicart/Drawer/Content/index.tsx
- packages/store-ui/src/Minicart/Drawer/Footer/index.tsx
- packages/store-ui/src/Minicart/Drawer/Header/index.tsx
- packages/store-ui/src/SearchSuggestions/Autocomplete.tsx
- packages/store-ui/src/SearchSuggestions/Products.tsx
- packages/store-ui/src/SearchSuggestions/SearchHistory.tsx
- packages/store-ui/src/SearchSuggestions/TopSearches.tsx
- packages/store-ui/src/ShippingSimulator/ShippingTable.tsx
- packages/store-ui/src/ShippingSimulator/TranslateEstimate.tsx
- packages/store-ui/src/ShippingSimulator/index.tsx
- yarn.lock
In this PR we remove `@vtex/gatsby-plugin-i18n` from `store-ui`
> feat: using react-intl

- packages/store-ui/src/atoms/Button/Button.tsx
> fix: using elementType on as prop

- packages/store-ui/src/atoms/Button/Button.tsx
> Revert "fix: using elementType on as prop"

- .codesandbox/ci.json
Using the React Typescript Template as Sandbox we can test all components from Store UI
> feat: using ts sandbox on codesandbox

- packages/store-ui/src/atoms/Button/Button.test.tsx
> tests: improvement button tests

- .codesandbox/ci.json
To packages works on codesandbox we need to have a template with pkg installed previously
> chore: using own template on codesandbox

- packages/store-ui/src/atoms/Input/Input.stories.tsx
- packages/store-ui/src/atoms/Input/Input.test.tsx
- packages/store-ui/src/atoms/Input/Input.tsx
- packages/store-ui/src/atoms/Input/index.ts
- packages/store-ui/src/index.tsx
We create the new Input component as the next atom component.
```tsx
import { Input } from "@vtex/store-ui";
export default function Buttons() {
return (
<div className="space-x-2">
<Input placeholder="Input" />
<Input placeholder="Disabled" disabled />
<Input placeholder="custom" className="input-custom" />
<Input placeholder="Error" isError />
<Input placeholder="Required" required />
</div>
);
}
```
```css
[data-store-input] {
@apply border border-gray-200 px-4 py-2 rounded-md shadow-sm text-sm bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent;
}
[data-store-input]:disabled {
@apply bg-gray-100;
}
[data-store-input][data-error] {
@apply border-red-500 focus:ring-red-500 placeholder-red-500 focus:border-transparent;
}
.input-custom {
@apply …
```
> feat: Input

- packages/store-ui/package.json
- packages/store-ui/src/atoms/Popover/Popover.stories.tsx
- packages/store-ui/src/atoms/Popover/Popover.test.tsx
- packages/store-ui/src/atoms/Popover/Popover.tsx
- packages/store-ui/src/atoms/Popover/index.ts
- packages/store-ui/src/index.tsx
- yarn.lock
> feature: ui popover

- packages/gatsby-theme-store/src/templates/product.browser.tsx
- packages/gatsby-theme-store/src/views/search/index.tsx
We were getting some linting issues like:
This PR fixes these linting issues
> Fix lint issues

- README.md
In the past months we have changed our philosophy. This PR moves the README closer to this philosophy
> Change Core Philosophy

- .github/workflows/release.yml
We are ready for our next step: FastStore Release Notes 🚀
The purpose is to create Release Notes and share our:
- 🚀 Features.
- 🐛 Bug fixes.
- ✔️ Improvements.
- ✨ Breaking changes.
- 📑 Documentation.
This way we can all be on the same page and evolve even more!
Teamwork makes the dream work 🤜🤛
Every two weeks we plan to make a release note with the changes from the period on the section [Releases On Github](https://github.com/vtex/faststore/releases).The release note will list each new version and commits made on that time, that's why is **important** to describe in each new commit:
- The purpose of the change.
- How it Works.
- **How to test it.**
- Anything that makes your description clear to all audiences.
If you have any questions, don't worry! Please share it with us so that we can …
> Change to minor release to patch

- CONTRIBUTING.MD
This PR updates the CONTRIBUTING.md guide to not include the commands to release the application, since we have a bot that does that for us now.
I was following this guide and almost re-released the version I merged, so I think it would be good for contributors to have a disclaimer about the bot. Also, I think the command may still be useful, so I left it there with a disclaimer.
> Updating CONTRIBUTING.md 

- packages/gatsby-source-vtex/README.md
- packages/gatsby-source-vtex/gatsby-config.js
- packages/gatsby-source-vtex/gatsby-node.js
- packages/gatsby-source-vtex/package.json
- packages/gatsby-source-vtex/src/gatsby-config.ts
- packages/gatsby-source-vtex/src/index.ts
- packages/gatsby-source-vtex/test/api.test.ts
- packages/gatsby-source-vtex/tsconfig.json
- yarn.lock
As title says, this PR migrates source plugin to tsdx. Also, add some tests
https://github.com/vtex-sites/btglobal.store/pull/648
> Chore | migrate source plugin to TSDX

- packages/gatsby-theme-store/src/sdk/channel/__generated__/DefaultSalesChannelQuery.graphql.ts
- packages/gatsby-theme-store/src/sdk/search/usePersonalizedSearchRedirect.ts
Use replace instead push to replace the URL to personalized search when redirect.
> fix: force replace on personalized search redirect

- packages/gatsby-source-vtex/package.json
- packages/gatsby-source-vtex/src/gatsby-config.ts
- packages/gatsby-source-vtex/src/index.ts
There was a problem in source-vtex that we were not adding some files to the registry. This PR fixes this issue
> Fix | source-vtex

- packages/gatsby-theme-store/src/index.ts
> feat: Export search hooks

- packages/gatsby-plugin-thumbor/gatsby-node.js
Remove the sending of cookies to the thumbor service
> Strip cookies to thumbor

- docs/how-to-create-banner-search.md
This PR adds documentation about how to create a banner search for terms.
> docs: Add banner search docs

- packages/store-ui/src/atoms/TextArea/TextArea.test.tsx
- packages/store-ui/src/atoms/TextArea/TextArea.tsx
- packages/store-ui/src/atoms/TextArea/index.ts
- packages/store-ui/src/atoms/TextArea/stories/TextArea.mdx
- packages/store-ui/src/atoms/TextArea/stories/TextArea.stories.tsx
- packages/store-ui/src/index.ts
Add TextArea atom component, respective tests, and stories.
> feature(store-ui): TextArea atom component

- packages/store-ui/package.json
- yarn.lock
Updates `@vtex-components/accordion` to the latest version
> feat: update accordion version

- packages/store-ui/src/index.ts
We weren't exporting the bullets. Now we do
> Export bullets from store-ui

- packages/gatsby-theme-store/src/sdk/seo/product/useMetadata.ts
On a previous PR I have removed trailing slashes, however, there are some cases where they are not present. This PR fixes this issue but removing the slash only when it's present.
> fix: Remove trailing slashes only

- packages/store-ui/src/molecules/PriceRange/PriceRange.test.tsx
- packages/store-ui/src/molecules/PriceRange/PriceRange.tsx
- packages/store-ui/src/molecules/PriceRange/index.ts
- packages/store-ui/src/molecules/PriceRange/stories/PriceRange.mdx
- packages/store-ui/src/molecules/PriceRange/stories/PriceRange.stories.tsx
- themes/theme-b2c-tailwind/src/molecules/index.css
- themes/theme-b2c-tailwind/src/molecules/price-range.css
> feat(store-ui): price range

- .github/workflows/release.yml
Adds 0.x to CI list so it can be automatically released
> feat: add 0.x to release CI

- packages/gatsby-theme-store/src/sdk/region/controller.ts
fix possibly null window during ssr localstorage access
> fix: possibly null window during ssr localstorage access

- packages/store-api/src/platforms/vtex/utils/facets.ts
This PR fixes fetching product by slug
> fix(store-api): fetch product by slug

- README.md
- themes/theme-b2c-tailwind/README.md
This PR will update UI links from https://storeui.netlify.app/ to https://faststoreui.netlify.app/ in README files.
> fix: Fix FastStore UI link in README files

- packages/api/src/platforms/vtex/loaders/simulation.ts
The simulationLoader required that the checkout API simulates and returns the items we asked for it to simulate. Turns out, this assumption is false. There are some cases where the simulation API returns less items than the ones we asked for. Also, there are more nonsense cases where it returns more items than what we asked for. 
For this reason, when we tried to use base.store in accounts like `storecomponents` or `carrefourbr` we got an error like:
```
Error: Simulation asked for 40, but received 28 items
at call (/Users/gimenes/Documents/code/vtex-sites/base.store/node_modules/@faststore/api
/src/platforms/vtex/loaders/simulation.ts:41:13)
```
This PR fixes the aforementioned error by relaxing the conditions around the simulation loader such that it may return less items than we ask it …
> fix: Relax simulation

- packages/ui/.storybook/main.js
- packages/ui/package.json
- yarn.lock
Since we are aiming for customizable and accessible components, I think this storybook addon could help us develop our components. It helps to test component compliance with web accessibility standards. We already have tests covering accessibility issues, but it would be easier/helpful to check it on the storybook. What do you think?
It provides a new tab called `Accessibility,` and it will check it automatically.
- You can find more about this addon here: [storybook-addon-a11y](https://storybook.js.org/addons/@storybook/addon-a11y)
- If the addons panel doesn't appear on your browse, you can try to clear the storage and refresh the browser.
> Chore: Adds accessibility addon to storybook

- packages/api/src/platforms/vtex/clients/commerce/types/Portal.ts
- packages/api/src/platforms/vtex/resolvers/query.ts
- packages/api/src/platforms/vtex/utils/errors.ts
Throws error when collection is not found
> fix(api): Throws NotFoundError when collection is not found

- packages/ui/src/molecules/RadioGroup/stories/RadioGroup.stories.tsx
- packages/ui/src/typings/index.ts
Hotfix for mismatched imports in UI
> fix: fix UI storybook imports

- docs/docusaurus.config.js
- packages/api/README.md
- packages/sdk/README.md
- packages/ui/README.md
Our docs from api/sdk/ui were duplicated on both docs and on their readmes. This PR removes the readmes content and links to our main docs
> docs: Move docs

- packages/ui/src/index.ts
Adds export missing from internal Banner components
> fix: Add Banner Components exportation

- docs/docusaurus.config.js
Updates the algolia account due to new netlify intregration
> docs: Algolia to faststore.dev

- docs/docs/reference/ui/molecules/Alert.mdx
- docs/docs/reference/ui/molecules/Banner.mdx
- docs/docs/reference/ui/molecules/PaymentMethods.mdx
- docs/src/theme/ReactLiveScope/index.tsx
Add Alert, Banner and PaymentMethods docs
> docs: Add Alert, Banner and PaymentMethods docs

- docs/config.json
- docs/docusaurus.config.js
Search stopped working. Rollback config
> fix(docs): Fix algolia search

- packages/ui/src/index.ts
- packages/ui/src/organisms/Card/Card.test.tsx
- packages/ui/src/organisms/Card/Card.tsx
- packages/ui/src/organisms/Card/CardActions.tsx
- packages/ui/src/organisms/Card/CardContent.tsx
- packages/ui/src/organisms/Card/CardImage.tsx
- packages/ui/src/organisms/Card/index.tsx
- packages/ui/src/organisms/Card/stories/Card.mdx
- packages/ui/src/organisms/Card/stories/Card.stories.tsx
- themes/theme-b2c-tailwind/src/index.css
- themes/theme-b2c-tailwind/src/organisms/card.css
- themes/theme-b2c-tailwind/src/organisms/index.css
This PR intends to add the Card organism.
The `Card` component works together with its own wrapper components for each content's details:
- `CardImage`: the wrapper component for the content's image;
- `CardContent`: the wrapper component for the content's details;
- `CardActions`: the wrapper component for the content's CTAs (call-to-action).
- Visually, through Storybook;
- Unit tests through Jest: yarn test packages/ui/src/organisms/Card/Card.test.tsx
**Storybook preview**:
- [ARIA Roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles)
- ["How to build accessible cards–block links"](https://www.nomensa.com/blog/how-build-accessible-cards-block-links)
- [Radix UI](https://www.radix-ui.com/docs/primitives/components/)
- [Reach UI - Menu …
> feat(ui): Card component

- packages/ui/src/atoms/Badge/Badge.tsx
I noticed that we are not passing other props (`...otherProps`)  to this component. This PR attempts to do so.
> chore: Adds other props to Badge component

- packages/ui/src/atoms/Incentive/Incentive.test.tsx
- packages/ui/src/atoms/Incentive/Incentive.tsx
- packages/ui/src/atoms/Incentive/index.tsx
- packages/ui/src/atoms/Incentive/stories/Incentive.mdx
- packages/ui/src/atoms/Incentive/stories/Incentive.stories.tsx
- packages/ui/src/atoms/Incentive/stories/assets/Icons.tsx
- packages/ui/src/index.ts
- themes/theme-b2c-tailwind/src/atoms/incentive.css
- themes/theme-b2c-tailwind/src/atoms/index.css
This PR intends to add the Incentive atom.
The `Incentive` component work as a group/list's item with the purpose of informing users about a product's benefit.
- Visually, through Storybook;
- Unit tests through Jest: `yarn test packages/ui/src/molecules/Incentive/Incentive.test.tsx`
**Storybook Preview:**
- ARIA Roles: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/
> feat(ui): Incentive atom

- packages/ui/src/index.ts
- packages/ui/src/molecules/QuantitySelector/QuantitySelector.test.tsx
- packages/ui/src/molecules/QuantitySelector/QuantitySelector.tsx
- packages/ui/src/molecules/QuantitySelector/index.ts
- packages/ui/src/molecules/QuantitySelector/stories/QuantitySelector.mdx
- packages/ui/src/molecules/QuantitySelector/stories/QuantitySelector.stories.tsx
- packages/ui/src/molecules/QuantitySelector/stories/assets/Icons.tsx
- themes/theme-b2c-tailwind/src/molecules/index.css
- themes/theme-b2c-tailwind/src/molecules/quantity-selector.css
This PR adds the QuantitySelector component.
It adds the following files that compose the QuantitySelector component logic, its documentation and tests:
- `QuantitySelector.tsx`, the main component which aims to be as small as possible and allow user-defined custom logic considering the "inversion of control" pattern
- `index.tsx`, which exports the `QuantitySelector` component and the type of its props, `QuantitySelectorProps`
- `QuantitySelector.mdx`, which is the Storybook page.
- `QuantitySelector.stories.tsx`, which defines the sample `QuantitySelector` component with some basic add/subtract logic and is rendered in the storybook
- `Icons.tsx`, which defines two simple react components that renders the plus and minus signs from an SVG, to be used with the `IconButton` component
- …
> feat: (Atomic) QuantitySelector component

- packages/ui/.storybook/Welcome/Welcome.js
- packages/ui/.storybook/Welcome/welcome.css
- packages/ui/src/atoms/Checkbox/stories/Checkbox.stories.tsx
- packages/ui/src/atoms/Radio/stories/Radio.stories.tsx
- packages/ui/src/atoms/Select/stories/Select.stories.tsx
- packages/ui/src/atoms/TextArea/stories/TextArea.stories.tsx
- packages/ui/src/molecules/Carousel/Carousel.tsx
- packages/ui/src/molecules/IconButton/IconButton.test.tsx
- packages/ui/src/molecules/IconButton/IconButton.tsx
- packages/ui/src/molecules/IconButton/stories/IconButton.stories.tsx
- packages/ui/src/molecules/QuantitySelector/QuantitySelector.test.tsx
- packages/ui/src/molecules/QuantitySelector/QuantitySelector.tsx
- themes/theme-b2c-tailwind/src/atoms/badge.css
- themes/theme-b2c-tailwind/src/atoms/price.css
- themes/theme-b2c-tailwind/src/molecules/icon-button.css
This PR fix some accessibility issues in sotrybook.
Some storybook’ components have accessibility issues. The goal is to fix that.
> fix: fix accessibility on storybook

- docs/src/pages/sections/StarterComponentPage/StarterComponentPage.tsx
- docs/src/pages/starters/storeframework.js
- docs/static/data/starters.json
Adds a new starter to the starter list. This new starter is based on base.store and integrates base.store with VTEX CMs
> chore: Add storeframework.store starter

- packages/gatsby-source-vtex/src/gatsby-node.ts
Add sales channel to product query since it exists on the original schema
> feat: Sales channel to product query

- packages/gatsby-theme-store/src/sdk/buyButton/useBuyButton.ts
- packages/gatsby-theme-store/src/sdk/orderForm/controller/__generated__/AddToCartMutation.graphql.ts
- packages/gatsby-theme-store/src/sdk/orderForm/controller/addToCart.ts
- packages/gatsby-theme-store/src/sdk/orderForm/useMutateAddItems.ts
Forwards sales channel info to orderform api
> feat: Sales channel order form

- packages/gatsby-plugin-nginx/src/gatsby-node.ts
- packages/gatsby-plugin-nginx/src/nginx-generator.ts
- packages/gatsby-plugin-nginx/src/pluginOptions.ts
- packages/gatsby-plugin-nginx/src/typings/types.d.ts
- packages/gatsby-plugin-nginx/test/nginx-generator.test.ts
Retrofits #1050 into 0.x branch.
> chore(gatsby-plugin-nginx): Try local files before returning 404 (#1050)

- docs/blog/2022-02-04-faststore.md
- docs/static/data/releases.json
Fix minor issues with the January, 2022 release notes
Trivial change
> Fix: Wrong URL and typo in release notes

- docs/blog/2021-10-08-faststore.md
- docs/blog/2021-11-18-faststore.md
- docs/blog/2021-12-22-faststore.md
- docs/blog/2022-02-04-faststore.md
- docs/blog/2022-02-08-webops.md
- docs/src/theme/BlogSidebar/index.js
- docs/static/data/releases.json
Add "Improved WebOps pipeline execution time" announcement to Releases.
> Add WebOps announcement

- packages/ui/src/index.ts
- packages/ui/src/molecules/SearchInput/SearchInput.tsx
- packages/ui/src/molecules/SearchInput/index.ts
This PR adjusts the SearchInput reference, to be able to do imperative code with the Input behaviors, like a InputFocus.
This behaviour is necessary in base store in this PR https://github.com/vtex-sites/base.store/pull/350.
> feat: Ajust SearchInput reference export

- packages/lighthouse-config/src/index.ts
More info at: https://github.com/vtex-sites/base.store/pull/395
> chore: lighthouse config

- packages/ui/src/molecules/Dropdown/Dropdown.test.tsx
- packages/ui/src/molecules/Dropdown/Dropdown.tsx
- packages/ui/src/molecules/Dropdown/DropdownButton.tsx
- packages/ui/src/molecules/Dropdown/DropdownItem.tsx
- packages/ui/src/molecules/Dropdown/DropdownMenu.tsx
- packages/ui/src/molecules/Dropdown/contexts/DropdownContext.ts
- packages/ui/src/molecules/Dropdown/hooks/useDropdown.ts
- packages/ui/src/molecules/Dropdown/hooks/useDropdownPosition.ts
- packages/ui/src/molecules/Dropdown/index.ts
- packages/ui/src/molecules/Dropdown/stories/Dropdown.mdx
- packages/ui/src/molecules/Dropdown/stories/Dropdown.stories.tsx
- packages/ui/src/molecules/Dropdown/stories/assets/Caret.tsx
- packages/ui/src/molecules/Modal/ModalContent.tsx
- themes/theme-b2c-tailwind/src/molecules/dropdown.css
- themes/theme-b2c-tailwind/src/molecules/index.css
Implement Dropdown Molecule
This PR adds the Dropdown Molecule on faststore UI. This component is based on some references, like a Menu component of the ReachUI and the ChackraUI. 
This component can be used as an options menu and a dropdown select, it can also be used as a controlled or uncontrolled component.
```jsx
<Dropdown>
<DropdownButton>Dropdown Button</DropdownButton>
<DropdownMenu>
<DropdownItem>
Dropdown Item 1
</DropdownItem>
<DropdownItem>
Dropdown Item 2
</DropdownItem>
<DropdownItem>
Dropdown Item 3
</DropdownItem>
</DropdownMenu>
</Dropdown>
```
The variants can be seen in storybook docs.
<table>
<tr>
<td>Enter
<td>When focus on DropdownButton the Dropdown menu opens and focus go to first DropdownItem.
<tr>
<td>ArrowDown 
<td>Move focus to next MenuItem
<tr>
<td>ArrowUp …
> feat(UI): Add dropdown component

- docs/docs/tutorials/cms/01 - Configuring your VTEX account.md
- docs/static/data/doc-update.json
Adding the `vtex.admin-releases@0.x` app to [Part 1: Configuring your VTEX account](https://faststore.dev/tutorials/cms/1#step-2---installing-the-headless-cms-app-on-your-vtex-account)
> Add vtex.admin-releases@0.x to faststore.dev docs

- docs/blog/2022-04-01-faststore.md
- docs/static/data/releases.json
- lerna.json
- The `lerna.json` file for the March FastStore Release Notes.
- FastStore - March Release Notes
> doc: FastStore Release Notes - March

- docs/blog/2022-04-01-basestore.md
- docs/blog/2022-04-01-faststore.md
- docs/static/data/releases.json
Base Store Release Notes
Title tag
> Release notes update and new Base Release notes

- docs/blog/2022-04-01-basestore.md
Fixed the images on the Base Store Release Notes
> fix: release notes images

- docs/docs/how-to-guides/cms/vtex-headless-cms/Enabling private CMS previews.md
- docs/src/components/CardGrid/CardGrid.module.css
- docs/src/components/DocStructure/DocStructure.js
- docs/src/components/DocUpdate/DocUpdate.tsx
- docs/src/components/FastStore/FastStore.tsx
- docs/src/components/FastStorePackages/FastStorePackages.module.css
- docs/src/components/FeedbackForm/FeedbackForm.module.css
- docs/src/components/LatestUpdates/LatestUpdates.module.css
- docs/src/components/PropsComponent/PropsComponent.module.css
- docs/src/components/StarterComponent/StarterComponent.module.css
- docs/src/components/ViewAll/ViewAll.module.css
- docs/src/css/custom.css
- docs/src/pages/sections/FaqPage/FaqPage.module.css
- docs/src/pages/sections/StarterComponentPage/StarterComponentPage.js
- docs/src/pages/sections/StarterComponentPage/StarterComponentPage.module.css
- docs/src/theme/BlogSidebar/styles.module.css
- docs/src/theme/Playground/styles.module.css
- docs/static/data/doc-update.json
- docs/tailwind.config.js
Add Enabling private CMS previews guide
> Add Enabling private CMS previews guide

- packages/sdk/src/analytics/events/add_payment_info.ts
- packages/sdk/src/analytics/events/add_shipping_info.ts
- packages/sdk/src/analytics/events/add_to_cart.ts
- packages/sdk/src/analytics/events/add_to_wishlist.ts
- packages/sdk/src/analytics/events/begin_checkout.ts
- packages/sdk/src/analytics/events/common.ts
- packages/sdk/src/analytics/events/login.ts
- packages/sdk/src/analytics/events/purchase.ts
- packages/sdk/src/analytics/events/refund.ts
- packages/sdk/src/analytics/events/remove_from_cart.ts
- packages/sdk/src/analytics/events/search.ts
- packages/sdk/src/analytics/events/select_item.ts
- packages/sdk/src/analytics/events/select_promotion.ts
- packages/sdk/src/analytics/events/share.ts
- packages/sdk/src/analytics/events/signup.ts
- packages/sdk/src/analytics/events/view_cart.ts
- packages/sdk/src/analytics/events/view_item.ts
- packages/sdk/src/analytics/events/view_item_list.ts
- packages/sdk/src/analytics/events/view_promotion.ts
- packages/sdk/test/analytics/__fixtures__/EventSamples.ts
More info at: https://github.com/vtex-sites/base.store/pull/389
> feat: Add url to events

- packages/lighthouse-config/src/index.ts
https://github.com/vtex-sites/base.store/pull/439
> chore(lighthouse-config): Increase the performance budget back to 95

- docs/docs/index.mdx
> docs: update description (seo) home

- packages/api/src/platforms/vtex/resolvers/searchResult.ts
> fix(api):SearchResult send events

- docs/docs/tutorials/gatsby/02 - Setting up your development environment.mdx
- packages/api/src/platforms/vtex/resolvers/offer.ts
- packages/api/src/platforms/vtex/utils/price.ts
- packages/api/src/platforms/vtex/utils/productStock.ts
> fix(api): Remove circular dependencies

- docs/src/components/FastStore/FastStore.js
- docs/src/components/FeatureCard/FeatureCard.module.css
- docs/src/components/FeedbackButton/FeedbackButton.module.css
- docs/src/components/FeedbackForm/FeedbackForm.module.css
- docs/src/components/FeedbackModal/FeedbackModal.js
- docs/src/css/custom.css
- docs/src/pages/sections/StarterComponentPage/StarterComponentPage.module.css
- docs/src/pages/sections/StarterPage/StarterPage.js
- docs/src/pages/sections/StarterSubmissionForm/StarterSubmissionForm.jsx
- docs/src/pages/sections/StarterSubmissionForm/StarterSubmissionForm.module.css
- docs/src/pages/starters/submissions.js
- docs/src/theme/BlogSidebar/styles.module.css
- docs/src/theme/Playground/styles.module.css
- docs/tailwind.config.js
> docs: update homepage

- packages/api/src/typeDefs/query.graphql
> fix: search result with products as required

- packages/api/src/__generated__/schema.ts
> fix: api schema

- docs/blog/2022-04-05-faststore.md
- docs/docs/how-to-guides/local-development/troubleshooting-problems-in-faststore.md
- docs/docs/quickstart.md
- docs/docs/reference/api/faststore-api.md
- docs/docs/tutorials/gatsby/04 - Understanding the project structure.md
> docs: fix base store links

- docs/docusaurus.config.js
- docs/vercel.json
https://github.com/vercel/vercel/issues/7246
> docs: fix docusaurus build

- .github/workflows/ci.yml
- .github/workflows/release.yml
After changing the name from `master` to `main` for the master branch, the universe did what Einstein most feared, it divided by zero and our CI/CD workflow stopped working. Hopefully a good samaritan in the restaurant at the end of the universe was paying attention and called the one and only true smart race on planet earth to fix the issue. This race was born millions of years ago and they are still looking for THE answer to life, the universe, and everything.
Some fools believed this answer was 42, however, the true answer, the true and most secret answer lies on this PR.
> fix: Release workflow

- packages/api/src/platforms/vtex/clients/search/index.ts
- packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts
- packages/api/src/platforms/vtex/resolvers/searchResult.ts
- yarn.lock
After the PR of using the new search api, the suggestions stopped working, this PR is premised on fixing this issue.
> fix: suggestions api url

- lerna.json
This PR updates lerna.json due to the [April Release Notes](https://github.com/vtex/faststore/releases/tag/1.8.0)
> docs: updated lerna.json due to Release Notes

- packages/api/src/__generated__/schema.ts
The last commits on our main branch are failing to release automatically with the following error:
This PR runs a build and commit missing file changes to our main branch, making our CI/CD bot to work again
> fix: CI/CD Bot

- packages/api/src/__generated__/schema.ts
After I build the faststore, automatically was generated the schema.ts with some comments.
> chore: comments to query api

- .vscode/settings.json
> chore: remove .vscode settings

- packages/api/src/platforms/vtex/utils/channel.ts
This is a continuation of #1297.
> fix: Region on Search

- packages/api/src/__generated__/schema.ts
- packages/api/src/platforms/vtex/clients/commerce/types/OrderForm.ts
- packages/api/src/platforms/vtex/resolvers/validateCart.ts
- packages/api/src/typeDefs/product.graphql
- packages/api/src/typeDefs/propertyValue.graphql
Pass attchaments to orderForm and validate
> feat: validate cart with attachments

- docs/docs/how-to-guides/cms/vtex-headless-cms/Installing Releases on VTEX Headless CMS.md
Add Installing Releases on VTEX Headless CMS
> docs: Add Installing Releases on VTEX Headless CMS

- packages/sdk/src/index.ts
- packages/sdk/src/search/Provider.tsx
- packages/sdk/src/search/serializer.ts
- packages/sdk/src/search/usePagination.ts
- packages/sdk/src/search/useSearchState.ts
- packages/sdk/src/types.ts
- packages/sdk/src/utils/format.ts
Remove Circular dependency on sdk package
> fix: Circular dependency

- .codesandbox/ci.json
> fix: remove docs from build on codesandbox

- apps/docs/blog/2022-05-06-basestore.md
- apps/docs/blog/2022-05-06-faststore.md
- apps/docs/blog/2022-06-03-basestore.md
- apps/docs/blog/2022-06-03-faststore.md
- apps/docs/static/data/releases.json
May Release Notes for FastStore and Base Store.
> Docs: May Release Notes

- packages/ui/src/organisms/OutOfStock/OutOfStockMessage.tsx
- packages/ui/src/organisms/OutOfStock/OutOfStockTitle.tsx
This Pull Request adds "otherProps" to OutOfStock nested components, allowing new data-attributes to be added.
> feat(ui): Fix OutOfStock nested components

- lerna.json
Updated lerna.json due to the [May Release Notes](https://github.com/vtex/faststore/releases/tag/1.9.0).
> Update lerna.json 

- apps/docs/package.json
- yarn.lock
> fix: docussaurus

- .codesandbox/ci.json
Ignore docs build at codesandbox ci
> fix: codesandbox ci

- packages/lighthouse/tsconfig.json
- packages/sdk/package.json
- packages/ui/package.json
After upgrading to `tsc` building, some `module` fields were not upgraded accordingly. This PR fixes this issue
> fix: module field

- apps/docs/docs/how-to-guides/troubleshooting/analytics-and-partytown.md
Add docs on how to troubleshoot analytics and partytown.
> docs: add troubleshooting for analytics and partytown

- apps/docs/docs/how-to-guides/platform-integration/vtex/hosting-a-faststore-vtex-website.md
does insert the new hosting steps
> Does update hosting documentation

- packages/api/src/platforms/vtex/clients/commerce/types/Portal.ts
- packages/api/src/platforms/vtex/loaders/collection.ts
- packages/api/src/typeDefs/collection.graphql
Add proper support for page types:
- `SubCategory`
- `Collection`
- `Cluster`
This should enable stores to render pages that match those types without issues. Here's an example of one of those issues: 
- https://community.vtex.com/t/problemas-nas-rotas-de-collection-clusters/33353
- https://community.vtex.com/t/enum-storecollectiontype-nao-pode-representar-o-valor-subcategory/33352
Enabling those pageTypes to be returned when the field `collection.type` is queried, instead of throwing an error.
You can run this branch locally using `yarn develop`, inside `packages/api`.
Here's an example taken from the VTEX Community questions linked above:
**Query for a SubCategory page**
```graphql
{
collection(slug: "feminino/acessorios/cinto") {
seo {
title
description
}
breadcrumbList { …
```
> fix: Add missing Catalog pageTypes to `@faststore/api`

- apps/docs/docs/conceptual-guides/analytics-on-faststore.md
- apps/docs/docs/reference/sdk/analytics/how-to-send-custom-events.md
- apps/docs/docs/reference/sdk/analytics/useAnalyticsEvent.md
This PR fixes errors found in the analytics docs. Thanks @eduardoformiga for reviewing the docs so mindfully and for making the suggestions!
> docs: fix analytics docs errors

- apps/docs/docs/how-to-guides/platform-integration/vtex/hosting-a-faststore-vtex-website.md
> docs: Update hosting-a-faststore-vtex-website.md

- lerna.json
This PR fixes the changelog sections that are generated automatically considering commit messages.
Changes lerna config
Not sure how to
https://github.com/lerna/lerna/blob/main/commands/version/README.md#--changelog-preset
> chore: fix changelog sections

- packages/ui/README.md
This PR updates the link to our `faststore/ui` documentation
https://faststore.dev/reference/ui/overview => 404 - PAGE NOT FOUND
Check if the link is directing to the right documentation
> Chore: Updates documentation link

- packages/ui/src/molecules/ProductTitle/ProductTitle.tsx
This PR adds fowardRef to `ProductTitle`.
> feat: Add fowardRef to `ProductTitle`

- packages/api/src/__generated__/schema.ts
I forgot to do this in #1407 😢 .
> chore: Update generated types from `@faststore/api`

- apps/docs/blog/2022-08-05-faststore.md
- apps/docs/static/data/releases.json
- lerna.json
> docs: Add FastStore Release Notes

- packages/ui/.storybook/Welcome/Welcome.js
- Updates storybook welcome page content
> chore: Updates storybook welcome page content

- apps/docs/src/components/BackgroundCard/BackgroundCard.js
- apps/docs/src/components/ComponentsOverview/ComponentsOverview.js
- apps/docs/src/components/FeedbackForm/FeedbackForm.module.css
- apps/docs/src/components/FeedbackForm/FeedbackForm.tsx
- apps/docs/src/components/FeedbackScan/FeedbackScan.js
- apps/docs/src/components/FeedbackScanModal/FeedbackScanModal.js
- apps/docs/src/components/Hero/Hero.js
- apps/docs/src/pages/index.js
- Many Lint issues appearing after merging https://github.com/vtex/faststore/pull/1446
- Attempted to fix some of these [errors](https://github.com/vtex/faststore/runs/8099336847?check_suite_focus=true) 
Everything should look the same, but the linter errors should go away.
> Fix: Lint issues

- apps/docs/docs/how-to-guides/performance/lighthouse.md
- apps/docs/static/data/doc-update.json
- apps/docs/static/data/releases.json
Add doc Getting started with Lighthouse
> docs: getting started with lighthouse

- packages/api/src/platforms/vtex/resolvers/query.ts
This PR addresses this issue: https://vtex.slack.com/archives/C02JXD6RZU3/p1664396722336099?thread_ts=1664292988.979879&cid=C02JXD6RZU3
https://github.com/vtex-sites/nextjs.store/pull/261
https://github.com/vtex-sites/gatsby.store/pull/210
> fix: Wrong sku being returned for slug

- apps/docs/docs/tutorials/cms/04 - Querying the CMS data.md
> Update 04 - Querying the CMS data.md

- packages/api/src/platforms/vtex/resolvers/collection.ts
- When pageType is collection we should return the search meta as a productclusterids facet. Today we return the search meta as a category facet.
- Also the breadcrumbs returns only the path with the collection id when the correct is to return the page slug.
- Basically if the page type is a Collection we handle the search facets and breadcrumb in a different way. Facets as productclusterids and breadcrumb URL as the page slug that it's being requested by the user.
1. Create a collection thru VTEX admin
2. Slugify the collection name (remove any special character and replace  all whitespaces with hyphens)
3. Post to the collection query using the pathname as the slug vaue.
- ❌ Navigate to page: [https://gatsby.vtex.app/just-arrived](https://gatsby.vtex.app/just-arrived) and you will see …
> Fix meta and breadcrumbList for collections

- packages/components/README.md
- packages/components/package.json
This PR proposes creating the `components` package and making the first publish on npm.
https://www.npmjs.com/package/@faststore/components
> feat: create the components packages

- packages/api/package.json
- packages/api/tsconfig.json
- packages/cli/package.json
- packages/cli/tsconfig.json
- packages/graphql-utils/package.json
- packages/graphql-utils/tsconfig.json
- packages/lighthouse/package.json
- packages/lighthouse/tsconfig.json
- packages/sdk/package.json
- packages/sdk/tsconfig.json
- packages/shared/package.json
- packages/ui/package.json
- packages/ui/tsconfig.json
- yarn.lock
shared package needs the npm user `@faststore` because npm has a package called [shared](https://www.npmjs.com/package/shared)
rename the package shared to `@faststore/shared` and install in all package that's dependency.
> chore: shared rename

- .git-blame-ignore-revs
I made a PR #1482 that messed up the commits, so in this current PR I remove the past commit from the git blame in order to organize.
> chore: git blame ignore modification by rename data-store to data-fs

- .codesandbox/ci.json
- packages/components/package.json
- packages/ui/.storybook/main.js
- packages/ui/.storybook/preview.js
- packages/ui/.storybook/styles.scss
- packages/ui/package.json
- packages/ui/src/index.ts
- packages/ui/src/styles/components.scss
- packages/ui/src/styles/global.scss
- yarn.lock
This PR brings all basic styles to FSUI's Storybook.
> Chore: Adds basic styles to Storybook

- packages/styles/src/molecules/bullets.css
- packages/styles/src/molecules/carousel.css
- packages/ui/package.json
- packages/ui/src/hooks/useSlider/useSlider.ts
- packages/ui/src/molecules/Bullets/Bullets.test.tsx
- packages/ui/src/molecules/Bullets/Bullets.tsx
- packages/ui/src/molecules/Bullets/stories/Bullets.mdx
- packages/ui/src/molecules/Carousel/Carousel.test.tsx
- packages/ui/src/molecules/Carousel/Carousel.tsx
- packages/ui/src/molecules/Carousel/CarouselItem.tsx
- packages/ui/src/molecules/Carousel/stories/Carousel.mdx
- packages/ui/src/molecules/Carousel/stories/Carousel.stories.tsx
- yarn.lock
This PR intends to add a new `Carousel` variant (`scroll`) to support the new design prototype for the component and other code improvements.
[feat: Revisit Carousel component](https://github.com/vtex-sites/nextjs.store/pull/273)
> feat: Revisit `Carousel` component

- .github/workflows/release.yml
- apps/docs/docs/reference/ui/atoms/Button.mdx
- apps/docs/src/components/ColorPalette/ColorPalette.tsx
- apps/docs/src/components/TokensTable/Table.tsx
This PR intends to change from `patch` to `prepatch` releases as we moved to the package's pre-release stage.
> chore: Change from `patch` to `prepatch` release (alpha)

- yarn.lock
Fix CD's Publish step by committing `yarn.lock` changes.
> fix: CD's Publish step

- apps/docs/docs/templates/ui-components.md
Updates `ui-components.md` template.
Adds some improvements.
> docs: Updates `ui-component` template file

- packages/cli/src/utils/directory.ts
- packages/cli/src/utils/generate.ts
In order to standardize the framework, we decided to rename store.config.js to `faststore.config.js`
> chore: rename config file

- packages/cli/src/utils/generate.ts
When the starter has no customization for the CMS, the CLI requires it to have a folder with files, this PR solves that.
Checks for actual customization before trying to merge.
> fix: cli cms merge

- apps/docs/docs/tutorials/cms/02 - Setting up the VTEX Headless CMS in your FastStore project.md
Update the documentation with the changes of the new version of CMS cli command.
> fix: cli plugin cms documentation

- yarn.lock
Just updates the `yarn.lock` file.
> chore: Update lock file

- packages/components/src/molecules/Table/Table.tsx
> fix: Edit TableProps

- packages/components/src/molecules/Table/Table.tsx
- packages/components/src/molecules/Table/TableBody.tsx
- packages/components/src/molecules/Table/TableCell.tsx
- packages/components/src/molecules/Table/TableFooter.tsx
- packages/components/src/molecules/Table/TableHead.tsx
- packages/components/src/molecules/Table/TableRow.tsx
This PR intends to apply some improvements to `Table` and its components.
> chore: `Table` component's improvements

- apps/site/pages/index.mdx
Fix this issue
Add some HTML elements
> fix: dom element at home

- packages/ui/package.json
Increase the size limit from 20 to 30
> fix: ui size limit

- package.json
- yarn.lock
Upgrade lerna in order to use the last version of `parse-url`
> fix: dependabot

- packages/cli/src/utils/directory.ts
Depends on https://github.com/vtex-sites/nextjs.store/pull/305
Updates the CMS folder inside the CLI.
https://github.com/vtex-sites/nextjs.store/pull/305/files
> chore: updates cms folder for faststore builder

- apps/site/pages/components/atoms/button.mdx
Fix some problems using prettier and others like that
> fix: button documentation

- packages/api/package.json
- yarn.lock
fixes the error while trying to run the local API
|Before|After|
|-|-|
|<img width="1877" alt="Screen Shot 2023-01-31 at 17 51 02" src="https://user-images.githubusercontent.com/11325562/215880909-4509522b-92a8-4650-a56f-c1d8a8884334.png">|<img width="1885" alt="Screen Shot 2023-01-31 at 17 52 58" src="https://user-images.githubusercontent.com/11325562/215880929-eb354c76-7e1f-4771-8b01-4f1b88df59dd.png">|
`yarn develop` in package/api
> fix: local api server error

- yarn.lock
> chore: updates yarn lock

- packages/api/src/__generated__/schema.ts
- packages/api/src/platforms/vtex/resolvers/query.ts
- packages/api/src/platforms/vtex/resolvers/searchResult.ts
- packages/api/src/typeDefs/query.graphql
- yarn.lock
1.x port of PRs https://github.com/vtex/faststore/pull/1633 and https://github.com/vtex/faststore/pull/1637
> Fix/move sp event to frontend 1.x

- .github/workflows/release.yml
- package.json
- yarn.lock
Fixes version publish by using lerna 6.4.1
> Fix: publish version

- .github/workflows/release.yml
- package.json
- yarn.lock
Fixes branch `1.x` version publish by using lerna 6.4.1
> fix: publish version workflow

- packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
I forgot to add back the [cart sidebar testId](https://github.com/vtex/faststore/pull/1649/files#diff-bc55adb273e27dfb220da8699e7463fac6bc3e1292439e1fa7530e09e9a6d009)
[https://github.com/vtex-sites/starter.store/pull/20](https://github.com/vtex-sites/starter.store/pull/20/checks?check_run_id=12022586638)
> fix: Adds missing test id

- packages/components/src/hooks/UIProvider.tsx
Quick Fix `yarn test` from FS root monorepo.
> fix: yarn test script

- packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
Puts cart-sidebar test id in the right place.
> fix: Puts cart-sidebar test id in the right place

- packages/components/src/molecules/SearchProducts/SearchProductItem.tsx
- packages/components/src/molecules/SearchTop/SearchTopTerm.tsx
- packages/core/src/components/search/SearchTop/SearchTop.tsx
Fix forwardRef related errors in console
You shouldn't see these errors anymore in your console while running the store.
> Fix: forwardRef errors

- apps/site/pages/docs/themes/midnight.mdx
- apps/site/pages/docs/themes/soft-blue.mdx
- packages/core/src/styles/themes/midnight.scss
Just a small quick fix for the navbar bg-color.
> docs: Updates midnight theme stylesheet

- packages/core/cms/sections.json
> modify sections

- packages/api/src/platforms/vtex/clients/commerce/index.ts
- packages/api/src/platforms/vtex/clients/commerce/types/Session.ts
- packages/api/src/platforms/vtex/resolvers/validateCart.ts
- packages/api/src/platforms/vtex/utils/getCookies.ts
- packages/api/test/mutations.test.ts
- packages/api/test/queries.test.ts
Replicate the changes from https://github.com/vtex/faststore/pull/1653 in branch `1.x`.
> chore: applies PR #1653 in 1.x branch

- packages/core/package.json
- yarn.lock
Updates the version of `faststore/api` in core package.
> chore: updates api version in core package

- packages/core/cms/sections.json
- packages/core/src/components/sections/BannerText/BannerText.tsx
Add CMS mapping for all default sections in our starter.
Install this version of Faststore on your [starter](https://github.com/vtex-sites/starter.store), run `vtex cms sync` and see if everything is in place or use the preview link.
[Link Preview](https://arthurspace2--storeframework.myvtex.com/admin/new-cms/faststore)
> Create CMS Mapping for Sections

- packages/components/src/molecules/SearchInputField/SearchInputField.tsx
- packages/core/cypress/integration/analytics.test.js
- packages/core/cypress/integration/cart.test.js
- packages/core/cypress/integration/search.test.js
- packages/core/package.json
- packages/core/src/components/search/Filter/FilterSlider.tsx
> fix: fix tests

- apps/site/pages/docs/_meta.json
- apps/site/pages/docs/getting-started/getting-started-overview.mdx
- apps/site/pages/docs/getting-started/next-steps.mdx
- apps/site/pages/docs/getting-started/onboarding.mdx
- apps/site/pages/docs/getting-started/project-structure.mdx
- apps/site/pages/docs/getting-started/settingup-project.mdx
This PR adds the new documentation for the FastStore Onboarding app. It also adds a new section for the (coming soon) **Setting Up the Project** doc.
The new **FastStore Onboarding** documentation consists of the following:
- App's overview 
- Step-by-step on how to start the project
- Next Step: links to the (coming soon) Setting Up the Project documentation
This is a documentation improvement only.
[Preview](https://faststore-site-git-doc-onboarding-faststore.vercel.app/docs/getting-started/onboarding)
> Doc: FastStore Onboarding

- apps/site/pages/docs/getting-started/getting-started-overview.mdx
- apps/site/pages/docs/getting-started/onboarding.mdx
This PR has the following updates:
1. `getting-started-overview.mdx`
- Adds Headless CMS hyperlink.
- Adds a short description for each topic of the track.
2. `onboarding.mdx`
- Fixes image's path (@renatamottam, I found out how to use file manager to upload images 👀 )
- Adds missing Hyperlinks
[Visit Preview](https://faststore-site-git-fix-onboarding-faststore.vercel.app/)
> Doc: Update onboarding.mdx

- apps/site/pages/components/atoms/icon.mdx
- apps/site/pages/docs/component-customization/override-component.mdx
- apps/site/pages/docs/customizing.mdx
- apps/site/pages/docs/getting-started/onboarding.mdx
- apps/site/pages/docs/global-tokens/typography.mdx
- apps/site/pages/docs/icons.mdx
- apps/site/pages/docs/themes/midnight.mdx
- apps/site/pages/docs/themes/soft-blue.mdx
- apps/site/pages/docs/troubleshooting/identifying-development-errors-and-starter-bugs.mdx
- apps/site/pages/index.mdx
- packages/components/src/atoms/Icon/Icon.tsx
- packages/core/src/components/common/Footer/Footer.tsx
- Icons doc page was outdated.
- Adds props do icon doc page.
- General docs fixes/improvements
- [Icons doc page](https://faststore-site-git-chore-docs-icons-faststore.vercel.app/docs/icons)
- [Icon component](https://faststore-site-git-chore-docs-icons-faststore.vercel.app/components/atoms/icon)
> Docs: Updates Icons docs + general updates

- apps/site/pages/docs/_meta.json
- apps/site/pages/docs/component-customization/creating-component.mdx
This PR creates the **Creating a Component** documentation.
🔗 [Preview](https://faststore-site-git-doc-component-faststore.vercel.app/docs/component-customization/creating-component)
> Doc: How to Create a Component

- packages/core/src/components/cms/GlobalSections.tsx
Update content-type to globalSections
> feat: Update content-type to globalSections

- packages/core/cms/faststore/content-types.json
- packages/core/cms/faststore/sections.json
Feat: Add PLP Content-type e refacts sections to use CamelCase
> Feat: Add PLP Content-type e refacts sections to use CamelCase

- apps/site/pages/components/atoms/badge.mdx
- apps/site/pages/components/molecules/discount-badge.mdx
- packages/ui/src/components/atoms/Badge/styles.scss
- Adds missing badge token (border-style)
- Removes unused css from stylesheet
- Updates DiscountBadge doc with Badge's import
> Chore: Update Badge tokens

- apps/site/pages/components/organisms/hero.mdx
- Adds Hero's component props
- Check if the props list is appearing according. You can check through [preview](https://faststore-site-git-docs-hero-docs-update-faststore.vercel.app/components/organisms/hero).
> docs: Adds Hero's props

- apps/site/pages/docs/index.mdx
This PR updates the introduction for Evergreen doc to mention its three packages: core, UI, and CLI
🔗 [Preview](https://faststore-site-git-review-introduction-faststore.vercel.app/docs#what-is-included)
> Doc: Update introduction

- packages/core/cms/faststore/content-types.json
- packages/core/faststore.config.js
- packages/core/src/pages/api/preview.ts
- packages/core/src/pages/index.tsx
This PR improves the preview feature, redirecting the preview page according to content-type.
Also, apply adjusts in content-types creating a content-type home singleton.
> feat: Apply adjusts in preview and content-types

- packages/api/src/telemetry/useFaststoreTelemetry.ts
Fixes lint error that was not present locally
> fix: telemetry lint error

- apps/site/pages/docs/_meta.json
- apps/site/pages/docs/go-live.mdx
- apps/site/pages/docs/go-live/1-setting-up-vtex-account-for-faststore.mdx
- apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
- apps/site/pages/docs/go-live/3-integrating-the-the-vtex-login.mdx
- apps/site/pages/docs/go-live/4-integrating-the-vtex-checkout.mdx
- apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
- apps/site/pages/docs/go-live/before-you-start.mdx
- apps/site/pages/docs/go-live/overview.mdx
This PR adds the `Go-live` track.
🔗 [Preview](https://faststore-site-git-vtex-integration-faststore.vercel.app/docs/go-live/overview)
This PR adds the following changes:
- An overview of the go-live process along with a checklist.
- Sections dedicated to future documentation for each step in this track.
P.s. 1: This PR does not include the complete content for the new sections. The focus is an overview and go-live checklist. The content for future documentation will be added in separate PRs.
P.s. 2: The [file to download the checklist](https://github.com/vtex/faststore/pull/1765/files#diff-629beef3bbe7ac0684f68db056e93af84c4c469a5da8df9328771b38d456ee77R25) is still under construction 🚧
> Doc: Go-live track

- packages/core/cms/faststore/sections.json
- packages/core/src/components/sections/BannerNewsletter/BannerNewsletter.tsx
- packages/core/src/components/sections/Newsletter/Newsletter.tsx
- packages/core/src/components/ui/Newsletter/Newsletter.tsx
This PR adds Toast options to Newsletter CMS component
> feat: Add Toast options in newsletter

- apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
> Doc: Fix node version recommendation

- packages/core/cypress/integration/a11y.test.js
- packages/core/cypress/integration/analytics.test.js
- packages/core/cypress/integration/performance.test.js
Temporarily skip flaky tests.
- https://github.com/vtex-sites/starter.store/pull/68
> chore: temp skip flaky tests

- apps/site/pages/docs/go-live/4-integrating-the-vtex-checkout.mdx
- apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
- apps/site/pages/docs/go-live/before-you-start.mdx
This PR adds the lasts two docs for the [Go-live: VTEX Integration track](https://evergreen.faststore.dev/docs/go-live):
🔗 [Part 4: Integrating the VTEX Checkout](https://faststore-site-git-docs-integrating-checkout-faststore.vercel.app/docs/go-live/4-integrating-the-vtex-checkout)
🔗 [Part 5: Integrating the VTEX Order Placed and My Account](https://faststore-site-git-docs-integrating-checkout-faststore.vercel.app/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account)
> integrating checkout

- packages/components/src/atoms/Link/Link.tsx
- packages/components/src/organisms/OutOfStock/OutOfStock.tsx
- packages/core/src/components/sections/Newsletter/Newsletter.tsx
- packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
- packages/core/src/components/ui/Link/Link.tsx
- packages/core/src/components/ui/ProductDescription/ProductDescription.tsx
This PR intends to use real product description data incoming from API.
Some other minor fixes were applied too.
1 - Open the PDP page and check if the product description data is there;
2 - Navigate through all store pages, open the development console, check if there are any error.
https://github.com/vtex-sites/starter.store/pull/69
> fix: Product description mock data

- apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
This PR adds the second doc for the [Go-live: VTEX Integration track](https://evergreen.faststore.dev/docs/go-live/2-configuring-external-dns).
🔗 [Preview](https://faststore-site-git-docs-configuring-external-dns-faststore.vercel.app/docs/go-live/2-configuring-external-dns)
> Docs: Configuring external DNS for a custom domain

- packages/core/cypress/integration/a11y.test.js
- packages/core/src/components/sections/Navbar/Navbar.tsx
This PR intends to fix a11y tests.
> fix: A11y tests

- package.json
> fix: release

- packages/core/cypress/integration/a11y.test.js
This PR intends to skips a11y tests... 😞 
https://github.com/vtex-sites/starter.store/pull/73
> chore: Skip a11y tests

- packages/api/src/platforms/vtex/index.ts
- packages/api/src/platforms/vtex/resolvers/searchResult.ts
For some reason when we researched the products we always got the first item, however this item was not always available, which made it seem that there was no more item available. So this PR is intended to fix this problem by taking the item that is available instead of the first one.
> fix: maybe sku

- packages/core/src/components/sections/BannerText/BannerText.tsx
This PR intends to fix `BannerText` override props.
> fix: `BannerText` component

- apps/site/pages/docs/component-customization/overriding-components-props.mdx
- apps/site/pages/docs/getting-started/1-faststore-onboarding/onboarding.mdx
- apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
- apps/site/pages/docs/getting-started/3-project-structure.mdx
- apps/site/pages/docs/getting-started/4-faststore-cli.mdx
- apps/site/pages/docs/go-live/before-you-start.mdx
- apps/site/pages/docs/go-live/overview.mdx
- Fixes broken links
- Updates some content
> Docs: updates broken links + review 

- packages/components/src/organisms/Banner/BannerContent.tsx
- packages/core/lighthouserc.js
- packages/core/src/components/navigation/Navbar/Navbar.tsx
- packages/core/src/components/product/ProductCard/ProductCard.tsx
- packages/core/src/components/ui/Newsletter/Newsletter.tsx
This PR intends to improve Lighthouse results to acceptable levels.
https://github.com/vtex-sites/starter.store/pull/88
> fix: Lighthouse to acceptable levels.

- packages/core/src/components/ThirdPartyScripts/vtex.tsx
To add ActivityFlow support to our stores.
Run the deployment on our starter and check the network tab for `activity-flow` activity.
[Starter PR
](https://github.com/vtex-sites/starter.store/pull/93)
[Preview](https://sfj-534b609--starter.preview.vtex.app/4k-philips-monitor-99988213/p)
> Adds Activity Flow script

- packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
- packages/core/src/components/ThirdPartyScripts/vtex.tsx
Add `vtexaf` function that's required by ActivityFlow
> Improve ActivityFlow initialization script

- apps/site/pages/components/_meta.json
- apps/site/pages/docs/building-sections/component-customization-overview.mdx
- apps/site/pages/docs/building-sections/overriding-a-native-component.mdx
- apps/site/pages/docs/building-sections/overriding-components-props.mdx
Quick fixes: updates broken links and updates code example
> Docs: Updates broken links and fixes code example

- apps/site/pages/docs/getting-started-requirements.mdx
This PR aims to improve the requirement for installing VTEX intelligent search.
Preview: https://faststore-site-git-docs-review-requirements-faststore.vercel.app/docs/getting-started-requirements#enable-the-vtex-intelligent-search-app-in-your-account
> Docs: improve requirements

- packages/core/lighthouserc.js
- packages/lighthouse/src/index.ts
This PR aims to increase the _resource-summary:script:size_ metric in the Lighthouse. With the understanding that [this task](https://vtex-dev.atlassian.net/browse/FS-1128) was created to review the amount of loaded scripts and the way we are rendering the components.
> fix: Fix lh parameter

- packages/api/src/platforms/vtex/clients/search/index.ts
> Fixes typo defalt for default on variable name

- packages/core/src/pages/[slug]/p.tsx
[Offer data in Structured Data is broken](https://validator.schema.org/#url=https%3A%2F%2Fstarter.vtex.app%2F4k-philips-monitor-99988213%2Fp).
So in this PR, I fixed it.
> fix: product structured data

- apps/site/pages/docs/building-sections/creating-a-new-section.mdx
- Update `Create New Section` to work with new version.
- You should be able to create a new section/component in the CMS following the [guide](https://faststore-site-rj6ydz4y8-faststore.vercel.app/docs/building-sections/creating-a-new-section).
> docs: Review Create New Section doc 

- apps/site/pages/docs/go-live/3-integrating-the-the-vtex-login.mdx
- apps/site/pages/docs/go-live/before-you-start.mdx
- apps/site/pages/docs/go-live/overview.mdx
This PR:
- Adds the new doc _Integrating the VTEX Login_, part of the go-live track.
- Moves the _Setting up a VTEX account for FastStore_ doc to the go-live track.
🔗 [Preview](https://faststore-site-git-docs-integrating-vtex-login-faststore.vercel.app/docs/go-live/3-integrating-the-the-vtex-login)
> Docs: Integrating the VTEX login

- apps/site/pages/docs/building-sections/creating-a-new-section.mdx
- apps/site/pages/docs/getting-started/4-faststore-cli.mdx
This PR adds the step on what to update on the `content-types.json` and fixes some typos.
> Docs: Update Creating a new section

- packages/core/cypress/integration/plp.test.js
- packages/core/faststore.config.js
This PR intends to fix the PLP integrations tests related to price sort.
We will be using the `/technology` page while the IS team investigate the products bug.
https://github.com/vtex-sites/starter.store/pull/116
> fix: PLP integration tests

- packages/core/cypress/integration/analytics.test.js
- packages/core/cypress/integration/cart.test.js
- packages/core/cypress/integration/search.test.js
Attempts to fix current tests.
https://github.com/vtex-sites/starter.store/pull/114
https://github.com/vtex-sites/starter.store/pull/126
> Fix: Integrations tests

- packages/components/package.json
- packages/ui/package.json
This PR intends to revert the #1924 changes while we fix the store's build.
> fix: Revert #1924

- apps/site/components/ExtendableQueryTable/ExtendableQueryTable.tsx
- apps/site/pages/docs/api-extensions.mdx
Doc: [Preview](https://faststore-site-git-docs-consume-api-extensions-208f13-faststore.vercel.app/docs/api-extensions).
- https://github.com/vtex/faststore/pull/1967
> Docs: Consume API extensions

- apps/site/pages/docs/_meta.json
- apps/site/pages/docs/faststore-config-options.mdx
- apps/site/pages/docs/faststore-config-options/custom-cypress-test.mdx
- apps/site/pages/docs/getting-started/3-project-structure.mdx
Improves [Custom Cypress test doc](https://www.faststore.dev/docs/faststore-config-options/custom-cypress-test) page
Access the[ Configuration options for `faststore.config.js`](https://faststore-site-git-docs-cypress-test-faststore.vercel.app/docs/faststore-config-options) and [custom Cypress preview](https://faststore-site-git-docs-cypress-test-faststore.vercel.app/docs/faststore-config-options/custom-cypress-test) page, and check if everything works accordingly.
> docs: Updates Cypress doc

- packages/api/src/platforms/vtex/utils/getCookies.ts
> rm getCookie function

- apps/site/pages/index.mdx
Minor changes in the Landing Page doc.
> Docs: review landing page

- apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
The doc "Part 2: Configuring external DNS for a custom domain" had duplicated content, mixing the information for steps 3 and 4. This PR deletes this content and fixes some typos.
Preview: [Part 2: Configuring external DNS for a custom domain](https://faststore-site-git-docs-update-go-live-faststore.vercel.app/docs/go-live/2-configuring-external-dns)
> Docs: Removed duplicated content 

- packages/core/src/components/common/Alert/Alert.tsx
> Revert "fix: Changes prop type to string instead of react node"

- packages/core/src/components/common/Alert/Alert.tsx
- packages/core/src/components/sections/Alert/Alert.tsx
> fix: alert types

- CONTRIBUTING.MD
> docs: contributing

- packages/api/package.json
- packages/core/package.json
- packages/eslint-config/package.json
Adds the repository to the `package.json` from some packages.
> chore: adds repository to package.json

- apps/site/pages/docs/api-extensions/extending-queries-using-fragments.mdx
Fix small issues and add a more extensive warning on the callout about filenames.
> docs: Update "Extending Queries using Fragments" docs

- packages/api/src/platforms/vtex/resolvers/searchResult.ts
- packages/api/src/platforms/vtex/utils/sku.ts
this PR replicates the logic from 
- https://github.com/vtex/faststore/pull/2136
in the `1.x` branch.
> chore: pickBestSku instead of first sku in suggestions query

- lerna.json
- packages/api/README.md
- packages/api/package.json
Attempts to update the version manually using `1.x` branch.
As `v1.12.47` already exists since 2 months ago. When this PR got merged, the `v1.12.48` should be publish.
> chore: attempts to update lerna according to existing tags

- apps/site/pages/docs/handling-third-party-scripts.mdx
PR to review and update the doc about adding third-party scripts to FastStore projects. Also, it adds a disclaimer about using those scripts with Partytown.
Preview: [Adding third-party scripts](https://faststore-site-git-docs-handling-third-party-scripts-faststore.vercel.app/docs/handling-third-party-scripts)
> Docs: review third-party scripts

- package.json
- turbo.json
After #2156 here are some codemode fixes that need to be done.
ref: https://turbo.build/repo/docs/reference/codemods
> fix: turbo codemode

- apps/site/pages/components/atoms/badge.mdx
- apps/site/pages/components/atoms/button.mdx
- apps/site/pages/components/atoms/checkbox.mdx
- apps/site/pages/components/atoms/icon.mdx
- apps/site/pages/components/atoms/input.mdx
- apps/site/pages/components/atoms/label.mdx
- apps/site/pages/components/atoms/link.mdx
- apps/site/pages/components/atoms/list.mdx
- apps/site/pages/components/atoms/loader.mdx
- apps/site/pages/components/atoms/overlay.mdx
- apps/site/pages/components/atoms/price.mdx
- apps/site/pages/components/atoms/radio.mdx
- apps/site/pages/components/atoms/select.mdx
- apps/site/pages/components/atoms/skeleton.mdx
- apps/site/pages/components/atoms/slider.mdx
- apps/site/pages/components/atoms/sr-only.mdx
> docs: Updates atoms components docs

- apps/site/pages/docs/headless-cms-troubleshooting/error-permission-denied.mdx
Add a new troubleshoot on how to fix the `Error: Permission denied` while running `vtex cms sync`.
> Docs: new Headless CMS troubleshoot

- apps/site/pages/docs/building-sections/overriding-components-and-props.mdx
Just fix in our documentation example.
When user copy the code example, it should work.
> docs: Fixes import in doc example

- apps/site/pages/docs/getting-started/3-project-structure.mdx
Quick fix on link mentioning FastStore CLI.
> Docs (quick win): FastStore CLI link

- packages/core/cypress/integration/seo.test.js
After that https://github.com/vtex/faststore/pull/2207 we needed to fix the e2e tests.
> fix: canonical tests

- packages/core/src/sdk/cart/useCheckoutButton.ts
Revert commit 77fd613:
https://github.com/vtex/faststore/commit/77fd6136bd2918035bb10baf4ebd77158b772361#diff-c81ed83250c24b93206d75c6183b1ae5a61ab82887832cd9c9ef42e40fc7c9d2
> Revert previously commit

- apps/site/pages/docs/go-live/overview.mdx
- apps/site/pages/docs/multiple-page-templates.mdx
This pull request introduces a "Before you begin" section. This section explains the steps to update your core package and synchronize the hCMS updates before using the templates.
> Docs (quick fix): Multiple page templates

- apps/site/middleware.ts
Redirect any docs or component to developer portal keeping the path
> Add middleware for redirecting URLs in the site

- packages/sdk/src/store/persisted.ts
This PR aims to fix the sync cart problem while syncing Checkout and FastStore minicart.
Our current `validateCart` (optimistic cart) feature sometimes has problems syncing Checkout and FastStore minicart. Taking a look at the solution, we noticed that the `validateCart` mutation is called based on the `window` 'focus' event, and 
'visibilitychange' event, when `document.visibilityState === 'visible'` ([reference](https://github.com/vtex/faststore/blob/HEAD/packages/sdk/src/store/persisted.ts#L56-L61)). That occurs because these events are fired depending on the device (desktop/mobile) and the different browsers. 
That said, sometimes, these events are fired multiple times in a small fraction of time, which can cause concurrence problems when dealing with indexed DB updates. So this PR …
> fix: Checkout and FastStore minicart sync

- packages/core/src/server/cms/plp.ts
> fix: PLP slug

- .github/workflows/ci.yml
- package.json
- packages/core/@generated/graphql.ts
- packages/eslint-config/package.json
- packages/ui/package.json
- yarn.lock
upgrade to the last version of turbo
> chore: upgrade turbo

- packages/core/src/components/cart/CartItem/CartItem.tsx
> fix: useUnitMultiplier as optional

- packages/core/src/components/templates/LandingPage/LandingPage.tsx
- packages/core/src/components/templates/ProductListingPage/ProductListing.tsx
- packages/core/src/components/templates/SearchPage/SearchPage.tsx
- packages/core/src/pages/[slug]/p.tsx
- packages/core/src/pages/index.tsx
This PR aims to add more sections to pages.
you can see the commit messages to ensure which sections were added to which page.
- https://github.com/vtex-sites/starter.store/pull/439
> Feat: adds sections to pages

- packages/core/README.md
> release: FastStore core v3.0.68

- packages/api/src/platforms/vtex/clients/search/index.ts
- packages/api/src/platforms/vtex/loaders/sku.ts
- packages/api/src/platforms/vtex/resolvers/validateCart.ts
related https://github.com/vtex/faststore/pull/2431
> Fix: invisible items minicart v2

- packages/api/mocks/ValidateCartMutation.ts
Follow up of https://github.com/vtex/faststore/pull/2435
> Fix: test for invisible items minicart v2 

- packages/api/mocks/ValidateCartMutation.ts
- packages/api/src/platforms/vtex/clients/search/index.ts
- packages/api/src/platforms/vtex/loaders/sku.ts
- packages/api/src/platforms/vtex/resolvers/validateCart.ts
related https://github.com/vtex/faststore/pull/2431
> Fix: Invisible items minicart v1

- packages/core/src/pages/_app.tsx
Fix custom theme import priority
> Fix: Custom theme import priority

- README.md
> docs: update version on readme

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.MD
- README.md
Updates contributing guide to reduce friction for contributors.
- Updates the contributing file (added more details and instructions about the process and label)
- Updates the pull request template
Check the modified files and review it.
[Preview](https://github.com/vtex/faststore/blob/4adeb901b5bc031161111f0078d3fcd2b8716efb/CONTRIBUTING.MD)
> Chore: Updates FastStore Contributing Guide

- packages/cli/src/utils/generate.ts
Display a warning when typescript versions are different
compare between package json
> Chore: Add checkDependencies function to generate script

- packages/cli/src/utils/directory.ts
- packages/cli/src/utils/generate.ts
- packages/core/discovery.config.js
- Updates package/cli and fix import paths to use `discovery.config`
> fix:  import paths to use discovery.config

- packages/core/src/components/common/Footer/FooterLinks.tsx
- packages/core/src/components/navigation/Navbar/Navbar.tsx
- packages/core/src/components/search/Filter/Filter.tsx
- packages/core/src/components/sections/RegionBar/RegionBar.tsx
- packages/core/src/components/ui/Carousel/Carousel.tsx
- packages/core/src/sdk/ui/useScreenResize.ts
- packages/ui/src/styles/base/layout.scss
This PR intends to add a hook to resize depending on the current screen size.
It's related to the performance POC #2404.
It checks the user's screen size (or manual browser resizing) and returns the value corresponding if is mobile or not.
vtex-sites/starter.store#562
> feat: Add `useScreenResize` hook (SFS-1509)

- package.json
- packages/eslint-config/package.json
- turbo.json
- yarn.lock
Upgrading the turborepo major, this fixes some issues and improve the dx.
> Upgrade turbo

- packages/cli/src/commands/dev.ts
- packages/cli/src/commands/generate-graphql.ts
- packages/cli/src/utils/dependencies.ts
- packages/cli/src/utils/generate.ts
- packages/cli/src/utils/logger.ts
- packages/cli/src/utils/runCommandSync.ts
- turbo.json
To decrease accidental verbosity of FastStore commands.
Created a logger object that's equal to `console` but overrides the `log` function to check if the `DISCOVERY_DEBUG` flag is enabled.
Install the CLI version on a test store and see how much less output is being generated. :)
> Decrease FastStore CLI verbosity

- packages/core/src/components/region/RegionModal/RegionModal.tsx
Loads `RegionModal` using dynamic import.
We are aiming to optimize the performance  loading components only when they are needed, rather than at the initial page load.
- Click on `Set your location` button, the `RegionModal` should appear as expected.
> chore: Applies next/dynamic for RegionModal

- apps/site/middleware.ts
Uncomment middleware in vtex sites
> fix: uncomment middleware

- packages/cli/src/utils/generate.ts
- packages/cli/src/utils/hcms.ts
- packages/core/src/components/cms/GlobalSections.tsx
- packages/core/src/components/templates/LandingPage/LandingPage.tsx
- packages/core/src/components/templates/ProductListingPage/ProductListing.tsx
- packages/core/src/components/templates/SearchPage/SearchPage.tsx
- packages/core/src/pages/404.tsx
- packages/core/src/pages/500.tsx
- packages/core/src/pages/[slug]/p.tsx
- packages/core/src/pages/index.tsx
- packages/core/src/pages/login.tsx
- packages/core/src/plugins/index.tsx
Add the capacity of plugins creates component overrides
> feat: Add plugins overrides

- package.json
- yarn.lock
upgrading 2 minors of turbo repo
> chore: update turbo package to version 2.3.1

- lerna.json
- package.json
Generate semantic release from the commit merged into main (PR title). We squash the commits before merging into main. The resulting commit will have by default the PR title. So we have to ensure that the PR title has this convention.
TODO: Create an action to block merge button if the PR title is not following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification. 
Solutions: `lerna version --conventional-commits --yes`
When run with this flag, lerna version will use the [Conventional Commits Specification](https://conventionalcommits.org/) to [determine the version bump](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump) and [generate CHANGELOG.md …
> feat: generate semantic release from the commit merged into main

- packages/core/src/experimental/index.ts
export the useScreenResize hook so that stores can leverage the use of this hook.
> chore: export the useScreenResize hook

- package.json
- yarn.lock
> chore: update turbo package to version 2.3.3

- packages/sdk/package.json
- packages/sdk/test/analytics/useAnalyticsEvent.test.ts
- packages/sdk/test/search/Provider.test.tsx
- packages/sdk/test/search/usePagination.test.tsx
- packages/sdk/test/ui/Provider.test.tsx
- yarn.lock
- Remove React 17 warnings on test
> chore: remove react 17 warnings on test

- packages/core/src/components/templates/SearchPage/SearchWrapper.tsx
Small fix: The `title` decides if there will be a colon or not.
> fix: remove unnecessary colon

- packages/core/src/pages/[slug]/p.tsx
> fix: adds revalidate as false when not experimental

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.MD
- packages/api/README.md
- packages/cli/README.md
- packages/core/README.md
- packages/graphql-utils/README.md
- packages/sdk/README.md
- packages/ui/README.md
> docs: update package docs with pnpm information

- .github/workflows/release.yml
attempts to run publish directly in ci
> fix: attempts to run publish directly in ci

- .github/workflows/release.yml
- lerna.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- Revert CI script
- Fix lerna package identification
> chore: fix lerna release step

- .github/workflows/ci.yml
- Removes invalid input `cache`
> fix: Removes CI invalid input

- packages/core/index.ts
this PR aims to export the `Section` component so that stores can use it appropriately.
> chore: exports Section

- packages/core/src/sdk/shipping/useShippingSimulation.ts
`ClientShippingSimulationQuery` is being called multiple unnecessary times, this PR fixes it.
The issue is related to how React compares the dependencies inside the `useEffect` dependency list: it compares by reference and it creates an issue with objects and arrays because their reference can change while the values are the same. To fix it, I've used an approach of stringifying the object and then parsing it again, so the dependency on `useEffect`'s dependency list would be a string and not an object.
Check in the `Network` tab of the browser's devtools that the request related to `ClientShippingSimulationQuery` is not having unnecessary calls. It should be called when there is a change, for example if the postal code changes or if the product quantity changes.
Before it was being called …
> fix: ClientShippingSimulationQuery being called multiple times

- packages/core/cms/faststore/sections.json
- packages/core/src/components/reviews/FilterProductReviews/FilterProductReviews.tsx
- packages/core/src/components/reviews/FilterProductReviews/index.ts
- packages/core/src/components/reviews/ReviewList/ReviewList.tsx
- packages/core/src/components/reviews/ReviewList/index.ts
- packages/core/src/components/reviews/SortProductReviews/SortProductReviews.tsx
- packages/core/src/components/reviews/SortProductReviews/index.ts
- packages/core/src/components/sections/ReviewsAndRatings/DefaultComponents.ts
- packages/core/src/components/sections/ReviewsAndRatings/ReviewsAndRatings.tsx
- packages/core/src/components/sections/ReviewsAndRatings/section.module.scss
- packages/core/src/components/ui/ReviewsAndRatings/ReviewsAndRatings.tsx
- packages/core/src/typings/overrides.ts
>⚠️ THIS PR DEPENDS ON:  ⚠️
> - https://github.com/vtex/faststore/pull/2707
This pull request introduces the reviews filtering and sorting feature to the `ReviewsAndRatings` section.
New components for filtering and sorting reviews:
* [`packages/core/src/components/reviews/FilterProductReviews/FilterProductReviews.tsx`](diffhunk://#diff-a2b0bd1e2cdbfbcf09123edfce232730783b1b1137ade37ee1e695fb03455afbR1-R55): Introduced `FilterProductReviews` component to filter reviews by rating.
* [`packages/core/src/components/reviews/SortProductReviews/SortProductReviews.tsx`](diffhunk://#diff-c75acab76a9610dd3829f0261b68aff5951f22de317c4a8915c6794fe43d1fddR1-R52): Introduced `SortProductReviews` component to sort reviews by different criteria.
Updates to `ReviewList` and `ReviewsAndRatings` sections: …
> feat: add filter and sort selects to review and ratings

- packages/core/src/pages/api/graphql.ts
This PR aims to handle errors when `parseRequest` fails.
suggestion: review with the `hide whitespace` option enabled.
> fix: handle invalid requests in `parseRequest` function

- packages/core/src/pages/_app.tsx
> fix: add key prop to Component in App for better rendering

- packages/core/discovery.config.default.js
Update discovery.config.default.js store urls
> chore: Update discovery.config.default.js store urls

- packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountStatusCard/MyAccountStatusCard.tsx
Handles `Canceled` and `Cancellation Requested` status on MyAccountStatusCard
When the order has `Canceled` or `Cancellation Requested` status, it must show the cancel status in the middle and "ghost" the others.
- https://github.com/vtex-sites/faststoreqa.store/pull/805
> feat: canceled statuses order status

- packages/ui/src/components/molecules/SearchProducts/styles.scss
- Remove duplicate tokens
- Fix lint issues
> fix: search product styles tokens

- packages/core/package.json
- pnpm-lock.yaml
Updates next version from 13.5.8 to 13.5.9.
No breaking changes or other changes are expected in the application.
> chore: updates next from 13.5.8 to 13.5.9

- packages/components/src/molecules/Modal/Modal.tsx
Fix a behaviour that prevented to use tab to focus the apply button on the region modal
Checks if the event was triggered by the correct element
Opens the RegionModal component and test if:
1. Focus should be in the input when modal opens
2. On typing in the input and pressing tab, it should focus the button and stays there.
> fix: Modal was triggering event onEntered when content bubbled transition event up

- packages/core/src/pages/account/orders/[id].tsx
- packages/core/src/pages/account/orders/index.tsx
- packages/core/src/server/index.ts
- packages/core/src/utils/utilities.ts
> feat: extract error status handling and improve error messages

- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/MyAccountListOrdersTable.tsx
- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/styles.scss
- packages/core/src/components/account/orders/MyAccountOrderDetails/MyAccountOrderDetails.tsx
- packages/core/src/pages/account/orders/[id].tsx
> fix: redirect order details

- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountFilterSlider/MyAccountFilterSlider.tsx
- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrders.tsx
> fix: use window.location.href to apply filters

- packages/core/cms/faststore/content-types.json
- packages/core/src/sdk/deliveryPromise/useDeliveryPromise.ts
- packages/core/src/utils/globalSettings.ts
Add delivery option facets to `useDeliveryPromise` hook.
Adds the "All delivery options" option to Delivery Option facets and removes the DO and dynamic estimates facets when DP is not enabled in faststore.
DO isn't in production in the IS API yet, so we have to test this PR using the IS beta version.
Make sure that the workspace `vtexis` (`vtex login vendemo -w vtexis`) has the app `vtex.intelligent-search-api` installed in the version `0.52.0-beta.1` (`vtex ls`). Then, make some changes in the `packages/core/discovery.config.default.js` and `packages/api/src/platforms/vtex/clients/search/index.ts`:
- Use the `vendemo` account, `BRA` country and `pt-BR` locale. You can test the behavior with DP enabled and disabled.
- Add the workspace to the `base` URL in `index.ts`, it should be: 
``` …
```
> feat: add delivery option facets to useDeliveryPromise hook

- packages/components/src/molecules/ToggleField/ToggleField.tsx
- packages/components/src/organisms/Filter/FilterFacetBooleanItem.tsx
- packages/components/src/organisms/Filter/FilterFacets.tsx
- packages/core/cms/faststore/content-types.json
- packages/core/src/components/search/Filter/FilterDesktop.tsx
- packages/core/src/components/search/Filter/FilterSlider.tsx
- packages/core/src/components/search/Filter/section.module.scss
- packages/core/src/components/sections/ProductGallery/section.module.scss
- packages/core/src/sdk/deliveryPromise/useDeliveryPromise.ts
- packages/core/src/utils/globalSettings.ts
- packages/ui/src/components/organisms/Filter/styles.scss
Displays dynamic estimate options facets to Filter.
The integration will be addressed in another PR, this PR is implementing only the UI.
- Added `toggle` type to `FilterFacetBooleanItem` component
- Added `highlighted` prop to `FilterFacets` component | Adjust style for this variation
- Splits `highlighted` facet (dynamic-estimate) from the others in order to list it in the top.
|Desktop|Mobile|
|-|-|
|<img width="1183" height="800" alt="desktop" src="https://github.com/user-attachments/assets/88d5e3fc-6af1-4431-a7e3-32343e8eb38a" />|<img width="410" height="800" alt="mobile" src="https://github.com/user-attachments/assets/9891a902-7339-49db-aed4-2c81bc6eab55" />|
When the dynamic estimate facets are available, they should be displayed at the top of the Filters section. Unlike other …
> feat: Dynamic Estimate Filter UI

- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/MyAccountListOrdersTable.tsx
remove client name and placed by from order list
| <img width="1312" height="651" alt="Screenshot 2025-08-07 at 18 48 40" src="https://github.com/user-attachments/assets/9f5bb8a3-1e79-4805-b45b-5f566468e5eb" /> | <img width="1300" height="571" alt="Screenshot 2025-08-07 at 18 49 36" src="https://github.com/user-attachments/assets/d2e1eef8-327c-45f4-ab5b-fccc3add9f00" />|
> feat: remove client name and placed by from order list - SFS-2795

- packages/core/src/components/account/security/SecurityDrawer.tsx
- packages/core/src/sdk/account/useSetPassword.ts
> refactor: simplify response messages on useSetPassword hook

- packages/core/@generated/graphql.ts
removes unused type left behind
> fix: remove SearchShopperResult type definition

- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/ExpandButton/ExpandButton.tsx
- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/MyAccountListOrdersTable.tsx
- packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/styles.scss
Account > Orders
Account > Orders
> feat: adjust Custom Fields in MyAccountListOrdersTable

- pnpm-lock.yaml
Fix canary lockfile after rebase
> fix: lockfile 

- packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx
Wait for the analytics autocomplete click event before navigating.
reference thread: https://vtex.slack.com/archives/C051B6LL91U/p1758570585786029
> fix: refactor search dropdown to handle analytics events asynchronously
